### ISSUE TITLE
[4.0.4] xTESEdit & xTESEdit64 is trying to load Fallout 4's Data Path instead of Skyrim SE's Data Path

### ISSUE THREAD

**Issue by WaCrex** [TES5Edit/TES5Edit#1000]
**What is the version of xEdit you are using?**
4.0.4

**Describe the bug**
Once started xTESEdit & xTESEdit64 will attempt to look for where Fallout 4 is installed and attempt to use Fallout 4's Data Path & ini-file instead of Skyrim SE's Data Path & ini-file. Also xTESEdit says "FO4Edit 4.0.4" in the the title bar instead of "SSEEdit 4.0.4" as you would expect it to, same thing goes for xTESEdit64 which says "FO4Edit 4.0.4 x64" in the the title bar instead of "SSEEdit 4.0.4 x64".

**To reproduce**
1. Just launch  xTESEdit.exe & xTESEdit64.exe.

**Expected behavior**
I would have expected it to load Skyrim SE's Data Path and ini-file, but it doesn't.

**Screenshots**
[Screenshot 1](https://photos.app.goo.gl/qVuJ8tCCeE9jNxAv9)
[Screenshot 2](https://photos.app.goo.gl/o5yjAPq5xYaqhaUG6)

**Comment by VlitS** [comment]
xTesEdit is a generic name, you have to rename the exe to SSEEdit.exe for it to point at Skyrim SE. It defaults to FO4 when nothing is specified.

**Comment by WaCrex** [comment]
Ah thx, renaming the files to SSEEdit.exe & SSEEdit64.ext fixed it :)

I'm usually not using the GitHub version, usually I'm just grabbing SSEEdit off Nexus Mods. But I got a message that there were a newer version here so I thought I might as well grab it instead, so I went here to grab it instead..
