### ISSUE TITLE
Feature request: Api delphi Classes and Generics

### ISSUE THREAD

**Issue by hoppaman** [TES5Edit/TES5Edit#1001]
**What is the version of xEdit you are using?**
SSEEdit 4.0.4

**Describe the bug**
Everything compiles well in RAD Studio but SSEEdit compiler goes nuts and does not detect Generic package. I am crating rather complex / many conversion scripts for SSEEdit and would desperately need class and generic containers. 

**To reproduce**
1. Define uses System.Generics.Collections;
2. Use TList<TSomeType>
3. Compile and witness error that complains that Generics path does not exists.

**Expected behavior**
Generics to work as API and GUI defines.

I am scanning for armors and need to store information of those items and it gets really messy if you store different data value and meta datas all in different arrays / TStringLists. If support of generics is not possible if you could explain other potential way to approach the problem it would be greatly appreciated.

**Comment by ElminsterAU** [comment]
JvInterpreter is not Delphi.
It didn't support defined classes or using genetics.

**Comment by zilav** [comment]
Use TJsonObject instead.

**Comment by ralphtherapper** [comment]
Thanks for specifying the interpreter and for the helpful tip.
