### ISSUE TITLE
FNAM Scene Flags

### ISSUE THREAD

**Issue by tarlazo** [TES5Edit/TES5Edit#1002]
**What is the version of xEdit you are using?**
SSEEdit 4.0.4 (103758D4) starting session 2022-02-15 10:48:14

**Describe the bug**
The flag "Stop on Quest End" in 'FNAM - Flags' should be named "Stop Quest on End".
It might be confusing for those who don't know what it actually does.

**Comment by ElminsterAU** [comment]
should be fixed with commits referenced above, will be in 4.x.4e
