### ISSUE TITLE
about wbVWDAsQuestChildren in FO4

### ISSUE THREAD

**Issue by supamu123** [TES5Edit/TES5Edit#1003]
-

**Comment by ElminsterAU** [comment]
wbVWDAsQuestChildren should always be true for FO4

**Comment by supamu123** [comment]
`GRUP Cell Visible Distant Children of QUST - Quest [00003648] <DialogueDiamondCity>` from xdump ?

**Comment by ElminsterAU** [comment]
yes, the text is incorrect. As I said, it *should* always be true for FO4

**Comment by supamu123** [comment]
okay, thanks!
