### ISSUE TITLE
Record counter difference dilemma

### ISSUE THREAD

**Issue by supamu123** [TES5Edit/TES5Edit#1004]
-

**Comment by ElminsterAU** [comment]
GRUP count

**Comment by supamu123** [comment]
thanks!

**Comment by ElminsterAU** [comment]
What's your username in discord? Giving you a role should circumvent the verification requirement I think....

**Comment by supamu123** [comment]
oh, awesome, we can try that, thank you! I just rejoined your server on discord at 12:15 PM GMT +8 ( my local time ) I should be the last one listed in #introduction. I'm sporting a philosopher name 😃

**Comment by supamu123** [comment]
Even better, I just successfully verified by phone using my SO phone, no idea why mine didn't work in the first place. Anyways, all set, you don't have to do anything anymore! thanks! 😄
