### ISSUE TITLE
2 issues - inconsistence Loot <-> SSEEdit for Mods of SSE AE CC creations on DC

### ISSUE THREAD

**Issue by Dreifels** [TES5Edit/TES5Edit#1006]
Inconsictence of SSEEdit and Loot
I have two issue, both  with mods of Skyrim AE Creadtion Cit content of the DC:
( posted it also at LOOT support: https://www.afkmods.com/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/page/39/ )
1)  File cceejsse005-cave.esm (Creation Club content od Skyrim AE Upgrde) after I run SSEEditQuickAutoClean and got
  - name: 'cceejsse005-cave.esm'
    clean:
      - crc: 0xE8559DF8
        util: 'SSEEdit v4.0.4'
I run Loot and got YELLOW Warnung
# cceejsse005-cave.esm
- CRC: E8559DF8
- Load Order Index: 08
- Attributes: Active, Dirty, Master Plugin, Loads Archive
- Group: Creation Club
- Add Bash Tags: C.Acoustic, C.Climate, C.ImageSpace, C.Light, C.Location, C.Music, C.Name, C.Water
## Messages
- Warning: [SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164) hat 1 ITM-Eintrag gefunden.... 

2)  Same Issue is with cc creation ccbgssse018-shadowrend.esl

  - name: 'ccbgssse018-shadowrend.esl'
    clean:
      - crc: 0xEDDE17F4
        util: 'SSEEdit v4.0.4' 
   
Loot says (and refers to SSEEdit v4.0.4 output, so I understand Loot does not read SSEdit's output correctly) 
 # ccbgssse018-shadowrend.esl
- CRC: EDDE17F4
- Load Order Index: FE 001
- Attributes: Active, Dirty, Master Plugin, Light Plugin, Loads Archive
- Group: Creation Club
## Messages
- Warning: [SSEEdit v4.0.4](https://www.nexusmods.com/skyrimspecialedition/mods/164) hat 1 ITM-Eintrag gefunden. 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by ElminsterAU** [comment]
LOOT does not "read" xEdit's output or interact with xEdit in any way.

**Comment by Dreifels** [comment]
sorry, how LOOT can give this message if Loot does nor read output of SSEEdit local
![loot](https://user-images.githubusercontent.com/40837496/158733793-fe02700c-e231-46ed-8550-c42b788ef997.jpg)
?

**Comment by ElminsterAU** [comment]
Because someone has added the information into the LOOT master list.
LOOT does not analyze your files.
LOOT does not start xEdit to analyze your files.

The only thing LOOT does is look up the checksum of the file in the master list and shows whatever message there is for that checksum.

**Comment by Dreifels** [comment]
and how LOOT does not show such message, after I did clean a mod that had the message before cleaning? (except at this two mods). If it reads the checksum only, then this means that a clean mod has this notice, which is false. (I sent a message to the SSEdit staff, too)  These two are mods of the Skyrim AE payed ADDON (Upgrade), made by Bethesda.

**Comment by ElminsterAU** [comment]
Again. NOT. A. XEDIT. ISSUE.
