### ISSUE TITLE
[Pri: Enhancement] FO4 related minor UI adjustment.

### ISSUE THREAD

**Issue by Diskmaster** [TES5Edit/TES5Edit#1009]
**What is the version of xEdit you are using?**
4.0.4b

**Describe the bug**
In automated and manual previsibine building, we build precombines first (PCMB), previsual information second (VISI)

**To reproduce**
Look at any cell header. In current builds of xedit, regardless of branch, VISI and PCMB dates are shown as expected. This is fine.

**Expected behavior**
**Flip** the display order of the two rows. That's it. (As in PCMB first, not VISI first.)

**Screenshots**
n/a, as this is a cosmetic enhancement request.

**Additional context**
This is filed as a wish list item and can honestly be shoved so far down the priority list to the point where it could never see the light of day, but the current ordering of those two rows always bothered me.

**Comment by ElminsterAU** [comment]
There is no such thing as a "display order". The order of subrecords depends on what order they occur in the file format.
