### ISSUE TITLE
Condition GetIsID does not accept an Enchantment ID (FO4)

### ISSUE THREAD

**Issue by PJMail22** [TES5Edit/TES5Edit#1012]
**What is the version of xEdit you are using?**
4.0.4b x86

**Describe the bug**
The GetIsID condition will accept an enchantment when created via the CK, but it can't be done in FO4edit. "Check for Errors" xedit function returns errors when such Enchantments are added via the CK.

**To reproduce**
Via CK, add a condition (say on a Perk) using GetIsID and in the parameter select an Enchantment (they appear as "Enchantement: enchantmentname") and save the mod.
Open the mod in xEdit and do a check for errors.

**Expected behavior**
Enchantments are valid in this function, but xEdit does not agree.

**Screenshots**
![xEditPerkBug](https://user-images.githubusercontent.com/105346053/167794518-272d34fc-facc-4d4d-9c8a-5a37a368d00e.jpg)

**Additional context**
xEdit is being used with latest version of FO4.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above, will be in 4.x.4e
