### ISSUE TITLE
xEdit SSE Start Error

### ISSUE THREAD

**Issue by Lonewolf1893** [TES5Edit/TES5Edit#1014]
**What is the version of xEdit you are using?**
XEdit 4.0.4

**Describe the bug**
The Launcher from SSE start everytime the Fallout 4 xEdit Launcher

I start the xTESEdit65 for SSE and the launcher start everytime the FO4Edit with errors because FO4 is not installed
FO4Edit 4.0.4 x64 (20781F15) starting session 2022-05-14 08:52:13
Using Fallout4 Data Path: 
Using Scripts Path: C:\Users\weber\Desktop\Neuer Ordner (2)\Edit Scripts\
Using Cache Path: 
Using ini: 
Fatal: Could not find ini

**Comment by ElminsterAU** [comment]
Yes. You either need to rename the exe or start it with appropriate parameters.

Or use the versions from nexusmods which have already been appropriately renamed.
