### ISSUE TITLE
Advanced User Compatibility

### ISSUE THREAD

**Issue by GammaLead** [TES5Edit/TES5Edit#1018]
**What is the version of xEdit you are using?**
SSEEdit 4.0.4 (103758D4) starting session 2022-06-03 15:17:34
~and~ SSEEdit 3.2.1 starting session 2022-06-03 15:16:13

**Describe the bug**
Advanced User Options

**To reproduce**
-Inability to unilaterally "clear" (delete) master files from an .esp.

**Expected behavior**
As in v 3.2.1 (which I still keep as a secondary XEdit)--I cannot unilaterally decide to delete a mater file from a mod/patch if needed in v 4.0.4. Personally, I move < ModX > to the "top" of the load order (using LOOT/Wrybash), sort load order, then close out/save. I rename the just saved file as < ModX2 >. I then re-add and reload the base files of < ModX > and < ModX2 > in SSEEdit, and run error checker on < ModX2 > to remove the references from < ModZ > from < Mod X > to remove all references from the deleted mod. This is a useful tool if re-patching a mod from "RND" to "Survival Mode" or other similar uses (follower frameworks/etc).

If possible: 1) The ability to streamline the process ("mark master for removal" or similar could be implemented (obviously with another message box to approve), It would be appreciated. Otherwise, please add in the settings menu a checkbox which states: "I am an experienced modder" or similar, and if selected, allows the user to unilaterally delete masters from an .esp as is available in the 3.2.1 version. Thank you.

**Screenshots**
Available upon request.

**Additional context**
This is simply because I'm unaware of a better option, and because I find SSEEdit to be 1000x+ easier to understand and use (and load) than the Creation Kit. This is at once a "bug" as it is an "improvement" request. Regardless, THANK YOU for supporting SSEEdit, and even if you refuse this request, I'll still simply just continue to use TESVEdit 3.1.2 alongside SSEEdit 4.0.4+. Thank you for allowing me and many others to easily mod and patch mods with XEdit. I wish I could donate more for this wonderous tool. Many thanks.

**Comment by jbostrus** [comment]
I'm slightly hesitant to offer this information, as the reason it was default disabled is precisely to prevent what you're doing. That will break the plugin. If you check the What's new tab and use the search box to enter **Editing "Master Files" in "File Header"** you will see the explanation.

The only arguably valid reason I can think of to use the allowance to edit the master table directly is to rename a master. Changing the order, removing, or adding a master directly will break something.

Elminster can correct me if I'm wrong in the following.

The proper way to remove the references and clear a master would be to use the **Report Masters** script to identify which records use the master you want to remove. Modify the records or remove them. Then use the clean masters function. That ensures that the master table and all internal form ids remain correct. Manually removing a master from the master list via the old 3.x.x method will cause the internal form ids to become corrupted. Any subsequent save potentially makes it worse.

An example of one case where you could potentially break a reference without knowing:
Your patch plugin has 4 masters
Fallout4.esm
SomeCoolMod1.esp
SomeCoolMod2.esp
SomeCoolMod3.esp

Let's say that mod1 and mod2 both have new record IDs of XX000810.

If you have the patch pointing to 01000810 (a record in SomeCoolMod1). Now force remove SomeCoolMod1.esp using your method above. The patch will be pointing to 01000810 still which is now SomeCoolMod2. A check for errors may not show an error **unless** wherever that reference is used is of an incompatible type.

A different but related issue could occur if you had new IDs in mod3 and the patch. If you had it pointing to the record in mod3 and removed mod1 AND/OR mod2 the patch will now incorrectly be pointing to itself and not mod3.

**Comment by ElminsterAU** [comment]
The function has been disabled for very good reasons. Countless people have destroyed their files by doing something so harebrained and incredibly stupid that I hadn't even consider people would be doing that. Simply deleting a master entry from the file header will destroy the structure of the file.

The correct way to remove as master is:

a) run the report masters script to find all references to the master you want to remove and remove these references
b) clean masters

Just for the record, the "old 3.x.x method" was never any kind of method. The only correct approach has always been to remove all references and then run Clean Masters.

**Comment by GammaLead** [comment]
The responses are much appreciated. I didn't know 'report masters' was a thing. It seems a bit... mis-named, but I digress.

As mentioned above, I know that removing masters was a bad idea, which is why I only used it on a copy of the main file, and used that copy as my variant of "report masters". I'm also aware of how screwed up it can leave a file--unless it's the last master file, it'll mess up all of the references of the masters below.

Regardless, thank you for continuing to support this tool, and for teaching me a new thing.
