### ISSUE TITLE
TES files run wrong file

### ISSUE THREAD

**Issue by CragOrion** [TES5Edit/TES5Edit#1021]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.
FO4Edit 4.0.4 x64 (20781F15) starting session 2022-07-04 14:49:24

**Describe the bug**
After downloading the newest version of xEdit, I extracted all files to a folder, then ran xTESEdit.exe and it opens the FOEdit instead. Gives this error: 
"Fatal: could not open registry key \SOFTWARE\Bethesda
\Softworks\Fallout4
This can happen after Steam updates, run the game's launcher 
to restore registry settings"

After I click OK, it then opens the Fall Out version.

I don't even own Fall Out.

This happens with both xTESEdit.exe and xTESEdit64.exe

**To reproduce**
1. Download xEdit 4.04 from GitHub
2. Extract files to empty folder
3. Run xTESEdit.exe or xTESEdit64.exe

**Expected behavior**
I expected xTESEdit.exe to open xTESEdit, not xFOEdit

**Screenshots**
![image](https://user-images.githubusercontent.com/45319228/177206598-cebbeaea-0e31-474e-a1e6-bfc8c05478d5.png)

![image](https://user-images.githubusercontent.com/45319228/177206690-02ea88bb-7db8-4c04-97ab-c4caa2bdd40f.png)

**Additional context**

**Comment by CragOrion** [comment]
You guys need to document this somewhere like in a readme file with the download or on the front page of your site. I looked and found no install or set up instructions on your site (https://tes5edit.github.io/docs/index.html). I only found the answer by googling and finding someone mentioning manually changing the name of the files depending on what game you're using it for. 

I don't even understand why you would provide a file like this without giving any instructions on how to at least run it correctly. WTF? You put all this time and effort into making this utility, but you don't want people to be able to use it? Nice job, two thumbs up

**Comment by eckserah** [comment]
> You guys need to document this somewhere like in a readme file with the download or on the front page of your site. I looked and found no install or set up instructions on your site (https://tes5edit.github.io/docs/index.html). I only found the answer by googling and finding someone mentioning manually changing the name of the files depending on what game you're using it for.
> 
> I don't even understand why you would provide a file like this without giving any instructions on how to at least run it correctly. WTF? You put all this time and effort into making this utility, but you don't want people to be able to use it? Nice job, two thumbs up

Hey there, So the reason you were having an issue is because you need to run it as TES5Edit not xTESEdit. The x in xEdit is what gets replaced with the game abbreviation (FO3, FNV, TES5, SSE, FO4, FO76).

**Comment by ElminsterAU** [comment]
Releases on GitHub are meant for experienced users. For people that need a pre-chewed spoon-fed version, there are the game specific releases on NexusMods.
