### ISSUE TITLE
[FNV] TESClimate Moons / Phase Length field is read from the .esm incorrectly

### ISSUE THREAD

**Issue by c6-dev** [TES5Edit/TES5Edit#1027]
**What is the version of xEdit you are using?**
FNVEdit 4.0.4 (103758D4)

**Describe the bug**
TESClimate Moons / Phase Length field is read incorrectly in Fallout NV. Instead of Masser moon, the field contains Secunda moon.

**To reproduce**
1. Load FalloutNV.esm
2. Expand Climate tab
3. Select any climate with a Moon specified
4. Moons / Phase Length field has "Secunda" moon.

**Expected behavior**
All climates in FalloutNV.esm have Masser moon selected in GECK, so this is expected in xEdit as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/31777460/181720028-bed480ad-9397-4bb1-8ada-cfe97e5a3206.png)
![image](https://user-images.githubusercontent.com/31777460/181720082-413f47d5-7cd0-4127-a751-045e0838d826.png)

**Comment by anahuj** [comment]
The moon bits here differ from the fallout 3 order. In fallout 3, the masser is the highest bit. See my decodings:

https://github.com/anahuj/esptools/blob/master/f3espparser/parsebuffer_clmt.c
