### ISSUE TITLE
[OB] Mod with duplicated form ID in two different record types is not detected.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#1030]
TES4Edit 4.0.4b (C1CB925E) starting session 2022-08-06 17:02:36

The following mod has a defect where two records in it have the same form ID. One in the ARMO (armors) list, the other in the ENCH (enchantments) list.

Form ID 01000ED6.

https://www.nexusmods.com/oblivion/mods/51691 version 0.9 uploaded on August 5. Forgotten King.esp

Drop the mod into the Oblivion Data folder.
Load xEdit with that mod.
Note that the Messages tab emits no errors about the duplicate form ID.

I am reasonably certain this sort of thing used to be reported during load.

A user was attempting to build a Bashed Patch with this mod included and it was during checking that patch that the issue was identified when xEdit noted the clash between Forgotten King.esp and the bashed patch file.

**Comment by ElminsterAU** [comment]
Try with 4.1.4.

I'm reasonable sure that the reporting and handling of duplicated FormID was only added in 4.1.x

**Comment by Arthmoor** [comment]
Yes, 4.1.4 does report it but it doesn't stop loading so it could be easily missed. It might be beneficial to make sure it stops loading and brings the error to the user's attention. Perhaps with an option to skip over the form instead of doing so automatically.

**Comment by ElminsterAU** [comment]
If it stopped loading, you couldn't do anything to fix it.

**Comment by yarrmateys** [comment]
instead if it detects the duplicate form id it could show a message box with info after the loading is finished, with one of the options taking the user directly to offending entry.

**Comment by ElminsterAU** [comment]
A mod with multiple records with the same formid is an extreme corner case. Because of the extend of the needed changed, I don't plan to backport this to 4.0.x.

For 4.1.x, I don't currently plan to make fundamental changes to the loading process as would be required for the suggestion above.
