### ISSUE TITLE
Incorrect encoding for cyrillic symbols for Player Dialog Prompts

### ISSUE THREAD

**Issue by DelmorS** [TES5Edit/TES5Edit#1034]
**What is the version of xEdit you are using?**
I've tried 3 versions: 4.0.4, 4.0.4c and 4.1.4c, for each of them I have this bug

**Describe the bug**
For Dialog Topics in Fallout 3, Prompts of Player are shown in incorrect encoding, when using -l: russian, while Response Texts of NPCs are shown correctly. 

**To reproduce**
1. Launch xEdit with -l: russian option
2. Load any esm/esp file, containing Cyrillic symbols
3. Open Any Dialog Topic for this esp, and then find any record, which contains Prompt of Player. It will be with incorrect encoding.

**Expected behavior**
Encoding of Player Prompt should be the same, as for all the other objects: NPCs, Weapon, Projectiles, Response Texts of NPCs and etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/41177486/186179966-6ab1f34c-e3e6-460c-beb7-398810ba8b5e.png)

**Comment by ElminsterAU** [comment]
should be fixed with commit referenced above, will be in 4.0.4d
