### ISSUE TITLE
4.0.4. Critical Error at drag & drog copy

### ISSUE THREAD

**Issue by GitHubExorzist** [TES5Edit/TES5Edit#1035]
SSEdit 4.0.4

When I drag and drop entries from various ESPs (possibly only for Male World Model & Female World Model or when the complete entry is copied in the Armor Addon), the ESP can become corrupted.
I have triggered this error several times now and each time it was one or several of the Armor Addon entries that caused Skyrim as well as CreationKit to no longer start with this ESP. If you have found the bad entry with a lot of try & error and deleted it, the ESP works again. Copying the bad entry into a new ESP leads directly to the same error again.

Maybe I have a work around, at least I was able to copy the entries anyway, although with significantly more work. Drag & Drop of the individual categories worked for all except those of "Male World Model & Female World Model". There I added the entry with "Add" and then copied the entries from the other ESP via drag & drop. So it worked that the ESP was not damaged.

I have attached two ESP in the archive. One with the error and the other I have rebuilt identically with the above described work around solution. Means, with one Skyrim can be started, with the other not. 

[Files.zip](https://github.com/TES5Edit/TES5Edit/files/9439208/Files.zip)

**Comment by zilav** [comment]
Both "Male World Model and "Female World Model" contain texture files hashes field, which format depends on the Form Version of a record. Copying newer format hashes to the older record version and vice versa in xEdit make the game and CK unable to read it. Remove all hashes and resave plugin in CK to amend that.

**Comment by ElminsterAU** [comment]
4.1.x supports decoding texture hashes and converting them between different form versions on assignment
