### ISSUE TITLE
Opening xTESEdit.exe runs xFOEedit.exe?

### ISSUE THREAD

**Issue by mitolegy** [TES5Edit/TES5Edit#1037]
this is probably just me being stupid but I cant find an answer for it anywhere. whenever I click "xTESEdit.exe" it launches an application called "xFOEdit.exe" and starts loading fallout 4 plugins. I don't see anywhere where it says to load Skyrim plugins instead. 
keep in mind, it still has the xTESEdit logo. both as an icon for the exe file and in the app window. but regardless is starts loading fallout plugins. 

this happens to both version of xTESEdit. both the 32-bit and the 64-bit. only difference being that the 64-bit version fittingly loads the 64-bit FO4 version. 
I've tried launching the xFOEdit.exe and it launches the correct application. this time with the correct application logo. but that doesn't help me as it just means I have two ways of launching the same program. 

this has happened on both the newest release version. and the experimental version (though i have not tried the extremally experimental version) 

please help?

**Comment by Evan555alpha** [comment]
Rename the executable to "TES5Edit.exe" for Oldrim, "SSEEdit.exe" for SSE.
Alternatively, run the executable with the "-TES5" or "-SSE" parameters.
This info is available on the docs (https://tes5edit.github.io/docs/2-overview.html#QuickTipsandShortcuts) as well as the built-in "What's New".
