### ISSUE TITLE
Possible Bug with GOG Version of Skyrim AE

### ISSUE THREAD

**Issue by LazyDunmer** [TES5Edit/TES5Edit#1043]
**What is the version of xEdit you are using?**
4.0.4.0

**Describe the bug**
Upon launch of SSEedit & Autoclean I get the following error message: Fatal: Could not open registry key: \SOFTWARE\Bethesda Softworks\Skyrim Special Edition\    This can happen after Steam updates, run the games launcher to restore settings.

Upon closing the error message the exectuable will open but no data will be present which prompts a second error message: 
SSEEdit 4.0.4 (103758D4) starting session 2022-10-02 12:45:25
Using Skyrim Special Edition Data Path: 
Using Scripts Path: C:\Users\DS\Desktop\SSEEdit 4.0.4\Edit Scripts\
Using Cache Path: 
Using ini: 
Fatal: Could not find ini

As of yet I haven't found a way to set a path for the ini with the GOG version.
Please note the error might be entirely mine, but I am not sure whether its user error or a bug with the new version of GOG.

**To reproduce**
Install GOG Version of Skyrim
Install SSEedit
Open Program

**Expected behavior**
For SSEedit to run as normal as per Steam version of the game.

**Screenshots**

**Additional context**

**Comment by Infernio** [comment]
On the command line, pass:
```
-D:"C:\GOG\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\Documents\My Games\Skyrim Special Edition GOG\Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG\plugins.txt"
```
Adjust the `C:\GOG\Skyrim Anniversary Edition\Data` path to match where you installed GOG/Skyrim and replace `admin` with your own username.

**Comment by LazyDunmer** [comment]
Thanks for responding so quickly. I've given it a go, but have obviously taken a misstep somewhere, but will persevere until I get it right as you have confirmed that it does work with GOG.

Edit: Thanks got it sorted

**Comment by Rful68** [comment]
Thank you so much! I've been racking my brain on this and was close to checking into the local mental facility, drumming my lips. Working beautifully!! Thanks again

**Comment by gorgaknight** [comment]
Please could you assist me? I would greatly appreciate it.

I am having a similar issue. 
I installed Skyrim SE GOG version
I installed Mod organizer 2

When I load SSEEdit from MOD 2 I get this error message
Fatal: Could not open registry key: \SOFTWARE\Bethesda Softworks\Skyrim Special Edition.

Per an online thread I found I edited the registry by adding this 
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Skyrim Special Edition]
"Installed Path"="E:\\DRMFreeLibrary\\Skyrim Anniversary Edition"

After I added the above reg keys, SSEEdit load from MO2 without the above error pop-up box. But now I get this new error.
Fatal: Could not find ini

Skyrim SE is installed to this directory (this is SE but GOG creates a folder called AE not sure why)
E:\DRMFreeLibrary\Skyrim Anniversary Edition

I have these 2 Skyrim Folders under appdata \ local
C:\Users\xxx\AppData\Local\Skyrim Special Edition - Contains 1 file "Plugins.sseviewsettings.txt"
C:\Users\xxx\AppData\Local\Skyrim Special Edition GOG - Contains NO files

My .ini files are located here
C:\Users\xxx\Documents\My Games\Skyrim Special Edition GOG
Skyrim.ini
SkyrimPrefs.ini

The "plugin.ini" and Skyrim.ini files are located here and contain the exact same files
C:\Documents and Settings\xxx\AppData\Local\ModOrganizer\Skyrim Special Edition\profiles\Default
C:\Users\xxx\AppData\Local\ModOrganizer\Skyrim Special Edition\profiles\Default

This is from the log file
SSEEdit 4.0.4 (103758D4) starting session 2022-11-23 09:08:04
Using Skyrim Special Edition Data Path: E:\DRMFreeLibrary\Skyrim Anniversary Edition\Data\
Using Backup Path: E:\DRMFreeLibrary\Skyrim Anniversary Edition\Data\SSEEdit Backups\
Using Scripts Path: E:\My Data\2.Entertainment\Games\Games2\Skyrim SE - GOG\Mods\SSEEdit 4.0.4\Edit Scripts\
Using Cache Path: E:\DRMFreeLibrary\Skyrim Anniversary Edition\Data\SSEEdit Cache\
Using ini: C:\Users\xxx\Documents\My Games\Skyrim Special Edition\Skyrim.ini
Fatal: Could not find ini

From What I can tell is that SSEEdit is looking for the "ini: file in
C:\Users\xxx\Documents\My Games\Skyrim Special Edition\ - This Folder does not exist
C:\Users\xxx\AppData\Local\Skyrim Special Edition GOG\ - This is what the GOG version of created 

I have also run Shyrim a few times using the Skyrim launcher "SkyrimSELauncher.exe"

Not sure on how to fix this?

Please could you assist me? Thank You!

**Comment by BellCubeDev** [comment]
If you're interested in a quick-and-dirty workaround, you can create a Symbolic Link to redirect xEdit to read the right path using the following command:
```bat
mklink /d "C:\Users\%username%\Documents\My Games\Skyrim Special Edition" "C:\Users\%username%\Documents\My Games\Skyrim Special Edition GOG"
```

**Comment by gorgaknight** [comment]
Thank You so much. That Fixed the issue.
Again Thank you!!!

**Comment by ElminsterAU** [comment]
xEdit currently only officially supports Steam versions of all games it supports.

**Comment by H4RP00N770X** [comment]
I do wonder why no one is able to make a video out of this. I tried the command line from Vortex and SSEedit is still not working...

**Comment by uityuyth232134** [comment]
Универсальное решение для всех!!!!!(Ничего мне не помогло кроме этого варианта(обшарил весь интернет ничего не помогло), можно сказать что до этого додумался почти сам). Решил помочь всем бедолагам(не стоит благодарностей)



Решение: Если вы установили Skyrim пиратку(non steam) как и я и у вас SSEEdit не находит игру, все просто, делайте как я.

1 - удаляем скайрим (Если это для вас не проблема!) ( возможно можно и без удаления игры установить по соседству вторую игру но это все только на ваш страх и риск (не проверял!!!!!))

​2 - устанавливаем пиратку ​Steam​ версии ( запустите игру через steam и выйдите )

​3 - у вас в директории должен появиться путь к игре, и все готово. ( рекомендую устанавливать игру steam и non steam в одно и то же место)

4 - Теперь вы можете удалить steam версию и поставить пиратку non steam ​(у меня это GOG-версией Skyrim AE) ( тест проводил именно с этой версией игры)

**Comment by harungulmez** [comment]
*uck this shit trying to do this but searched all the *ucking google to solve this for 4 hours straight none of them works guess needs to play with *ucking bethesda's dirty dlc and plugins

**Comment by GacrivaStudio-hub** [comment]
> On the command line, pass:
> 
> ```
> -D:"C:\GOG\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\Documents\My Games\Skyrim Special Edition GOG\Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG\plugins.txt"
> ```
> 
> Adjust the `C:\GOG\Skyrim Anniversary Edition\Data` path to match where you installed GOG/Skyrim and replace `admin` with your own username.

where do you add this command?

**Comment by Baernergieu** [comment]
> If you're interested in a quick-and-dirty workaround, you can create a Symbolic Link to redirect xEdit to read the right path using the following command:
> 
> ```batchfile
> mklink /d "C:\Users\%username%\Documents\My Games\Skyrim Special Edition" "C:\Users\%username%\Documents\My Games\Skyrim Special Edition GOG"
> ```

I`m relativ new either on skyrim and MO2 so: where i can type in this command?

**Comment by nerwus3456** [comment]
> > If you're interested in a quick-and-dirty workaround, you can create a Symbolic Link to redirect xEdit to read the right path using the following command:
> > ```batchfile
> > mklink /d "C:\Users\%username%\Documents\My Games\Skyrim Special Edition" "C:\Users\%username%\Documents\My Games\Skyrim Special Edition GOG"
> > ```
> 
> I`m relativ new either on skyrim and MO2 so: where i can type in this command?

Command Prompt

**Comment by Baernergieu** [comment]
> ```batchfile
> mklink /d "C:\Users\%username%\Documents\My Games\Skyrim Special Edition" "C:\Users\%username%\Documents\My Games\Skyrim Special Edition GOG"
> ```

Thank you very much ! I`d always looked (like a complete idiot/being complete loss) for a command line in MO2 ...;-)))

No it works..!

**Comment by J0Santos** [comment]
It took me 3 hours to figure out what everyone here and on other websites was saying. I'm very new to modding so everything was tough to understand. 

If you are like me and are using Vortex, follow these steps.

On the Dashboard, go to tools and if SSEEdit is not there yet, add it by clicking on the big plus icon inside the section and selecting "New":

![imagem](https://github.com/TES5Edit/TES5Edit/assets/78555896/69d0d70a-5c5a-46b8-982d-eea7502d5631)

A new popup like this will appear

![imagem](https://github.com/TES5Edit/TES5Edit/assets/78555896/6984a20a-2d16-410b-a01d-bfe56371a53c)


Fill the fields accordingly:

**Name:** Whatever name you want to call the tool, I'd suggest keeping it standard and calling it "SSEEdit"
**Target:** Press the folder icon on the right and select the SSEEdit.exe. 
**Command Line:** 
> On the command line, pass:
> 
> ```
> -D:"C:\GOG\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\Documents\My Games\Skyrim Special Edition GOG\Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG\plugins.txt"
> ```
> 
> Adjust the `C:\GOG\Skyrim Anniversary Edition\Data` path to match where you installed GOG/Skyrim and replace `admin` with your own username.

After filling these, press "Save" and SSEEdit should now work since the remaining fields are not necessary.

If, when already inside SSEEdit, you get an error message saying it couldn't find _.ini_ file, all you have to do is start the game through GOG once. The file will automatically be created and you can close the game right after.

I hope this helps save some headaches for anyone who needs it

**Comment by GonStar59** [comment]
Just to tell people in my case Im using windows 11 and I have my laptop on spanish the changes should be:
-D:"C:\GOG\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\OneDrive\Documentos\My Games\Skyrim Special Edition GOG\Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG\plugins.txt"

as you can see it has aded oneDrive and documents has to be in spanish as documentos i hope it helps someone

**Comment by kainlt04** [comment]
> It took me 3 hours to figure out what everyone here and on other websites was saying. I'm very new to modding so everything was tough to understand.
> 
> If you are like me and are using Vortex, follow these steps.
> 
> On the Dashboard, go to tools and if SSEEdit is not there yet, add it by clicking on the big plus icon inside the section and selecting "New":
> 
> ![imagem](https://private-user-images.githubusercontent.com/78555896/307535461-69d0d70a-5c5a-46b8-982d-eea7502d5631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzMyODUsIm5iZiI6MTcxNDk3Mjk4NSwicGF0aCI6Ii83ODU1NTg5Ni8zMDc1MzU0NjEtNjlkMGQ3MGEtNWM1YS00NmI4LTk4MmQtZWVhNzUwMmQ1NjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA1MjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMjE0MDc0OWI3MGFiMWY2OTk3MDE3ZWRhZjZlYjFlYzgxMGFjMjNiODBiNjdhODNiMDA5MmRkODdmOTI5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoMtV6YTqTZYct4e-mXg0nYcQYJMe-_OrRFavkG1NiM)
> 
> A new popup like this will appear
> 
> ![imagem](https://private-user-images.githubusercontent.com/78555896/307535605-6984a20a-2d16-410b-a01d-bfe56371a53c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzMyODUsIm5iZiI6MTcxNDk3Mjk4NSwicGF0aCI6Ii83ODU1NTg5Ni8zMDc1MzU2MDUtNjk4NGEyMGEtMmQxNi00MTBiLWEwMWQtYmZlNTYzNzFhNTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA1MjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzI3MzAyODI3ZGI0Y2U0MTRiNTJhOTU2NTM1ZmEwN2YzNmZmZmQ4ZWU2NDg4YjYzOGQxYjRmYzY0NjBjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJQ_9RIuTFNqrhiN1QeyHIqJH5-VMEywYDAOCebrZQM)
> 
> Fill the fields accordingly:
> 
> **Name:** Whatever name you want to call the tool, I'd suggest keeping it standard and calling it "SSEEdit" **Target:** Press the folder icon on the right and select the SSEEdit.exe. **Command Line:**
> 
> > On the command line, pass:
> > ```
> > -D:"C:\GOG\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\Documents\My Games\Skyrim Special Edition GOG\Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG\plugins.txt"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Adjust the `C:\GOG\Skyrim Anniversary Edition\Data` path to match where you installed GOG/Skyrim and replace `admin` with your own username.
> 
> After filling these, press "Save" and SSEEdit should now work since the remaining fields are not necessary.
> 
> If, when already inside SSEEdit, you get an error message saying it couldn't find _.ini_ file, all you have to do is start the game through GOG once. The file will automatically be created and you can close the game right after.
> 
> I hope this helps save some headaches for anyone who needs it

Thank you very much my brother, I spent many hours looking for a solution for that error, in my case using FO3Edit
For those who use Mod Organizer 2, the command line goes in "Arguments"

![11111](https://github.com/TES5Edit/TES5Edit/assets/81399372/50fb0711-0962-46f6-94bf-1e8a918a100e)

**Comment by ccamp612** [comment]
I am on GOG skyrim using NMN and after fixing the command prompt for SSEEdit I no longer get the INI error message. However for some reason it now says that there are no modules in the folder. I don't know if i missed something but assistance would be nice.

**Comment by aarchiee1965** [comment]
> I am on GOG skyrim using NMN and after fixing the command prompt for SSEEdit I no longer get the INI error message. However for some reason it now says that there are no modules in the folder. I don't know if i missed something but assistance would be nice.

Getting the same. Its found the ini file ok using the above instructions to find the ini but it still looks in the wrong folder for the gamesaves according to what comes up when you launch SSEEdit.

**Comment by Gabriel-Eredin** [comment]
> Levei 3 horas para descobrir o que todo mundo aqui e em outros sites estava dizendo. Sou muito novo em modding, então tudo foi difícil de entender.
> 
> Se você é como eu e usa o Vortex, siga estas etapas.
> 
> No Dashboard, vá em ferramentas e se o SSEEdit ainda não estiver lá, adicione-o clicando no grande ícone de adição dentro da seção e selecionando "Novo":
> 
> ![imagem](https://private-user-images.githubusercontent.com/78555896/307535461-69d0d70a-5c5a-46b8-982d-eea7502d5631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMTc5MDMsIm5iZiI6MTczNzAxNzYwMywicGF0aCI6Ii83ODU1NTg5Ni8zMDc1MzU0NjEtNjlkMGQ3MGEtNWM1YS00NmI4LTk4MmQtZWVhNzUwMmQ1NjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA4NTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYmJjMzU5ZTFjZWIwNmQzNTcxNWFhMmRjZWYxNTAxMDNiZTcwZWQ1YTE1MmQ5OGY1ZWNjZTBjNTc5ODE0ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-9oEv8pI6YrtslYJ-K8jdalrFcVHTZEbA7QPx0pwB2c)
> 
> Um novo pop-up como este aparecerá
> 
> ![imagem](https://private-user-images.githubusercontent.com/78555896/307535605-6984a20a-2d16-410b-a01d-bfe56371a53c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMTc5MDMsIm5iZiI6MTczNzAxNzYwMywicGF0aCI6Ii83ODU1NTg5Ni8zMDc1MzU2MDUtNjk4NGEyMGEtMmQxNi00MTBiLWEwMWQtYmZlNTYzNzFhNTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA4NTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTMzNWIyMDBkMmFjODQwMDZhNDc2YTljNTY0NThlZGExOWJiZDc0MDU5MzYxMzQzOTU0MjU5ZDY4ZGZhMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DSU2CwkJqoA80p2YpfIeavsd0r5Jxw2TXQ0hMiYs8rs)
> 
> Preencha os campos adequadamente:
> 
> **Nome:** Seja qual for o nome que você deseja chamar para a ferramenta, sugiro mantê-lo padrão e chamá-lo de "SSEEdit". **Alvo:** Pressione o ícone da pasta à direita e selecione SSEEdit.exe. **Linha de comando:**
> 
> > Na linha de comando, passe:
> > ```
> > -D:"C:\GOG\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\Documents\My Games\Skyrim Special Edition GOG\Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG\plugins.txt"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ajuste o `C:\GOG\Skyrim Anniversary Edition\Data`caminho para corresponder ao local onde você instalou o GOG/Skyrim e substitua `admin`pelo seu próprio nome de usuário.
> 
> Após preenchê-los, pressione "Salvar" e o SSEEdit deverá funcionar agora, pois os demais campos não são necessários.
> 
> Se, já dentro do SSEEdit, você receber uma mensagem de erro dizendo que não foi possível encontrar o arquivo _.ini_ , tudo o que você precisa fazer é iniciar o jogo pelo GOG uma vez. O arquivo será criado automaticamente e você poderá fechar o jogo logo em seguida.
> 
> Espero que isso ajude a evitar algumas dores de cabeça para quem precisa

THANK YOU VERY MUCH!!!!!!! GOD BLESS YOU!!!

**Comment by McPixelat0r** [comment]
> It took me 3 hours to figure out what everyone here and on other websites was saying. I'm very new to modding so everything was tough to understand.
> 
> If you are like me and are using Vortex, follow these steps.
> 
> On the Dashboard, go to tools and if SSEEdit is not there yet, add it by clicking on the big plus icon inside the section and selecting "New":
> 
> ![imagem](https://github.com/TES5Edit/TES5Edit/assets/78555896/69d0d70a-5c5a-46b8-982d-eea7502d5631)
> 
> A new popup like this will appear
> 
> ![imagem](https://github.com/TES5Edit/TES5Edit/assets/78555896/6984a20a-2d16-410b-a01d-bfe56371a53c)
> 
> Fill the fields accordingly:
> 
> **Name:** Whatever name you want to call the tool, I'd suggest keeping it standard and calling it "SSEEdit" **Target:** Press the folder icon on the right and select the SSEEdit.exe. **Command Line:**
> 
> > On the command line, pass:
> > ```
> > -D:"C:\GOG\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\Documents\My Games\Skyrim Special Edition GOG\Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG\plugins.txt"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Adjust the `C:\GOG\Skyrim Anniversary Edition\Data` path to match where you installed GOG/Skyrim and replace `admin` with your own username.
> 
> After filling these, press "Save" and SSEEdit should now work since the remaining fields are not necessary.
> 
> If, when already inside SSEEdit, you get an error message saying it couldn't find _.ini_ file, all you have to do is start the game through GOG once. The file will automatically be created and you can close the game right after.
> 
> I hope this helps save some headaches for anyone who needs it

YOU ARE AN ABSOLUTE LEGEND. THANK YOU YOU GLORIOUS PERSON!!

**Comment by ThunderFall11** [comment]
-D:"C:\Program Files (x86)\GOG Galaxy\Games\Skyrim Anniversary Edition\Data" -I:"C:\Users\admin\OneDrive\Documentos\My Games\Skyrim Special Edition GOG/Skyrim.ini" -P:"C:\Users\admin\AppData\Local\Skyrim Special Edition GOG/Plugins.txt"

this work for people who install on program files x86 on windows 11
