### ISSUE TITLE
[Solved]FNVEDIT doesnt show plugins' data in right tab

### ISSUE THREAD

**Issue by giathai** [TES5Edit/TES5Edit#1045]
Recently I have a continueing bug of FNVEDT 4.04 doesnt show data of an item across several plugins.
Example, I open a load list of TTW with an extra mod for conversion.

But the item, armor, weapon, npc etc... doesnt show data that come from masters. Some only one line, some show some lines, some just plainly show nothing other than the name of masters on the right tab. Change to xedit 64bit doesnt improve~

I dont know why that is. My original load order doesnt have more than 70 esp/esm. And even so, a session with TTW masters plus one or three mods shouldnt cause trouble since I did it before.

This bug happen quite sudden and unexplainable. Anybody know why that is and any help????

**Comment by VlitS** [comment]
Right click on the right side, and uncheck "hide no conflict rows"

**Comment by giathai** [comment]
On the dot! Thank you, thank you. The whole dang issue drove me crazy the last few days.
