### ISSUE TITLE
Background Loader: Fatal: <Exception: Unknown archive format>

### ISSUE THREAD

**Issue by psw14kr** [TES5Edit/TES5Edit#1049]
**What is the version of xEdit you are using?**
FO4Edit 4.0.4 (5B1C2C51) starting session 2022-10-27 02:09:36

**Describe the bug**

An error occurred while loading modules editing is disabled
Background Loader: Fatal: <Exception: Unknown archive format>

**Expected behavior**

After running FO4EDIT, a problem occurs just by checking Fallout4.esm and pressing the OK button.
This sentence was written using a translator.

**Screenshots**
![FO4EDIT 02](https://user-images.githubusercontent.com/35949882/198093710-4dac92bc-4731-4b3b-9422-d8345474dfa0.png)
![FO4EDIT 03](https://user-images.githubusercontent.com/35949882/198093733-37ade50b-e113-4045-a185-61fae7cf41e6.png)

[FO4EditException.log](https://github.com/TES5Edit/TES5Edit/files/9872227/FO4EditException.log)

**Comment by ElminsterAU** [comment]
You either have corrupted files in your data folder and/or your games .ini file lists an `dlcrobot.esm` to be loaded as a resource archive (which it isn't).

Also, what the heck is going on with your path separators?

This btw is not an issue with xEdit and shouldn't be reported here.

This is a support question which should be handled via the xEdit discord. (See button in the top right corner of xEdit to join.)
