### ISSUE TITLE
Incorrect "Loading Active Plugin List" How do I change it??

### ISSUE THREAD

**Issue by PFC-Valdez** [TES5Edit/TES5Edit#1050]
**What is the version of xEdit you are using?**
It is not an actual bug pop-up rather an issue where SSEEdit automatically connects to the wrong intended folder game files where all my mods are not located. I am using version 4.0.4.

**Describe the bug**
SSEEdit keeps pulling Skyrim SE from wrong files, specifically from the user files which I assume automatically download with cloud drive. This causes me not to be able to load and edit my mods downloaded into my local drive on a separate folder other than user and program files. I can edit the game files from the user folders, but will not reflect the game files associated with my mods on my local drive Steam folder.

**To reproduce**
1. On start-up no mods are displayed

**Expected behavior**
What I expect to happen is to open the SSEEdit.exe and automatically have all my game files and mods load altogether so that I can edit them. Then see those edits through LOOT to check my progress. 

**Screenshots**

**Additional context**
I did try download the mods into the file location that SSEEdit automatically connects to, but I cannot find it. What I hope to hear is a manual way that I can set the "Loading Active Plugin List" on SSEEdit 4.0.4 to exact file location of my choice as I did with LOOT because I had a similar problem there too.

**Comment by ElminsterAU** [comment]
xEdit works just fine for literally millions of people. Whatever your problem is, it's not an bug in xEdit.

If you have support questions, they should be addressed to the xEdit Discord (see the button in the top right corner of xEdit). 

GitHub issues are for reporting bugs (which this isn't).
