### ISSUE TITLE
[Skyrim SE - GoG]

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#1058]
Using xEdit 4.0.4c

xEdit does not correctly identify the location of the plugins.txt file or the Skyrim.ini file if it is launched from within the Data folder of the GoG version of the game.

The start of the log when executed:

```
SSEEdit 4.0.4c (264F2054) starting session 2022-11-23 22:07:51
Using Skyrim Special Edition Data Path: C:\GoG Games\Skyrim Anniversary Edition\Data\
Using Backup Path: C:\GoG Games\Skyrim Anniversary Edition\Data\SSEEdit Backups\
Using Scripts Path: C:\GoG Games\Skyrim Anniversary Edition\Edit Scripts\
Using Cache Path: C:\GoG Games\Skyrim Anniversary Edition\Data\SSEEdit Cache\
Using ini: C:\Users\[username]\Documents\My Games\Skyrim Special Edition\Skyrim.ini
Using save path: C:\Users\[username]\Documents\My Games\Skyrim Special Edition\Saves\
Using Creation Club Content list: C:\GoG Games\Skyrim Anniversary Edition\Skyrim.ccc
Using plugin list: C:\Users\[username]\AppData\Local\Skyrim Special Edition\Plugins.txt
Using settings file: C:\Users\[username]\AppData\Local\Skyrim Special Edition\Plugins.sseviewsettings
Using language: English
Using general string encoding: 1252  (ANSI - Latin I)
Using translatable string encoding: 1252  (ANSI - Latin I)
Using VMAD string encoding: 65001 (UTF-8)
Loading active plugin list: C:\Users\[username]\AppData\Local\Skyrim Special Edition\Plugins.txt
[00:00] Background Loader: starting...
```

Rather than C:\Users\[username]\AppData\Local\Skyrim Special Edition\ it should be locating the plugins.txt file in :\Users\[username]\AppData\Local\Skyrim Special Edition GOG\

Skyrim.ini should be located in C:\Users\[username]\Documents\My Games\Skyrim Special Edition GOG\

These folders do not have a different name when run with the AE version so it should work for both types of GOG installs once the path detection is corrected.

**Comment by ElminsterAU** [comment]
xEdit currently has no official support for any non-steam version of any otherwise supported game

**Comment by bukiru** [comment]
it's very bad, that this tool can't do simple things....
for me, I had to make hardlink with mklink
