### ISSUE TITLE
changing values in override doesn't update record color on left side

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#1060]
**What is the version of xEdit you are using?**
FNVEdit 4.1.4d EXTREMELY EXPERIMENTAL (02F3F04E) starting session 2022-11-28 13:36:39

**Describe the bug**
whenever you override a record, it will get a color on the left window if it didn't have one already. when you then change a value in the record, it should change the color, ex from green to yellow if it was itm, but on the file/record list on the left the color will remain the same as it was on load/first override until it's forced to reset, usually by restarting the program. saving doesn't update it either.

**To reproduce**
1. override any record
2. change the value in it

**Expected behavior**
expected the record's color to change from green to yellow on the left, but it remained green.

**Comment by ElminsterAU** [comment]
should be fixed with commit above, which will be in 4.1.4e
