### ISSUE TITLE
Unable to edit ammunition weight value

### ISSUE THREAD

**Issue by Ghostwalker71** [TES5Edit/TES5Edit#1062]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.
SSEEdit 4.0.4 (103758D4) starting session 2022-12-17 18:44:33

**Describe the bug**
In Skyrim version 1.6.640.0.8 ammunition has a weight value to work with the survival content. This new weight value is not enabled in SSEEdit and cannot be edited and/saved to a new esp file.

**To reproduce**
1. Go to '...' any arrow in a mod file
2. Click on '....' the weight value  and try to edit the entry and save the edit.
3. See error as the value will not save

**Expected behavior**
The edited weight value of ammunition should save and be useable in game

**Screenshots**

**Additional context**
I'm going to blindly assume that this can be fixed in 5 minutes and will be ready to use by tomorrow. What? that's not how coding works?! ;)

**Comment by ElminsterAU** [comment]
It's working fine. I didn't change anything. This has always worked.
![image](https://user-images.githubusercontent.com/27037648/208272121-ace85f94-a929-405c-9212-46cd125b5fb5.png)

**Comment by Ghostwalker71** [comment]
Thanks for the lightning fast response, It looks like I get to rebuild my mod again. I attempted many times and ways to edit the weight value in my mod, but forgot the simple step of making a new esp and trying to edit there.
