### ISSUE TITLE
Feature Request: Provide build instructions

### ISSUE THREAD

**Issue by nikitalita** [TES5Edit/TES5Edit#1066]
I needed a bug fix that is on the current master but not in the current release, so I attempted to build this from source. 

I see this is a Pascal project. I have no idea how to build a pascal project, and there isn't any build documentation. Can you please provide instructions on how to do so?

**Comment by ElminsterAU** [comment]
Instructions for how to setup the necessary development environment are in the #dev-support channel on the xEdit discord.

Given your complete lack of knowledge in regards to Delphi, your much much better option is to have patience and wait for the next release though.
