### ISSUE TITLE
[Feature Request] Sort LCTN Record data tables by Form ID?

### ISSUE THREAD

**Issue by robertgk2017** [TES5Edit/TES5Edit#1072]
I know the program has to read the data as it is written in the plugin, but would it be possible to have the various data tables on a LCTN record sorted?

Say sorted by form ID, and then stacked at the top visually?

[https://imgur.com/a/X39aKv0](url)   Here is an example, using the FalkreathLocation.   ACID table, Dawnguard - Hearthfires - and another mod are touching this record and table.   Could each plugins entries for that table be sorted by FormID and pushed up to the top of the field list for easier condensed viewing?

**Comment by zilav** [comment]
It is unknown if the order matters there or not. To be safe they were made unsorted.

**Comment by robertgk2017** [comment]
would it be possible to make it a sorted field exclusively in xEdit, but not effect otherwise the order the entries are written?   Or would that be an egregious amount of work?

**Comment by VlitS** [comment]
The problem is how you would edit the order, if order matters and it was sorted despite that. The only time things will be sorted in xEdit is if it is confirmed/verified that order doesn't matter.

**Comment by robertgk2017** [comment]
Im probably wording this wrong.  I'm only thinking about it being sorted visually, having no impact whatsoever on the order it is written in the plugin file.  This ain't a huge deal, I just figure it'd be a little easier visually as i'm tryin to actually figure out the ins and outs of these things.

**Comment by robertgk2017** [comment]
Feature has been implemented, issue closed
