### ISSUE TITLE
Why is proprietary BCompare.exe hard-coded?

### ISSUE THREAD

**Issue by TryToRemember** [TES5Edit/TES5Edit#1076]
**What is the version of xEdit you are using?**
4.0.4 & 4.0.4c 

**Describe the bug**
in xEdit/xeViewElementsForm.pas, bcompare.exe is hardcoded? Beyond Compare is paid software, we can d/l 30-day trialware not shareware, he apparently enforces timeout? Why would an open source project use this? Is it yours, a friend of yours, are you promoting it? Am I missing something? Is there a way to set this on the Options page? Can I manually edit the appdata\local\blahblah\*viewsettings ini file?

[[ Sidebar - any logical (or particular) reason the configuration file isn't, I don't know, properly named and with the exe like every other program since the era of TI-99/4As and TRS-80s on datacassettes? Or just use the registry! Is this some Pascal thing? Delphi thing? Why do this this way?? ]]

**To reproduce**
Click the compare button when two or more files are in your modal view window.
It will complain it cannot launch bcompare.exe

**Expected behavior**
Something besides this.

**Screenshots**
Unnecessary. 

**Additional context**
There are plenty of PE 32/64 diff-style GUI programs with similar functionality; two that immediately come to mind are Meld (https://meldmerge.org) and WinMerge (https://winmerge.org) and can be passed the files as %1 %2 %3 etc. the same way, or, both being open source and more permissive licensing than xEdit's MPL2, could be bundled, callable as function, even source internal as part of xEdit's compilation. Your call.

**Recommended solution**
Perhaps a configurable field under Options, not requiring a manual edit, symlinking, or editing the .pas source and re-compiling?

**Workaround**
Since it's hard-coded, it's easy enough to have the aforementioned meld or winmerge and just alias or symbolic link to the name bcompare.exe in the xEdit directory and this works.

**Comment by zilav** [comment]
It was a requested feature, and the author of huge well known modding project specifically asked for Beyond Compare. Nothing else.

**Comment by Infernio** [comment]
It's not hardcoded, that's just the default. You can change it to whatever comparison program you want and adjust what parameters are passed in as well. I use KDiff3, for example.

**Comment by Infernio** [comment]
![image](https://user-images.githubusercontent.com/2845240/217606009-362d9165-140e-4f10-8d76-c739e2d0a209.png)

There, click the little arrow next to compare and choose "Configure external tool". Then choose an executable and adjust the parameters:

![image](https://user-images.githubusercontent.com/2845240/217606705-8d05a00d-4d05-4a02-bf11-436505d36d32.png)

**Comment by TryToRemember** [comment]
Ahh you guys rock! Thanks greatly.

As an aside, can we reach out to said author, is he active? I get that he wants to be paid for his work, but if he knows it's in something that EVERY Bethesda game user who mods, has and will get used to using? Think he'd do it for it for free advertising? It doesn't even utilize the whole package, correct, the BCompare.exe is compiled standalone static. Would the xEdit project steering committee (eg you guys!) be up for this, contacting him for an include for credit and a link? Get another icon up there on the right for him?

Anyway, again, thanks. Closing.
