### ISSUE TITLE
[Feature] Extra options to manipulate sorted index lists

### ISSUE THREAD

**Issue by robertgk2017** [TES5Edit/TES5Edit#1079]
For sorted index lists, there is the function to Right Click > Move Up/Down.   Would it be possible to add an addition to this to say Move entry to X index.

e.g. i got an index list with 500 entries, and I want to take 250 and move it to 100.   I'd like to be able to right click on 250 and click on move to X, and input 100 and it'll go there?  resulting in the original 100 being shifted down to 101, and so on to 249 taking 250s place.

On top of this how about the ability to right click and swap 2 entries?  e.g if i wanted to take 250 and put it at 100, and take 100 and put it at 250.   Right click > some button > input the 2 to be swapped?

Or even a third option, and this one might be the most complicated code wise.  Allow the scripting engine to be able to execute the Move Up/Down functions?

For context i'm thinking my use case is only in SSE mode, but i see no reason this shouldn't be on all the game modes.

**Comment by ElminsterAU** [comment]
you can just hold ctrl+up and it should keep moving pretty quickly through the list until you let go?

**Comment by robertgk2017** [comment]
yes holding this works, not an issue anymore.
