### ISSUE TITLE
CELL Records: XPRI and XCRI Subrecord Naming

### ISSUE THREAD

**Issue by Glitchfinder** [TES5Edit/TES5Edit#1080]
**What is the version of xEdit you are using?**
FO4Edit 4.0.4 (5B1C2C51) starting session 2023-03-18 18:25:53

**Describe the requested change**
Currently the XPRI and XCRI subrecords for the CELL record are named "Physics References" and "Combined References" in release builds. The "PRI" and "CRI" records are likely acronyms of "PreVis Reference Index" and "Combined Reference Index," respectively.

**Additional context**
These subrecords contain data used by the precombine and previs optimization systems for Fallout 4.

XCRI is filled during the precombine generation step, and contains an index of references that have precombined, mapping them to their respective meshes. Ingame, this suppresses loading the references while precombines are enabled. It also contains a list of all precombined meshes for the given cell.

XPRI is filled during both the precombine and previs generation step, but the data during the precombine step appears to be unused and nonfunctional, and is prone to master errors. The data filled in during the previs step, however, is accurate. Ingame, any references included in the XPRI subrecord will be culled by previs in the same manner as precombined objects, so long as they are contained within the previs data. This can be demonstrated by moving one of the references from the XPRI subrecord. Once moved, the reference (which is typically a container or furniture object) will still be visually culled as though it were in its original position.

**Comment by ElminsterAU** [comment]
Fixed in 4.1.5
