### ISSUE TITLE
Access denied when trying to save edited esp

### ISSUE THREAD

**Issue by JaySher123** [TES5Edit/TES5Edit#1082]
Started to face this error while trying to merge npcs from different mods, at first it worked just fine nut now its not letting me edit

 Error "EFCreateError": "Cannot create file "E:\lost legacy - manual\The Elder Scrolls V Skyrim Special Edition\Data\The Ordinary Women.esp". The process cannot access the file because it is being used by another process"
[00:00] Errors have occured. At least one file was not saved.

**Comment by ElminsterAU** [comment]
the error tells you EXACTLY, word for word, what the problem is.
