### ISSUE TITLE
Path directory

### ISSUE THREAD

**Issue by echo3355** [TES5Edit/TES5Edit#1087]
Using SSEEdit 4.0.4

Recently changed the directory path of the game. I simply copied everything to a new folder. I'm using MO2 and it loads the game correctly. Was told it's a bad idea to use ProgramFiles for the game. I changed it, but SSEEdit keeps looking for plugins in ProgramFiles. How can I tell SSEEdit to look for the plugin in the customized path I created.

**Comment by BuendelErdnuss** [comment]
Modify the executable in MO2
add to the Arguments: -d:"[path of your Skyrim Date folder]"
just without the square brackets

it also could be that u have to change the directory in steam
but u will probably get auto updates after that
