### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by satorkain** [TES5Edit/TES5Edit#1092]
TES5Edit 4.0.4 (Quick Auto Clean) (103758D4)

Recently installed Skyrim AE GOG. I choose to clean for example Update.esm or any other DLC. After finishing, right after the line in the log `Quick Clean mode finished.`, a window appears with the error `Access violation at address 00BF845C in module TES5EditQuickAutoClean.exe. Read of address 00000000` ([screenshot](https://imgtr.ee/images/2023/06/18/YF2oL.png)). I try to save the file, but I also get an error in the log:

```
[00:00] Saving: Update.esm.save.2023_06_18_16_30_49
[00:01] Error saving Update.esm.save.2023_06_18_16_30_49: File Update.esm contains top level group without known sort order: GRUP Top "VOLI"
[00:01] Errors have occured. At least one file was not saved.
```

Full log on [pastebin](https://pastebin.com/gDTbD9nk)

**Comment by ElminsterAU** [comment]
You must have worked really hard to get TES5Edit to work on files or was never meant to be used on.

**Comment by satorkain** [comment]
But why? I do everything according to the official instructions. The only difficulty was getting it to work with the GOG.

**Comment by VlitS** [comment]
Tes5Edit is for Oldrim, for Skyrim SE/AE (which is the same as SE, just a new update), you need SSEEdit. 

It is the same executable, so you just need to change any instance of TES5 to SSE (e.g TES5EditQuickAutoClean.exe -> SSEEditQuickAutoClean.exe).

**Comment by satorkain** [comment]
@VlitS Yes, it works! Thank you! And I tried before with xEdit, then with TES5Edit and got the same error.
