### ISSUE TITLE
Access Violation Error

### ISSUE THREAD

**Issue by Spankarea** [TES5Edit/TES5Edit#1097]
SSEEdit 4.0.4

access violation at address 01237667 in module 'SSEEdit.exe'. Read of address 0000000C. 

1. Load SSEEdit.exe
2. Edit any plugin(s)
3. Exit and save
4. See the error

It was working fine until about 2 days ago haven't changed anything load order-wise or in SSEEdit's installation folder or the location of SSEEdit and SSE.

[Screenshot of the error window.
](https://imgur.com/kudjxsx)

The actual SSEEdit window isn't showing any errors in its log and is saying it's saved properly, also reloading to check shows the edits are actually being saved. Reinstalling/using a fresh SSEEdit and or SSE install also reproduces the bug so it may be something on my end, though I haven't added any new programs or changed anything in my pc in a couple of months aside from updating Windows recently. Should also mention that SSEEditQuickAutoClean.exe isn't throwing this error, only SSEEdit.exe is.

**Comment by ElminsterAU** [comment]
no actionable information provided
