### ISSUE TITLE
Cannot open Worldspace Browser 

### ISSUE THREAD

**Issue by DavidAndrewWhite** [TES5Edit/TES5Edit#1098]
**What is the version of xEdit you are using?**
FO4Edit 4.0.4 (5B1C2C51) starting session 2023-08-14 10:32:27

**Describe the bug**
Attempting to open the Worldspace Browser results in a (NVidia?) pop-up on the upper right of my screen saying "A supported game is required to use this feature"

**To reproduce**

1. Select a Worldspace or Cell in the xEdit tree view
2. Press Alt-F3

**Expected behavior**
Pressing Alt-F3 should open the Worldspace Browser.

**Screenshots**
See attachment.

<img width="303" alt="error popup when opening Worldspace Browser" src="https://github.com/TES5Edit/TES5Edit/assets/141742404/35e36bb0-2eab-4e0b-8f91-729d876b7c17">

**Additional context**
I have a Steam installation of Fallout 4, and I'm using F4SE.

**Comment by zilav** [comment]
Just google `nvidia a supported game is required to use this feature`

**Comment by DavidAndrewWhite** [comment]
Interesting. This is the first time I've run into this issue.

I can start the Worldspace Browser normally using "Apply Script..." FWIW
