### ISSUE TITLE
Starfield PNDT.PPBD

### ISSUE THREAD

**Issue by vitrvvivs** [TES5Edit/TES5Edit#1123]
I would make a PR, but I'm having trouble describing this struct (running into type errors)

### PPBD

| type | desc | notes |
| --- | --- | --- |
| BIOM ref | biome
| float | surface_percent
| unknown | 4 bytes
| RSGD ref | resource generator override | only on unique planets
| int32 | array_len critters
| NPC_ ref | array of critters
| unused | | 00000000 on all planets
| int32 | array_len flora | 
| int32 | flora array member_size | always = 00000009
| FLOR ref | flora_struct model
| IRES ref | flora_struct resource from harvest
| int8 | flora_struc frequency? | possible values (base 10): 10, 15, 20, 25, 30, 35, 50, 70, 75, 80, 90, 94, 100
| int32 | mystery array length ? | 0 on all planets except 10 on Schrodinger II
| ... | mystery array | 160 bytes on Schrodinger II

**Comment by s9w** [comment]
Hey, I just saw this while we tried to make sense of this exact same structure, too. Any chance you're on discord for a little exchange of information?

**Comment by vitrvvivs** [comment]
I am `vitruvius` on discord. There are a handful of other things I've halfway figured out.

**Comment by s9w** [comment]
I took the liberty to implement this with some help. Thanks for putting this out! And I'm always up for discussions
