### ISSUE TITLE
Feature Request: Extend F2 to assigning editable elements

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#1196]
When you press F2, if the element is editable, you start to edit the field, but if the element does not exist, nothing happens. In that case, pressing F2 should also assign the element. Automate the intermediate steps. This would probably be implemented in the `TfrmMain.pmuNavPopup` procedure.

**Comment by ElminsterAU** [comment]
should be implemented with above referenced commit. Will be in 4.1.5b.
