### ISSUE TITLE
[SF] Adding Entries to a complex AVMD can result in an exception

### ISSUE THREAD

**Issue by gibzie90** [TES5Edit/TES5Edit#1223]
https://www.dropbox.com/scl/fo/qj85byc1oo4yq5fh5giqn/h?rlkey=pacpqia4g7v8hyteiqz7854fy&dl=0

i'm not sure how to easily share files here, so have a dropbox link instead.

i included test.esm and my project AerospaceCasualwear.esm
The last error/save in the log is from Test.esm, all others are from AerospaceCasualwear.esm

The error is easily repeatable by removing any simple group from the complex group and adding it again.

To repeat my exact steps in Test.esm = 
copy a complex group from old mars
copy the relevant simple groups from old mars
rename the links in the complex group to point to the newly copied simple groups.

**Comment by gibzie90** [comment]
The error also seems repeatable by adding new entries (with fields filled out) to simple groups

**Comment by ElminsterAU** [comment]
should be fixed with above commit. will be in 4.1.4s (or 4.1.5)
