### ISSUE TITLE
Feature Request: Ctrl+S actually save .esm (either option check box, or make it as default behaviour)

### ISSUE THREAD

**Issue by Aguinore** [TES5Edit/TES5Edit#1226]
**What is the version of xEdit you are using?**
SF1Edit 4.1.4r EXTREMELY EXPERIMENTAL (RC1 for 4.1.5) x64 (C1AEB452)

**Describe the bug**
Saving changes to .esm file (Ctrl+S) does not actually save changes, only "Queued renaming of save, will overwrtite on shutdown". Alt+S does nothing at all, at least no new messages and bolded fields stay bolded as if not saved

**To reproduce**
1. Change any field
2. Press ctrl+s
3. observe messages tab

**Expected behavior**
Changes to .esm file written and ready to be launched with the game

**Screenshots**

**Additional context**
 I do not want to restart both the game AND xEdit each time I want to test if changes I made have the effect I expected. If I wanted to create a backup copy of .esm file, I would do so manually. In any other app I use, ctrl+s actually write changes to disk, not queues them to be written on shutdown

**Comment by ElminsterAU** [comment]
The original file is open as a memory mapped file and can't be overwritten until the process ends and the file is no longer locked.

Reading What's New is going to show you a solution for your desired behaviour though.
