### ISSUE TITLE
Loading BA2 files impossible : Exception Unknown archive version...

### ISSUE THREAD

**Issue by StarKnightOne** [TES5Edit/TES5Edit#1228]
When loading "Starfield.esm" (only it) with xEdit : Loading BA2 files impossible !

xEdit version: Latest xEdit x64 : 4.0.4
Win10-64b, Steam Game

BATCH executable shortcut (arguments) :

> C:\Games\Steam\steamapps\common\Starfield\xFOEdit64.exe -AllowMasterFilesEdit -B:"D:\Modding\StarField\Tools\xEdit\xEditMods\Backup_files" -D:"C:\Games\Steam\steamapps\ common\Starfield\Data" -G:"D:\Modding\StarField\Tools\xEdit\xEditMods\Modded" -o:"D:\Modding\StarField\Tools\xEdit\xEditMods\Modded" -S:"D: \Modding\StarField\Tools\xEdit\Edit Scripts" -R:"D:\Modding\StarField\Tools\xEdit" -I:"C:\Games\Steam\steamapps\common\Starfield\Starfield.ini" l: fr -cp:utf-8 -IgnoreESL -SF -P:"C:\Users\Thier\AppData\Local\Starfield\Plugins.txt"

```
> [00:00] Background Loader: [Starfield - LODTextures.ba2] Loading Resources.
> [00:00] Background Loader: Fatal: <Exception: Unknown archive version 0x00000003>
```

Here is the content of the Starfield.ini file (game folder) below.
(I also customized StarfieldCustom.ini as it should be, user documents folder)

I probably forgot something, I don't know...
Is it because of the new BA2 file format ?
How can I resolve my problem, please ? :)

I'm very far from being an expert in modding, even if I modded in the past when we had a Creation Kit for Morrowind, Oblivion, Skyrim, Fallout4.

**EDIT : 
If I remove the archives in Starfield.ini, the ESM loads but I can't edit or modify anything afterwards, and create a plugin ESP/ESL.**

Starfield.ini :
```
> [General]
> uExterior Cell Buffer=36
> sGPUDefaultQualitySettingsJSON=DefaultGlobalGraphicsSettings.json
> 
> [Display]
> uiUpscaleTech=3
> 
> [Wwise]
> iDefaultExternalCodecID=4
> 
> [Archive]
> bInvalidateOlderFiles=1
> sResourceDataDirsFinal=STRINGS\, TEXTURES\, MUSIC\, SOUND\, INTERFACE\, MESHES\, PROGRAMS\, MATERIALS\, LODSETTINGS\, VIS\, MISC\, SCRIPTS\, SHADERSFX\
> SResourceArchiveList=Starfield - Animations.ba2, Starfield - DensityMaps.ba2, Starfield - FaceAnimation01.ba2, Starfield - FaceAnimation02.ba2, Starfield - FaceAnimation03.ba2, Starfield - FaceAnimation04.ba2, Starfield - FaceAnimationPatch.ba2, Starfield - FaceMeshes.ba2, Starfield - GeneratedTextures.ba2, Starfield - LODMeshes.ba2, Starfield - LODMeshesPatch.ba2, Starfield - Materials.ba2, Starfield - Meshes01.ba2, Starfield - Meshes02.ba2, Starfield - MeshesPatch.ba2, Starfield - Misc.ba2, Starfield - Particles.ba2, Starfield - PlanetData.ba2, Starfield - Terrain01.ba2, Starfield - Terrain02.ba2, Starfield - Terrain03.ba2, Starfield - Terrain04.ba2, Starfield - TerrainPatch.ba2
> sResourceIndexFileList=Starfield - LODTextures.ba2, Starfield - Textures01.ba2, Starfield - Textures02.ba2, Starfield - Textures03.ba2, Starfield - Textures04.ba2, Starfield - Textures05.ba2, Starfield - Textures06.ba2, Starfield - Textures07.ba2, Starfield - Textures08.ba2, Starfield - Textures09.ba2, Starfield - Textures10.ba2, Starfield - Textures11.ba2, Starfield - TexturesPatch.ba2
> SResourceArchiveMemoryCacheList=Starfield - Interface.ba2, Starfield - Misc.ba2
> sResourceStartUpArchiveList=Starfield - Interface.ba2, Starfield - Localization.ba2, Starfield - Shaders.ba2, Starfield - ShadersBeta.ba2, Starfield - WwiseSounds01.ba2, Starfield - WwiseSounds02.ba2, Starfield - WwiseSounds03.ba2, Starfield - WwiseSounds04.ba2, Starfield - WwiseSounds05.ba2, Starfield - WwiseSoundsPatch.ba2, BlueprintShips-Starfield - Localization.ba2
> sResourceEnglishVoiceList=Starfield - Voices01.ba2, Starfield - Voices02.ba2, Starfield - VoicesPatch.ba2
> sResourceLocaleVoiceList=Starfield - Voices_fr01.ba2, Starfield - Voices_fr02.ba2, Starfield - Voices_fr_Patch.ba2

```
The entire LOG:
```
> FO4Edit 4.0.4 x64 (2A83B8BB) starting session 2023-10-25 23:21:44
> Using Fallout4 Data Path: C:\Games\Steam\steamapps\common\Starfield\Data\
> Using Backup Path: D:\Modding\StarField\Tools\xEdit\xEditMods\Backup_files
> Using Scripts Path: D:\Modding\StarField\Tools\xEdit\Edit Scripts
> Using Cache Path: C:\Games\Steam\steamapps\common\Starfield\Data\FO4Edit Cache\
> Using ini: C:\Games\Steam\steamapps\common\Starfield\Starfield.ini
> Using save path: D:\Modding\StarField\Tools\xEdit\xEditMods\Modded\
> Using plugin list: C:\Users\XXXX\AppData\Local\Starfield\Plugins.txt
> Using settings file: C:\Users\XXXX\AppData\Local\Starfield\Plugins.fo4viewsettings
> Using language:
> Using general string encoding: 1252 (ANSI - latin I)
> Using translatable string encoding: 65001 (UTF-8)
> Using VMAD string encoding: 65001 (UTF-8)
> Loading active plugin list: C:\Users\XXXX\AppData\Local\Starfield\Plugins.txt
> [00:00] Background Loader: starting...
> [00:00] Background Loader: [Starfield - LODTextures.ba2] Loading Resources.
> [00:00] Background Loader: Fatal: <Exception: Unknown archive version 0x00000003>
> [00:19] Background Loader: finished
```

**Comment by jbostrus** [comment]
I'll be blunt. 4.0.4 any letter release does not support Starfield. It's not surprising that will fail horribly.

Starfield support is only in the 4.1.x chain. And only since the 4.1.4e releases.

Currently the only Starfield capable binary is available from the Discord server in the #xedit-builds channel. We currently have 4.1.4t in the server which supports editing. You must join the Discord server and download it from there if you want to use it before it's published out in binary form to GitHub or NexusMods.

Once a little more testing has been done and we're comfortable that it correctly writes files that aren't broken and doesn't have any show stopping bugs then a release here on GitHub and on NexusMods will be published. I believe EliminsterAU stated the version would be bumped to 4.1.5 when that occurs.

**Comment by StarKnightOne** [comment]
> I'll be blunt. 4.0.4 any letter release does not support Starfield. It's not surprising that will fail horribly.
> 
> Starfield support is only in the 4.1.x chain. And only since the 4.1.4e releases.
> 
> Currently the only Starfield capable binary is available from the Discord server in the #xedit-builds channel. We currently have 4.1.4t in the server which supports editing. You must join the Discord server and download it from there if you want to use it before it's published out in binary form to GitHub or NexusMods.
> 
> Once a little more testing has been done and we're comfortable that it correctly writes files that aren't broken and doesn't have any show stopping bugs then a release here on GitHub and on NexusMods will be published. I believe EliminsterAU stated the version would be bumped to 4.1.5 when that occurs.

OK, thanks, I understand better now, I saw more and more modders using xEdit and creating ESP/ESM/ESL, so I thought this version could do it, sorry !
So, I'm going to go to the discord, thanks.

**Comment by StarKnightOne** [comment]
> I'll be blunt. 4.0.4 any letter release does not support Starfield. It's not surprising that will fail horribly.
> 
> Starfield support is only in the 4.1.x chain. And only since the 4.1.4e releases.
> 
> Currently the only Starfield capable binary is available from the Discord server in the #xedit-builds channel. We currently have 4.1.4t in the server which supports editing. You must join the Discord server and download it from there if you want to use it before it's published out in binary form to GitHub or NexusMods.
> 
> Once a little more testing has been done and we're comfortable that it correctly writes files that aren't broken and doesn't have any show stopping bugs then a release here on GitHub and on NexusMods will be published. I believe EliminsterAU stated the version would be bumped to 4.1.5 when that occurs.

I am looking for the link to download xEdit 4.1.x to be able to create my own mods, can you give it to me, please ?
or the right / good discord url link ?

**Comment by jbostrus** [comment]
This should be the same link to the server that you get from the button in xEdit https://discord.gg/5t8RnNQ

Then you'll want the channel #xedit-builds which is towards the bottom of the xedit group (2nd group of channels). Not sure if this will work but this should link directly to the channel https://discord.com/channels/471930020454072348/518048160526893057

**Comment by ElminsterAU** [comment]
Every version of xEdit has a discord button in in the top right corner

**Comment by StarKnightOne** [comment]
OK thanks ! :)

**Comment by StarKnightOne** [comment]
Calistria on Discord = me
I found it and downloaded it.
