### ISSUE TITLE
Starfield Quest Priority and Quest Delay Time reversed?

### ISSUE THREAD

**Issue by ghost** [TES5Edit/TES5Edit#1232]
**What is the version of xEdit you are using?**
SF1Edit 4.1.4u EXTREMELY EXPERIMENTAL (RC4 for 4.1.5) x64 (C0729E26) starting session 2023-10-27 12:25:38

**Describe the bug**
xEdit seems to have mislabeled the fields in the DNAM of QUST records.  The console command SQV shows quest priority is equal to the Delay Time in the DNAM, not the Priority.  Quest priority seems to behave accordingly, e.g. setting a Delay Time in quest A that is higher than the one in quest B causes quest A's AI packages to take precedence.

**To reproduce**
1. Copy as Override any Quest into a new plugin
2. Change the copied Quest's DNAM->Priority and DNAM->Delay Time
3. Run the game, open console, and do SQV on the QUST Form ID
4. The Priority shown in SQV will be equal to the Delay Time you set above, not the Priority

**Expected behavior**
Priority should be the same in SQV and xEdit

**Comment by jbostrus** [comment]
Good catch. Should be fixed with the commit I just pushed. Awaiting new build.
