### ISSUE TITLE
GBFM Component Data - Property Sheet

### ISSUE THREAD

**Issue by Jimmison** [TES5Edit/TES5Edit#1242]
**What is the version of xEdit you are using?**
SF1Edit 4.1.5 EXPERIMENTAL x64 (C857BD90) starting session 2023-11-04 19:52:50

**Describe the bug**
When adding "Components - Component Data - Property Sheet" (GBFM) the first record is created incorrectly.
in this case, the addition of the second record (Property Sheet) occurs only on the second attempt
if the bad entry is not deleted, then the entire section  (Component X) is saved incorrectly

![3](https://github.com/TES5Edit/TES5Edit/assets/148339168/6a6fe17c-b632-4863-8167-94be6c591264)

**To reproduce**
create file
add GBFM
add Components
add "Component Data - Property Sheet"

**Comment by ElminsterAU** [comment]
Should be fixed with the commit referenced above. Included in xEdit 4.1.5a, which has been posed in #xedit-builds on the xEdit Discord.

**Comment by ElminsterAU** [comment]
Note: even with the fix, what your screenshot shows wouldn't work because you forgot to set Component Type
