### ISSUE TITLE
problem with conversion FormID in scripts

### ISSUE THREAD

**Issue by Jimmison** [TES5Edit/TES5Edit#1246]
**What is the version of xEdit you are using?**
SF1Edit 4.1.5a EXPERIMENTAL x64 (AC1BF928) starting session 2023-11-06 14:03:43

**Describe the bug**
RecordByFormID() FileFormIDtoLoadOrderFormID() and possibly other functions don't work as they should

**To reproduce**
```
unit Test;

function Initialize: integer;
var
    e: IInterface;
    i: integer;
begin
    AddMessage(GetFileName(FileByIndex(0)));
    AddMessage(GetFileName(FileByIndex(1)));
    AddMessage(GetFileName(FileByIndex(2)));
    AddMessage(GetFileName(FileByIndex(3)));
    e := RecordByFormID(FileByIndex(0), $01, false);
    AddMessage(p(e));
    e := RecordByFormID(FileByIndex(3), $01, false);
    AddMessage(p(e));
    AddMessage(IntToHex(FileFormIDtoLoadOrderFormID(FileByIndex(3), $01),8));
    AddMessage('-------');
    AddMessage(IntToHex(FileFormIDtoLoadOrderFormID(FileByIndex(3), $02000001),8));
    e := RecordByFormID(FileByIndex(3), $02000001, false);
    AddMessage(p(e));
    e := RecordByFormID(FileByIndex(0), $02000001, false);
    AddMessage(p(e));
end;

function p(e: IInterface): string;
begin
    AddMessage('[' + Signature(e) + ':' + IntToHex(GetLoadOrderFormID(e),8) + '] from ' + GetFileName(GetFile(e)));
end;

end.
```
```
[00:00] Start: Applying script "ShipDoorway\Test"
Starfield.esm
Starfield.exe
BlueprintShips-Starfield.esm
testplugin.esm
[STAT:00000001] from Starfield.esm
[STAT:00000001] from Starfield.esm
00000001
-------
02000001
[KYWD:02000001] from testplugin.esm
[STAT:00000001] from Starfield.esm
[00:00] Done: Applying script "ShipDoorway\Test", Elapsed Time: 00:00
```

**Expected behavior**
```
[00:00] Start: Applying script "Test3"
Fallout4.esm
Fallout4.exe
DLCRobot.esm
testplugin.esp
[STAT:00000001] from Fallout4.esm
[KYWD:02000001] from testplugin.esp
02000001
-------
02000001
[KYWD:02000001] from testplugin.esp
[STAT:00000001] from Fallout4.esm
[00:00] Done: Applying script "Test3", Processed Records: 1, Elapsed Time: 00:00
```

**Screenshots**
![3](https://github.com/TES5Edit/TES5Edit/assets/148339168/ce169d1c-535e-4213-adfe-ceb9ad5cdacd)

**Comment by zilav** [comment]
They work exactly as they should, your expected behavior doesn't match the written code.
`e := RecordByFormID(FileByIndex(3), $01, false);`
You are trying to get record 00000001 from the first master of your plugin (Starfield.esm according to screenshot) which is [STAT:00000001]. First byte is the index in plugin's masters list.

**Comment by Jimmison** [comment]
You are not right. Read the description of these functions. This argument is "Local FormID" aka "FixedFormID", not a "LoadOrderFormID". I also showed the result of the script in version 4.0.4.

**Comment by ElminsterAU** [comment]
The behavior is correct. you are wrong.

**Comment by zilav** [comment]
Do you know how FormIDs are stored inside plugins? What's the difference between local FormIDs and load order corrected FormIDs?
Local FormID of your keyword is 02000001 because your plugin has 2 masters.
Local FormID 00000001 corresponds to the first master of your plugin which is Starfield.esm

**Comment by Jimmison** [comment]
Then I don't understand how to use it. I need to get an instance of an object based on a known FormID, but I can’t know what is loaded and how many and what masters the plugin has. I need to write a function that will calculate
id := (id and $FFFFFF) or (MasterCount(pluginfile)  shl 24)
I thought it was logical that this had already been done for me

**Comment by ElminsterAU** [comment]
Please use the xEdit Discord for support questions. TIA.
