### ISSUE TITLE
copy as override into not working for container forms with filled Component field

### ISSUE THREAD

**Issue by Marcurios** [TES5Edit/TES5Edit#1247]
with xEdit version 4.1.5

I also tried to make a new container form and drag the component data field values over, that doesn't work either.

see screenshot..

[[url=https://ibb.co/fvBGr36][img]https://i.ibb.co/VmrpMFn/Untitled-1.jpg[/img][/url]](https://i.ibb.co/Z65m5WS/Untitled-1.jpg)

**Comment by ElminsterAU** [comment]
### RTFM
https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.5/whatsnew.md#reflection-based-data-streams
