### ISSUE TITLE
Loading Time

### ISSUE THREAD

**Issue by AsgardTM** [TES5Edit/TES5Edit#1250]
SF1Edit 4.1.5a EXPERIMENTAL x64 (AC1BF928)

For some reason when I installed 4.1.5a the loading time has increased at almost 5 minutes anytime I open it. Why ?
I did have prior SF1edit 4.1.4r and the loading time was like under 1 min.

I deeply apologize if this is not the place to ask this, but I don't use Discord, sorry.

PS: Screenshot with last line : https://prnt.sc/R8jeStcyLC4D

**Comment by ElminsterAU** [comment]
Screenshot does not provide any useful information. Please provide the full log.

**Comment by AsgardTM** [comment]
I found this file. I don-t know which one you need.

[SF1Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/13291031/SF1Edit_log.txt)
[SF1Edit64Exception.log](https://github.com/TES5Edit/TES5Edit/files/13291035/SF1Edit64Exception.log)

**Comment by ElminsterAU** [comment]
You've turned on "track all editorid". Don't .

**Comment by AsgardTM** [comment]
Thank you. I don't know when I did that! Good to know.
Now is 36 seconds loading time.
Regards.
