### ISSUE TITLE
SF1Edit does not use paths specified in commandline arguments.

### ISSUE THREAD

**Issue by saltyexxer** [TES5Edit/TES5Edit#1253]
**What is the version of xEdit you are using?**
SF1Edit 4.1.5a EXPERIMENTAL x64 (AC1BF928)

**Describe the bug**
SF1Edit assumes that my game is installed under C:\Program Files (x86)\, but my Steam library is not located there.
When I specify the correct paths on the commandline, SF1Edit does not pick up the paths.

Example:
I run:
.\SF1Edit64.exe -D C:\Games\Steam\steamapps\common\Starfield\Data\ -I C:\Games\Steam\steamapps\common\Starfield\Starfield.ini -B C:\Games\xEdit_4.1.5a_EXPERIMENTAL\Starfield\Backups\

Output:
Using Starfield Data Path: \
Using Backup Path: 
Using Scripts Path: C:\Games\xEdit_4.1.5a_EXPERIMENTAL\Edit Scripts\
Using ini: 
Fatal: Could not find ini 

**To reproduce**
Move your Steam instance to a nonstandard directory.
Attempt to override the defaults using commandline options.
Note: I have tried with and without quotes surrounding the paths, which should not be necessary anyway because there's no spaces in any of the names. It's recognizing the switches but the parameters are empty.

**Expected behavior**
The program should use the paths and files specified on commandline

**Screenshots**

**Additional context**
I can't find any control in the UI to configure the paths.

**Comment by VlitS** [comment]
You entered them wrong. It should be
-D:C:\Games\Steam\steamapps\common\Starfield\Data\ -I:C:\Games\Steam\steamapps\common\Starfield\Starfield.ini -B:C:\Games\xEdit_4.1.5a_EXPERIMENTAL\Starfield\Backups\

No space between the argument and the path, just a `:`.
