### ISSUE TITLE
Report Error when a NULL Faction is in the Function GetCrimeGoldViolent/GetCrimeGold/GetCrimeGoldNonviolent

### ISSUE THREAD

**Issue by elafrosicky** [TES5Edit/TES5Edit#1254]
**What is the version of xEdit you are using?**

**SSEEdit 4.1.5 EXPERIMENTAL (01F611AE) starting session 2023-11-10 22:30:35**

**Describe the bug**

**Report Error when a NULL Faction is in the Function GetCrimeGoldViolent/GetCrimeGold/GetCrimeGoldNonviolent this Faction parameter is actually optional, and can be used without passing a Faction (NULL). I mean, this isn't an error.**

**To reproduce**

**Check for errors in Crime Overhaul mod**

**Expected behavior**

Dont report this as an error when "checking for errors" option

**Comment by ElminsterAU** [comment]
should be fixed in 4.1.5b
