### ISSUE TITLE
[FalloutNV] Epic Games release does not create game location registry entry

### ISSUE THREAD

**Issue by WilliamImm** [TES5Edit/TES5Edit#1262]
The Epic Games Store (EGS) version of New Vegas is weird, flat out. The game is fully moddable, but among other issues introduced in it, *no* registry key entry is created at all to indicate the game's location. As such, xEdit's location checks fail on this game.

Mod Organizer 2 worked around this issue by checking the Epic Games manifests, see https://github.com/ModOrganizer2/modorganizer-game_gamebryo/blob/de53b9256d0e82d179812c138d04979ad7d471ce/src/gamebryo/gamegamebryo.cpp#L407 and https://github.com/ModOrganizer2/modorganizer-game_falloutnv/blob/a6edbf9b79c429fafcf75e69d9fc4f212cfe4966/src/gamefalloutnv.cpp#L73

Whether via manifests or other means, I'd like to request that xEdit correctly locate and run on the EGS version of Fallout NV without extra arguments.

**Comment by robertgk2017** [comment]
xEdit does not official support non-steam versions of Bethesda games.  You can use the command line arguments on the Information Tab in the program to redirect xEdit to the data/ini/game/etc folders for your installation.

-D:<path> [Specify a Data Directory]
-I:<path><filename>  [Game Main INI File]
All path parameters must be specified with trailing backslash.

**Comment by WilliamImm** [comment]
Thanks for letting me know. 

I would like to have a second opinion on this from a member of the xEdit team/maintainers if possible, unless the lack of support for non-Steam versions of games is their policy. I do respect if they *don't* want to deal with weird branching versions of a game where Steam itself is the most popular version by far, but at the same time, this is enough of a pain point for using the EGS version that it is worth bringing up.

**Comment by ElminsterAU** [comment]
The only officially supported game versions currently are Steam versions.

Other versions can make use of the various mechanisms that exist (parameters, "run in"/"working directory", or putting the exe into a subfolder of the game folder) to point xEdit at the right location. 

No official support is provided for this though.

**Comment by WilliamImm** [comment]
Alright, thank you! And thanks for the quick response, I respect your decision.

Closing.
