### ISSUE TITLE
Copy as New Record into... Not Available for All Weapons -- SF1Edit

### ISSUE THREAD

**Issue by juliandwillett** [TES5Edit/TES5Edit#1264]
**What is the version of xEdit you are using?**
4.1.5

**Describe the bug**
While some weapons are available to create as new records into a new ESM, not all, like the Negotiator (0026ED2A).

**To reproduce**
Right click on it, see no option. Then right click on the Russian assault rifle, and see that the option is available there.

**Expected behavior**
Able to click both

**Screenshots**

**Additional context**

**Comment by jbostrus** [comment]
The FormID you referenced above (0026ED2A) is for the Old Earth Assault Rifle not Negotiator. The Negotiator is 0026D970.

If you read the What's New document you would have seen it explain the Reflection Data
https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.5/whatsnew.md#reflection-based-data-streams
It does state it cannot be copied as override, but that also means you can't copy it as new as well. The data is not decoded and thus cannot be copied in any form.

This is why it cannot be copied.
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/90578cfa-620b-435e-bc09-3bebc72f657a)

**Comment by juliandwillett** [comment]
Great, thanks. Looking forward to the next release!
