### ISSUE TITLE
xEdit may incorrectly report "Navemesh triangle not found" for overridden DOORs

### ISSUE THREAD

**Issue by renngar** [TES5Edit/TES5Edit#1265]
**What is the version of xEdit you are using?**
SSEEdit 4.1.5 EXPERIMENTAL (01F611AE)

**Describe the bug**
If two or more plugins edit a `REFR` to a `DOOR` where the Teleport Marker Triangle of the `XNDP` differs, running **Check for Errors** may incorrectly report "Navmesh triangle not found" errors for one of the plugins.

Two such errors show up if [Skyrim Landscape and Water Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/26138), SLaWF, and [Navigator](https://www.nexusmods.com/skyrimspecialedition/mods/52641) are in the same load order, even with the SLaWF-provided Navigator patch.

```[00:00] Start: Checking for Errors
[00:00] Checking for Errors in [FE 002] Landscape and Water Fixes.esp
[00:00] [REFR:000A3D84] (places RiftenRWDoorLoad01 "Door" [DOOR:0006F267] in GRUP Cell Persistent Children of RiftenRatway02 "The Ratway Vaults" [CELL:000A1BFD])
[00:00]     REFR \ XNDP - Navigation Door Link \ Teleport Marker Triangle -> <Warning: Navmesh triangle not found in "[NAVM:0010CD01] (in GRUP Cell Temporary Children of RiftenRatway02 "The Ratway Vaults" [CELL:000A1BFD])">
[00:00] [REFR:0002E227] (places NorDoorSmLoad01 "Iron Door" [DOOR:0002ABAB] in GRUP Cell Persistent Children of YngolBarrow01 "Yngol Barrow" [CELL:000151F5])
[00:00]     REFR \ XNDP - Navigation Door Link \ Teleport Marker Triangle -> <Warning: Navmesh triangle not found in "[NAVM:001052A5] (in GRUP Cell Temporary Children of YngolBarrow01 "Yngol Barrow" [CELL:000151F5])">
```

**To reproduce**
1. Create a load order with Navigator and SLaWF.
2. Load it in xEdit.
3. Select both plugins and optionally the patch in the left pane.
4. Run **Check for Errors**.
5. The above errors are reported.

It seems that this check uses the final override of the navmesh, but not for the door reference, instead using the record as found in the currently tested plugin.

**Expected behavior**
No errors unless the final override for the door references a triangle that is invalid in the final override of the navmesh.

**Screenshots**
Here Navigator provides the ultimate version of the navmesh and door, but the overridden version of the door references a triangle that does not exist in the final navmesh.

![image](https://github.com/TES5Edit/TES5Edit/assets/39202621/17f549b3-8715-45ec-94c9-8a4f3e5838c2)

![image](https://github.com/TES5Edit/TES5Edit/assets/39202621/5f0e6909-f21c-46bb-9ec7-5a2b5698f262)

**Additional context**
In narrowing this down, I tested it with both the SSE and AE versions of Skyrim to make sure it wasn't an issue with using the plugins against an unsupported version.  The results are the same for both versions.

**Comment by robertgk2017** [comment]
xEdit will by design always look at the winning override when parsing references between records.  This intentional by design.  You need to use Check For Errors correctly by only running it on a module when just that module and it's masters are active in xEdit.   Anything else is an invalid use of Check For Errors.

In the given example you should only be running Check For Errors specifically on the SLAWF+Navigator patch module and nothing else.  If any errors result from that, then they are actual errors.
