### ISSUE TITLE
SSEEdit64 4.1.5 access violation

### ISSUE THREAD

**Issue by SteveTownsend** [TES5Edit/TES5Edit#1266]
**What is the version of xEdit you are using?**
SSEEdit 4.1.5 EXPERIMENTAL x64 (1D9D5A69) starting session 2023-12-05 18:49:02

**Describe the bug**
Access violation during plugin load. Edit disabled.
v4.0.4 does not reproduce the error

**To reproduce**
4.1.5 fails to load my large Skyrim SE Load Order.

**Expected behavior**
v4.0.4 stability preserved with my Load Order, or a more graceful failure if something is detected broken

**Screenshots**
Here is the error
_[05:22] Background Loader: Fatal: <EAccessViolation: Access violation at address 0000000000C1AC68 in module 'SSEEdit64.exe'. Read of address 0000000000000000>_

**Additional context**
Full output attached.
[4.0.4.txt](https://github.com/TES5Edit/TES5Edit/files/13574147/4.0.4.txt)
[4.1.5.txt](https://github.com/TES5Edit/TES5Edit/files/13574148/4.1.5.txt)

**Comment by robertgk2017** [comment]
update to the latest version 4.1.5a and attempt to recreate your issue.

**Comment by SteveTownsend** [comment]
Downloaded the package from Discord.
<img width="589" alt="image" src="https://github.com/TES5Edit/TES5Edit/assets/14825099/6a780f70-6f6a-45ea-8925-e77531200acc">
Ran _xEdit64.exe -sse_ over the same Load Order using existing cached data from old version when prompted.
<img width="678" alt="image" src="https://github.com/TES5Edit/TES5Edit/assets/14825099/21d2aca5-51f5-43e2-9318-5fa389e3169d">

`[05:22] Background Loader: Fatal: <EAccessViolation: Access violation at address 000000000100AD58 in module 'xEdit64.exe'. Read of address 0000000000000000>
`
[4.1.5a.txt](https://github.com/TES5Edit/TES5Edit/files/13574362/4.1.5a.txt)

**Comment by ElminsterAU** [comment]
Provide exception log. Delete it before doing one single run that reproduces the error

**Comment by SteveTownsend** [comment]
Log generated as requested is attached
[xEdit64Exception.log](https://github.com/TES5Edit/TES5Edit/files/13574507/xEdit64Exception.log)

**Comment by ElminsterAU** [comment]
Error in some error reporting code. The access violation will be gone in the next version. The underlying error in your mods not.

A mod contains a child group for a record which is not contained in the same container as the record itself.

**Comment by SteveTownsend** [comment]
Ok great, I'll see if it can fix that.
I can test an updated build if you need confirmation.
Thanks for quick response.

**Comment by ElminsterAU** [comment]
If you DM me on Discord, I can give you a pre-release version to test

**Comment by SteveTownsend** [comment]
Test build 4.1.5b loaded everything. This error group in the output looks like the case mentioned above.
I am unblocked, thanks,
_Line 46937: [05:33] Background Loader: <Error: Group "GRUP Topic Children of [REFR:60000EBF] (places BoneDeerSkullHornedStatic [STAT:00073CC2] in GRUP Cell Temporary Children of [CELL:00009C66] (in Tamriel "Skyrim" [WRLD:0000003C] at -15,-21))" has not the same container as record "[REFR:60000EBF] (places BoneDeerSkullHornedStatic [STAT:00073CC2] in GRUP Cell Temporary Children of [CELL:00009C66] (in Tamriel "Skyrim" [WRLD:0000003C] at -15,-21))">
Line 46938: [05:33] Background Loader: <Error: Group "GRUP Topic Children of [REFR:60000EC2] (places BoneDeerSkullStatic [STAT:00073CD8] in GRUP Cell Temporary Children of [CELL:00009C66] (in Tamriel "Skyrim" [WRLD:0000003C] at -15,-21))" has not the same container as record "[REFR:60000EC2] (places BoneDeerSkullStatic [STAT:00073CD8] in GRUP Cell Temporary Children of [CELL:00009C66] (in Tamriel "Skyrim" [WRLD:0000003C] at -15,-21))">
Line 46939: [05:33] Background Loader: <Error: Group "GRUP Topic Children of [REFR:60000EC4] (places BoneDeerSkullStatic [STAT:00073CD8] in GRUP Cell Temporary Children of [CELL:00009C66] (in Tamriel "Skyrim" [WRLD:0000003C] at -15,-21))" has not the same container as record "[REFR:60000EC4] (places BoneDeerSkullStatic [STAT:00073CD8] in GRUP Cell Temporary Children of [CELL:00009C66] (in Tamriel "Skyrim" [WRLD:0000003C] at -15,-21))">_

**Comment by jbostrus** [comment]
Well that's a very distressing set of messages. But in any case, the module in question is whatever was loaded at prefix 60 at the time of your recording.

**Comment by ElminsterAU** [comment]
Having "Topic Childeren of" a REFR makes not sense. That file is broken.

**Comment by SteveTownsend** [comment]
The problem was in a ZMerge output plugin, caused by ZMerge not handling records injected to master by patches.
One more thing for my ZMerge checklist, and thanks to your updates for flagging this. Thanks for the test build as well.

**Comment by ElminsterAU** [comment]
should be resolved in 4.1.5b with the commit referenced above
