### ISSUE TITLE
Skyrim VR Now Supports ESL Plugins

### ISSUE THREAD

**Issue by dystopiat** [TES5Edit/TES5Edit#1274]
I could not find a way to message about this on NexusMods.

A new mod has just been released by Nightfallstorm that gives Skyrim VR ESL support:

https://www.nexusmods.com/skyrimspecialedition/mods/106712

As you know xEDIT will currently not load .esl type plugins, nor more than 255 plugins when launched with the -TES5VR argument. 

VR users can now use .esl and esl flagged plugins and have more than 255 plugins in their load orders. This is huge.

Would it be possible for TES5Edit to support this new development?

Thank you very much!

**Comment by ElminsterAU** [comment]
added in xEdit 4.1.5c (when running in TES5VR mode and the presence of the required SKSE plugin is detected)

**Comment by darkphoenixff4** [comment]
Does that mean that the new ESL limits are in SSEEdit too?  Nukem released a plugin to backport this to earlier versions of SSE as well.

https://old.reddit.com/r/skyrimmods/comments/18btob5/updated_information_about_the_new_skyrim_update/

**Comment by robertgk2017** [comment]
Yes the lower form ID range is already supported in 1.71 header plugins as of the latest current release, which is 4.1.5b  This setup for VR will come out when 4.1.5c drops.

**Comment by dystopiat** [comment]
I'm having trouble locating a 4.1.5c version for download

**Comment by ElminsterAU** [comment]
sorry, there has been a delay in releasing it. I'm hoping to get it out this weekend.
