### ISSUE TITLE
Missing x64 version of SSEEdit

### ISSUE THREAD

**Issue by metacubed** [TES5Edit/TES5Edit#1281]
On Nexus, the 4.1.5 version (latest) of SSEEdit is a 32-bit exe. Preferably it should be on x64 architecture.

On Github, the Release archive of 4.1.5 does not contain xEdit64.exe or xEdit.exe.

It contains named exes for FO, SF and TES, but no SSE. Each of these have different file sizes and CRCs, so I'm not sure which one to use with `-sse`.

The previous release 4.1.4c did contain both xEdit64.exe and xEdit.exe.

**Comment by robertgk2017** [comment]
the latest build 4.1.5b contains both xEdit.exe and xEdit64.exe in the download archive.

**Comment by VlitS** [comment]
The only differences between the FO,SF, and TES versions are the icons built into them (very slightly different size resulting from that). So you can rename (or use the -sse argument) with any of them.

**Comment by metacubed** [comment]
Thanks, I downloaded the latest build from Discord, and it does contain the generic exe.

The latest one on Github [here](https://github.com/TES5Edit/TES5Edit/releases/tag/xedit-4.1.5) seems to be older and missing the generic.

Good to know about the file (icon) differences as well, that makes it easier.

**Comment by robertgk2017** [comment]
Always get the latest build posted on the Discord, that's where the incremental builds are posted.
