### ISSUE TITLE
Fatal: <EAccessViolation: Access violation at address 01370F9B in module 'SSEEdit.exe'. Read of address 00000000>

### ISSUE THREAD

**Issue by Alaeba** [TES5Edit/TES5Edit#1289]
**What is the version of xEdit you are using?**
4.1.5 EXPERIMENTAL

**Describe the bug**
I cannot edit anymore my plugin because of the error in the title. 

**To reproduce**

**Expected behavior**
I don't know what to expect honestly

**Screenshots**
Logs enclosed as seen in other bug reports

**Additional context**
I think this has something to do with the new way creation kit overwrites data on files. 
[exception.txt](https://github.com/TES5Edit/TES5Edit/files/14212106/exception.txt)
[log.txt](https://github.com/TES5Edit/TES5Edit/files/14212107/log.txt)

Thank you very much for your support

**Comment by jbostrus** [comment]
A quick skim of your logs would indicate that you're using newer plugins that have the 1.71 header and the extended from range. These are not compatible with xEdit 4.1.5. You **must** upgrade to 4.1.5**b** to load and work with those kinds of files. It is available only on Discord in the **#xedit-builds** channel.

**Comment by Alaeba** [comment]
> A quick skim of your logs would indicate that you're using newer plugins that have the 1.71 header and the extended from range. These are not compatible with xEdit 4.1.5. You **must** upgrade to 4.1.5**b** to load and work with those kinds of files. It is available only on Discord in the **#xedit-builds** channel.

Thank you very much, i didn't know that.
