### ISSUE TITLE
SF1Edit 4.1.5 x64 is a very long run.

### ISSUE THREAD

**Issue by sweddd** [TES5Edit/TES5Edit#1313]
SF1Edit 4.1.5 EXPERIMENTAL x64 (C857BD90)

Hi. First of all, thanks for xEdit. I used it for Skyrim, Fol 4, and now Starfield. Past versions of the program for past Bethesda games, which I ran almost on a "calculator", loaded in a couple of minutes. 
Now I have to wait at least 10 minutes (once it was 20). I emphasize that I am not talking about the "first launch". At the same time, I have literally several small mods. I tried running it on two different systems: Win 11, 32 GB of RAM / win10, 16gb ram.
I tried running SF1Edit 4.1.5 x32 - it took a couple of minutes.. 
Any tips on why the 64-bit version takes so long to run.

![image](https://github.com/TES5Edit/TES5Edit/assets/95692357/a55c8836-fd2b-4102-983a-e023bd395027)
[SF1Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/15012156/SF1Edit_log.txt)
[SF1Edit64Exception.log](https://github.com/TES5Edit/TES5Edit/files/15012158/SF1Edit64Exception.log)

**Comment by VlitS** [comment]
Starfield has updated since 4.1.5 came out, if you look at the log you will see unexpected/out of order subrecord errors. Those errors prevent the cache from saving, so it tries to build it every time.

You need to grab 4.1.5d from the #xEdit-Builds channel on the xEdit discord (link in top right corner of xEdit).

32 bit xEdit will give an out of memory error for just the base game, so not sure how it would "finish building cache" without giving you an error.

**Comment by sweddd** [comment]
Looks like 4.1.5c and 4.1.5d doesn't work for me. For some reason they are trying to consider already non-existent paths for fallout.

FO4Edit 4.1.5d x64 (5E27DB7F) starting session 2024-04-17 20:19:02

The Source Code Form of this program is subject to the terms of the Mozilla Public License, v. 2.0
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

The Source Code Form is available at https://github.com/TES5Edit/TES5Edit

Using Fallout4 Data Path: E:\Games\Fall4\Fallout 4\Data\
Using Backup Path: E:\Games\Fall4\Fallout 4\Data\FO4Edit Backups\
Using Scripts Path: F:\games\Starfield\xEdit_4.1.5d\Edit Scripts\
Using Cache Path: E:\Games\Fall4\Fallout 4\Data\FO4Edit Cache\
Using ini: C:\Users\38222\OneDrive\Документы\My Games\Fallout4\Fallout4.ini
Fatal: Could not find ini

**Comment by VlitS** [comment]
Rename xEdit64.exe to SF1Edit64.exe. It is the same program, xEdit just defaults to FO4 if no game mode is specified.

**Comment by sweddd** [comment]
Okay, the situation has changed for the better, just 4-5 minutes. However, I would like it faster) Maybe something else?
[04:21] Background Loader: finished

[SF1Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/15022938/SF1Edit_log.txt)
[SF1Edit64Exception.log](https://github.com/TES5Edit/TES5Edit/files/15022939/SF1Edit64Exception.log)

**Comment by VlitS** [comment]
Doublecheck that "Track All EditorIDs" wasn't turned on at some point. I see it is off in your screenshot, but it takes about 30 seconds for the base game to load for me without that checked, and enabling it makes it suddenly take 3+ minutes, with the delay in the same place as yours (building string indices, you can see in the SF1Edit_log.txt file what it taking so much time, that is the same as what shows in the message tab during the xEdit session).

**Comment by sweddd** [comment]
lol, I changed the xedit version and didn't check the settings. That was exactly the problem - Track All EditorIDs. thank you, close.
