### ISSUE TITLE
FO3Edit doesn't use the .ini filepath specified in the command line.

### ISSUE THREAD

**Issue by K4rn31r0** [TES5Edit/TES5Edit#1327]
**What is the version of xEdit you are using?**
FO3Edit 4.1.5f (AC5635A7)

**Describe the bug**
After installing FO3Edit on Nexus and trying to run it, an error message appears saying that the "my documents" folder could not be found. The application then opens and indicates a fatal error: could not find ini.
My Fallout.ini file is located at C:\Users\\[username]\Documents\My Games\Fallout3. So I added the following to my command line on Nexus Mod Manager:
-I:C:\Users\\[username]\Documents\My Games\Fallout3\Fallout.ini
However, the same error happens. Is there something wrong with the command line?

**To reproduce**
1. Install FO3Edit from Nexus
2. Place FO3Edit.exe in the same directory of Fallout 3
3. Run FO3Edit.exe

**Expected behavior**
The expected behavior was that the program would automatically detect the path to my Fallout.ini and start running normally. But this didn't happen, so I added the -I: command line switch on NMM, forcing FO3Edit to follow a specific path. Still, nothing changed.

**Screenshots**
Initial error msg on startup:
![image](https://github.com/TES5Edit/TES5Edit/assets/146667900/f47a5886-fabe-4b79-90e0-0e71aab5ebd2)
The Messages tab in the program:
![image](https://github.com/TES5Edit/TES5Edit/assets/146667900/b44916d2-5ed7-4a94-972a-7bc30a3b8948)

My command line on NMM:
![image](https://github.com/TES5Edit/TES5Edit/assets/146667900/f8f9a645-f3c2-45c4-907b-df6ebe030400)

**Additional context**
Probably worth mentioning that my game is installed on D: and my saves and inis are on C:, don't know how much of a difference this makes. Also, I believe the command line switches were originally supposed to be used on MO? I'm not sure if they're designed for NMM.

**Comment by zilav** [comment]
`-I:"C:\Users\[username]\Documents\My Games\Fallout3\Fallout.ini"`

**Comment by K4rn31r0** [comment]
> `-I:"C:\Users\[username]\Documents\My Games\Fallout3\Fallout.ini"`

Didn't work... Same error

**Comment by jbostrus** [comment]
Well you shouldn't need to specify the ini line if it's the default. But if you followed what zilav said, show a screenshot of what it looks like now?

**Comment by K4rn31r0** [comment]
I did try to put the file path in quotation marks, but the result is the same.

![image](https://github.com/TES5Edit/TES5Edit/assets/146667900/4f5677cd-6906-4034-b783-9b98e015eba7)
![image](https://github.com/TES5Edit/TES5Edit/assets/146667900/d270857f-9a45-42c8-8a01-c542a57a5d66)

**Comment by jbostrus** [comment]
oh ahh...well something in your configuration of NMM is jank. And that line goes in arguments. Not the command line field in NMM. I can't even explain why it launches at all like that.

**Comment by K4rn31r0** [comment]
Well, you're probably right about the NMM jank. I was thinking about switching to another mod manager anyways, I'll try again with a clean reinstall as well. Since it's probably an issue on my side and not a general bug, I'm closing the thread, thanks for the help
