### ISSUE TITLE
Fallout 4 edtit help needed 

### ISSUE THREAD

**Issue by avrel820** [TES5Edit/TES5Edit#1334]
Hello i a have tried to find directly Xedit to post this with no luck 
So there is no bug for me in the version 4.1.5F the issue is in Fo4 edit 4.0.4 the writing size (Font size) is kinda better in this version.
I have got the latest version 4.1.5F by any chance is there a way to get back old font or make font size slightly bigger ???
I use xedit full screen my resolution is 2560x1440P on a 27 inch screen and i am 42 years old at times i am really having a hard time to see what i am doing ....
Thanks to you & your team (if you have one) i have been able to mod games my way XEdit is amazing 

Kind Regards M.Sedge

**Comment by jbostrus** [comment]
We generally ask that tech support questions go through Discord. This allows us to provide a quicker response and get additional details in a timely manner when necessary.

The 4.0.x branch is no longer developed. I believe that branch handled the Windows UI scaling differently than the 4.1.x branch. But I could be misremembering.

In any case, an option may be to simply change the font size of the text areas. To do this open the options of xEdit (Control-O)  and goto the UI Settings tab. Then use the 3 buttons to open the font settings for the different areas.
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/6e7a790b-31c1-494e-a96a-4f27173787ff)

If you still need further assistance please use the Discord button in the top right corner of the xEdit application to join the server. Then use one of the support channels.

**Comment by avrel820** [comment]
Thank you so much i have set all fonts to 11 instead of 9 it helps me a bunch
