### ISSUE TITLE
Hardcoded UI colours that don't follow system theme result in unreadable interface

### ISSUE THREAD

**Issue by dsp2oo3** [TES5Edit/TES5Edit#1336]
**What is the version of xEdit you are using?**
xEdit 4.1.5f / BSArchPro 0.9c

**Describe the bug**
Hardcoded UI colours in xEdit ($**CCCCCC** for text in "What's New" window, $**A0A0A4** for empty elements) and BSArchPro ($**242400** and $**292900** for its filelist columns) do not follow Windows theming, resulting in unreadable interface.

Note: Apologies if these values are presented in reverse order - I forgot how exactly Delphi IDE sets them and this is how they are stored in compiled binary.

**To reproduce**
Install or switch to any classic theme (I use Plum Classic theme under Windows 7).

**Screenshots**
![bsarchpro-unreadablearchive](https://github.com/TES5Edit/TES5Edit/assets/169328594/b54052e7-c492-44fe-9018-f74f47c379b5)
![xedit-disabledelements](https://github.com/TES5Edit/TES5Edit/assets/169328594/ab70dc79-a7f2-49a6-b13f-0023c5d666fc)
![xedit-whatsnew](https://github.com/TES5Edit/TES5Edit/assets/169328594/8169359b-b7ee-49ee-85b4-78cff69340f1)

**Temporary solution for impatient people like myself**
Because I didn't have time and patience to setup a Delphi environment, and BSArchPro was the main deal breaker for me, I located the offsets for colour codes in HEX editor and replaced them with **ffffff**, which does the trick for my colour scheme (might not be ideal for other cases, though). The offsets are 0x4433BA and 0x4433C0.
![bsarchpro-patched](https://github.com/TES5Edit/TES5Edit/assets/169328594/f91e016d-b5dd-449f-85d5-f7661e2cac5b)

**Comment by ElminsterAU** [comment]
Just select a Theme of your choice from the ones available in xEdit/BSArchPro

**Comment by dsp2oo3** [comment]
What themes?
![bsarchpro-nothemeslol](https://github.com/TES5Edit/TES5Edit/assets/169328594/f32597ad-cb26-4040-93e3-9e90138d4b35)

**Comment by ElminsterAU** [comment]
The ones in the folder called Themes which you didn't copy.

**Comment by dsp2oo3** [comment]
Doesn't change the fact your default built-in theme is broken. Asking users to switch it is not a solution. BSArchPro 0.9's interface was rendering properly without any extraneous theming before.

Moreover, you outright ignored xEdit's unreadable colours. xEdit, as far as I see, does not have theming support.

**Comment by jbostrus** [comment]
A fix for BSArchPro's color theming has already been merged. #1329 
Some themes have better results than others. But at least it's not a fixed background color now. It ultimately would be up to the theme selection color.
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/04ad585b-93c0-462d-b747-81f381813ff4)
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/4fa765ea-cf4b-4d5a-8cd8-08dae2188ab3)
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/603a8654-fa4d-43a3-8e74-8026a30889f9)

As for xEdit's main interface. The disabled (dark grey text) elements are kind of irrelevant. But the color for those are controlled by the default Windows theme for disabled items or the active VCL theme. The default black text looks fine.

For the What's New document. I can totally understand the issue you have. But that's a bit more complicated. The document is an embedded RTF file. Which contains its own hard coded fonts and colors for the text. So adjusting for a theme is tricky. I have a proposed option that will recolor text at the time of loading xEdit and will color based on the then current theme. But changing the theme after load will not adjust the text until the next load of xEdit. 

Default Windows
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/85a36fff-b050-4b83-ace8-b741de0f49c0)
Lavender Classico
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/ec583a60-0345-4997-9032-6ede878780dd)
Stellar
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/1cc71373-b8dd-4550-a8c5-28407a9619eb)
Auric
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/ef84a93c-697b-40dd-a6ce-2f573ace7452)
Carbon
![image](https://github.com/TES5Edit/TES5Edit/assets/12855515/a48f0752-42c9-4b2b-8101-e8eed6f0e949)
