### ISSUE TITLE
Resources cache rebuilding on every startup and superseded patch bsa warning

### ISSUE THREAD

**Issue by naaitsab** [TES5Edit/TES5Edit#1340]
Version: SSEEdit 4.1.5f (094C4648)

On every startup the execution hangs for about 20 seconds on this line:
[00:00] Background Loader: Start building resources cache...
Followed by:
[00:08] Background Loader: ...resources cache finished building

This behaviour is not present in the pre 4.1x build and it makes the current version noticeable slower to load content. Not sure if it's a bug or intended behaviour but haven't read up on it anywhere. So hence the headsup. This is not a full rebuild als that takes 1.5-2 min when I first started 4.1.5. Number of plugins selected makes no difference. Behaviour is also present on only loading Skyrim.ESM

The other thing that pops up is the warning about an old BSA that got me triggered to look for the reason:
[00:00] Background Loader: Warning: <Can't find Skyrim - Patch.bsa>

This BSA should be missing on game versions marked as "AE" so 1.6.xxx and beyond. So this is not a valid warning on current game patch versions, released in the last 5 years. On the contrary, if it's possible for xEdit to detect the game version it should warn the user if they have that BSA loaded to remove it. As it messes up your game. If the user is still on a non AE version then the warning is valid.

**Comment by jbostrus** [comment]
The missing patch file is known and not a bug of xEdit. xEdit is reading the list of archives to read from the ini file. And Skyrim's ini (SSE) still lists that patch file even though it no longer exists on disk. That "bug" is on Bethesda's side for not updating their default ini. If it bothers you, go edit your Skyrim.ini in the My Games folder and remove it. xEdit is correctly stating that it can't find a file that it is being told to read (by the ini). Whether it should or not is not for xEdit to decide.

The resources cache is required to rebuild every time you launch in case any of the archives have been modified. And the time it takes depends on

1. How many archives are being loaded
2. How fast is the drive media that the archives are on

It is faster to just rebuild the resources cache than it would be to read the entire archive to computer a CRC and compare to a pre-saved value for a cache like it does for the plugins.

**Comment by naaitsab** [comment]
Thanks for the explanation on both parts. Might be something to put in the FAQ regarding the warning. Could be confusing if users actually read the error log. And not surprising it's another of Beth's lazy work at play here.

Does 4.1 handle the archiving differently? As on 4.0 it loads noticeably faster on the same load order.

**Comment by jbostrus** [comment]
There's a lot of differences involving archives. One of them being that the hashes for file paths is able to be decoded. Which is one of the reasons the resources cache needs to be built. It only has to read the header and file table info. Not the whole file. But depending on the size of the archives and how many that directly influences how long it will take.
