### ISSUE TITLE
Lack of dark mode option

### ISSUE THREAD

**Issue by Brakker643** [TES5Edit/TES5Edit#1354]
Hi

There was no dark mode option with 4.1.5. 64 bit Staring at the white background really hurts my eyes. And at times there is a lot of staring! :D

Thanks for a great tool!

**Comment by Evan555alpha** [comment]
- Ctrl+O to open the options
- Go to the `UI Themes` tab
- Select `Dark`
- Select your theme of choice. I recommend Carbon.

**Comment by Brakker643** [comment]
"Dark" and "Light" are ghosted. Only "System" is selectable.

I should have clarified that I use 64bit version- normal version runs out of memory.

**Comment by ElminsterAU** [comment]
The exe needs the Themes folder to give you themes.
