### ISSUE TITLE
AddRequiredElementMasters not adding BSassets.esm for XLCN subrecord when called on Worldspace record BSHeartland

### ISSUE THREAD

**Issue by RocketHog55** [TES5Edit/TES5Edit#1361]
**What is the version of xEdit you are using?**
SSEEdit 4.1.5f (094C4648) starting session 2024-07-01 16:00:35

**Describe the bug**
I wrote a script that removes the ownership tags from beds, and it works, except for one error (two actually) with one record when running it on Beyond Skyrim: Bruma.

Script:
```
unit foodBuff;

var 
  plugin: IwbFile;


function Initialize : integer;
var
  doit : boolean;
begin
  plugin := AddNewFile();
end;

function IsBed(r : IInterface) : boolean;
var
  base_record, mep, FNPR, the_type : IInterface;
  n, i : integer;
  bed : boolean;
begin
  bed := false;

  base_record := WinningOverride(LinksTo(ElementByPath(r, 'NAME')));

  if Signature(base_record) <> 'FURN' then exit;

  mep := ElementByPath(base_record, 'Marker Entry Points');
  
  n := ElementCount(mep);

  for i := 0 to n - 1 do begin
    FNPR := ElementByIndex(mep, i);
    the_type := ElementByPath(FNPR, 'Type');

    if GetEditValue(the_type) = 'Lay' then begin
      bed := true;
      break;
    end;
  end;
  
  Result := bed;
end;

function Process(r : IInterface) : integer;
var
  copied_record, copied_cell, cell, XLCN : IInterface;
begin
  // only check REFR records
  if Signature(r) <> 'REFR' then exit;

  // get latest loaded version of the record
  r := WinningOverride(r);

  if not ElementExists(r, 'Ownership') then exit;

  if not IsBed(r) then exit;

  AddRequiredElementMasters(r, plugin, false, true);

  // get parent CELL
  cell := WinningOverride(LinksTo(ElementByPath(r, 'Cell')));
  AddRequiredElementMasters(cell, plugin, false, true);

  // adding the XLCN's master, BSAssets.esm, doesn't prevent the error
  XLCN := WinningOverride(LinksTo(ElementByPath(cell, 'XLCN')));
  AddRequiredElementMasters(XLCN, plugin, false, true);
  
  // line that triggers the error
  copied_cell := wbCopyElementToFile(cell, plugin, false, true);

  copied_record := wbCopyElementToFile(r, plugin, false, true);
  
  RemoveElement(copied_record, 'Ownership');
end;

end.
```

Error:
```
Error assigning to [ \ [29] fsfsd.esp \ [1] GRUP Top "WRLD" \ [0] BSHeartland "Tamriel" [WRLD:120A764B] \ [3] XLCN - Location] from [ \ [12] BSHeartland.esm \ [48] GRUP Top "WRLD" \ [12] BSHeartland "Tamriel" [WRLD:120A764B] \ [3] XLCN - Location]: [Exception] Load order FileID [11] can not be mapped to file FileID for file "fsfsd.esp"
```

**To reproduce**
Select BSAssets.esm, BSHeartland.esm and BS_DLC_Patch.esp and run the above script.

In the generated plugin, the Worldspace record BSHeartland's XLCN subrecord gets a NULL value, instead of BSKBeyondSkyrimLocation. That record comes from BSAssets.esm. Adding the linked LCTN record's master with AddRequiredElementMasters before copying the cell doesn't seem to prevent the error.

One other issue is that the copied Worldspace record appears to be copied from the first one in the load order, not the last, despite calling WinningOverride on the cell before copying it. This results in a red conflict in the Object Bounds. This doesn't seem to happen with any other copied cells, such as the Tamriel Worldspace just before BSHeartland, which has the correct updated Max Height Data which is blank in Skyrim.esm.

**Expected behavior**
The XLCN subrecord has the correct value, and the copied BSHeartland Worldspace is copied from the last one in the load order.

**Comment by zilav** [comment]
When copying REFR as override, CELL and WRLD are copied from the same plugin. First, you added masters for CELL but not for WRLD. You don't need to add masters for XLCN or any other linked records.

Second - if the file you are copying from is the last loaded one in xEdit then WinningOverride() before adding masters is fine, otherwise you have to get the right CELL and WRLD when adding masters.

**Comment by RocketHog55** [comment]
Adding masters for WRLD worked for the first error and XLCN now has the correct value, thanks. The BSHeartland WRLD was still being copied from the first plugin, but I fixed that by manually copying the WinningOverride'd WRLD, instead of letting xEdit auto-copy it. There were other errors that occured before when I didn't manually copy the CELL to the plugin, and let xEdit auto-copy them too. So, copying the CELL and WRLD to the generated plugin is needed when copying a REFR.

Should the auto-copying of cells and worldspaces when copying a ref use WinningOverride on them internally? And should AddRequiredElementMasters also add the masters of the parent CELL and WRLD records when called on a REFR?

Updated script:
```
unit foodBuff;

var 
  plugin: IwbFile;


function Initialize : integer;
var
  doit : boolean;
begin
  plugin := AddNewFile();
end;

function IsBed(r : IInterface) : boolean;
var
  base_record, mep, FNPR, the_type : IInterface;
  n, i : integer;
  bed : boolean;
begin
  bed := false;

  base_record := WinningOverride(LinksTo(ElementByPath(r, 'NAME')));

  if Signature(base_record) <> 'FURN' then exit;

  mep := ElementByPath(base_record, 'Marker Entry Points');
  
  n := ElementCount(mep);

  for i := 0 to n - 1 do begin
    FNPR := ElementByIndex(mep, i);
    the_type := ElementByPath(FNPR, 'Type');

    if GetEditValue(the_type) = 'Lay' then begin
      bed := true;
      break;
    end;
  end;
  
  Result := bed;
end;

function Process(r : IInterface) : integer;
var
  copied_record, copied_cell, copied_wrld, cell, WRLD : IInterface;
begin
  // only check REFR records
  if Signature(r) <> 'REFR' then exit;

  // get latest loaded version of the record
  r := WinningOverride(r);

  if not ElementExists(r, 'Ownership') then exit;

  if not IsBed(r) then exit;

  AddRequiredElementMasters(r, plugin, false, true);

  // get parent CELL
  cell := WinningOverride(LinksTo(ElementByPath(r, 'Cell')));
  AddRequiredElementMasters(cell, plugin, false, true);

  // add master for WRLD for exterior cells
  if ElementExists(cell, 'Worldspace') then begin
    WRLD := WinningOverride(LinksTo(ElementByPath(cell, 'Worldspace')));
    AddRequiredElementMasters(WRLD, plugin, false, true);
    copied_wrld := wbCopyElementToFile(WRLD, plugin, false, true);
  end;
  
  copied_cell := wbCopyElementToFile(cell, plugin, false, true);
  copied_record := wbCopyElementToFile(r, plugin, false, true);
  
  RemoveElement(copied_record, 'Ownership');
end;

end.
```

**Comment by zilav** [comment]
Always copying the winning overrides internally will cause a lot of issues when creating patches in large load orders like adding unwanted master files. Or straight up prevent copying if winning record references a file loaded after the destination plugin.

xEdit API works directly on records/elements you pass. This is a difference between working in xEdit GUI (which does a lot for you and has safety checks) and using xEdit API directly - you have to take safety measures and do all the necessary work yourself.
