### ISSUE TITLE
Start building resources cache... | long loading times

### ISSUE THREAD

**Issue by poepkat** [TES5Edit/TES5Edit#1363]
**What is the version of xEdit you are using?**
4.1.5f

**Describe the bug**
Updated from 4.0.4. When loading up 4.1.5f for the first time I get asked if I want to delete older version resource caches - I said yes. Any time I load a plugin in 4.1.5f there are long loading times regarding resource caching. Seems like something is not working well with resource caching. I can't find anyone else mentioning this anywhere online, except for one post on Reddit. It's baffling to me why there's not more attention re: this issue. I feel like this is a major issue for power users.

I'm using Root Builder, might be influencing things. 4.0.4 didn't have this problem, though.

Hopefully I'm just doing something wrong; in that case some more in depth documentation how to fix / tweak this would be nice.

**To reproduce**
1. load any plugin in xedit (in my case tested loading only skyrim.esm)

**Expected behavior vs Current behavoir**

expected loading times skyrim.esm (with 4.0.4):

> [00:00] Background Loader: [C:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\] Setting Resource Path.
> [00:00] Background Loader: loading "Skyrim.esm"...
> [00:06] Background Loader: finished

current loading times skyrim.esm (with 4.1.5f)

> [00:00] Background Loader: [C:\Games\Steam\SteamApps\common\Skyrim Special Edition\Data\] Setting Resource Path.
> [00:00] Background Loader: Start building resources cache...
> [00:36] Background Loader: ...resources cache finished building
> [00:36] Background Loader: loading "Skyrim.esm"...
> [00:42] Background Loader: finished

**Comment by ElminsterAU** [comment]
Everything is working correctly as it should.

**Comment by poepkat** [comment]
Does this mean we just need to accept the longer loading times? Or is there something wrong on my end?

**Comment by ElminsterAU** [comment]
Yes
