### ISSUE TITLE
xEdit always opens FO4Edit.

### ISSUE THREAD

**Issue by Little-Equinox** [TES5Edit/TES5Edit#1370]
Heya I am using the latest version I can find from xEdit(4.1.5.0).

But I have a very very annoying bug, no matter which xEdit I start, Skyrim, Starfield or FO4, it simply launches into the FO4Edit, and FO4 isn't even installed on my system.

I tried this through MO2 and just through the EXE but all launch into FO4Edit with no way to change it.
I even deleted FO4Edit and left SFEdit, yet it still launches in FO4Edit.

Maybe it's a me issue but I am clueless how to change this.

**Comment by robertgk2017** [comment]
You aren't setting a valid gamemode argument.   -TES3, -TES4, -TES5, -SSE, -FO3, -FNV, -FO4, -FO76, -SF1.

**Comment by Little-Equinox** [comment]
Thanks, This has been very frustrating as I couldnt find it anywhere.
I really appreciate the help.
