### ISSUE TITLE
Overriding records from a 1.71 esl into a 1.70 esl-flagged esp creates an override pointing to a wrong record

### ISSUE THREAD

**Issue by alexoj** [TES5Edit/TES5Edit#1374]
**What is the version of xEdit you are using?**
SSEEdit 4.1.5f (094C4648) starting session 2024-08-30 19:15:52

**Describe the bug**
Overriding records from a 1.71 esl into a 1.70 esl-flagged esp creates an override pointing to a wrong record

**To reproduce**
1. Open SSEEdit with all vanilla files and any 1.70 esl flagged esp.
2. Open _ResourcePack.esl, Static, first record (RP_DweRmLgMid01_DetailedCeilingCollision)
![image](https://github.com/user-attachments/assets/9c2ac7c8-2c45-452b-8250-3d442e6761f7) 
4. Right click, copy as override into, select your 1.70 esl flagged esp.
5. See new record has wrong FormID and overrides wrong record.
![image](https://github.com/user-attachments/assets/d71b147a-3031-4a7c-b3e9-04ce91a3e3d2)
![image](https://github.com/user-attachments/assets/5333bcc1-0c44-4afa-8906-4d186a0e324b)

**Expected behavior**
Either warn that the file needs to be changed to 1.71 version or offer to change it

**Comment by robertgk2017** [comment]
This is not a bug.  This is the program working exactly as intentionally designed to work with the files and engine Bethesda provides.  xEdit currently shows an error message for 1.70 files referencing new records below 800 defined by plugins that are not skyrim.esm

**Comment by alexoj** [comment]
I followed the steps I described above and I saw no warning, the only indicator that something is wrong is that the override record doesn't appear on screen (until you look for it in the new file and see it exists, but references the wrong record).

In my humble opinion, at the very least it should tell you that the override will not work and why, if I didn't happen to suspect that it had something to do with the plugin file version it would have taken me a long time to find out why when I try override a record in SSEEdit nothing seemingly happens.

**Comment by jbostrus** [comment]
The application does not offer to change it because there may be reasons it should not be changed. Similarly because of that, it cannot determine that one behavior or the other is the desired outcome. It is up to you the modder to make the decision as to which version it should be. If you're supporting other plugins which have HEDR 1.71 then ALL your files should be 1.71 to alleviate such issues.

**Comment by alexoj** [comment]
Ok
