### ISSUE TITLE
An error occured while loading modules. Didnt happen with previous version I used.

### ISSUE THREAD

**Issue by generaleagleyt** [TES5Edit/TES5Edit#1381]
**What is the version of xEdit you are using?**
TES5VREdit 4.1.5f (094C4648) starting session 2024-09-13 20:55:11

**Describe the bug**
When I start xEdit and decide to load all of my mods, the following happens (see picture). When I try it with just a few mods, everything works.

**To reproduce**
1. Open xEdit
2. Leave all mods selected
3. Let xEdit load

**Expected behavior**
xEdit loads all mods succesfully.

**Screenshots**
![obrázok](https://github.com/user-attachments/assets/d88c6139-88d3-4652-a2bb-dd0c22e514da)

**Additional context**
I dont understand what does the error mean. Maybe some of my mods is causing it? I updated to this version of xEdit today, before that I had no problem loading all the mods. I play Skyrim VR with 2k+ mods. My previous xEdit version: TES5VREdit 4.0.3 (1CDF3AC7)

**Comment by robertgk2017** [comment]
Update to current 4.1.5j and try to replicate the issue.   If it repeats, also post your exception log.

**Comment by generaleagleyt** [comment]
> Update to current 4.1.5j and try to replicate the issue. If it repeats, also post your exception log.

Sure, where can I find it? I don't see it on github

**Comment by robertgk2017** [comment]
All updates are posted in the #xedit-builds channel of the Discord Server.

**Comment by generaleagleyt** [comment]
Using the latest version, the same thing happened. After I clicked OK, the second picture appeared.
![obrázok](https://github.com/user-attachments/assets/38b12ffb-9c63-4a00-a5b5-68784a98cc27)

![obrázok](https://github.com/user-attachments/assets/f70de2f0-83d1-434e-a8e4-4c5727f02558)

**Comment by generaleagleyt** [comment]
I found [this](https://www.reddit.com/r/skyrimmods/comments/18zncu2/xedit_fatal_errors/) reddit post, of someone having similar problem. One of the comments said to use x64 version of xedit, so I tried it. It even gave me a warning to only use it if I'm getting "out of memory" with x32 version. This seems to have solved the problem.
