### ISSUE TITLE
Scrolls & Shouts in Fallout 4

### ISSUE THREAD

**Issue by Kuroitsune** [TES5Edit/TES5Edit#1385]
Did you know you can access and make Skyrim specific forms in the Fallout 4 Creation Kit? I didn't, and if you did then you can ignore and close this as this isn't a bug.

You can't directly make these forms since they are not in the object window, so you would need to copy at least one of each form (Scrolls, Soul Gems, Shouts, and Words of Power) from Skyrim, do some fuckery with the master file list and file version and load it up in the Fallout 4 Creation Kit. Since they don't appear in the Object Window, you have to search for their Editor ID in the Search Text Window.

![image](https://github.com/user-attachments/assets/75e57753-5401-4955-a686-bf584342806e)

You can access all four of the forms and make new ones,

![image](https://github.com/user-attachments/assets/f7ff532d-ed59-4ac9-9b93-fec3d1818074)

Creating new forms and doing more fuckery to load them up in TES5Edit shows (from my knowledge anyway), that the Fallout 4 Creation Kit save the forms the same way they were meant for Skyrim.

Do they work in game? Debatable? Shouts will not work full stop. You can teach and unlock words for the player, but the functions to add and equip shouts were gutted from Fallout 4, and most likely the teach and unlock word functions don't really do anything. Scrolls can be equipped but don't do anything when activated. This is likely because of my lack of knowledge of Skyrim (hain't no guns in TES5). I'll do more research into it. Soul Gems might work but tests haven't confirmed it. I think the mechanic may have been removed but again, lack of Skyrim knowledge.

Granted, none of this really matters but it is interesting to note that the SCRL, SHOU, WOOP, and SLGM forms are valid forms in Fallout 4.

I was setting up the development environment for xEdit so I could tinker with the FO4 Definitions to allow FO4Edit to natively support them for my own personal use and messing around. I think I know what needs to change in the .pas file to allow it but setting up the environment is a headache. Is there somewhere or someone that would be able to help?

Anyway, this isn't a bug, more of rantings on trivial stuff.

Back to my [project]!

**Comment by nerwus3456** [comment]
"Look, Fallout 4 and Skyrim are on the same engine!"

Seriously though, that was to be expected, both Skyrim and FO4 are made on Creation Engine, so it's not surprising that Skyrim specific forms ara available in Fallout 4's CK.

**Comment by jbostrus** [comment]
Fun fact. You can also do shenanigans with NOTE in Skyrim CK if you can get the record created. Though in game they're functionally useless. You can't see them in inventory, you can't interact with it if you have it spawned. So it's basically useless to do so beyond a mental workout.

For the FO4 stuff mentioned above. It's also moot. Even though you can manipulate the records if they're created. They don't have a functionality in game.

**Comment by nerwus3456** [comment]
TBF NOTE existing before FO4 makes sense, as FO4 was in pre-production phase when Skyrim was in full production, so including form types they could use in other games made sense.

**Comment by jbostrus** [comment]
NOTE was present in FO3 and FNV.
