### ISSUE TITLE
Blue Screen during Background Loader

### ISSUE THREAD

**Issue by pvpxan** [TES5Edit/TES5Edit#1386]
4.1.5f
Copy the first line from your xEdit messages window.

First time opening the app during the "Background Loader" and after about 5 minutes or so, my PC will Blue Screen.

1. Checking only Starfield.esm and BluePrintShips-Starfield.esm
2. Wait...
3. See error.

I might be able to get a dump from windows event viewer if needed. This has never happened with other versions of xEdit on my PC for other games.

**Comment by nerwus3456** [comment]
use the most recent xEdit 4.1.5j from https://discord.com/channels/471930020454072348/518048160526893057/1279695339678597161

**Comment by pvpxan** [comment]
I do not have access to that.

**Comment by pvpxan** [comment]
> use the most recent xEdit 4.1.5j from https://discord.com/channels/471930020454072348/518048160526893057/1279695339678597161

I do not have access to that.

**Comment by robertgk2017** [comment]
Update to the current version from our discord, and make sure you are using the 64 bit exe.

**Comment by pvpxan** [comment]
> Update to the current version from our discord, and make sure you are using the 64 bit exe.

Thanks. Think it is working now.
