### ISSUE TITLE
Can't save Starfield master

### ISSUE THREAD

**Issue by zairaLL** [TES5Edit/TES5Edit#1388]
**What is the version of xEdit you are using?**
4.1.5h x64 (Starfield)

**Describe the bug**
Can't save master
Logfile:
```
[00:00] Saving: mymodf.x.esm.save.2024_09_28_11_32_40
[00:00] Error saving mymodf.x.esm.save.2024_09_28_11_32_40: Modules with Small, Medium, or Overlay flagged modules as masters can't be saved in SF1Edit
[00:00] Errors have occured. At least one file was not saved.
```
None of these flags are set in the header

**To reproduce**
1. Create esp in CK
2. Export as ESM in CK or convert to master using [Starfield Plugin Bridge](https://www.nexusmods.com/starfield/mods/10189)
3. Edit in xEdit
4. Try to save the ESM

**Expected behavior**
File can be saved when only `Master` is set in the esm Header

**Comment by robertgk2017** [comment]
one of the masters of the plugin being saved is a small/medium master.  Its not just the file being saved that cant be.   xEdit only has basic read support of small/medium masters currently

**Comment by zairaLL** [comment]
Then this error message is misleading, would be helpful to see more details - eg. which plugin prevents saving the file.

**Comment by robertgk2017** [comment]
Theres nothing misleading in that message.  It says exactly whats what.   Files with Small/Medium/etc masters as Masters cant be saved.   To see which ones look at the masterlist of the plugin on tge File Header.

**Comment by zairaLL** [comment]
I understand this message as I can't save my mod because it has this flag set.
Not that I can't save my mod because I depend on a mod having this flag set.

**Comment by jbostrus** [comment]
How did you come up with that? The message says nothing of the sort. It clearly says that it's referring to masters of modules.

**Comment by zairaLL** [comment]
Yes, you are right.
