### ISSUE TITLE
Dark theme for X64?

### ISSUE THREAD

**Issue by Brakker643** [TES5Edit/TES5Edit#1394]
FO4Edit 4.1.5f x64

It would be really nice to have the option of using dark theme in x64. The white background is really hard on the eyes when staring down those pesky records for longer durations of time!

Br

**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jbostrus** [comment]
Make sure you have the x64 exe in the root xEdit folder so it can find the Themes (ie right next to the normal 32bit one). Then you can use the same themes with x64 as you can the x86.

**Comment by Brakker643** [comment]
Thx!!!
