### ISSUE TITLE
wbString aForward Bug?

### ISSUE THREAD

**Issue by Kuroitsune** [TES5Edit/TES5Edit#1395]
Alright, I didn't want to bug the xEdit team with this one, since its a personal learning experience but I've been banging my head against this problem for too long. I've been improving the decoding of TES3, for shits and giggles, and I'm pretty much done except for one issue: aForward doesn't seem to work when wbString is nested in a wbRArray & wbRUnion.

NPC_s and CREAs have AI Packages which can be assigned to them in any order, requiring me to use a union to define what signature xEdit finds. On top of that, its an array of packages so its a wbRUnion inside a wbRArray. Everything works, including keeping the target's optional cell(CNDT) with the appropriate AI_E and AI_F struct defs. Except the wbString to define the target for AI_E, AI_F, & AI_A doesn't work as intended.

When (specifically) wbString(True, 'Target', 32) is normally used it grabs 32 bytes and only displays the chars before the terminating 0 and ignores the junk after. At least to my understanding.

When used inside the wbRArray & wbRUnion I made for defining AI Packages however they are ordered or however many there are, wbString(True, 'Target', 32) doesn't ignore the junk bytes after the terminating 0 and displays both the correct string and then the junk data as one big string. Obviously wbString('Target', 32) has the same effect and the same with wbString(True, 'Target', 0) but with the addition of pulling the byte (2 bytes for AI_E  AI_F) used for the repeat flag.

I don't know what to do. I think I've done things right and looking at the other def files there isn't much to gleam from them since TES3 is so uniquely bizarre. Is this a bug with core xEdit or have I done something wrong and just can't see it? I'm also not sure what to provide to help. Like, do I upload the .pas file for checking or just code snippets, etc.? This is not your normal bug report.

This is what it looks like. Obviously, the junk data should not be after the target name.
![image](https://github.com/user-attachments/assets/9e0af662-d574-490f-8223-f5a7cfa49337)
(Not sure why Adondasi Sadalvel is added onto the AI_A target string, it is confirmed to be added to the AI_A signature in the plugin with a Hex Editor. I assume it is just junk data.)

Strangely, when modifying the init.pas to allow a TES3Edit (that can't do anything useful, obviously, aside from allowing me to use my sniffer script), double clicking the string to modify it (without the pop up box) doesn't show the junk data. I assume because of the first terminating zero?
![image](https://github.com/user-attachments/assets/f52ec51f-0b39-4a51-917f-69c14a82495e)

**Comment by ElminsterAU** [comment]
please use #dev-support on the xEdit discord for development support
