### ISSUE TITLE
[Skyrim] Event data function throws errors due to unknown value.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TES5Edit/TES5Edit#154]
```
What steps will reproduce the problem?
1. Load Skyrim.esm (or the USKP or whatever)
2. Look at record 000BFC7B
3. Run a "check for errors" and note that the Unknown: 826998784 populates 
several reported errors.

What is the expected output?
The display should list it as a GetIsID function.

What do you see instead?
An unknown value.

What version of the product are you using? On what operating system?
3.0.32 though I don't recall which svn revision.
```

Original issue reported on code.google.com by `arthmoor` on 24 Jan 2014 at 8:43

Attachments:
* [UnknownValue.jpg](https://storage.googleapis.com/google-code-attachments/skyrim-plugin-decoding-project/issue-154/comment-0/UnknownValue.jpg)
* [UnknownValue2.jpg](https://storage.googleapis.com/google-code-attachments/skyrim-plugin-decoding-project/issue-154/comment-0/UnknownValue2.jpg)

**Comment by zilav** [comment]
After I fixed it long time ago, there were no new issues regarding events data. I guess I covered all of them.
