### ISSUE TITLE
[Skyrim] Hardcoded formID file needs default ash piles added.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TES5Edit/TES5Edit#176]
```
Skyrim.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it
.dat

Needs entries added for the two default ash pile objects, DefaultAshPile1 
[ACTI:0000001B] and DefaultAshPile2 [ACTI:00000022].

They are supposed to be referenced in the game code whenever an ash pile gets 
generated. They are listed in the CK even with no mods loaded, so they're 
definitely hardcoded.
```

Original issue reported on code.google.com by `arthmoor` on 28 Nov 2014 at 1:55

**Comment by ElminsterAU** [comment]
This is a non-issue with vanilla skyrim.esm, as that contains the records.
It only affects people that are doing a total conversion and replacing skyrim.esm with a version that doesn't include these records.

The problem with including any records in the hardcoded file that also exist in the game master is that they will load after the game master in xEdit currently, and I can't change that really. So the records in the hardcoded file would always override the information from the game master.

If someone creates a total conversion replacing Skyrim.esm (or any other of the game masters), they should include versions of all the <$800 records that are also present in vanilla Skyrim.esm. I would consider not doing so modder error. Which makes hits whole issue a non-issue.
