### ISSUE TITLE
[Skyrim] MNAM subrecord of STAT does not display string path to filenames.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#199]
In a STAT record I was trying to duplicate, I wanted the string path for the filename from it. Turns out, xEdit isn't displaying that. Instead, you get something awful like this:

6C 6F 64 5C 77 68 69 74 65 72 75 6E 5C 77 72 68 6F 75 73 65 77 69 6E 64 30 31 6C 6F 64 5F 6C 6F 64 2E 6E 69 66 00 00 00 BD 04 EF FE 00 00 01 00 00 00 06 00 02 40 70 17 00 00 06 00 02 40 70 17 3F 00 00 00 00 00 00 00 04 00 04 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 EA 02 00 00 01 00 53 00 74 00 72 00 69 00 6E 00 67 00 46 00 69 00 6C 00 65 00 49 00 6E 00 66 00 6F 00 00 00 C6 02 00 00 01 00 30 00 30 00 30 00 30 00 30 00 34 00 42 00 30 00 00 00 4C 00 16 00 01 00 43 00 6F 00 6D 00 70 00 61 00 6E 00 79 00 4E 00 61 00 6D 00 65 00 00 00 00 00 4D 00 69 00 63 00 72 00 6F 00 73 00 6F 00 66 00 74 00 20 00 43 00 6F 00 72 00 70 00 6F 00 72 00 61 00 74 00 69 00 6F 00 6E 00 00 00 4A 00 11 00 01 00 46 00 69 00 6C 00 65 00 44 00 65 00 73 00 63 00 72 00 69 00 70 00 74 00 69 00

For whatever is in this mess, the first part:

6C 6F 64 5C 77 68 69 74 65 72 75 6E 5C 77 72 68 6F 75 73 65 77 69 6E 64 30 31 6C 6F 64 5F 6C 6F 64 2E 6E 69 66

is the string for the file path, which in that case corresponds to:

lod\whiterun\wrhousewind01lod_lod.nif

Could the MNAM subrecord in STAT be updated to reflect readable strings for the path?

I have to assume there's a NULL terminator that marks the end of the string off from whatever the rest of that stuff is. http://www.rapidtables.com/convert/number/hex-to-ascii.htm basically showed junk followed by something to do with Microsoft for the remainder.

**Comment by zilav** [comment]
I know, but there is no such data type "null terminated string with garbage up to N (260) total length in bytes" in xEdit, need to add a new one for that. Maybe later, for now you can use "List LOD objects and meshes.pas" script to export LOD meshes and textures of selected STAT records into a spreadsheet.

**Comment by Arthmoor** [comment]
So is it just that they created a field to hold 260 chars and didn't zero out the contents first? If so, lazy of them :P

**Comment by Hugues92** [comment]
There is something similar in Morrowind. In Spell ID and rank. I implemented it as wbStringForward in that branch. Still I'll look if there is anything in the MNAM record beyond the string.

**Comment by Hugues92** [comment]
If I change the ByteArray to String, will that break the script (and the LOD programs) ?

**Comment by zilav** [comment]
Yes, it will break lodgen and scripts like DynDOLOD.

**Comment by Arthmoor** [comment]
Actually it makes sense after I thought about it. 260 bytes to hold a file path, which can only be 255 bytes long in Windows. So they gave it 5 bytes of wiggle room for some reason.

Would it not be a relatively simple thing to update those other scripts to be correct as well?

**Comment by zilav** [comment]
I can update my scripts, but can't force that on others. Better to postpone it for the next release and warn authors to update their scripts beforehand.
Hlp maybe you can change them to your string type if you have time, but comment it for now. Will need to speak with Sheson first before releasing, DynDOLOD is now a part of STEP and a lot of people use it. I know BS team uses MNAM too in their scripts, they asked me how to read it last year. Maybe there are other scripts out therre I don't know of.
