### ISSUE TITLE
TES5Edit Could not find .ini using runas command for elevated privileges

### ISSUE THREAD

**Issue by MrBones1102** [TES5Edit/TES5Edit#200]
I was told to always run TES5Edit as administrator. Unfortunately, Skyrim is installed on the non-administrator account for security reasons. When I run TES5Edit "As Administrator" I get the UAC popup and put in my password and it runs successfully with one exception, it looks for the Skyrim.ini file in the administrator environment but Skyrim.ini is located in the basic-account's environment (where it is installed). As there is no way of manually changing the file path for the Skyrim.ini in TES5Edit (could be implemented), I chose to use the runas command in cmd so as to run the program with elevated privileges while in the correct environment. The program claims to be looking in the proper spot but still cannot find the Skyrim.ini. I do not know if I am even posting this in the right place but I was out of options as this is the only place to report issues or get any help at all that I could find. There should be a picture below in hopes of clearing up any possible confusion.
![tes5editrunas](https://cloud.githubusercontent.com/assets/13145808/8471119/f981b984-2049-11e5-8dd8-9615814d6363.png)

**Comment by Hugues92** [comment]
Who told you to run as administrator ? Don't, particularly if your skyrim installation is in a non system folder.

**Comment by MrBones1102** [comment]
Well, apparently "the TES5Edit staff". Here is the url to the page:
http://www.nexusmods.com/skyrim/mods/52612/?tab=1&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmoddescription%2F%3Fid%3D52612%26preview%3D&pUp=1

And here is an image of where the wording is located.

![realshelter](https://cloud.githubusercontent.com/assets/13145808/8489718/a24fe8cc-20d3-11e5-83fb-ee87499c560d.png)

**Comment by zilav** [comment]
The problem here is that RS uses standalone patcher script with *.tes5pas extension, and it didn't work for some people because tes5edit couldn't register that extension in Windows if not running under admin, or couldn't locate the ini.  I don't know when and why that happens, it occures only for a small amount of uses.

**Comment by MrBones1102** [comment]
So if I can run the patcher without any problems then I shouldn't worry about it then? It's just that I have had problems with programs before that were not obvious until after some prolonged use and running as admin fixed them. Just wanted to make sure I did not have to worry about that from this program. Still there is a problem with it not finding the file and being unable to manually set a path for it to work with, but as my problem is basically solved, I'm happy.

I want to leave this open for another day then I'll close it, just in case someone wants to add their knowledge.

Thanks Hugues92 and zilav for the quick and helpful responses.
