### ISSUE TITLE
Eregistry Exception Error Tes5edit Invalid Data Type

### ISSUE THREAD

**Issue by broken-modder** [TES5Edit/TES5Edit#201]
Super new to this. And google hates you guys I have been troubleshooting for HOURS and it took some random guy in the Nexus chat to tell me about this GitHub site.......Not sure what to do but Ill just post the bug report.

![capture](https://cloud.githubusercontent.com/assets/13204016/8526562/1c1d05e4-23cd-11e5-9ef8-a17344cbe048.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13204016/8526564/1fc7816a-23cd-11e5-962b-3c148c812a3f.PNG)

**Comment by zilav** [comment]
Looks like your windows system registry is damaged or maybe TES5Edit has no access to write there due to some reason in your system (security settings, antivirus, etc).

**Comment by broken-modder** [comment]
Hey there. Ive been modding heavy for the last week. Did a few fresh installs and never had a problem with tes5edit. Then with my most recent. I got this error. I dont use antivirus and I run everything admin. Happen to know how to fix the reg? A dev told me the target for tes5 is in the wrong format. He said he could help but he doesnt know what format the reg strings need to be for TES5 to read it

**Comment by broken-modder** [comment]
He was the dev for madexcept. Cool guy :P

**Comment by broken-modder** [comment]
I did forget to show the very first error when clicking tes5edit. here its is lol
![capture3](https://cloud.githubusercontent.com/assets/13204016/8528209/41a82762-23d7-11e5-9043-a26b5f4be894.PNG)

**Comment by broken-modder** [comment]
PROBLEM SOLVED
I was wary of doing it but besides reinstalling windows/restoring all my backups I went ahead and edited the registry.

I went one by one to all 7 entries that contained tes5 (search option in regedit)
Backed them up, then deleted them, then restored the previous, one by one, trying to find the broken entry. Al the while trying to load up TES5 in between. Didn't work. So I deleted them all at once and loaded up TES5Edit ..........BAM it worked.

Hate to go nuts trying to figure something out. But maybe this could help someone else.
          Googling this issue got nothing but other people with ERegistry exception Invalid Data Type for "" errors. And none of them using xedit but programs using madexcept and Delphi, mainly delphi. At its core its not a game modding issue, but a registry issue within windows that could come from many different programs or software, I imagine or maybe just these particluars. I will point out though that changing the filename to change to the other xedits, that worked, and created new strings of registry keys with the changed filename in the registry. Just something I wanted to note.

The error;

"Eregistry Error Exception Invalid data type for "____"

I've narrowed it down to this being caused by my registry cleaner program. At least in my case. Even restoring the backups using that program didnt work, neither did system restore. So just deleting them all and allowing the program to rebuild it was the key here.--I think :D lol

After doing fresh installs of the game, as well as the mod organizer/nmm and tools, I would use my reg cleaner to clean the registry, Thinking Oh yay how cool saving space blah blah. efficient yadda yadda

After doing that a few times, boom my windows registry is damaged.

Maybe this could help you guys maybe its a fluke lol. But problem solved guess you can delete the ticket or whatever. :) And a special thanks to you guys for all youve done for the community. :)

**Comment by zilav** [comment]
Majority of registry cleaners, driver cleaners, system optimizers, etc. are just a malware, or only "damage" your system if you are lucky.
