### ISSUE TITLE
Request to Remove commit

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#207]
@Utumno I am in need of your assistance.  One of my members is going through some of the growing pains with the differences between Git and SVN.  He has made three commits that I want to keep but one that I don't want.

Is it possible to get rid of commit a25e7bd06208f39ddff388244117d646514a2047 and keep all of the other commits?

![Remove Commit](http://i.imgur.com/6dQ42ka.jpg)

Zilav is pretty new to Git so although you know a lot more then me and could give him good advice, the concepts of Git and it's tools are just as daunting to him as they were for me.  So I can really relate to his frustration.  It would be best to let him find his own tools and workflow.  In other words suggesting to use GitK, and MySysgit and such might not help him yet since he is not familiar with anything Git related.

I have no idea how to fix this.  Is there is a fairly easy way to do it from GitK?  If so I am open to the idea.  As long as it's all from a GUI like GitK because using command line stuff and integrating with Notepad++ like you suggested before isn't working for me at this time.

**Comment by Sharlikran** [comment]
@Utumno nevermind.  I made another branch to test with.  Then I made another branch as a placeholder for the changes I wanted.  Then I used git cherry-pick [from branch] [commit I wanted] and it worked.

![Cherry Pick Result](http://i.imgur.com/8G231dX.jpg)

The question is, did I do that right or is that a like a hack and not the best way to resolve my issue.

**Comment by Utumno** [comment]
Right click on the commit you want (having checked out the branch you want) > Cherry-pick this commit ;)

**Comment by Sharlikran** [comment]
@Utumno Does it sound like I did that correctly to begin with? I had one branch with a commit in the middle of several other commits that I don't want.  Is what I did the proper way to handle a situation like that?

**Comment by Utumno** [comment]
The "right way" in the sense it does what you want and more is `rebase --interactive --onto f2a0fa f2a0fa sharlrikran-fo4` - then you edit the rebase todo file just deleting the line of the commit in question.

**Comment by Sharlikran** [comment]
Does that involve that notepad++ integration?  If so I will look into that a bit more at a later time because i want to use it if I can get it to work.

**Comment by Utumno** [comment]
Ninja'd - in general `rebase --onto` is _the_ command - you learn by using (and using the right click on the tree to checkout branches etc).

**Comment by Utumno** [comment]
Yes - notepad++ is for --interactive (goes without saying that it's the interactive part of the rebase we care in the first place! --onto just allows you to rebase any range of commits onto any branch/commit)

For notepad just issue:

    git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"

notice `"'path/to/npp.exe'..."`

From: http://stackoverflow.com/questions/1634161/how-do-i-use-notepad-or-other-with-msysgit/2486342#2486342

**Comment by Sharlikran** [comment]
@Utumno in commit cf0c5c4c1f7e17f9909af8e044e63f9f3254cee8 several records are changed.  Don't explain how yet, but is it possible for me to break those up into one commit per record defined or updated?

**Comment by zilav** [comment]
Why do you want to break it per record? Those are not even the final definitions and will change.

**Comment by Sharlikran** [comment]
For practice.  Plus if I can get what I am talking to him about working I can also learn to squish two commits together.  Say one commit changes CLAS and another changes CLAS they can become one commit.

**Comment by Utumno** [comment]
Yep of course - rebase interactive - mark the commit as `edit` - rebase will pause on that commit - go to the gui - hit amend last commit - and here is the commit at your mercy - unstage the lines (records) you don't want, change the message, commit - rinse and repeat.

Some of it can be done in the tree (but not easily for commits in the middle of a branch) - explore reset soft/mixed/hard

**Comment by Sharlikran** [comment]
Okay I'll take a look at those thanks.

**Comment by Sharlikran** [comment]
@Utumno Another question.

![odd commit](https://cloud.githubusercontent.com/assets/1912426/11235212/530d764e-8d84-11e5-989b-63420e4771ed.jpg)

When Hlp sync's with the Repo it adds that commit randomly.  Once it's committed it's like a virus.  It gets to all three of us.  If I do a hard reset I can clear it up on my end and cherry pick any missing commits from a backup.  If they sync without doing anything else it crops back up.  Any ideas on how I can resolve this?

**Comment by Utumno** [comment]
No clue, sorry - I have to have access to the local Hlp's branch. He must rebase out this commit - it's empty ?

**Comment by Hugues92** [comment]
I deleted the local copy here as it wasn't useful at the moment anyway. I'll do the same at home later.

**Comment by Hugues92** [comment]
By the way I don't have any clue where this commit is coming from :) Which branch ?

**Comment by Sharlikran** [comment]
I think it's some odd one off random occurrence that would be difficult to reproduce. I don't think it's from anywhere specifically and I think it's basically cached somewhere or somehow.  

Zilav and I deleted the repo from our hard drives.  Zilav did a hard reset of the branch.  I restored the commits by cherry picking them from a backup.  Then I deleted my repo and cloned it once more and it finally went away for the both of us.  It's nothing you are doing intentionally and all you have to to is sync the branch for it to happen.

Since Utumno would have to see things on your end to know a way to fix it I'll just e-mail you in your Hotmail and we will just have to do the hack Zilav and I did.

**Comment by Sharlikran** [comment]
> He must rebase out this commit - it's empty ?

It's not empty and it's from September 2 and it's pretty old.  I sent him the steps Zilav and I took to get rid of it so once he does that it should go away.  I was just hoping there was a way to rewrite or flush the .git folder for the repo from a shell and then update it using some command I might have never used.

**Comment by Sharlikran** [comment]
@Utumno 

I tested with just git rebase --interactive and Notepad++ finally opened.

```
noop

# Rebase 17f7fde..17f7fde onto 17f7fde
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```
I have a test branch named fo4dump-refactor so I can play with it.  How would I do the following:

1. start an interactive rebase from e21513dd393d0d47e4fdf93c84bbc9286af4e9ce to the most recent commit.
2. Stop on commit e21513dd393d0d47e4fdf93c84bbc9286af4e9ce
3. edit wbDefinitionsFO4.pas and add the changes I want for 1 of 3 changes I want to make.
4. Commit the changes 1 of 3
5. Edit wbDefinitionsFO4.pas for 2 of 3 and commit the changes for 2 of 3
6. Edit wbDefinitionsFO4.pas for 3 of 3 and commit the changes for 3 of 3
7. allow rebase to continue without any more changes

That would let me practice and see how editing one commit works in interactive mode.

The next thing I see from the file in Notepad++ is, squash = use commit, but meld into previous commit. What I want to do is squash or combine commits that are not sequential.  I'm not squashing 96 and 97 which 96 is the previous commit.  I want to Squash 91 and 97 for example.  Is that possible with the notepad interaction?  I think you told me it was possible but I can't remember.

Maybe if I can get this working I can do this on our Wrye Bash repo in the future as needed also but for now I'd just like to see if I can get it to work at all and understand what the heck I am doing.

**Comment by Utumno** [comment]
Feww - finally - actually no npp > no rebase > no git

But Sharl is all in the manual - any hooo:

1.

git rebase --interactive --onto e21513d^ e21513d^ fo4dump-refactor

The `^` takes parent commit - read on `--onto` three params

2. In the text that pops in notepad ++ change pick to e for e21513d 

Rebase will stop - open up git gui and hit amend last commit make your edits stage them and commit

Rinse and repeat (without ammending - just new commits)

7. `git rebase --continue`

Have the tree open and refresh it often. I am used to checking out a branch `reb` on the rebase head so I can perform more tricks in the tree (reset soft and the like). Git takes along the branch for the ride. Git 2.6 I presume ?

Re squash non sequential:

> # These lines can be re-ordered; they are executed from top to bottom.

Just reorder and change to s from pick on all the commits you want squashed (apart from the first they will be squashed into). Git will let you edit the message of the squashed commit.

Have the guyi open but avoid to commit !

Till you're confortable do this on a backup branch - then compare the HEADs in the tree.


Once you get the hang of it you will just bang your head on the wall for not having learned that earlier :D

This really allows you to do whatever you want with the commits.

If doing any work (like I do) what you basically do is make a few commits and then rebase them again and again and again - splitting, squashing, editing, rearranging till the branch works and makes sense - then merge.

**Comment by Sharlikran** [comment]
@Utumno It seems to be working thanks.
