### ISSUE TITLE
Renumber FormIDs fails on WRLD, CELL for multiple records

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#208]
Mods used:
[Elsweyr Anequina by Iliana](http://www.theassimilationlab.com/forums/files/file/1070-elsweyr-anequina/)
[Valenwood Improved by Eldarie](http://www.nexusmods.com/oblivion/mods/22555)

Plugins used are:

ElsweyrAnequina.esp
Valenwood Improved.esp
ElsweyrValenwoodImprovedPatch.esp

Log File from display name is already in use in [Bethesda Post](http://forums.bethsoft.com/topic/1504458-relz-tes4edit/?p=24511330) : [TES5Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/36206/TES5Edit_log.txt)

Issue:

Renumber FormIDs function does not seem to renumber FormIDs properly on long iterations.

Steps:

Download ElsweyrAnequina
Open ElsweyrAnequina.esp in TES4Edit
Change FormID [01094DBB] in file "ElsweyrAnequina.esp" to [0112594F]
Run check for errors.

**Comment by eFrysTon** [comment]
Is this still an issue?

**Comment by Sharlikran** [comment]
I no longer have this issue with c3f4193a15ce3b099bc5b6737ca7269ceefba158 3.2.3v
