### ISSUE TITLE
FO4Edit: Error on trying to copy COBJ as new

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#209]
This is for the fo4dump-refactor branch build of FO4Edit. (Rev 1842)

Attempting to copy some COBJ records as new or override throws an error at line 4015 in `wbImplementation.pas`. That's in the `TwbContainer.FreeInstance` procedure.

```
procedure TwbContainer.FreeInstance;
begin
  Assert(cntElementRefs = 1); // line 4015
  inherited;
end;
```

Seems to affect primarily, or only, COBJ records named `workshop_co_Scrap`, although some of those records are not affected.

Other record types could be affected.

Example affected record:

> workshop_co_ScrapFloraWildMutfruit01 [COBJ:00247409]

Example unaffected record:

> workshop_co_ScrapRadio [COBJ:002462E2]

**Comment by fireundubh** [comment]
XE debugger says:

* First chance exception at $767AC44D. Exception class Exception with message 'Found a ALCH reference, expected: CMPO'. Process TES5Edit.exe (6856)

* First chance exception at $767AC44D. Exception class EAssertionFailed with message 'Assertion failure (D:\Projects\xEdit\branches\fo4dump-refactor\wbImplementation.pas, line 4015)'. Process TES5Edit.exe (6856)

**Comment by fireundubh** [comment]
Ah, the problem is simply that the COBJ Components can be several record types:

    wbArrayS(FVPA, 'Components',
      wbStructSK([0], 'Component', [
        wbFormIDCk('Component', [ALCH, AMMO, CMPO, MISC]),
        wbInteger('Count', itU32)
      ])
    )

Found the other valid component record types by running a script on all of the COBJ records in Fallout4.esm and outputting their component record types.

**Comment by zilav** [comment]
The current definitions are incorrect until official editor is released, they only serve the purpose of loading Fallout4.esm without errors for now.
