### ISSUE TITLE
FO4Edit: Adding second component to MISC requires clicking Add twice

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#210]
This is for the fo4dump-refactor branch.

### Summary
Adding a second component to the CVPA element of a MISC record requires clicking "Add" twice from the right-click context menu.

### Steps to Reproduce
1. Create a MISC record in a way that the CVPA element is unassigned.
2. Add the CVPA element.
3. Add a second component by using the context menu.
4. Try again to add a second component.

### Results

* The first attempt to add a second component fails.
* The second attempt to add a second component succeeds.
* Successive attempts to add components beyond Component 1 succeed.

### Expected Results
The first attempt to add a second component succeeds.

**Comment by fireundubh** [comment]
This is still an issue in the latest build, but I'm not sure it's limited to MISC records.

In any case, here's the regression test:

1. Copy a MISC record as an override to a new plugin.
2. Remove the CVPA field.
3. Right-click the CVPA field and click Add. This will add the CVPA field and the first Component array.
4. Right-click the CVPA field and click Add. This is supposed to add the second Component array but does not.
5. Right-click the CVPA field and click Add. This adds the second Component array.

**Comment by zilav** [comment]
I know, but that's not something breaking at least and so can wait.
