### ISSUE TITLE
FO4Edit: Known Valid Signatures

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#211]
I wrote a script that looks at each record, loops through the appropriate element arrays, and copies the known valid signatures to a sorted TStringList. These are the results so far.

We won't know the full list of valid signatures until the CK is released in March, of course, but this should help resolve some of the errors we're seeing now.

I'll update this thread with more elements and their known valid signatures later.

COBJ \ Component:
`[ALCH, AMMO, CMPO, MISC]`

COBJ \ Created Object:
`[ACTI, ALCH, ARMO, CONT, DOOR, FLOR, FLST, FURN, LIGH, MISC, MSTT, NPC_, OMOD, SCOL, STAT, TERM, WEAP]`

LVLI \ Reference:
`[ALCH, AMMO, ARMO, BOOK, CMPO, KEYM, LVLI, MISC, NOTE, WEAP]`

LVLN \ Reference:
`[LVLN, NPC_]`

CONT or NPC_ \ Items \ Item:
`[ALCH, AMMO, ARMO, BOOK, KEYM, LVLI, MISC, NOTE, WEAP]`

OTFT \ INAM:
`[ARMO, LVLI]`

**Comment by zilav** [comment]
REFR in LVLI? Brobably unused broken record.

**Comment by fireundubh** [comment]
> REFR in LVLI? Brobably unused broken record.

Actually, it looks like a bug.

`LLI_Vendor_PowerArmor_Mods_Unique [LVLI:00137820]`

**Comment by zilav** [comment]
Definitely something for unofficial patch to fix.

**Comment by fireundubh** [comment]
Errors related to valid types:

```
CONT \ Items \ Item \ CNTO - Item \ Item -> Found a NOTE reference, expected: ALCH,AMMO,ARMO,BOOK,INGR,KEYM,LIGH,LVLI,MISC,SCRL,SLGM,WEAP
INFO \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a FLST reference, expected: KYWD,NULL
INFO \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a NOTE reference, expected: ACTI,ALCH,AMMO,ARMA,ARMO,ASPC,BOOK,CONT,DOOR,ENCH,FLST,FURN,GRAS,IDLM,KEYM,LIGH,LVLI,LVSP,MISC,MSTT,NPC_,NULL,OMOD,PROJ,SOUN,SPEL,STAT,TACT,TREE,WEAP
INFO \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a NULL reference, expected: FACT
INFO \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a NULL reference, expected: FLST,VTYP
LSCR \ NNAM - Loading Screen NIF -> Found a SCOL reference, expected: NULL,STAT
LVLI \ Leveled List Entries \ Leveled List Entry \ LVLO - Base Data \ Reference -> Found a CMPO reference, expected: ALCH,AMMO,ARMO,BOOK,INGR,KEYM,LIGH,LVLI,MISC,SCRL,SLGM,WEAP
LVLI \ Leveled List Entries \ Leveled List Entry \ LVLO - Base Data \ Reference -> Found a NOTE reference, expected: ALCH,AMMO,ARMO,BOOK,INGR,KEYM,LIGH,LVLI,MISC,SCRL,SLGM,WEAP
LVLI \ Leveled List Entries \ Leveled List Entry \ LVLO - Base Data \ Reference -> Found a REFR reference, expected: ALCH,AMMO,ARMO,BOOK,INGR,KEYM,LIGH,LVLI,MISC,SCRL,SLGM,WEAP
NPC_ \ Items \ Item \ CNTO - Item \ Item -> Found a NOTE reference, expected: ALCH,AMMO,ARMO,BOOK,INGR,KEYM,LIGH,LVLI,MISC,SCRL,SLGM,WEAP
PACK \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a FLST reference, expected: KYWD,NULL
PACK \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a NULL reference, expected: QUST
QUST \ Aliases \ Alias \ Items \ Item \ CNTO - Item \ Item -> Found a NOTE reference, expected: ALCH,AMMO,ARMO,BOOK,INGR,KEYM,LIGH,LVLI,MISC,SCRL,SLGM,WEAP
QUST \ Aliases \ Alias \ VTCK - Voice Types -> Found a FACT reference, expected: FLST,NPC_,NULL
QUST \ Aliases \ Alias \ VTCK - Voice Types -> Found a VTYP reference, expected: FLST,NPC_,NULL
QUST \ Objectives \ Objective \ Targets \ Target \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a NOTE reference, expected: ACTI,ALCH,AMMO,ARMA,ARMO,ASPC,BOOK,CONT,DOOR,ENCH,FLST,FURN,GRAS,IDLM,KEYM,LIGH,LVLI,LVSP,MISC,MSTT,NPC_,NULL,OMOD,PROJ,SOUN,SPEL,STAT,TACT,TREE,WEAP
REFR \ NAME - Base -> Found a BNDS reference, expected: ACTI,ADDN,ALCH,AMMO,ARMA,ARMO,ARTO,ASPC,BOOK,CONT,DOOR,FLOR,FURN,GRAS,IDLM,INGR,KEYM,LIGH,LVLC,LVLN,MISC,MSTT,SCRL,SLGM,SNDR,SOUN,SPEL,STAT,TACT,TREE,TXST,WEAP
REFR \ NAME - Base -> Found a NOTE reference, expected: ACTI,ADDN,ALCH,AMMO,ARMA,ARMO,ARTO,ASPC,BOOK,CONT,DOOR,FLOR,FURN,GRAS,IDLM,INGR,KEYM,LIGH,LVLC,LVLN,MISC,MSTT,SCRL,SLGM,SNDR,SOUN,SPEL,STAT,TACT,TREE,TXST,WEAP
REFR \ NAME - Base -> Found a SCOL reference, expected: ACTI,ADDN,ALCH,AMMO,ARMA,ARMO,ARTO,ASPC,BOOK,CONT,DOOR,FLOR,FURN,GRAS,IDLM,INGR,KEYM,LIGH,LVLC,LVLN,MISC,MSTT,SCRL,SLGM,SNDR,SOUN,SPEL,STAT,TACT,TREE,TXST,WEAP
REFR \ NAME - Base -> Found a TERM reference, expected: ACTI,ADDN,ALCH,AMMO,ARMA,ARMO,ARTO,ASPC,BOOK,CONT,DOOR,FLOR,FURN,GRAS,IDLM,INGR,KEYM,LIGH,LVLC,LVLN,MISC,MSTT,SCRL,SLGM,SNDR,SOUN,SPEL,STAT,TACT,TREE,TXST,WEAP
REGN \ WNAM - Worldspace -> [0001D1D0] < Error: Could not be resolved >
RFGP \ RNAM - Reference -> [0023AF81] < Error: Could not be resolved >
SCEN \ Phases \ Phase \ Start Conditions \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a NOTE reference, expected: ACTI,ALCH,AMMO,ARMA,ARMO,ASPC,BOOK,CONT,DOOR,ENCH,FLST,FURN,GRAS,IDLM,KEYM,LIGH,LVLI,LVSP,MISC,MSTT,NPC_,NULL,OMOD,PROJ,SOUN,SPEL,STAT,TACT,TREE,WEAP
SCOL \ Parts \ Part \ ONAM - Static -> Found a ALCH reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a AMMO reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a BOOK reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a CONT reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a DOOR reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a FURN reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a MISC reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a MSTT reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a NULL reference, expected: STAT
SCOL \ Parts \ Part \ ONAM - Static -> Found a WEAP reference, expected: STAT
SNDR \ Conditions \ Condition \ CTDA -  \ Parameter #1 -> Found a NULL reference, expected: WTHR
TERM \ Items \ Item \ CNTO - Item \ Item -> Found a NOTE reference, expected: ALCH,AMMO,ARMO,BOOK,INGR,KEYM,LIGH,LVLI,MISC,SCRL,SLGM,WEAP
```

**Comment by zilav** [comment]
Thanks, updated where it has sense. But some errors in conditions about NULL references either mean that CTDA parameters are wrong in definitions for those functions, or it is indeed an error in esm and should be fixed by unofficial patch.

**Comment by fireundubh** [comment]
NULL could also be perfectly valid.

**Comment by zilav** [comment]
GetStageDone on a NULL quest doesn't make sense, the same as GetInFaction on a NULL faction. Maybe they are valid technically, but those conditions are useless.

**Comment by fireundubh** [comment]
You're probably right. I checked the affected records in SCOL and SNDR.

### SCOL

These records appear to be temporary objects probably created as templates or tests.

* BLDGTemp04 [SCOL:0006AB16]
* BLDGTemp06 [SCOL:0006B7C7]
* BLDGTemp07 [SCOL:0006B7C9]
* PWell04Concord [SCOL:00115795]
* SCConsoleB06 [SCOL:000537C1]
* TempBuilding02 [SCOL:0006953F]
* TempBuilding05 [SCOL:0006B19B]
* TempBuilding06 [SCOL:0006B1C1]
* VltHallRes1WayHalf01DUPLICATE000 [SCOL:000854A0]

### SNDR

Same deal with these, which have null GetIsCurrentWeather conditions.

* AMBWeatherRainExteriorSpotContainerInterior2DLP [SNDR:0004A781]
* AMBWeatherRainExteriorSpotContainerInterior3DLP [SNDR:0004A796]
* AMBWeatherRainExteriorSpotTESTLAYERDry [SNDR:000422BF]
* AMBWeatherRainExteriorSpotTESTLAYERWetLPM [SNDR:000422C0]

**Comment by zilav** [comment]
I added extra signatures to SCOL, maybe FO4 indeed can build meshes out of something else than statics like it was in FO3. If only STAT will be used in GECK, we'll remove them.

**Comment by fireundubh** [comment]
I believe static collections are just static "presets." For example, if you want to place a stack of tires with a bottle on top next to a stool, you'd lay down those statics, group them, and create a static collection. Then when you want to fill out some other part of the environment with those objects, you can place the static collection instead, and all of those objects will spawn in place as they should.

**Comment by zilav** [comment]
Static collections are real nif meshes built from from several other ones by official editor, including lod meshes if present.
