### ISSUE TITLE
FO4Edit: Quest Stage integer should be itU16

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#213]
Wherever the Quest Stage integer is referenced, the integer should be 16 bits. (itU16)

* CTDA > Parameter 2 > Quest Stage
* PERK > Effects > Effect Data > Quest Stage
* Script Fragments Quest > Quest Fragments > Quest Stage (already itU16)

**Comment by zilav** [comment]
Done.

**Comment by fireundubh** [comment]
This bug has resurfaced in the latest CTDA commit.

**Comment by zilav** [comment]
CTDA parameters have fixed size of 4 bytes no matter what type they store. As for Effects", well stages could never have been larger than 255 in all previous games, need GECK to check that.

**Comment by fireundubh** [comment]
> CTDA parameters have fixed size of 4 bytes no matter what type they store.

I don't know what to tell you. Maybe you need a 2-byte buffer.

Quest Stage in CTDA corresponds to Stage Index (itU16) in QUST.

iU16 matches Quest Stage to Stage Index, and no errors are found.

`BloodyMessPerk01 "Bloody Mess" [PERK:0004A0BB]`
* Quest: `PerksQuest "Perks Quest" [QUST:0004A09E]`
* Quest Stage: 300

`PerksQuest "Perks Quest" [QUST:0004A09E]`
* Stage Index: 300
* Stage Note: Bloody Mess

> As for Effects", well stages could never have been larger than 255 in all previous games, need GECK to check that.

We don't need the toolset. There's a console command: ShowQuestStages.

In the game, type:

> sqs PerksQuest

PerksQuest's stage indices go up to 1740.

**Comment by zilav** [comment]
Extended quest stage field in PERK record from itU8 to itU16, other quest stage instances would fit (VMAD and QUST).
