### ISSUE TITLE
xEdit Feature Request: FileSelectFrm defaults to first checkbox checked and the rest unchecked

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#214]
After re-running xEdit innumerable times while testing, I've found that the start-up checkbox states of FileSelectFrm have become very inconvenient.

Currently, the checkbox states load like so:

* First Plugin: Unchecked
* Every Plugin In Between: Checked
* Last Plugin: Unchecked

I think they should load like this:

* First Plugin: Checked
* Every Plugin In Between: Unchecked
* Last Plugin: Unchecked

Can this be implemented?

**Comment by zilav** [comment]
It uses plugins.txt for checking active plugin and sorting them. Inactive ones are sorted using loadorder.txt from BOSS/LOOT/ModManagers, and if absent by file timestamps.

**Comment by fireundubh** [comment]
> It uses plugins.txt for checking active plugin and sorting them. Inactive ones are sorted using loadorder.txt from BOSS/LOOT/ModManagers, and if absent by file timestamps.

ESMs don't appear to be included in plugins.txt, at least with FO4, so Fallout4.esm will never be checked by default, at least not until there's a mod-manager-made loadorder.txt.

**Comment by zilav** [comment]
Hmm it is included in my game by default, strange. Anyway need to wait for the first patch from Beth, they'll likely include update.esm or something similar like in Skyrim that will require the game master, so unchecked master file is not a problem..
