### ISSUE TITLE
FO4Edit: Entry Point and Function Indices

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#215]
Once/if I get access to Gibbed's parser, we'll see if these indices match his results.

### Entry Points

[Here's a version formatted for wbEntryPointsEnum.](http://hastebin.com/raw/gumaqabuli)

Index | Entry Point | State
--- | --- | ---
0 | Mod Breath Timer | Verified
1 | Mod My Critical Hit Chance | Verified
2 | Mod My Critical Hit Damage Mult | Verified
3 | Mod Mine Explode Chance | Verified
4 | Mod Incoming Limb Damage | Verified
5 | Mod Book Actor Value Bonus | Unused (PERK)
6 | Mod Recovered Health | Verified
7 | Set Should Attack | Unused (PERK)
8 | Mod Buy Prices | Verified
9 | Add Leveled List On Death | Unused (PERK)
10 | Set Max Carry Weight | Unused (PERK)
11 | Mod Addiction Chance | Verified
12 | Mod Addiction Duration | Unused (PERK)
13 | Mod Positive Chem Duration | Unused (PERK)
14 | Activate | Verified
15 | Ignore Running During Detection | Verified
16 | Ignore Broken Lock | Unused (PERK)
17 | Mod Enemy Critical Hit Chance | Unused (PERK)
18 | Mod Sneak Attack Mult | Verified
19 | Mod Max Placeable Mines | Unused (PERK)
20 | Mod Bow Zoom | Unused (PERK)
21 | Mod Recover Arrow Chance | Unused (PERK)
22 | Mod Exp | Verified
23 | Mod Telekinesis Distance | Unused (PERK)
24 | Mod Telekinesis Damage Mult | Unused (PERK)
25 | Mod Telekinesis Damage | Unused (PERK)
26 | Mod Bashing Damage | Verified
27 | Mod Power Attack Action Points | Verified
28 | Mod Power Attack Damage | Unused (PERK)
29 | Mod Spell Magnitude | Verified
30 | Mod Spell Duration | Verified
31 | Mod Secondary Value Weight | Unused (PERK)
32 | Mod Armor Weight | Verified
33 | Mod Incoming Stagger | Verified
34 | Mod Target Stagger | Unused (PERK)
35 | Mod Weapon Attack Damage | Verified
36 | Mod Incoming Weapon Damage | Verified
37 | Mod Target Damage Resistance | Verified
38 | Mod Spell Cost | Unused (PERK)
39 | Mod Percent Blocked | It's Complicated (PlayerPerk [PERK:00056DD7])
40 | Mod Shield Deflect Arrow Chance | Unused (PERK)
41 | Mod Incoming Spell Magnitude | Verified
42 | Mod Incoming Spell Duration | Unused (PERK)
43 | Mod Player Intimidation | Unused (PERK)
44 | Mod Ricochet Chance | Verified
45 | Mod Ricochet Damage | Verified
46 | Mod Bribe Amount | Unused (PERK)
47 | Mod Detection Light | Verified
48 | Mod Detection Movement | Verified
49 | Mod Scrap Reward Mult | Unused (PERK)
50 | Set Sweep Attack | Unused (PERK)
51 | Apply Combat Hit Spell | Verified
52 | Apply Bashing Spell | Unused (PERK)
53 | Apply Reanimate Spell | Unused (PERK)
54 | Set Boolean Graph Variable | Unused (PERK)
55 | Mod Spell Casting Sound Event | Unused (PERK)
56 | Mod Pickpocket Chance | Verified
57 | Mod Detection Sneak Skill | Verified
58 | Mod Falling Damage | Verified
59 | Mod Lockpick Sweet Spot | Verified
60 | Mod Sell Prices | Verified
61 | Set Pickpocket Equipped Item | Verified
62 | Set Player Gate Lockpick | Verified
63 | Set Lockpick Starting Arc | Unused (PERK)
64 | Set Progression Picking | Unused (PERK)
65 | Set Lockpicks Unbreakable | Verified
66 | Mod Alchemy Effectiveness | Unused (PERK)
67 | Apply Weapon Swing Spell | Unused (PERK)
68 | Mod Commanded Actor Limit | Verified
69 | Apply Sneaking Spell | Verified
70 | Mod Player Magic Slowdown | Unused (PERK)
71 | Mod Ward Magicka Absorption Pct | Unused (PERK)
72 | Mod Initial Ingredient Effects Learned | Unused (PERK)
73 | Purify Alchemy Ingredients | Unused (PERK)
74 | Set Filter Activation | Unused (PERK)
75 | Set Dual Cast | Unused (PERK)
76 | Mod Outgoing Explosion Limb Damage | Unused (PERK)
77 | Mod Enchantment Power | Unused (PERK)
78 | Mod Soul Pct Captured to Weapon | Unused (PERK)
79 | Mod VATS Attack Action Points | It's Complicated (ModLegendaryCommonPerk [PERK:001E6849])
80 | Mod Reflect Damage Chance | Unused (PERK)
81 | Set Activate Label | Unused (PERK)
82 | Mod Kill Experience | Verified
83 | Mod Poison Dose Count | Unused (PERK)
84 | Set Apply Placed Item | Unused (PERK)
85 | Mod Armor Rating | Unused (PERK)
86 | Mod Lockpicking Crime Chance | Unused (PERK)
87 | Mod Ingredients Harvested | Unused (PERK)
88 | Mod Spell Range (Target Loc.) | Unused (PERK)
89 | Mod Critical Charge Mult on Ricochet | Verified
90 | Mod Lockpicking Key Reward Chance | Unused (PERK)
91 | Mod Auto Lockpicking Chance | Verified
92 | Mod Auto Hacking Chance | Verified
93 | Mod Typed Weapon Attack Damage | Verified
94 | Mod Typed Incoming Weapon Damage | Verified
95 | Mod Charisma Challenge Chance | Verified
96 | Mod Sprint AP Drain Rate | Verified
97 | Mod Drawn Weapon Weight Speed Effect | Verified
98 | Set Player Gate Hacking | Verified
99 | Mod Player Explosion Damage | Verified
100 | Mod Player Explosion Scale | Verified
101 | Set Rads To Health Mult | Verified
102 | Mod Actor Scope Stability | Verified
103 | Mod Actor Grenade Speed Mult | Unused (PERK)
104 | Mod Explosion Force | Unused (PERK)
105 | Mod VATS Penetration Min Visibility | Verified
106 | Mod Rads for Rad Health Max | Verified
107 | Mod VATS Player AP On Kill Chance | Verified
108 | Set VATS Fill Critical Bar On Hit | Verified
109 | Mod VATS Concentrated Fire Chance Bonus | Verified
110 | Mod VATS Critical Count | Verified
111 | Mod VATS Hold Em Steady Bonus | Verified
112 | Mod Typed Spell Magnitude | Verified
113 | Mod Typed Incoming Spell Magnitude | Verified
114 | Set VATS Gun-Fu Num Targets For Crits | Verified
115 | Mod Outgoing Limb Damage | Verified
116 | Mod Restore Action Cost Value | Verified
117 | Mod VATS Reload Action Points | Verified
118 | Mod Incoming Battery Damage | Verified
119 | Mod VATS Critical Charge | Verified
120 | Mod Exp Location | Verified
121 | Mod Exp Speech | Verified
122 | Mod VATS Head Shot Chance | Verified
123 | Mod VATS Hit Chance | Verified
124 | Mod Incoming Explosion Damage | Verified
125 | Mod Ammo Health Mult | Verified
126 | Mod Hacking Guesses | Verified
127 | Mod Terminal Lockout Time | Verified
128 | Set Undetectable | Verified
129 | Invest In Vendor | Verified
130 | Mod Outgoing Limb Bash Damage | Verified
131 | Set Run While Over Encumbered | Verified
132 | Get Component Radar Distance | Verified
133 | Show Grenade Trajectory | Verified
134 | Mod Cone-of-fire Mult | Verified
135 | Mod VATS Concentrated Fire Damage Mult | Verified
136 | Apply Bloody Mess Spell | Verified
137 | Mod VATS Critical Fill Chance On Bank | Verified
138 | Mod VATS Critical Fill Chance On Use | Verified
139 | Set VATS Critical Fill On AP Reward | Verified
140 | Set VATS Critical Fill On Stranger | Verified
141 | Mod Gun Range Mult | Verified
142 | Mod Scope Hold Breath AP Drain Mult | Verified
143 | Set Force Decapitate | Verified
144 | Mod VATS Shoot Explosive Damage Mult | Verified
145 | Mod Scrounger Fill Ammo Chance | Verified
146 | Set Can Explode Pants | Verified
147 | Set VATS Penetration Full Damage | Unused (PERK)
148 | Mod VATS Gun-Fu 2nd Target Dmg Mult | Verified
149 | Mod VATS Gun-Fu 3rd Target Dmg Mult | Verified
150 | Mod VATS Gun-Fu 4th+ Target Dmg Mult | Unused (PERK)
151 | Mod VATS Blitz Max Distance | Verified
152 | Set VATS Blitz Max Dmg Mult | Verified
153 | Mod VATS Blitz Dmg Bonus Dist | Verified
154 | Mod Bash Critical Chance | Verified
155 | VATS Apply Paralyzing Palm Spell | Verified
156 | Null Function | Unused (PERK)

### Functions

These are already implemented.

Index | Function
--- | ---
1 | Set Value
2 | Add Value
3 | Multiply Value
4 | Add Range To Value
5 | Add Actor Value Mult
6 | Absolute Value
7 | Negative Absolute Value
8 | Add Leveled List
9 | Add Activate Choice
10 | Select Spell
11 | Select Text
12 | Set to Actor Value Mult
13 | Multiply Actor Value Mult
14 | Multiply 1 + Actor Value Mult
15 | Set Text

### Perks with Entry Points and Functions

[Google Drive: Verification Spreadsheet](https://docs.google.com/spreadsheets/d/1rOtzLZIcOhiS1Ke_E-kyB4TFZ3uYlb55R2BvjtmOOWs/pubhtml)

**Comment by zilav** [comment]
Thanks, updated.
