### ISSUE TITLE
FO4Edit: EPFT Type 8 is AVIF

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#216]
Not much involved here. EPFT Type 8 is AVIF.

      wbRStruct('Function Parameters', [
        wbInteger(EPFT, 'Type', itU8, wbEnum([
          {0} 'None',
          {1} 'Float',
          {2} 'Float/AV,Float',
          {3} 'LVLI',
          {4} 'SPEL,lstring,flags',
          {5} 'SPEL',
          {6} 'string',
          {7} 'lstring',
          {8} 'AVIF'
        ])),

**Comment by zilav** [comment]
Updated.
