### ISSUE TITLE
How can I modify the prefix values in Forms?

### ISSUE THREAD

**Issue by espress0** [TES5Edit/TES5Edit#217]
https://i.imgur.com/S8cxH9m.jpg

I'm using latest Tes5edit for Skyrim.
I want to change FormID's FormID prefix. I searched for "Apply Script" selection, but I can't find for this.

If you add a script for this, I'll appreciate it.

**Comment by zilav** [comment]
Hit F2 when standing on a record in the left tree to change it's FormID number.

**Comment by espress0** [comment]
Yes I know how to edit these manually...
I want a script because this has 100+ in it...

**Comment by fireundubh** [comment]
So, write a script. This isn't the place for support and script requests.

* [/r/xEdit](https://www.reddit.com/r/xedit)
* [xEdit @ forums.bethsoft.com](http://forums.bethsoft.com/topic/1529894-relz-tes5edit/)
* [xEdit Scripting Functions](http://www.creationkit.com/TES5Edit_Scripting_Functions)

**Comment by espress0** [comment]
I'll do this manually then.
