### ISSUE TITLE
FO4Edit: Head Part (HDPT) PNAM Indices

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#218]
### Table: Head Parts

Index | Head Part
--- | ---
1 | Face
2 | Eyes
3 | Hair
4 | Facial Hair
5 | Scar
6 | Eyebrows
7 | Meatcaps
8 | Teeth
9 | Head Rear

### Code

    wbInteger(PNAM, 'Type', itU32, wbEnum([
      'Misc',
      'Face',
      'Eyes',
      'Hair',
      'Facial Hair',
      'Scar',
      'Eyebrows',
      'Meatcaps',
      'Teeth',
      'Head Rear'
    ])),

**Comment by zilav** [comment]
Thanks, updated.
