### ISSUE TITLE
FO4Edit: Check for Errors Assertion

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#220]
Affected record:

`DN079_VendorFaction [FACT:0003EFB3]`

Check for Errors throws assertion:

> First chance exception at $767AC44D. Exception class EAccessViolation with message 'Access violation at address 006E6FD2 in module 'FO4Edit.exe'. Read of address 00000000'. Process FO4Edit.exe (34248)

**Comment by fireundubh** [comment]
Also affected but not limited to:

* `AbernathyFarm_BlakeSandbox [PACK:0002093D]`
* `AbernathyFarm_ConnieStartingPosition [PACK:00019A9F]`
* `AbernathyFarm_LucyStartingPosition [PACK:00019A9E]`
* `AO_Dogmeat_WanderAtLinkedRef_LookAtLinkedRefANDPlayer [PACK:000459F8]`

**Comment by zilav** [comment]
That was due to unknown type 13 in location target union, works fine now.
Updated.
