### ISSUE TITLE
FO4Edit: Magic Effect Archetype (wbMGEFType) Indices

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#223]
No idea about 26, and 36 appears to be related to paralysis, melee attacks, or power attacks.

For 36, I looked at records that used that archetype and couldn't identify any similarities.

[Here's a version formatted for wbMGEFType.](http://hastebin.com/raw/supanudive)

Index | Archetype
--- | ---
0 | Value Modifier
1 | Script
2 | Dispel
3 | Cure Disease
4 | Absorb
5 | Dual Value Modifier
6 | Calm
7 | Demoralize
8 | Frenzy
9 | Disarm
10 | Command Summoned
11 | Invisibility
12 | Light
13 | Darkness
14 | Night Eye
15 | Lock
16 | Open
17 | Bound Weapon
18 | Summon Creature
19 | Detect Life
20 | Telekinesis
21 | Paralysis
22 | Reanimate
23 | Soul Trap
24 | Turn Undead
25 | Guide
26 | 
27 | Cure Paralysis
28 | Cure Addiction
29 | Cure Poison
30 | Concussion
31 | Stimpak
32 | Accum. Magnitude
33 | Stagger
34 | Peak Value Modifier
35 | Cloak
36 | 
37 | Slow Time
38 | Rally
39 | Enhance Weapon
40 | Spawn Hazard
41 | Etherealize
42 | Banish
43 | Spawn Scripted Ref
44 | Disguise
45 | Damage
46 | Immunity
47 | Permanent Reanimate
48 | Jetpack
49 | Chameleon

**Comment by zilav** [comment]
Thanks, updated.
