### ISSUE TITLE
FO4Edit: Text Issues/Bugs Thread

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#224]
I've come across a few spelling errors. I'll add more here if I find more.

* `Archtype` should be `Archetype`
* `Aggresion` should be `Aggression`
* `Destructable` should be `Destructible`

**Comment by zilav** [comment]
Updated.

**Comment by fireundubh** [comment]
`Modification` should be `Object Mod` (`OMOD`). Found the name in my Fallout4.exe string dump.

> Object Mod
> Parameter must be object mod type

**Comment by zilav** [comment]
Interesting, can you try to find names for other new records like INNR, SCCO, etc?

**Comment by fireundubh** [comment]
## AMDL

This one looks like Aim (A) Model (MDL).

Found among other record names like Damage Type and Material Swap:

> AimModel

## BNDS

This one seems to be Bendable (BND) Spline (S).

> BendableSpline
> The Bendable Spline used as wire for Workshop.
> GenerateBendableSpline

## INNR

`INNR` is likely Instance (IN) Naming Rules (NR). Looking at an INNR record now, I realize that these records are the rules for how the game decides to name modded items.

Found among other record names like Damage Type and Material Swap:

> Instance Naming Rules

## KSSM

Found among other record names like Damage Type and Material Swap:

> Sound Keyword Mapping

Bethesda probably switched Sound and Keyword, so that KSSM would sort next to KYWD. The original name was probably Keyword Sounds Mapping, hence the two `S` characters in KSSM.

## NOCM

There's not enough in the `NOCM` record that's clear to be certain, but this is the closest I could find with a broad RegEx pattern: Nav (N) Mesh Obstacle (OC) Manager (M).

> NavMeshObstacleManager

NOCM record looks like nav mesh data associated with obstacle models.

## OVIS

I'm not seeing anything right now. Will look again later. Assuming:

* `O = Object, Obstacle, Overlay, Override`
* `V = Value, Visible, Visibility, Visual`
* `I = Image`
* `S = Space`

OVIS is filled with decorative statics, like brambles, hedges, and shrubs—all objects you can't scrap or remove in the game without a mod.

## SCCO

`SCCO` is likely Complex Scene Object, or Scene (SC) Complex Object (CO).

> Complex Scene Object
> SceneComplex count >> %i
> SetSceneIsComplex

**Comment by zilav** [comment]
Thanks, updated everything except OVIS for now.

**Comment by fireundubh** [comment]
## NPC_

* LTPT is `Legendary Template` and contains only Legendary LVLN references
* LTPC is `Legendary Chance` and contains only `ChanceLegendary [GLOB:0016556E]`

Not related to text, but...

* RCLR contains only FLST references
* FTYP contains only LCRT references
* STCP contains only STAG references

**Comment by zilav** [comment]
Thx, updated. I also added NPC_ to LTPT signatures since Skyrim allowed them as templates.

**Comment by fireundubh** [comment]
Instance Naming Rule should be Instance Naming Rule**s**.

Each INNR record is *a set* of Instance Naming Rules, not a single Instance Naming Rule.

**Comment by zilav** [comment]
Lets wait for CK on this.

**Comment by fireundubh** [comment]
Told you so. ;)

![sshot-172](https://cloud.githubusercontent.com/assets/1261664/15005763/b3dda39a-117d-11e6-913b-0868c42775b9.png)

**Comment by zilav** [comment]
Ok :)
