### ISSUE TITLE
FO4Edit: wbMGEFData Magic Skill and Resist Value no longer use wbActorValueEnum

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#225]
Magic Skill and Resist Value no longer use wbActorValueEnum.

```delphi
      wbInteger('Magic Skill', itS32, wbActorValueEnum),
      wbInteger('Resist Value', itS32, wbActorValueEnum),
```
In Fallout4.esm:

* Magic Skill uses the following integer: `0`
* Resist Value uses the following integers: `0, 739, 740, 745, 746, 747`

I don't think Magic Skill is used at all.

**Comment by zilav** [comment]
Those resist values look like FormID numbers, probably all instances of actorvalueenum are AVIF forms now.

**Comment by zilav** [comment]
Updated.
