### ISSUE TITLE
FO4Edit: Bools now include False, True, and Conditional

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#226]
Once-strictly-boolean elements like `VATS Targetable` have three indices, I'm sure you noticed.

The third index (2) is most likely to be `Conditional`.

Fallout4.exe string dump:

> false
> true
> conditional

We know FO4 makes heavy use of conditional logic, conditional keywords, etc. I'll need to do more testing and investigating before I can verify. I'll pick this up later unless you verify before me.

**Comment by zilav** [comment]
Do you have any examples of FormIDs using this?

**Comment by fireundubh** [comment]
### Destructible\DEST\VATS Targetable

This element uses 0, 1, and 2.

Integer | Form ID
--- | ---
2 | MirelurkEgg_Harvestable [ACTI:001715CD]
2 | MirelurkEgg_Hatching [ACTI:0016579B]
2 | GraveStone01_Breakable [MSTT:001ACFDE]
2 | GraveStone02_Breakable [MSTT:001ACFDC]
2 | GraveStone03_Breakable [MSTT:001ACFE0]
2 | GraveStone04_Breakable [MSTT:001ACFE2]
2 | GraveStone05_Breakable [MSTT:001ACFE4]
2 | GraveStone06_Breakable [MSTT:001ACFE8]
2 | GraveStone07_Breakable [MSTT:001ACFEA]
2 | GraveStone08_Breakable [MSTT:001ACFE6]
2 | PlaygroundSpringRider01 [MSTT:000725FB]
2 | SandbagPileSmall01 [MSTT:0002FC43]
2 | SandbagWall01 [MSTT:00045762]
2 | SWBollardDest [MSTT:0005BA45]
2 | SWBollardDestCOPY0000 [MSTT:001ACFCC]

### Equip Type\DATA

This element uses 0, 1, 3, and 4. Maybe bool is the wrong type for this element?

Integer | Form ID
--- | ---
3 | BothHandsAltOptional [EQUP:0010FFFC]
3 | BothHandsMiddleOptional [EQUP:0012FB4F]
3 | BothHandsOptional [EQUP:0004334C]
3 | BothHandsOtherOptional [EQUP:00043350]
3 | HandyLMOptional [EQUP:0004718E]
3 | HandyRLOptional [EQUP:00047149]
3 | HandyRMOptional [EQUP:0004716D]
3 | LeftHandOptional [EQUP:0004334E]
4 | LeftHand [EQUP:00013F43]
4 | LeftHandAlt [EQUP:0010FFFA]
4 | MiddleHand [EQUP:0001A02F]
4 | PowerArmorBatterySlot [EQUP:00066991]
4 | RightHand [EQUP:00013F42]
4 | RightHandAlt [EQUP:0010FFFB]

### Color\FNAM

This element uses 0, 1, and 3.

Integer | Form ID
--- | ---
3 | HairColor01LightRed [CLFM:000A0439]
3 | HairColor02LightBrown [CLFM:000A042D]
3 | HairColor03GoldenBlond [CLFM:000A042F]
3 | HairColor04Silver [CLFM:000A042E]
3 | HairColor05Graying [CLFM:000A042C]
3 | HairColor06Red [CLFM:000A0431]
3 | HairColor07White [CLFM:0019EE5A]
3 | HairColor08Bleached [CLFM:0019EE5B]
3 | HairColor09Gray [CLFM:0019EE5C]
3 | HairColor10SteelGray [CLFM:0019EE5D]
3 | HairColor11WarmBlack [CLFM:0019EE5E]
3 | HairColor12CoolBrown [CLFM:0019EE5F]
3 | HairColor13JetBlack [CLFM:0019EE60]
3 | HairColor14DarkBrown [CLFM:0019EE61]
3 | HairColor15DeepRed [CLFM:0019EE62]
3 | HairColor16Blond [CLFM:0019EE63]
3 | HairColor17PlatinumBlond [CLFM:0019EE64]
3 | HairColor18DeepBrown [CLFM:0019EE65]
3 | HairColor19DirtyBlond [CLFM:0019EE66]
3 | HairColor20ChestnutBrown [CLFM:0019EE67]
3 | HairColor21Brown [CLFM:0019EE68]
3 | HairColor22Auburn [CLFM:0019EE69]

**Comment by zilav** [comment]
I'm not sure those values are actually bools in FO4, they are probably flags now or custom enumerations depending on form type. Better wait for GECK to check unless gibbed or someone else decode their meaning from runtime code.
