### ISSUE TITLE
Copying Human Race to New Record

### ISSUE THREAD

**Issue by JackArbiter** [TES5Edit/TES5Edit#227]
[TES5Edit_bugreport.txt](https://github.com/TES5Edit/TES5Edit/files/44763/TES5Edit_bugreport.txt)

The human race has had a bunch of head data crap added to it, I guess for character creation (not sure) and it can't be copied over as an override. 

Not complaining, just not sure if it's been noticed. I'm sure someone is working overtime on this. Thanks for the hard work.

**Comment by zilav** [comment]
Race records are not decoded, only outlined. They are the biggest and the most complex records ever in any of Bethesda games. Copying complex records requires proper definitions which won't be available until GECK.

**Comment by zilav** [comment]
Fixed.
