### ISSUE TITLE
FO4Edit: More Check for Error crashes on PACK

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#228]
Here are two crashes related to PACK enumeration.

### Target Data Type needs a 9th member to prevent crash

```delphi
  wbTargetData := wbStruct('Target Data', [
    wbInteger('Type', itS32, wbEnum([
      {0} 'Specific Reference',
      {1} 'Object ID',
      {2} 'Object Type',
      {3} 'Linked Reference',
      {4} 'Ref Alias',
      {5} 'Unknown 5',
      {6} 'Self',
      {7} 'Keyword',
      {8} 'Unknown 8'  // add this
    ]), cpNormal, False, nil, nil, 2),
```

### PLDT Type needs a 15th member to prevent crash

Example affected record: `DN054ZekeGunnerAttackPackage [PACK:00119B0F]`

```delphi
  wbPLDT := wbStruct(PLDT, 'Location', [
    wbInteger('Type', itS32, wbLocationEnum),
    wbUnion('Location Value', wbTypeDecider, [
      {0} wbFormIDCkNoReach('Reference', [NULL, DOOR, PLYR, ACHR, REFR, PGRE, PHZD, PMIS, PARW, PBAR, PBEA, PCON, PFLA]),
      {1} wbFormIDCkNoReach('Cell', [NULL, CELL]),
      {2} wbByteArray('Near Package Start Location', 4, cpIgnore),
      {3} wbByteArray('Near Editor Location', 4, cpIgnore),
      {4} wbFormIDCkNoReach('Object ID', [NULL, ACTI, DOOR, STAT, MSTT, FURN, SPEL, SCRL, NPC_, CONT, ARMO, AMMO, MISC, WEAP, BOOK, KEYM, ALCH, LIGH, FACT, FLST, IDLM, SHOU]),
      {5} wbInteger('Object Type', itU32, wbObjectTypeEnum),
      {6} wbFormIDCk('Keyword', [NULL, KYWD]),
      {7} wbByteArray('Unused', 4, cpIgnore),
      {8} wbInteger('Alias', itS32, wbPackageLocationAliasToStr, wbStrToAlias),
      {9} wbInteger('Reference', itS32, wbPackageLocationAliasToStr, wbStrToAlias),
     {10} wbByteArray('Unknown', 4, cpIgnore),
     {11} wbByteArray('Unknown', 4, cpIgnore),
     {12} wbByteArray('Unknown', 4, cpIgnore),
     {13} wbByteArray('Unknown', 4),
     {14} wbByteArray('Unknown', 4) // add this
    ]),
    wbInteger('Radius', itS32),
    wbUnknown
  ]);
```

### CTDA Related

Affected records:
* `MS09Mission01ReinforcementsPatrol [PACK:0019A7F9]`
* `RETravelKMK_BoSM02ClarkeFlee [PACK:0014DCF3]`

There are probably more.

### Unknown Causes

Affected records:
* `MinFlareGunGroupMovementDog [PACK:001D2745]`
* `MinRadiantOwned04ReturnToBase [PACK:000E61C6]`
* `MinRandomPatrolGroupMovement [PACK:0015CE50]`
* `MinRandomPatrolGroupMovementDog [PACK:001D2744]`
* `RESceneKMK09GroupMovement [PACK:001B224C]`
* `RESceneKMK09GroupMovementPrisoner [PACK:001B224F]`
* `RESceneKMK09GroupMovementPrisonerCombat [PACK:00217A9C]`
* `RESceneSC03_SupermutantRaidersHeadHome [PACK:00118B27]`
* `RETravel01GroupMovement [PACK:0006BA61]`
* `RETravel01GroupMovementWeaponOut [PACK:0006BA60]`
* `RETravel03GroupMovementWeaponOut [PACK:0002F61A]`
* `RETravelCT07_GroupMovement [PACK:0018F68E]`
* `RETravelDL01GroupMovement [PACK:0002F813]`
* `RETravelDL01GroupMovementGlowingOne [PACK:001860A3]`
* `RETravelKMK07_BOSGroupMovement [PACK:00142416]`

There are definitely more.

**Comment by zilav** [comment]
Updated, thanks.
