### ISSUE TITLE
xEdit Feature Request: View hex on the fly

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#229]
One thing that would be really useful, at least to me as an investigative tool, is an option to view elements as non-editable hex on the fly without having to modify the source and recompile.

To do that, currently, I have to replace wbFloat, wbStruct, etc., with wbUnknown, compile, test, and then replace wbUnknown with wbFloat, wbStruct, etc., compile, and test. Quite a process.

Would adding a "View Hex" toggle to the right-click element label context menu be possible?

**Comment by zilav** [comment]
xEdit is too clumsy for such tasks. Use FO4Dump instead. Without GUI overhead it is fast to complile, fast to execute, and easy to compare dumps using any text comparison tools.
For example this bat file dumps specific records into "1.txt" and all errors regarding records parsing into "_errors.txt"

@echo off
fo4Dump -dg:NPC_ -xr:TES4 "d:\games\fallout4\data\fallout4.esm" > 1.txt 2> "_errors.txt"

This is how we decode records using official editor when available. Change some value in GECK, hit save, run bat file to dump which also copies the previous dump into 2.txt for example before dumping, then switch to comparison tool for 1.txt and 2.txt which will autoreload changed files and immediately show the difference. All in all at takes like 5-10 seconds for each value on my SSD and Core i5.

**Comment by fireundubh** [comment]
All right. Sounds like something I'll use with BareTail when my new second monitor arrives. Thank you!
