### ISSUE TITLE
FO4Edit: CTDA has unused data

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#230]
Affected records:

* `CZ_ReduceDamage "Combat Zone Damage Reduction" [PERK:0020F48E]`
* `TutorialDrinkWater "Drink Water Tutorial" [PERK:001A54A4]`
* `DogmeatSuppressRegen [PERK:000D3625]`
* `PlayerPerk "Player Perk" [PERK:00056DD7]`

Adding `wbUnknown()` or `wbByteArray('Unknown', 2)` to the end of Parameter 2 seems to resolve the errors. Most records do not have any data here while the records above have `FF FF`.

```delphi
      wbInteger('Parameter #3', itS32),
      wbByteArray('Unknown', 2)
    ], cpNormal, False{, nil, 0, wbCTDAAfterLoad}),
    wbString(CIS1, 'Parameter #1'),
    wbString(CIS2, 'Parameter #2')
  ], [], cpNormal);
```

**Comment by zilav** [comment]
Are you sure? I checked those records, and then just dumped all PERKs and don't see any unused data anywhere. You probably modified something in your sources.

**Comment by fireundubh** [comment]
Probably related to #213.

**Comment by zilav** [comment]
Don't change quest stage to itU16 in CTDA, this field must have fixed length of 4 bytes. Unless FO4 has garbage values in higher 2 bytes there, it won't matter. Previous games always filled those with 0.

**Comment by fireundubh** [comment]
All right. Thank you for the commit!
