### ISSUE TITLE
FO4Edit: Form ID Subrecords

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#231]
### CELL / WRLD / ACHR / REFR

* RVIS references CELL records
* XASP references REFR records
* XLYR references LAYR records (Layer)
* XMSP references MSWP records (Material Swap)
* XRFG references RFGP records (Reference Group)
* XPRI references a dynamic array of REFR records. Unknown array max, but while investigating, I saw XPRIs with one REFR to XPRIs with 43 REFRs.

### INFO
* TSCE references SCEN records

### QUST
* LNAM references LCTN records

### RACE
* CNAM references TXST records
* NAM2 references TXST records
* RNAM references RACE records
* SRAC references RACE records
* STKD references KYWD records

### SCEN
* TNAM references SCEN records

### WTHR
* GNAM references LENS records

**Comment by fireundubh** [comment]
More...

### TERM: WNAM references REFR records

Action | Code
--- | ---
Change | `wbUnknown(WNAM)` 
To | `wbFormIDCk(WNAM, 'Unknown', [REFR])`

Seems weird to associate some TERMs with REFRs, but I tested more than a few.

### WTHR: GNAM references LENS records

Action | Code
--- | ---
Change | `wbUnknown(GNAM)` 
To | `wbFormIDCk(GNAM, 'Unknown', [LENS])`

**Comment by zilav** [comment]
Updated CELL/WRLD/REFR/ACHR.
Updated QUST, only LNAM, I don't see TNAM and TSCE there.
Updated WTHR.
Updated RACE.
WNAM in TERM doesn't reference records, skipped.

**Comment by fireundubh** [comment]
Sorry, the TNAM belongs to SCEN, and TSCE belongs to INFO.

**Comment by fireundubh** [comment]
More:

### RACE

* ATKS references EQUP records
* MPPT references TXST records
* SAKD references KYWD records

**Comment by fireundubh** [comment]
# QUST
* Alias\ALFV references VTYP records

# SCEN
* Action\DALC references KYWD records
* Action\JOUT references KYWD records (only found one though: `[SCEN:0013FEB4]`)
* Action\NNGT references DIAL records
* Action\NNUT references DIAL records
* Action\NPOT references DIAL records
* Action\NQUT references DIAL records
* Action\NTOP references DIAL records
* Action\ONAM references SOPM records
* Action\PTOP references DIAL records
* Action\QTOP references DIAL records
* Action\Unknown\Unnknown\LCEP references SCEN records

**Comment by zilav** [comment]
Updated, thanks.
No need in tables, 90% of those unknowns will be gone after GECK release. We are just running ahead of train right now.
