### ISSUE TITLE
FO4Edit: Missing String definitions

### ISSUE THREAD

**Issue by MGuffin** [TES5Edit/TES5Edit#232]
Hi
Here are 3 records field ref that are String (pulled from Fallout4_xx.Strings files), but not defined as such in 3.1.3

TERM:NAM0
TERM:WNAM
RACE:FMRN

From my experiment I also found:
English = codepage 1252
French, spanish, deutch, russian, polish, chinese, italian, ptbr = Utf8

**Comment by fireundubh** [comment]
> TERM:NAM0
> TERM:WNAM

These are not wbStrings. 

* NAM0 could be a 32-bit integer that references a string in one of the strings files, but that needs to be tested.
* WNAM is wbFormIDCk.

> RACE:FMRN

None of the RACE records appear to use FMRN, so there's no way to test and verify.

**Comment by MGuffin** [comment]
For the RACE record 
HumanRace, GhoulRace and few other are using this field.
Tested and verified through Fallout4translator.
FMRN seems to describe points for the morphing (or attach point maybe)

**Comment by fireundubh** [comment]
Ah, I see it now, but that tree is so huge I can't figure out the path.

**Comment by zilav** [comment]
Thanks, updated all 3 records.
When I need to quickly check for some ID in strings files, I use file content search tools (Total Commander for example) that support hex strings as searching subject.
