### ISSUE TITLE
FO4Edit: String Subrecords

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#234]
These are plain ol' strings, not string lookups.

Path | Form ID | Hex | String
--- | --- | --- | ---
ATKD\ATKT | 00187AF9 | 72 75 6E 6E 69 6E 67 2C 20 6A 75 6D 70 69 6E 67 20 62 69 74 65 00 | running, jumping bite
DSTD\DSTA | 0002058C | 44 65 73 74 72 6F 79 00 | Destroy
DSTD\DSTA | 001A6395 | 73 74 61 67 65 32 00 | stage2
LCEP\SSPN | 00174F8C | 53 6F 6E 67 20 4C 6F 6F 70 00 | Song Loop
MTNM\MTNM | 00187AF9 | 57 41 4C 4B | WALK

That's all I could find.

**Comment by zilav** [comment]
Thanks, updated.
