### ISSUE TITLE
FO4Edit: Unused data in CSTY and WATR

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#235]
### CSTY

* `<Warning: Unused data in:  \ [00] Fallout4.esm \ [60] GRUP Top "CSTY" \ [84] csRadStag [CSTY:00090E54] \ [3] CSME - Melee>`
* `<Warning: Unused data in:  \ [00] Fallout4.esm \ [60] GRUP Top "CSTY" \ [84] csRadStag [CSTY:00090E54] \ [6] CSLR - Long Range>`

### WATR

`<Warning: Unused data in:  \ [00] Fallout4.esm \ [63] GRUP Top "WATR" \ [40] IntMurkyWater [WATR:000713C4] \ [8] DNAM - Visual Data>`

**Comment by zilav** [comment]
Updated.
