### ISSUE TITLE
FO4Edit: WTHR expected bytes not found errors

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#236]
Errors aplenty looking like this:

`WTHR \ NAM0 - Weather Colors \ Unknown1 \ Color #0 (Sunrise) \ Red -> Expected 1 bytes of data, found 0`

**Comment by zilav** [comment]
Those are records with old Form Version. In case of weathers there is only a single old format record iirc, probably not even used, so I just ignored it instead of rearranging all definitions just because of it.
