### ISSUE TITLE
FO4Edit: VMAD Structure

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#239]
Can we figure out the VMAD structure?

```
[REFR:000250FE] SanctuaryWorkshopREF

01 00
0E 00
77 6F 72 6B 73 68 6F 70 73 63 72 69 70 74 workshopscript
01
05 // script property count
00 0C
00
43 75 72 72 65 6E 74 44 72 61 77 73 // CurrentDraws
03 01
AE 08 00 00 // value
0C 00 
4D 61 78 54 72 69 61 6E 67 6C 65 73 // MaxTriangles
03 01
C0 C6 2D 00 // value
1C 00
41 6C 6C 6F 77 55 6E 6F 77 6E 65 64 46 72 6F 6D 4C 6F 77 48 61 70 70 69 6E 65 73 73 // AllowUnownedFromLowHappiness
05 01
00 // boolean value: 0 = false, 1 = true
08 00 // ushort name len
4D 61 78 44 72 61 77 73 // MaxDraws
03 01
B8 0B 00 00 // value
10 00
43 75 72 72 65 6E 74 54 72 69 61 6E 67 6C 65 73 // CurrentTriangles
03 01
BB 55 // value
11 00
```

This is where those script sources come in a handy.

String | Object | Hex | Value | Type
--- | --- | --- | --- | ---
workshopscript | script name | 
(property count) | integer | 05 |
CurrentDraws | integer property | AE 08 00 00 | 2222 | 
MaxTriangles | integer property | C0 C6 2D 00 | 3000000 | 
AllowUnownedFromLowHappiness | boolean property | 00 | 0 (False) |
MaxDraws | integer property | B8 0B 00 00 | 3000 | 
CurrentTriangles | integer property | BB 55 | 21947 | 

For MaxDraws and MaxTriangles, those values match the defaults for the Workshop containers.

**Comment by zilav** [comment]
VMAD structure has changed in FO4. While some simple ones do indeed work using Skyrim's definition, more complex ones are not. All types of script fragments don't work for sure. VMAD is a huge binary blob, the only way to decode it is either having GECK or checking the game's runtime code.

**Comment by fireundubh** [comment]
I'm going to give Sir_Kane the longest VMAD I can find tomorrow. Please keep this open.

**Comment by Dominus-Sicarum** [comment]
```
01 00   // amount of scripts attached, little-endian.
0E 00 // script name's character count, little-endian.
77 6F 72 6B 73 68 6F 70 73 63 72 69 70 74 workshopscript
01 // most likely a flag.
05 00 // script property count
0C 00 // property name character/byte count/offset, little endian
43 75 72 72 65 6E 74 44 72 61 77 73 // CurrentDraws
03 01
AE 08 00 00 // value
0C 00 // property name character/byte count/offset, little endian
4D 61 78 54 72 69 61 6E 67 6C 65 73 // MaxTriangles
03 01
C0 C6 2D 00 // value
1C 00 // once again, property name offset
41 6C 6C 6F 77 55 6E 6F 77 6E 65 64 46 72 6F 6D 4C 6F 77 48 61 70 70 69 6E 65 73 73 // AllowUnownedFromLowHappiness
05 01
00 // boolean value: 0 = false, 1 = true
08 00 // ushort name len
```

01, 02, 03, 04 and 05 flags for property types work just like in skyrim. I did a little testing with script writing.

**Comment by zilav** [comment]
Such VMADs work right now too using Skyrim definition, I call them simple. What doesn't work is
1) script fragments
2) they also added new object types, I saw type 17 for example when checked some time ago. Without proper definition for all new types, VMAD's can't be parsed since it is a continuous data blob.

**Comment by Nephatrine** [comment]
I definitely agree we can't have a perfect VMAD representation before the GECK comes out, but it shouldn't be hard to determine whether a VMAD conforms to the Skyrim definitions and display the record properly if it does, falling back to the current hex display if it does not. It's currently a very error-prone endeavour to edit those VMADs in hex or even just to spot-check what was changed with an edit.

**Comment by zilav** [comment]
The VMAD format has changed a bit, that's why it is not decoded.

**Comment by Orvid** [comment]
The primary scripts section, as described [here](http://www.uesp.net/wiki/Tes5Mod:Mod_File_Format/VMAD_Field) are unchanged, except for the possible addition of a Struct property type as 6 and ArrayOfStructs as 16. As I haven't run into one of them yet, I can't be sure about that.

The QUST fragment is mostly the same as it is listed on the Wiki, with the difference that the unknown at the start is 3 instead, and fileName is no longer a wstring, and is a full [Script Section](http://www.uesp.net/wiki/Tes5Mod:Mod_File_Format/VMAD_Field#Scripts_Section) instead.

I have not investigated the other fragment types yet.

**Comment by zilav** [comment]
Thanks for information, VMAD is already fully decoded in the latest version, just forgot to close this. There are array of structs in vanilla records, but I didn't spot type 6 yet anywhere. Probably need to add it to definition if engine supports that type.
