### ISSUE TITLE
FO4Edit: loosing unknown flag by editing flags 

### ISSUE THREAD

**Issue by MGuffin** [TES5Edit/TES5Edit#241]
Some "unknown flags"  can be lost while using the rightclick->edit.

Example:
load fallout4.esm
go to the LIGHT formID  0002b557
Copy it as override in a test.esp
DATA Flags are set to Dynamic, Flicker, unknown15, unknown19
Edit flags with (contextmenu->edit)
it's not possible to set  unknown15, unknown19
and validating the edit actually loose  unknown15, unknown19

However it's possible to retain them with the dropdown edit (mouse click, mouse over)

Maybe there is a special command to unleash all data control for flags, in case this happens elsewhere?

**Comment by zilav** [comment]
Press F2 when standing on flags field for a full bits list, that's the preferred method of editing any values in xEdit except for multiline strings (Shift+DlbClick).

**Comment by zilav** [comment]
Oh if you know what those new flags mean, please reply so we can update definitions.

**Comment by MGuffin** [comment]
Yes, F2 is what I call the "dropdown edit"
but if someone use the menu->edit, then the data can be changed without notice.

Otherwise I didnt find yet what the new flags are for.
light->data-> flag<14> is mostly related to headlamp/power armor, but the goal is unclear.

**Comment by zilav** [comment]
"Edit" menu works differently, it edits the internal "edit values" of fields, think of it as .ToString() from other languages. F2 actually analyzes the field to be edited and creates appropriate editor. The difference is mostly obvious for CTDA\Type field for example where "edit value" is a string of bits while F2 shows a proper enumeration dropdown.

**Comment by MGuffin** [comment]
Yes, I figured that, but I was wondering for people who dont, and they are many, from what I've seen.
Maybe it could be safer to simply disable the menu->edit for this kind of datas.

**Comment by zilav** [comment]
Well this is how it was made by ElminsterAU and I don't intend to remove anything, we are only fixing bugs and adding new stuff.

**Comment by Sharlikran** [comment]
LIGH Updated
