### ISSUE TITLE
FO4Edit: WEAP references KYWDs and OMODs

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#242]
### Simple

```
06 00 // OMOD count
00 00 00 00
00 00 00 00
00 00 FF FF
01 00 // OMOD
00 00 // ???
C4 1F 09 00 // mod_10mm_Receiver_Standard [OMOD:00091FC4]
00 00 01
AB 31 02 00 // mod_10mm_Grip_Standard [OMOD:000231AB]
00 00 01
27 0E 10 00 // mod_10mm_Barrel_VeryShort [OMOD:00100E27]
00 00 01
C2 1F 09 00 // mod_10mm_Mag_Small [OMOD:00091FC2]
00 00 01
09 84 14 00 // mod_10mm_Scope_SightsIron [OMOD:00148409]
00 00 01
1D F2 04 00 // mod_Null_Muzzle [OMOD:0004F21D]
00 00 01
```

**Comment by zilav** [comment]
I noticed that OBTS ends with array of FormID and value pairs, but the problem is to determine where this array starts. For example check the second OBTS in 0005A665, if you skip 4 bytes after FF FF there is definitely not a FormID after them. Must define the data from the start before array can be defined at the end.

**Comment by fireundubh** [comment]
Other than that first byte, the structure is the same.

The first byte is the OMOD count.

The two bytes after `FF FF` looks like a flag.

* `01 00` = OMOD
* `00 01` = KYWD

If `00 01` is set, there's a KYWD before the OMOD array. This is a conditional.

# Conditional

## MQ203InstituteLaserGun "Institute" [WEAP:0005A665]

### Simple Rifle 

```
04 00 00 00 // OMOD count
00 00 00 00
00 00 00 00
FF FF 00 01
04 04 16 00 // if_tmp_SimplePistol [KYWD:00160404]
00 00
CB 33 16 00 // mod_InstituteLaserGun_LaserReceiver_Standard [OMOD:001633CB]
00 00 01
D0 33 16 00 // mod_InstituteLaserGun_BarrelLaser_Short_A [OMOD:001633D0]
00 00 01
F4 48 1A 00 // mod_InstituteLaserGun_Grip_Standard [OMOD:001A48F4]
00 00 01
0D 76 1A 00 // mod_InstituteLaserGun_Scope_SightsIron [OMOD:001A760D]
00 00 01
```

# Non-conditional

## BaseballBat "Baseball Bat" [WEAP:0008E736]

### 2076 World Series Baseball Bat

```
03 00 00 00 // OMOD count
00 00 00 00
00 00 00 00
FF FF 00 01
20 17 06 00 // if_Swatter_Restricted [KYWD:00061720]
00 00
C0 59 24 00 // modcol_melee_BaseballBat_Swatter [OMOD:002459C0]
00 00 01
34 97 0B 00 // modcol_melee_BaseballBat_Materials [OMOD:000B9734]
00 00 01
1F 17 06 00 // mod_melee_BaseballBat_LogoSwatter [OMOD:0006171F]
00 00 01
```

## HuntingRifle "Hunting Rifle" [WEAP:0004F46A]

### Simple Rifle

07 00 00 00 // OMOD count
00 00 00 00
00 00 00 00
FF FF 01 00
07 00 // another OMOD count?
A2 98 04 00 // mod_UniversalOffset_Range_BoltAction [OMOD:000498A2]
00 00 01
6B F4 04 00 // mod_HuntingRifle_Receiver_Standard [OMOD:0004F46B]
00 00 01
74 F4 04 00 // mod_HuntingRifle_Barrel_Short [OMOD:0004F474]
00 00 01
6E F4 04 00 // mod_HuntingRifle_Grip_StockShort [OMOD:0004F46E]
00 00 01
D8 D4 05 00 // mod_HuntingRifle_Mag_Small [OMOD:0005D4D8]
00 00 01
18 84 14 00 // mod_HuntingRifle_Scope_SightsIron [OMOD:00148418]
00 00 01
1D F2 04 00 // mod_Null_Muzzle [OMOD:0004F21D]
00 00 01

**Comment by fireundubh** [comment]
Sir_Kane says OBTF is a bool.

**Comment by zilav** [comment]
OBTS is used in ARMO WEAP FURN NPC_, is it the same for all form types?

**Comment by zilav** [comment]
I tested on WEAP, that definition looks ok except for this one
http://pastebin.com/raw.php?i=PV4cQzR0
There are 4 extra bytes at the end of the second OBTS

**Comment by zilav** [comment]
Looks like each Part B entry need to another 4 bytes after float, since OBTS with 2 parts B has 8 extra bytes at the end.

**Comment by zilav** [comment]
Updated.
