### ISSUE TITLE
Decoding WEAP - Weapons

### ISSUE THREAD

**Issue by BMASTER91** [TES5Edit/TES5Edit#244]
Hey guys

I start this ticket for particular questions about weapon changes. Where to find and what they do.
Hope we can get something together.

**Comment by BMASTER91** [comment]
My first question is, does someone know what all the property values in the mod section mean?
Like SightedTransitionSeconds or Rank?

**Comment by fireundubh** [comment]
If they're not in xEdit and there's no ticket open, then no, you're free to work on that.

**Comment by Khormin** [comment]
- Weapons (WEAP)
DAMA - Critical Data > Damage seems to effect energy weapon damage, while DNAM - Data > Damage is simply ballistic/physical damage.  Adjusting this value adds or increases existing energy damage of weapons.

I don't think DAMA affects criticals at all.

Pretty sure as well that WAMD - Unknown is references to the ironsight model for zooming.  Untested.

- Modifications (OMOD)
LNAM - Unknown seems to be the "long name" for the module as listed in the inventory.  Adjusting this causes the modification autonaming in weapons workbenches to reflect that change.

**Comment by zilav** [comment]
Since it only concerns the renaming of already defined fields, I'd prefer to wait for CK and copy field names from there. We are more interested in decoding values hidden in unknown hex arrays.
Thanks for the info anyway!
