### ISSUE TITLE
Multiple element select and drag

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#245]
Feature Request

This would really speed up conflict resolution.

**Comment by zilav** [comment]
Imposible unfortunately, drag&drop function checks source element against the target element for assignment possibility, there must be direct association between them to check. Dragging a selection is like having a lot of sources but only a single target. It is also the reason while there is no selection in the right pane since all right click menu options are targeted at particular element.

**Comment by RoyBatty64** [comment]
It should at least be possible for leveled lists and formlists where the record types are the same.

**Comment by zilav** [comment]
For sorted lists where destination index is irrelevant.. maybe. Form lists are not sorted. Anyway I doubt this is going to happen any time soon.

**Comment by fireundubh** [comment]
@RoyBatty64: Not as convenient as multiple drag-and-drop, but here's a script.

Libs required: [dubhFunctions](https://github.com/fireundubh/xedit-scripts/blob/master/lib/dubhFunctions.pas) and [mteFunctions](https://github.com/matortheeternal/TES5EditScripts/blob/master/Edit%20Scripts/mteFunctions.pas)

```delphi
unit UserScript;
uses dubhFunctions;

var
	lsElementsToCopy: TStringList;

function Initialize: Integer;
var
	sElementsToCopy: String;
begin
	lsElementsToCopy := TStringList.Create;
	// you can enter field names, signatures, paths, or indexed paths
	if not InputQuery('Enter fields separated by commas', 'Fields:', sElementsToCopy) then
		Result := 1;
	lsElementsToCopy.CommaText := sElementsToCopy;
end;

function Process(e: IInterface): Integer;
var
	i: Integer;
	m, el: IInterface;
begin
	m := OverrideMaster(e, 2); // try 1 if you need an override master further back
	for i := 0 to lsElementsToCopy.Count - 1 do begin
		el := GetElement(m, lsElementsToCopy[i]);
		wbCopyElementToRecord(el, e, false, true);
	end;
end;

function Finalize: Integer;
begin
	lsElementsToCopy.Free;
end;

end.
```
