### ISSUE TITLE
Decoding NPC_

### ISSUE THREAD

**Issue by capmac** [TES5Edit/TES5Edit#246]
Here is a list of TETI mappings. These are the extras when creating a character (makeup, blemishes, damage, markings)

Each of these has a corresponding TEND record which needs to be decoded yet. They hold values like 0% to 100%, predefined colors, etc.

These TETI/TEND pairs are in a list which doesn't have a fixed length. So the list can be empty.

There seems to be 7 groups according to the FO4Dump.

GhoulChild
MaleHumanChild
FemaleHumanChild
MaleGhoul
FemaleGhoul
FemaleHuman
MaleHuman

I decoded only the values for FemaleHuman for now

SkinTints
	Skin tone, 01 00 90 04

Blemishes
	Eye Socket Shade, 02 00 B5 06
	Lip Color, 01 00 B6 06
	Rough Face, 02 00 BE 06
	Forehead Blemishes 1, 02 00 BF 06
	Forehead Blemishes 2, 02 00 C0 06
	Forehead Blemishes 3, 02 00 C1 06
	Forehead Blemishes 4, 02 00 C2 06
	Forehead Blemishes 5, 02 00 C3 06
	Forehead Blemishes 6, 02 00 C4 06
	Forehead Blemishes 7, 02 00 C5 06
	Cheek Blemishes 1, 02 00 C6 06
	Cheek Blemishes 2, 02 00 C7 06
	Cheek Blemishes 3, 02 00 C8 06
	Cheek Blemishes 4, 02 00 C9 06
	Cheek Blemishes 5, 02 00 CA 06
	Cheek Blemishes 6, 02 00 CB 06
	Cheek Blemishes 7, 02 00 CC 06
	Mouth Blemishes 1, 02 00 CD 06
	Mouth Blemishes 2, 02 00 CE 06
	Mouth Blemishes 3, 02 00 CF 06
	Mouth Blemishes 4, 02 00 D0 06
	Mouth Blemishes 5, 02 00 D1 06
	Mouth Blemishes 6, 02 00 D2 06
	Mouth Blemishes 7, 02 00 D3 06
	Pocked Neck, 02 00 D4 06
	Pocked Face, 02 00 D5 06
	Cheek Creases, 02 00 D6 06
	Cheeks Gaunt, 02 00 D7 06
	Eyes Gaunt, 02 00 D8 06
	Sun Scorched, 02 00 D9 06
	Red Nose, 02 00 DA 06
	Splotches - Left Cheek, 02 00 DB 06
	Splotches - Right Cheek, 02 00 DC 06
	Splotches - Left Eye, 02 00 DD 06
	Splotches - Right Head, 02 00 DE 06
	Splotches - Left Head, 02 00 DF 06
	Splotches - Chin, 02 00 E0 06
	Splotches - Neck, 02 00 E1 06
	
Makeup
	Blush 1, 01 00 19 05
	Blush 2, 01 00 29 07
	Blush 3, 01 00 2A 07
	Lip Liner, 01 00 26 07
	Lip Gloss, 02 00 25 05
	Lip Matte, 02 00 27 05
	Lipstick, 01 00 28 05
	Eye Liner Waterline, 01 00 46 07
	Eye Liner 1, 01 00 56 07
	Eye Liner 2, 01 00 E2 06
	Eye Liner 3, 01 00 1E 07
	Eye Liner 4, 01 00 42 07
	Eye Liner 5, 01 00 43 07
	Eye Liner 6, 01 00 44 07
	Eye Liner Lower 1, 01 00 57 07
	Eye Liner Lower 2, 01 00 45 07
	Eye Shadow 1, 01 00 1E 05
	Eye Shadow 2, 01 00 52 07
	Eye Shadow 3, 01 00 20 07
	Lower Eye Shadow 1, 01 00 1F 05
	Lower Eye Shadow 2, 01 00 23 05
	
Markings
	Freckles - Upper, 02 00 B7 06
	Freckles - Lower, 02 00 B9 06
	Freckles - Middle, 02 00 B8 06
	Moles - Cheek, 02 00 BA 06
	Moles - Full Face, 02 00 BB 06
	Moles - Lower Face, 02 00 BC 06
	Moles - Nose, 02 00 BD 06
	
Damage
	Scar - Left Long, 02 00 E6 06
	Scar - Lip Gouges, 02 00 E7 06
	Scar - Right Brow Deep, 02 00 E8 06
	Scar - Center Burn, 02 00 E9 06
	Scar - Right Burn, 02 00 EA 06
	Scar - Left Brow Gash, 02 00 EB 06
	Scar - Middle Deep, 02 00 EC 06
	Scar - Left Back Deep, 02 00 ED 06
	Scar - Forehead, 02 00 EE 06
	Scar - Left Brow Small, 02 00 EF 06
	Scar - Nose Gouge, 02 00 F0 06
	Scar - Nose Arch, 02 00 F1 06
	Scar - Lip Cut, 02 00 F2 06
	Scar - Forced Smile, 02 00 F3 06
	Scar - Lip Scratch, 02 00 F4 06
	Scar - Right Stitches, 02 00 F5 06
	Scar - Right Brow Long, 02 00 F6 06
	Scar - Right Gouge, 02 00 F7 06
	Scar - Chin, 02 00 F8 06
	Scar - Head Burn, 02 00 F9 06
	Scar - Cheek Burn, 02 00 FA 06
	Boxer - 12 Rounds, 02 00 01 07
	Boxer - Broken Nose, 02 00 02 07
	Boxer - Black Eye, 02 00 03 07
	Boxer - Fat Lip, 02 00 04 07

**Comment by zilav** [comment]
Hmm looks like the 3rd byte is unique and actually identifies the feature, the first two and the last are probably flags. Don't you think?

**Comment by capmac** [comment]
I doubt it. I think all four bytes identify a face feature. In-game with showlooksmenu there is no indication that there are flags in addition to the TEND record. The value in the TEND record configures the facial feature. 64 is 100% for example

You can find the TETI entries in the RACE section too I think. But there the first byte is different. I just replaced it with 01, and if its 16 then its 02. Works so far.

**Comment by zilav** [comment]
Well if they are the same in RACE except for the first byte, then it is definitely a flag of some sort. And with second byte being always 00 I guess that flag field is 2 bytes integer.

**Comment by Cruor34** [comment]
Hello, I was asked to post this here.

Under "Non Player Character (actor) when you go into to edit an NPC, for most of them Health offset is actually the EXP they are worth, and Stamina Offset is there level. If you want an example simply sort my name and go to Raiders, and you can see the first raider is Health offset 5 (5 exp modified by int) and Stamina Offset it 1 (level 1) etc. 

The npcs before level 9 or so just have pitiful health and over 20 or so they start to get stupid amounts of health. On this topic I have found something odd, I THINK raiders are based on human race stats, thus a level 1 raider has -10 health, or 30 health. (human race default is 40) yet, when I give them posative health, like 40, they don't have 80 health as Id like, but 90-100 health... it is extremely puzzling. Gunners on the other hand seem to have the exact health I give to them, I am very confused over the issue. extra health for certain NPC's must exist somewhere, in some form, but I havn't figured it out yet.

**Comment by hurricanekali** [comment]
Okay so I was working with the NPC_ FMRI and FMRS sections trying to figure out how exactly to change skin tones on human children.

For HumanChild, I have two examples:
ID 2F15, Pete Pembroke
In RACE, Skin Tone is: 0C 00 BE 04 
In NPC_, Skin Tone TETI is: 01 00 BE 04\
BE seems to be the flag for males
In NPC_ he has the following TEND assigned as his skin tone: 64 E9 DA D8 00 C0 04
(Skin Tone associated: C0 04 00 00 00 00, "Rosy", based on the C0 or the C0 04 at the end)

ID 2A830, Erin Combes
In RACE, Skin Tone is: 0C 00 C9 04 
In NPC_, Skin Tone TETI is: 01 00 C9 04
C9 seems to be the flag for females
In NPC_ she has the following TEND assigned as his skin tone: 64 BF AE AA 00 D2 04
(Skin Tone associated: D2 04 00 00 00 00, "Copper", based on the D2 or the D2 04)

All skin tones, both for adult and child, that I have seen so far start with 64 in NPC_. The NPC_ skin tones also have 7 bytes instead of 6 like the RACE ones (the 64 in the front counts as the extra byte). And it seems the 00 is also always there in the skin tone. Not entirely sure on the second, third, and fourth bytes (from the left) yet, but I miiiight fiddle with them out of curiosity.

**Comment by zilav** [comment]
I guess the best way is to wait for CK here, too many unknowns.

**Comment by wmrojer** [comment]
NPC_ -> ACBS  
 Unknown dword before "Template Flags" are flags pointing to what fields in TPTA are used. 
 0x0001 -> field #0 in TPTA down to 0x1000 -> field #12 in TPTA.
 Order is not the same as "Template Flags" even thou the use is similar.
 Common values used are 0x1FBE, 0x1103

NPC_ -> TPTA 
 12 Template RefID's for different parts of NPC_.  This seems to override TPTL but both are set. Always contains 12 fields when used.
 #7 is RefID to get FULL and SHRT from. Name
 #8 is RefID to get COCT, CNTO, DOFT, SOFT from. Basically inventory
 The rest of the fields I haven't figured out.

If the flag in ACBS is set but that field in TPTA is null then if falls back and uses the old TPTL as RefID.
This makes it possible to have an NPC that uses several different other NPC's as templates for different parts.

Examples:
EncWorkshopNPCFemaleFarmer01 [NPC_:00113346]
 Flags 0x1FBE
 TPTA fields #1-5, 7-12 and TPTL points to EncWorkshopNPCMaleFarmer01Template "Settler" [NPC_:00113340]

WorkshopNPCMale "Settler" [NPC_:0014CEA8]
  Flags 0x1103
  TPTL points to LCharWorkshopNPC [LVLN:00113341]
  TPTA
     #0 LCharWorkshopNPCMale [LVLN:001243CC]
     #1 LCharWorkshopNPC [LVLN:00113341]
     #8 LCharWorkshopNPC [LVLN:00113341]
     #12 LCharWorkshopNPC [LVLN:00113341]

Hope it can be of some use.

**Comment by zilav** [comment]
Thanks, looks like their meaning matches the template flags from Skyrim, so I will name them using Skyrim's names until CK is out. Will also hide unused TPTA entries based on flags.
Updated.

**Comment by zilav** [comment]
Looks like only a part of TETI is responsible for a feature enumeration since the same feature can have different TETI value. I'm just leaving them as hex values unless someone can provide full reliable decoded outline.
