### ISSUE TITLE
No ESPs should be selected on start

### ISSUE THREAD

**Issue by dsandstrom** [TES5Edit/TES5Edit#248]
Sorry if this has been mentioned before, I didn't really know how to search for it.  Every time I start xEdit, I have to unselect all the mods I have enabled.  I think it would be better if no ESPs/ESMs were selected at start and let us select the one ESP that we are working on.

**Comment by zilav** [comment]
It is intended behaviour to select active plugins. You can select/deselect/invert selection for all plugins using right click menu.
