### ISSUE TITLE
FO4Edit: CMPO DATA is an Integer

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#254]
I think these integers are scalars used to determine the rarity of a component with 0 meaning "Super Common" and 50 meaning "Super Rare." You can see a very clear progression here.

Hex | Value | Form ID
--- | --- | ---
02 00 00 00 | 2 | c_Bone [CMPO:0001FA98]
02 00 00 00 | 2 | c_Wood [CMPO:0001FAC2]
03 00 00 00 | 3 | c_Concrete [CMPO:0005A0C4]
03 00 00 00 | 3 | c_Plastic [CMPO:0001FAB7]
03 00 00 00 | 3 | c_Steel [CMPO:0001FABD]
04 00 00 00 | 4 | c_Cloth [CMPO:001223C7]
05 00 00 00 | 5 | c_Cork [CMPO:0001FA9D]
05 00 00 00 | 5 | c_Fertilizer [CMPO:0005A0C7]
07 00 00 00 | 7 | c_Ceramic [CMPO:0001FA9A]
08 00 00 00 | 8 | c_Lead [CMPO:0001FAAD]
0A 00 00 00 | 10 | c_Acid [CMPO:0001FA8C]
0A 00 00 00 | 10 | c_Leather [CMPO:0001FAAE]
0A 00 00 00 | 10 | c_Rubber [CMPO:0001FAB9]
0C 00 00 00 | 12 | c_Screws [CMPO:0003D294]
0D 00 00 00 | 13 | c_Glass [CMPO:0001FAA4]
0F 00 00 00 | 15 | c_Aluminum [CMPO:0001FA91]
0F 00 00 00 | 15 | c_Antiseptic [CMPO:0001FA96]
0F 00 00 00 | 15 | c_Springs [CMPO:0001FABC]
12 00 00 00 | 18 | c_Gears [CMPO:0001FAB0]
14 00 00 00 | 20 | c_Copper [CMPO:0001FA9C]
14 00 00 00 | 20 | c_Oil [CMPO:0001FAB4]
17 00 00 00 | 23 | c_Crystal [CMPO:0001FA9F]
19 00 00 00 | 25 | c_AntiBallisticFiber [CMPO:0001FA94]
19 00 00 00 | 25 | c_Circuitry [CMPO:0001FA9B]
1C 00 00 00 | 28 | c_Fiberglass [CMPO:0001FAA1]
1E 00 00 00 | 30 | c_Asbestos [CMPO:0001FA97]
1E 00 00 00 | 30 | c_Silver [CMPO:0001FABB]
22 00 00 00 | 34 | c_FiberOptics [CMPO:0001FAA0]
28 00 00 00 | 40 | c_Adhesive [CMPO:0001FAA5]
2D 00 00 00 | 45 | c_Gold [CMPO:0001FAA6]
32 00 00 00 | 50 | c_NuclearMaterial [CMPO:0001FAB3]

I don't see how these values play with the `ModScrapScalar` globals, but math isn't my strong suit.

**Comment by zilav** [comment]
Well I can define it as rarity, but I don't see when and how those values could be used by the game. Components are firmly defined on other constructible records and recipes, and loot distribution is handled by leveled lists. Unless they added something else in FO4 on top of that.

**Comment by zilav** [comment]
Updated.

**Comment by isathar** [comment]
I know this one is closed, but thought I'd add that this value directly influences the amount of XP gained from crafting something that contains the component. So, if a recipe consists of 1 component with this set to 3, you'll get 3XP for crafting it. I'm not sure about the math on using multiple different components, though.
You've already updated the tool for this value, so I guess it doesn't matter and Rarity is as good a name as any for it. Awesome work on the FO4Edit updates, by the way.

**Comment by zilav** [comment]
All names will be updated once CK is out, so lets leave it as rarity, doesn't matter much.
