### ISSUE TITLE
FO4Edit: KYWD TNAM is a Flag

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#257]
I don't know what to name these flags, but you can see them clearly in the table below.

Examples:

* `00 00 00 00` obviously means None.
* `04 00 00 00` indicates the KYWD is a conditional.
* `09 00 00 00` associates the KYWD with crafting.
* `10 00 00 00` associates the KYWD with quests.
* `12 00 00 00` associates the KYWD with magic effects.

We won't have the formal names of these flags until the toolset is released, but I think we should have some placeholder names in the meantime.

## Long, long table

https://gist.github.com/fireundubh/d351ae079ebcd00c5ed3

## Bonus: DNAM

By the way, is "DNAM" right? DESC would seem more appropriate. In any case, DNAM isn't used by the game; it's just a notes field for internal reference.

**Comment by zilav** [comment]
It is obviously enumeration. Don't want to play a guessing game on names, will just define them as "unknown N" and copy proper names later from CK. The same with DESC. And all other similar fields in other records too. Names don't matter a lot right now, they will have to be updated later when CK is out anyway for consistency.

**Comment by zilav** [comment]
Updated.
