### ISSUE TITLE
FO4Edit: MATO DNAMs appear to be embedded NIFs

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#259]
Best I can do here is show you a screenshot.

## MarkarthMoss [MATO:00028B68]

![Screenshot](http://i.imgur.com/XLJ7e9e.png)
I tried saving to a NIF and loading the NIF in NifSkope. The file loads with this error:

> ""array Extra Data List invalid"" 

> ""device position incorrect after block number 0 (BSLightingShaderProperty) at 0x8a ended at 0x96 (expected 0x124)"" 

That might just be due to the current state of the NifSkope 2.0 Pre-Alpha.

This NIF has BSLightingShaderProperty and BSShaderTextureSet blocks.

## VolcanicSulfurCrystals [MATO:000998A7]

Both DNAMs load as NIFs in NifSkope *without* errors.

They have no mesh data as above, but these have different blocks.

* `Property Data\[0]` has a BSEffectShaderProperty block
* `Property Data\[1]` has a NiAlphaProperty block

**Comment by zilav** [comment]
Well if they still reference "markath" textures then they are probably not used at all. I don't remember an option to import nif file when editing MATO even in Skyrim's CK. Not sure what we could change here, better leave it as hex array like in Skyrim definitions.
