### ISSUE TITLE
FO4Edit: NOTE DNAM and DATA

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#261]
## DNAM

DNAM is a flag.

* `01` is associated with only quest holotapes.
* `02` is associated with only holotape games.
* `03` is associated with only special/collectible/recipe holotapes.

Those aren't the official names, of course. That's how they're grouped though.

## DATA

These NOTE records are the only NOTE records that have a non-nil float.

The first 4-byte block could be an integer or flags.

I'm betting on integer as `78` is 120, which would be way too many flags, if enum.

Possible integer/flag values in hex: `00`, `01`, `05`, `14`, `2C 01`, `78 03`.

Hex | Int | Float | Form ID
--- | --- | --- | ---
`01 00 00 00`<br>`CD CC 4C 3E` | 1 | 0.2 | holotapeLadiesAux01 [NOTE:0019D2E3]
`01 00 00 00`<br>`CD CC 4C 3E` | 1 | 0.2 | holotapeLadiesAux02 [NOTE:0019D2E8]
`01 00 00 00`<br>`CD CC 4C 3E` | 1 | 0.2 | holotapeLadiesAux03 [NOTE:0019D2E9]
`01 00 00 00`<br>`CD CC 4C 3E` | 1 | 0.2 | holotapeTheControl01 [NOTE:0019D2EC]
`01 00 00 00`<br>`CD CC 4C 3E` | 1 | 0.2 | holotapeTheControl02 [NOTE:0019D2F0]
`01 00 00 00`<br>`CD CC 4C 3E` | 1 | 0.2 | holotapeTheControl03 [NOTE:0019D2F1]
`2C 01 00 00`<br>`00 00 00 00` | 300 | 0.0 | AtomicCommand_HolotapeGame [NOTE:0006167B]

**Comment by zilav** [comment]
Thanks, updated.

**Comment by fireundubh** [comment]
Update for you:

* `DATA\[0]` is Value
* `DATA\[1]` is Weight
