### ISSUE TITLE
FO4Edit: SOUN REPT byte array contains (Float, Float, Flag)

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#262]
Hex | Values | Form ID
--- | --- | ---
`00 00 90 41`<br>`00 00 98 41`<br>`01` | 18.0<br>19.0<br>Flag | AMBWeatherRainExteriorSpotTESTmarker [SOUN:000422C1]
`00 00 C0 40`<br>`00 00 40 41` | 6.0<br>12.0 | AMBSanctuaryHouseRuinCreakAmarker [SOUN:0006E293]
`00 00 C0 40`<br>`00 00 40 41`<br>`00` | 6.0<br>12.0<br>Flag | AMBExtSanctuaryHillsSpotChargenAmarker [SOUN:0019DB7C]

**Comment by zilav** [comment]
Thanks, updated.
