### ISSUE TITLE
FO4Edit: TXST Unknowns

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#263]
* `DODT\Unknown` is Alpha Threshold. `7F 00` is 127, which is the default alpha threshold for DXT10 quantization. Records with this value have the Alpha Blending flag set.

* `DODT\Color\Unknown` is Alpha, as in RGBA. `00` means 100% transparent.

* `MNAM` is Material.

**Comment by zilav** [comment]
And what about `AB AB` values for Alpha threshold contained in some records?
As for the color and alpha, I'm not sure that it is really an alpha. There are a lot of instances of color values in records stored as 4 values but no way to change the alpha component in CK. Better wait for official editor to check that.
Updated MNAM

**Comment by fireundubh** [comment]
See:

> Records with this value have the Alpha Blending flag set.

None of these have the Alpha Blending flag.

Hex | Form ID | Flags
--- | --- | ---
AB AB | DecalBloodBladeHit [TXST:0001F827] | No subtextures
AB AB | DecalBloodDraugrHit [TXST:000F0EAC] | No subtextures
AB AB | DecalBloodHit01 [TXST:00023363] | No subtextures
AB AB | DecalBloodHit01Organic [TXST:002402D0] | No flags
AB AB | DecalBloodHitGlowing [TXST:001C7574] | No subtextures

**Comment by zilav** [comment]
I agree that this is a threshold value for alpha, but DODT is unchanged since Skyrim and there is no way to set this value in CK. Better wait for FO4 CK to check that.
