### ISSUE TITLE
FO4Edit: WTHR RGBA and UNAM

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#264]
Many of the Unknowns should be Alpha, as they're part of RGBA arrays. Too many to list.

### CommonwealthGSRadstorm [WTHR:001C3D5E]

Hex | Value
--- | ---
7B 5E 1C 00 | RadStormSpell [SPEL:001C5E7B]
00 00 00 00 | Same value for all other WTHR records
91 EC 23 00 | GlowingSeaPlayerRadiationRadStorm [SPEL:0023EC91]
00 00 00 00 | Same value for all other WTHR records
A8 44 1F 00 | Not a record or localized string Form ID
00 00 00 00 | Same value for all other WTHR records

**Comment by zilav** [comment]
Thx, updated.
