### ISSUE TITLE
FO4Edit: ZOOM GNAM Flags and Floats

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#265]
## GNAM\[1]

Looks like flags.

Hex | Value | Form ID
--- | --- | ---
00 00 00 00 | 0 | ZM_Default [ZOOM:0004B246]
00 00 00 00 | 0 | ZM_HuntingRifle [ZOOM:001EC01E]
00 00 00 00 | 0 | ZM_InstituteLaserGun [ZOOM:0006FF4C]
00 00 00 00 | 0 | ZM_Minigun_150 [ZOOM:0016429C]
00 00 00 00 | 0 | ZM_PipeSyringer [ZOOM:00211D66]
00 00 00 00 | 0 | ZM_SubmachineGun [ZOOM:001B2913]
01 00 00 00 | 1 | ZM_Standard_Scope_x2 [ZOOM:0019E105]
03 00 00 00 | 3 | ZM_Standard_Scope_x6 [ZOOM:000AF2AA]
06 00 00 00 | 6 | ZM_Standard_Scope_x4 [ZOOM:000AF2A9]
06 00 00 00 | 6 | ZM_Standard_Scope_x4_NightVision [ZOOM:0019DF76]
08 00 00 00 | 8 | ZM_Standard_Scope_x10 [ZOOM:000AF2AC]
0D 00 00 00 | 13 | ZM_Standard_Scope_x10_NightVision [ZOOM:000AF2B8]
0D 00 00 00 | 13 | ZM_Standard_Scope_x6_NightVision [ZOOM:000AF2B7]
10 00 00 00 | 16 | ZM_Recon_Scope_x10 [ZOOM:00247A24]
10 00 00 00 | 16 | ZM_Recon_Scope_x2 [ZOOM:001C6F3E]
10 00 00 00 | 16 | ZM_Recon_Scope_x4 [ZOOM:00247A25]
## GNAM\[3]

Hex | Value | Form ID
--- | --- | ---
`00 00 00 00`<br>`00 00 00 00`<br>`00 00 80 BE` | Unused?<br>Float<br>-0.25 | ZM_HuntingRifle [ZOOM:001EC01E]
`00 00 00 00`<br>`00 00 00 00`<br>`29 5C EF 3F` | Unused?<br>Float<br>1.87 | ZM_InstituteLaserGun [ZOOM:0006FF4C]
`00 00 00 00`<br>`00 00 A0 C0`<br>`00 00 00 00` | Unused?<br>-5.0<br>Float | ZM_Recon_Scope_x10 [ZOOM:00247A24]

**Comment by zilav** [comment]
Updated. Leaved the "flag" field as hex, this could be simply an integer. CK will decide :)
