### ISSUE TITLE
FO4Edit: WEAP DNAM Unknowns

### ISSUE THREAD

**Issue by phobos2077** [TES5Edit/TES5Edit#268]
DNAM data:
```
Ammo 
Fire Speed - Float
Reload Anim Speed - Float
Unknown - Float
Unknown - Float // usually 256
Unknown - Float // usually 256
Attack Delay, sec. - Float
Unknown - Float
Unknown - Float

```
Sixth float value is a delay between shots (probably in seconds, it controls rate of fire for some weapons).

**Comment by zilav** [comment]
Someone in Fo4Edit nexus comments said that this value is 10/value=RateOfFile. So we need more definite information to update this. Right now it is assumptions only.

**Comment by phobos2077** [comment]
Well I tested it (and used for my mod) so when I change this value from 0.5 to 0.4 for Combat shotgun, "Speed" is increased exactly 20%. BUT, for some weapons it is 0.0  (like Minigun), my guess is some other flag controls general weapon behavior and decides which value to use. I will try changing other values.

**Comment by phobos2077** [comment]
Updated after some testing. Sometimes you can't see the changes because of weapon mods that override default value instead of multiplying it.

**Comment by fireundubh** [comment]
I would recommend copying the WEAP record as new in xEdit, removing all OMODs from that weapon including the defaults, and spawning only the base WEAP object. You can also tweak the values live with xEdit, and then use the `hlp` command to hotload/hotreload the plugin in the game.

**Comment by fireundubh** [comment]
@zilav:

In `DNAM\[24]`, the first four bytes is a Form ID. I'd call this field `Sound - Fast Equip`.

* `Deliverer [WEAP:000DC8E7]`: `WPNPistolCovertEquipUpFast [SNDR:001D9336]`
* `DoubleBarrelShotgun [WEAP:00092217]`: `WPNShotgunDoubleBarrelEquipUpFast [SNDR:00231FC8]`

**Comment by phobos2077** [comment]
@fireundubh : Could you please point me to where I can learn how to "tweak the values live with xEdit" and how to do hotreload of the plugin?
Do you I need to reload from a save after I hotreloaded a plugin?

If I knew this yesterday it would've saved me at least an hour :)

**Comment by fireundubh** [comment]
1. Create the plugin, and play the game with the plugin loaded like any other mod.

2. While in the game, open xEdit, load the plugin, modify the plugin, and press Ctrl+S to save.

3. Back in the game, use the `hlp` command in the in-game console (e.g., `hlp plugin_name`.)

4. Switch back to xEdit, modify the plugin, and press Ctrl+S to save.

5. Repeat 3-4 as needed.

**Comment by zilav** [comment]
Added "Sound - Fast Equip" FormID.

**Comment by phobos2077** [comment]
@fireundubh : I can't modify the plugin when the game is loaded, seems like the file is locked by the game. When I press Ctrl+S it just saves another copy with date/time in it's extension, instead of modifying original plugin. When I try to close FO4Edit, it tells me it can't delete my plugin.

**Comment by fireundubh** [comment]
Is the game locking the plugin? Or is that xEdit's doing? @zilav, thoughts?

**Comment by phobos2077** [comment]
@fireundubh : You forgot to mention "fcf" console command that I need to input in order for Fallout4 process to unlock plugins. However, I can only save my changes by closing xEdit. xEdit itself blocks me from manually deleting plugin, renaming it. 

It's inconvenient that I can't just directly save my changes to the plugin without closing the program, if it is not locked by another process.

**Comment by zilav** [comment]
xEdit never overwrites original plugin while working, only when closing. However FO4Edit loads in 3-4 seconds on my SSD, then I bookmark the record I'm working with using Ctrl+1..5 and quickly go back with Alt+1..5
All in all it takes around 7 seconds for me to get back to editing the particular record in FO4Edit. You can also disable loading of BAS archives in Options to speed this up, but some xEdit features won't work without archives.

**Comment by phobos2077** [comment]
@zilav : do I need to provide some kind of proof before these offsets are included? Or someone already decoded the whole thing?

PS: about the saving - I'm sure there were some good reason for such behavior (save on close), but for me as an end user, it seems extremely strange why I can't just save the damn file I modified without closing and re-starting it (manually) every time :)

**Comment by zilav** [comment]
It is for your safety :)

Just write down your findings.

**Comment by phobos2077** [comment]
@zilav : they are in the top message.

**Comment by zilav** [comment]
Updated.

**Comment by phobos2077** [comment]
@zilav : I don't know yet what are these values exactly, but I can tell which are float values in the large Unknown section at the end of DNAM:

```
1b - unknown
4b - float
2b - unknown
4b - float
4b - float
4b - float
4b - unknown (looks like integer)
4b - unknown
```

Also the 4-byte Unknown right before *Weight* is also a float.

**Comment by zilav** [comment]
Updated, thx.
I left the value before Weight as bytes because for example in `Weapon [00210B63] <AssaultronRightBlade>` it has a value of `-107374176.000000` which is unlikely to be a float. Probably the type of this field depends on some flags, common practice in previous games.

**Comment by Kingcato** [comment]
16-Byte Unknown above Magazine size:

The 15th byte toggles infinite ammo and inventory visibility (Companion Weapons)

00 00 00 00 00 00 00 00 00 00 00 00 00 01 **12** 00 - Piper's 10mm
00 00 00 00 00 00 00 00 00 00 00 00 00 01 **00** 00 - 10mm

00 00 00 00 00 00 00 00 00 00 00 00 00 01 **52** 00        McCready's Hunting Rifle
02 00 00 00 00 00 00 00 00 00 00 00 00 01 **40** 00        Hunting Rifle

All companion Weapons have a +12 value there.
Converting this to binary toggles 2 bits to 1
Tested with +10 to toggle first bit. Still invisible in Inventory and Infinite Ammo
Tested with +02 to toggle second bit. No change to Weapon

**Comment by zilav** [comment]
Yes it is a flags field obviously, but I prefer to wait for CK to define all flags at once with correct names.

**Comment by snowsharky** [comment]
raverbane from nexus was able to id this as action point cost
http://forums.nexusmods.com/index.php?/topic/3621270-action-points-in-fo4edit/
![](http://i67.tinypic.com/157gh2b.jpg)

**Comment by zilav** [comment]
Updated.

**Comment by fireundubh** [comment]
I found what I want after a lot of testing, so I probably won't dig more into this until the CK arrives.

```delphi
    {09} //wbByteArray('Unknown 9', 16),
    wbInteger('Enum', itU32,
      wbEnum([
        'Unknown 0',
        'Unknown 1',
        'Unknown 2',
        'Unknown 3'
      ])
    ),
    wbByteArray('Unused', 4),
    wbByteArray('Unused', 4),
    wbInteger('Flags', itU32,
      wbFlags([
      {0x00000001} 'Player Only',     // even with the Use Weapon flag, turret won't fire
      {0x00000002} 'NPCs Use Ammo',   // turret ammo depletes after firing
      {0x00000004} 'Unknown Flag 2',
      {0x00000008} 'Unknown Flag 3',
      {0x00000010} 'Unknown Flag 4',
      {0x00000020} 'Unknown Flag 5',
      {0x00000040} 'Unknown Flag 6',
      {0x00000080} 'Unknown Flag 7',
      {0x00000100} 'Playable',        // every weapon has this, except mounted creature weapons (e.g., AssaultronLaser, Protectron01HeadLaser, TurretMountedSpotlight01)
      {0x00000200} 'Unknown Flag 9',
      {0x00000400} 'Unknown Flag 10',
      {0x00000800} 'Unknown Flag 11',
      {0x00001000} 'Unknown Flag 12',
      {0x00002000} 'Unknown Flag 13',
      {0x00004000} 'Unknown Flag 14',
      {0x00008000} 'Unknown Flag 15',
      {0x00010000} 'Unknown Flag 16',
      {0x00020000} 'Unknown Flag 17',
      {0x00040000} 'Unknown Flag 18',
      {0x00080000} 'Unknown Flag 19',
      {0x00100000} 'Use Weapon',      // without this checked, turrets won't attack with their weapons
      {0x00200000} 'Unknown Flag 21',
      {0x00400000} 'Unknown Flag 22',
      {0x00800000} 'Unknown Flag 23'
      ])
    ),
```

**Comment by Sharlikran** [comment]
Updated
