### ISSUE TITLE
FO4Edit: AURO AOR2 Structure

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#270]
## AOR2

It's pretty clear how the first value relates to the LOS records. No idea about the others.

I'm also pretty sure the last four bytes are flags.

### Companion_128_LOS [AORU:0017553D]
```
00 00 00 43 // float: 128.0
00 00 A0 40 // float: 5.0
00 00 A0 40 // float: 5.0
01 00 00 00 // uint32: 1
```

### Companion_256_LOS [AORU:0017553E]
```
00 00 80 43 // float: 256.0
00 00 A0 40 // float: 5.0
00 00 A0 40 // float: 5.0
01 00 00 00 // uint32: 1
```

### Companion_512_LOS [AORU:0017553C]
```
00 00 00 44 // float: 512.0
00 00 A0 40 // float: 5.0
00 00 A0 40 // float: 5.0
01 00 00 00 // uint32: 1
```

### Companion_1024_LOS [AORU:00181064]
```
00 00 80 44 // float: 1024.0
00 00 A0 40 // float: 5.0 
00 00 A0 40 // float: 5.0
01 00 00 00 // uint32: 1
```

### AO_BoS_ScribeCollectDataRule [AORU:0022CD85]
```
00 00 FA 43 // float: 500.0
00 00 A0 40 // float: 5.0
00 00 A0 40 // float: 5.0
00 00 00 00
```

### Min02EggClutchObjectRule [AORU:0012A26E]
```
00 00 2F 44 // float: 700.0
00 00 00 00
00 00 00 00
00 00 00 00
```

### WorkshopAlarmRule [AORU:001B5CB7]
```
00 00 FA 44 // float: 2000.0
00 00 00 40 // float: 2.0
00 00 20 41 // float: 10.0
00 00 00 00
```

### WorkshopResourceObjectRule [AORU:000E61B9]
```
00 00 FA 44 // float: 2000.0
00 00 00 00
00 00 F0 41 // float: 30.0
00 01 00 00 // uint32: 256
```

**Comment by zilav** [comment]
Thanks, updated. Not sure that it should be named "Object Rule", I just assumed that from "WorkshopResourceObjectRule [AORU:000E61B9]"
