### ISSUE TITLE
FO4Edit: QUST ALLA references Form ID

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#271]
## Aliases\Alias\ALLA

The first four bytes is a Form ID.

Record | ALLA
--- | ---
AO_LightsOutOBSOLETE [QUST:00023CBB] | AO_LinkedRef [KYWD:0002BF09]
AO_Dogmeat_FindItem [QUST:0004EFF2] | AO_LinkedRef [KYWD:0002BF09]
CIS_CaitLockPick_Reminder [QUST:001760E7] | CIS_LinkedRef [KYWD:0016F863]

**Comment by zilav** [comment]
Updated, thanks.
