### ISSUE TITLE
FO4Edit: Updated Cardinal Signature List

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#273]
I was on a mission last night/this morning to solve most of the remaining errors in Check for Errors.

Here's an updated list of whatever you call these.

This should correct and fill out the Object\Use fields in the DOBJ DNAM array.

Dashes and parentheses were stripped from the labels to facilitate sorting and ordering. I don't know if the exact labels are all that important. We can fix later if needed.

Comments indicate uncertainty due to similar character combinations.

edit: Correct table in comment below.

**Comment by zilav** [comment]
Updated, thx. There is still one unknown value though
Object #85
        Use: <Unknown: 1884047681>

**Comment by zilav** [comment]
One unknown value remains
`<Unknown: 1884047681>`

**Comment by fireundubh** [comment]
Can you convert that number to a string?

`IntToHex(1884047681, 8)` gives `pLIA`.

That doesn't look right, and doesn't appear in the Fallout4.exe string dump.

**Comment by zilav** [comment]
It is `AILp`, probably an error on Bethesda part.

**Comment by fireundubh** [comment]
Oh, that's in the string dump.

I removed that line from my filtered list because of the lowercase letter. Weird.

**Comment by fireundubh** [comment]
Okay, I checked out everything. I switched some signatures around. Here are the corrections:

Wrong Signature | Label | Right Signature
--- | --- | ---
AEXC | Action Exit Combat | AEXT
AEXI | Action Exit Cover | AECL
AECL | Action Dialogue Enter | AENI
AEXT | Action Dialogue Exit | AEXI
APII | Action Pipboy Inspect | APIN
APIN | Action Pipboy Inventory | APII
APIS | Action Pipboy Select | APPS
APPS | Action Pipboy Stats | APIS
APR1 | Action Pipboy Radio Off | APR0
APR0 | Action Pipboy Radio On | APR1
KWBR | Keyword nullptr Mod | CNMK
DOP3 | Dialogue Output Model 3D | DOP2
DOP2 | Dialogue Output Model 2D | DOP3
CNMK | Color Form | KWBR

**Comment by fireundubh** [comment]
See the corrected table in the comment above.

**Comment by zilav** [comment]
Updated, thx.
