### ISSUE TITLE
FO4Edit: Shifting records with new patch (possibly only RACE related?)

### ISSUE THREAD

**Issue by FelesNoctis** [TES5Edit/TES5Edit#274]
I'm unsure as to if this is a FO4Edit problem with reading the record, or Bethesda actually rearranging things. I was going to wait until the next patch to see, but was prompted to make a post anyway.

While FO4Edit doesn't handle the RACE records properly, it's at least been consistent in that regard. With the recent Fallout 4 patch to version 1.2, it seems that the body scale weights were repositioned.

These shots were made while comparing the RBreast_skin value's position specifically. Left is Fallout4.esm updated to version 1.2, right is an ESP plugin that modifies the body scale weights.
![](https://i.gyazo.com/d4b33b6062d12a44a0ffefaf1e414ca6.png)
![](https://i.gyazo.com/4b5379df824d899e9e448b07afa478d2.png)

The entire list of body scale weights has been rearranged. This doesn't affect functionality as far as I can tell, as the changes made by the plugin still function normally in-game despite being in a different location. It appears as though Bethesda took each bone point's "block" and just moved it around. This only happened after the patch, the positions otherwise stay consistent through repeated loads of FO4Edit.

While I didn't think it was a major concern, the person prompting me to post suggested that FO4Edit may be expecting static positions for these blocks. Since FO4Edit already has issues with RACE records this only adds to the confusion, and it may end up being a repeat event in future patches.

**Comment by badilator** [comment]
the shifting of the nodes may not be a big problem on its's own, as he said, but may lead to confusion and difficult mods update so was worth evidencing it.
Also the BSMS record like I referenced in another post:
>...
>I've found the BSMS fields at the end of a RACE record (the ones after each skeleton node name) are >3 floats for each of the 3 body profiles, a total of 9 floats.
>...
are corrected only in that section (scales values of the body weigth system)
But there seems to be many other places I was not aware where they are not exaclty 9 so the editor seems to mess things up
after the bodyslide section, in the old editor, followed another bones name list with groups of 16 bytes (I do not know if they are 4 floats may be)
In the ARMA record the BSMS seems to contain 3 floats, they add scaling to the bodyweight scaling factor of the armor fine tuning clothes dressing

**Comment by zilav** [comment]
The current version on nexus already has BSMS defined as a plain array of floats of variable size, so this shouldn't matter.

**Comment by FelesNoctis** [comment]
Ah ha, so it's just Bethesda messing with us then and shouldn't be an issue. Good to hear!

**Comment by Nephatrine** [comment]
The script properties in the VMADs for at least the Flora  were re-ordered with the patch, but it doesn't seem to matter either. Just was annoying seeing my records were flagged "changed".

**Comment by zilav** [comment]
Properties, along with a lot of other instances of collections in other records are "sorted" arrays in xEdit terms, which means official editor shuffles them randomly and xEdit tries to sort them in the same order for consistency. Since VMAD is a hex dump for now you see those changes since xEdit doesn't sort it.

**Comment by Nephatrine** [comment]
Thanks, that makes sense.
