### ISSUE TITLE
FO4Edit: WEAP FNAM - Unknown PROJ reference

### ISSUE THREAD

**Issue by isathar** [TES5Edit/TES5Edit#275]
Examples:

WEAP - 0001F669 - Minigun:
00 00 80 3F 00 00 80 3F 00 00 80 3F 9A 99 19 3E A2 77 57 40 00 00 00 00 9A 99 99 3E 01 [FB AD 03 00] 00 00 00 00 00 00 00 00

PROJ FormID - 0003ADDB - MiniGunProjectile

WEAP - 000EEBED - fragGrenade:
33 33 33 3F CD CC CC 3D 9A 99 99 3E 9A 99 19 3E CA 54 15 40 00 00 00 00 00 00 80 3E 01 [4E 57 0E 00] 00 00 00 00 00 00 00 00

PROJ FormID - 000E574E - fragGrenadeProjectile

Testing Results:
Projectile to spawn directly from the weapon (muzzle flashes or grenades/mines/boulders). Left as 00000000 if no weapon projectile is needed or everything is handled by the Ammunition's AMMO - DNAM - Projectile.

**Comment by fireundubh** [comment]
Verified.

Signature | Form ID | Path | Hex | Reference
--- | --- | --- | --- | ---
WEAP | 0001F669 | WEAP \ FNAM - Unknown | 0003ADFB | MiniGunProjectile [PROJ:0003ADFB]
WEAP | 00056917 | WEAP \ FNAM - Unknown | 00056918 | BoSVertibirdGrenadeProjectile [PROJ:00056918]
WEAP | 000589F2 | WEAP \ FNAM - Unknown | 000589F3 | SynthTeleportGrenadeProjectile [PROJ:000589F3]
WEAP | 0005A665 | WEAP \ FNAM - Unknown | 0012602C | LaserRifleBeamLtBlue [PROJ:0012602C]
WEAP | 00064B87 | WEAP \ FNAM - Unknown | 0003ADFB | MiniGunProjectile [PROJ:0003ADFB]
WEAP | 00065DEC | WEAP \ FNAM - Unknown | 00065DED | MS02HomingBeaconProjectile [PROJ:00065DED]
WEAP | 000662A7 | WEAP \ FNAM - Unknown | 0014BBDB | BehemothBoulderProjectile [PROJ:0014BBDB]
WEAP | 000B0F58 | WEAP \ FNAM - Unknown | 00216361 | SentryHandProjectileMissle [PROJ:00216361]
WEAP | 000BB6C0 | WEAP \ FNAM - Unknown | 001B5EE2 | TurretProjectile [PROJ:001B5EE2]
WEAP | 000CFB4D | WEAP \ FNAM - Unknown | 00216361 | SentryHandProjectileMissle [PROJ:00216361]
WEAP | 000E27A3 | WEAP \ FNAM - Unknown | 0003ADFB | MiniGunProjectile [PROJ:0003ADFB]
WEAP | 000E27A4 | WEAP \ FNAM - Unknown | 0003ADFB | MiniGunProjectile [PROJ:0003ADFB]
WEAP | 000E56C2 | WEAP \ FNAM - Unknown | 000E56C3 | FragMineProjectile [PROJ:000E56C3]
WEAP | 000E5750 | WEAP \ FNAM - Unknown | 000E5751 | nukaGrenadeProjectile [PROJ:000E5751]
WEAP | 000E98E5 | WEAP \ FNAM - Unknown | 000E98E4 | DN102_FrenzyGrenadeProjectile [PROJ:000E98E4]
WEAP | 000EDCE9 | WEAP \ FNAM - Unknown | 0009C663 | LaserRifleBeamRed [PROJ:0009C663]
WEAP | 000EEBED | WEAP \ FNAM - Unknown | 000E574E | fragGrenadeProjectile [PROJ:000E574E]
WEAP | 000FF21D | WEAP \ FNAM - Unknown | 000FF21E | CryoGrenadeProjectile [PROJ:000FF21E]
WEAP | 000FF21F | WEAP \ FNAM - Unknown | 000FF220 | PulseGrenadeProjectile [PROJ:000FF220]
WEAP | 0010771F | WEAP \ FNAM - Unknown | 00107720 | BottlecapMineProjectile [PROJ:00107720]
WEAP | 00107BD6 | WEAP \ FNAM - Unknown | 00107BD7 | BaseballGrenadeProjectile [PROJ:00107BD7]
WEAP | 0010A33D | WEAP \ FNAM - Unknown | 0010A33E | PlasmaGrenadeProjectile [PROJ:0010A33E]
WEAP | 0010A340 | WEAP \ FNAM - Unknown | 0010A33F | NukeMineProjectile [PROJ:0010A33F]
WEAP | 0010A342 | WEAP \ FNAM - Unknown | 0010A341 | PlasmaMineProjectile [PROJ:0010A341]
WEAP | 0010A344 | WEAP \ FNAM - Unknown | 0010A343 | PulseMineProjectile [PROJ:0010A343]
WEAP | 0010C3C6 | WEAP \ FNAM - Unknown | 0010C3C5 | MolotovCocktailProjectile [PROJ:0010C3C5]
WEAP | 0010C669 | WEAP \ FNAM - Unknown | 0010C668 | CryoMineProjectile [PROJ:0010C668]
WEAP | 001299A6 | WEAP \ FNAM - Unknown | 0003ADFB | MiniGunProjectile [PROJ:0003ADFB]
WEAP | 0012E2CA | WEAP \ FNAM - Unknown | 000A1337 | ArtillerySmokeFlareProjectile [PROJ:000A1337]
WEAP | 00134271 | WEAP \ FNAM - Unknown | 00188450 | SentryShoulderCluster [PROJ:00188450]
WEAP | 00134272 | WEAP \ FNAM - Unknown | 00188450 | SentryShoulderCluster [PROJ:00188450]
WEAP | 0014BBDA | WEAP \ FNAM - Unknown | 0014BBDB | BehemothBoulderProjectile [PROJ:0014BBDB]
WEAP | 001633CC | WEAP \ FNAM - Unknown | 0012602C | LaserRifleBeamLtBlue [PROJ:0012602C]
WEAP | 00174F8F | WEAP \ FNAM - Unknown | 00174F8E | InstituteBeaconProjectile [PROJ:00174F8E]
WEAP | 0017D52A | WEAP \ FNAM - Unknown | 0017FCE4 | LibertyPrimeBombProjectile [PROJ:0017FCE4]
WEAP | 0018325E | WEAP \ FNAM - Unknown | 000FF220 | PulseGrenadeProjectile [PROJ:000FF220]
WEAP | 001B5ED8 | WEAP \ FNAM - Unknown | 001B5EE2 | TurretProjectile [PROJ:001B5EE2]
WEAP | 001B5EDA | WEAP \ FNAM - Unknown | 001B5ED9 | TurretIncendiaryProjectile [PROJ:001B5ED9]
WEAP | 001B5EDD | WEAP \ FNAM - Unknown | 001B5EDB | TurretExplosiveProjectile [PROJ:001B5EDB]
WEAP | 001BBF98 | WEAP \ FNAM - Unknown | 001B5EE2 | TurretProjectile [PROJ:001B5EE2]
WEAP | 001BBF99 | WEAP \ FNAM - Unknown | 001B5EE2 | TurretProjectile [PROJ:001B5EE2]
WEAP | 00215CE4 | WEAP \ FNAM - Unknown | 0012602C | LaserRifleBeamLtBlue [PROJ:0012602C]
WEAP | 0021635F | WEAP \ FNAM - Unknown | 00188452 | SentryShoulderClusterIndoors [PROJ:00188452]
WEAP | 00216360 | WEAP \ FNAM - Unknown | 00188452 | SentryShoulderClusterIndoors [PROJ:00188452]
WEAP | 0023CACB | WEAP \ FNAM - Unknown | 0023CACC | RR301SynthTeleportGrenadeProjectile [PROJ:0023CACC]

**Comment by Sharlikran** [comment]
Updated
