### ISSUE TITLE
FO4Edit: PROJ DNAM - Data - Unknown PROJ reference

### ISSUE THREAD

**Issue by isathar** [TES5Edit/TES5Edit#276]
Examples:

Projectile10mm:
00 [07 1C 0B 00]

PROJ FormID - 000B1C07 - VatsBullet10mm

Projectile32:
00 [2A F1 0F 00]

PROJ FormID - 000FF12A - VatsBullet38

Testing Results:
Projectile to show while VATS is active (visible bullets for weapons using hit traces and visible tracer only). Left as 00000000 if the projectile isn't changed in VATS.

**Comment by fireundubh** [comment]
Verified.

Signature | Form ID | Path | Hex | Reference
--- | --- | --- | --- | ---
DNAM | 001F1C41 | PROJ \ DNAM - Data \ Unknown | 000FF12A | VATSBullet38 [PROJ:000FF12A]
DNAM | 001F1C40 | PROJ \ DNAM - Data \ Unknown | 0022E05B | VATSBulletGauss [PROJ:0022E05B]
DNAM | 001F1C3E | PROJ \ DNAM - Data \ Unknown | 000AEBB1 | VATSBullet45cal [PROJ:000AEBB1]
DNAM | 001F1C3D | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 001F1C3C | PROJ \ DNAM - Data \ Unknown | 000B1C07 | VATSBullet10mm [PROJ:000B1C07]
DNAM | 001E73BA | PROJ \ DNAM - Data \ Unknown | 00249369 | VATSBullet45cal_Explosive [PROJ:00249369]
DNAM | 001CC149 | PROJ \ DNAM - Data \ Unknown | 0022E05B | VATSBulletGauss [PROJ:0022E05B]
DNAM | 001B88DB | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 001B88D4 | PROJ \ DNAM - Data \ Unknown | 000B1C07 | VATSBullet10mm [PROJ:000B1C07]
DNAM | 001B5EE2 | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 001B5EDB | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 001B5ED9 | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 00182E05 | PROJ \ DNAM - Data \ Unknown | 000FF12A | VATSBullet38 [PROJ:000FF12A]
DNAM | 000FF12B | PROJ \ DNAM - Data \ Unknown | 000FF12A | VATSBullet38 [PROJ:000FF12A]
DNAM | 000FBF9B | PROJ \ DNAM - Data \ Unknown | 000AEBB1 | VATSBullet45cal [PROJ:000AEBB1]
DNAM | 000FBF99 | PROJ \ DNAM - Data \ Unknown | 000AEBB1 | VATSBullet45cal [PROJ:000AEBB1]
DNAM | 000A3A68 | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 000A292A | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 000A1337 | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 0005DDEF | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]
DNAM | 0003ADFB | PROJ \ DNAM - Data \ Unknown | 0023A608 | VATSBulletMinigun [PROJ:0023A608]
DNAM | 0001F277 | PROJ \ DNAM - Data \ Unknown | 000B1C07 | VATSBullet10mm [PROJ:000B1C07]
DNAM | 0000481F | PROJ \ DNAM - Data \ Unknown | 0006B4D9 | VATSBullet308cal [PROJ:0006B4D9]

**Comment by zilav** [comment]
Updated, thanks.
