### ISSUE TITLE
FO4Edit: RACE TTEC references CLFM Form IDs

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#277]
### HumanRace "Human" [RACE:00013746]

This is an example from the Mouth Grille TTGP under Male Head Data.

Other TTECs reference forms like `LipBrownishRed [CLFM:001ABFD1]` and `LightBlue [CLFM:0022D246]`, so they're not all warpaints. That was just this example.

```
D5 BF 1A 00 // None [CLFM:001ABFD5]
00 00 00 00
12 07 00 00
00 00 16 6E
0E 00 00 00
80 3F 90 04
00 00 00 00
61 9D 09 00 // WarpaintRed01 [CLFM:00099D61]
00 00 80 3F
E4 04 00 00
00 00 62 9D
09 00 00 00
80 3F 82 06
00 00 00 00
63 9D 09 00 // WarpaintRed03 [CLFM:00099D63]
00 00 80 3F
83 06 00 00
00 00 71 9D
09 00 00 00
80 3F 84 06
00 00 00 00
73 9D 09 00 // WarpaintBlue04 [CLFM:00099D73]
00 00 80 3F
85 06 00 00
00 00 74 9D
09 00 00 00
80 3F 86 06
00 00 00 00
75 9D 09 00 // WarpaintGreen02 [CLFM:00099D75]
00 00 80 3F
87 06 00 00
00 00 76 9D
09 00 00 00
80 3F 88 06
00 00 00 00
77 9D 09 00 // WarpaintOrange01 [CLFM:00099D77]
00 00 80 3F
89 06 00 00
00 00 78 9D
09 00 00 00
80 3F 8A 06
00 00 00 00
79 9D 09 00 // WarpaintYellow01 [CLFM:00099D79]
00 00 80 3F
8B 06 00 00
00 00 7A 9D
09 00 00 00
80 3F 8C 06
00 00 00 00
7B 9D 09 00 // WarpaintYellow03 [CLFM:00099D7B]
00 00 80 3F
8D 06 00 00
00 00 86 9D
09 00 00 00
80 3F 8E 06
00 00 00 00
```

**Comment by zilav** [comment]
Yep this looks like an array of structures where the first value is CLFM ref followed by floats and other values up to 28 bytes in totol. However there are TTEC subrecords having 12 bytes only, so I can't define TTEC until I know when it is an array and when is not.

**Comment by zilav** [comment]
Actually you missed another CLFM refs in between, it is an array of 12 bytes structures. Updated.
