### ISSUE TITLE
xEdit Feature Request: XMLDoc and RegularExpressions

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#281]
Can you expose any one of the following to the scripting interface?

* [XMLDoc](http://docwiki.embarcadero.com/VCL/XE/en/XMLDoc) (native Delphi unit)
* [JvSimpleXML](http://wiki.delphi-jedi.org/wiki/JVCL_Help:TJvSimpleXML) (JEDI VCL)
* [OXml](http://www.kluug.net/oxml.php) (fastest XML library for Delphi)

[RegularExpressions](http://docwiki.embarcadero.com/VCL/XE/en/RegularExpressions) (native Delphi unit) would be nice to have, too.

**Comment by zilav** [comment]
TPerlRegEx is already exposed. As for XMLDoc, it has quite a lot of classes, types, and operates with dynamic arrays which are not supported in JvInterpreter. Other libraries adds additional dependencies which I want to avoid. I'm actually thinking about some json support, xml is too verbose imho for scripting needs.

**Comment by fireundubh** [comment]
> TPerlRegEx is already exposed.

Awesome. Thanks.

> I'm actually thinking about some json support, xml is too verbose imho for scripting needs.

For my needs, JSON is fine, too. Whatever gets me away from CSVs. :)

**Comment by fireundubh** [comment]
Any idea when you'll be implementing JSON support? [SuperObject](https://github.com/hgourvest/superobject) is a good library.

**Comment by zilav** [comment]
It is good for Delphi using interfaces, but not so good for JvInterpreter as it doesn't support "writing" to interfaces. I'll have to create wrapper functions for that similar to xEdit's SetElement*.
The pure OOP lib using TObject descendants would work better with scripting, but I didn't decide yet.
