### ISSUE TITLE
FO4Edit: AVIF from Fallout4.exe into .esp causing CTD

### ISSUE THREAD

**Issue by pootthedestroyer** [TES5Edit/TES5Edit#282]
Discovered during: MGEF creation/modification.

Dropdown menu of AVIF in MGEF currently does not contain all AVIFs. Some are stored in Fallout4.exe, and are, at least seemingly, referenced successfully by Fallout4.esm.

Examples:

Blindness [AVIF:00000311] is stored in the .exe, and is referenced by:
BlindnessPoison "Blindness Poison" [MGEF:0017E8F9]

Deafness [AVIF:0000032D] is stored in the .exe, and is referenced by:
DeafnessPoisonEffect "Deafness Poison" [MGEF:0017E8FB]

All of my attempts to reference these two AVIFs in modified or new MGEFs results in CTD at startup - or, if I attempt to copy overrides of them from .exe to my .esp (with no changes,) CTD at save load.

**Comment by zilav** [comment]
Are they even used by the game? They could be leftovers from development.

**Comment by fireundubh** [comment]
I can say right away that you shouldn't copy records from `Fallout4.exe`. That's really just the `Fallout4.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat` file. None of those records are complete; they're just placeholders until we get our hands on the toolset. So, overriding them with blank records is obviously a problem for the game.

**Comment by pootthedestroyer** [comment]
As noted in my original comment, the game does reference the two AVIFs I mentioned. They're used to build the two MGEFs I listed, which are both used by BlindnessSpell "Blindness Spell" [SPEL:0017E8FA], which is then plugged into mindCloud "Mind Cloud Syringe" [ALCH:00058AF5].

Whether or not they work as intended in-game is another matter, but at the very least they're not causing CTD at startup or save-load.

**Comment by fireundubh** [comment]
Yes, but this:

> or, if I attempt to copy overrides of them from .exe to my .esp (with no changes,) CTD at save load.

is user error. Don't do that. No idea about the first issue.
