### ISSUE TITLE
FO4Edit: BSA support

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#284]
@zilav: I read your comment elsewhere regarding BSA support for FO4 plugins:

> I'd rather wait for CK. I have a feeling that there will be no BSA support and all those pre CK mods using BSA would have to be remade.

We don't know whether the FO4 toolset will support BSA and we won't know that until Q2 2016.

However, we do know now that the game itself supports BSA. In my opinion, xEdit should be supporting BSA for FO4 plugins until it no longer makes sense to continuing supporting that format.

FYI: Per Gibbed, BSA and BA2 are meaningfully different in two respects:

* the BA2 loader is more efficient when loading BA2s at game start (and only then); and
* texture lookups are considerably faster because the texture header info is now part of the file table.

This may also explain why BA2 archives can surpass the 2 GB limit and not crash the game at load.

**Comment by zilav** [comment]
I don't want to encourage bad modding practices by adding support for wrong outdated formats. People use BSA to compress textures which makes it even worse for the game
http://afkmods.iguanadons.net/index.php?/topic/4136-nifskope-20-dev/page-8#entry158606
Non texture mods shoud be distributed uncompressed for now.

**Comment by fireundubh** [comment]
> I don't want to encourage bad modding practices by adding support for wrong outdated formats.

Again, BSA is not a wrong or outdated format. *The game supports BSA.*

> People use BSA to compress textures which makes it even worse for the game. http://afkmods.iguanadons.net/index.php?/topic/4136-nifskope-20-dev/page-8#entry158606

Nothing that Jon said had anything to do to compression, and nor do loose texture assets, which are what comprise the big optimized (rescaled and resized) texture packs.

Jon, like Gibbed, is talking about how the BA2 loader performs texture mip lookups faster than the BSA loader, but **the speed of those lookups is completely irrelevant** when the game has to then render poorly optimized and oversized textures. So, Jon is wrong there. Those texture optimization mods are not "undoing" any work, but they could perform better in a BA2. "Better" is, of course, an unknown, as nobody except Bethesda has determined how much faster BA2 texture mip lookups actually are.

> Non texture mods shoud be distributed uncompressed for now.

For the most part, this is true, and has been true for awhile, but it's more nuanced. I wrote a program last year that reads the BSA header and identifies the flags used when creating the archive.

Here are the results I generated for Skyrim's BSAs.

File | Compressed? | Flags | Resource Types 
--- | --- | --- | ---
Skyrim - Animations.bsa | True | Include Directory Names, Include File Names |  
Skyrim - Interface.bsa | False | Include Directory Names, Include File Names |  
Skyrim - Meshes.bsa | True | Include Directory Names, Include File Names, Retain Strings During Startup | Meshes
Skyrim - Misc.bsa | False | Include Directory Names, Include File Names | 
Skyrim - Shaders.bsa | False | Include Directory Names, Include File Names | 
Skyrim - Sounds.bsa | False | Include Directory Names, Include File Names, Retain File Names | Sounds, Voices
Skyrim - Textures.bsa | True | Include Directory Names, Include File Names, Embed File Names | Textures
Skyrim - Voices.bsa | False | Include Directory Names, Include File Names | Sounds, Voices
Skyrim - VoicesExtra.bsa | False | Include Directory Names, Include File Names | Sounds, Voices
Dawnguard.bsa | False | Include Directory Names, Include File Names, Retain File Names, Retain Strings During Startup | Meshes, Sounds, Textures, Voices
HearthFires.bsa | False | Include Directory Names, Include File Names, Retain File Names, Retain Strings During Startup | Meshes, Sounds, Textures, Voices
Dragonborn.bsa | False | Include Directory Names, Include File Names, Retain File Names, Retain Strings During Startup | Meshes, Sounds, Textures, Voices
HighResTexturePack01.bsa | True | Include Directory Names, Include File Names, Embed File Names | Textures
HighResTexturePack02.bsa | True | Include Directory Names, Include File Names, Embed File Names | Textures
HighResTexturePack03.bsa | True | Include Directory Names, Include File Names, Embed File Names | Textures

Also note that many of those BSAs are *uncompressed*. Compression is not mandatory.

**Comment by zilav** [comment]
By "compression" I mean packaging files into archives even without the real compression. And packaging textures in BSA does hurt the game like Jon mentioned since it no longer allows to load selected mipsmaps from textures. Anyway I'll add BSA support back if the official tools will supports them. But right now I don't want to to support people who can not just a bit wait and instead use tools from one game to mod another. This is simply wrong.

**Comment by fireundubh** [comment]
> And packaging textures in BSA does hurt the game like Jon mentioned since it no longer allows to load selected mipsmaps from textures.

What? BSAs do not hurt the game. Textures not packed in BA2 archives don't benefit from the BA2 loader's texture lookup performance improvements. That's all!

**Comment by zilav** [comment]
They consume more VRAM because all mipmaps are loaded instead of only the needed ones, which hurts FPS if VRAM is running low.

**Comment by fireundubh** [comment]
Faster lookups for unoptimized textures is less performant than slower lookups for optimized textures.

When you use mods, you make trades like that all the time. For example, you might trade VRAM for 4K textures because the game might look prettier, or you might trade VRAM for optimized textures because eliminating stuttering improves your experience. In my case, stuttering quickens the pace at which I come down with nausea from playing Fallout 4, so optimized textures are almost a medical necessity. But whether users can successfully make those trades by, for example, meeting the hardware requirements should have zero bearing on whether xEdit supports the same file formats that the game supports.

**Comment by RoyBatty64** [comment]
You're making assumptions about the official tools. If it works in the engine then there is no reason to remove support for it. "Wrong" is subjective in this case.

**Comment by zilav** [comment]
In 1-2 months I will add BSA back if official tools support it. Yes it is subjective, but It is my decision.

**Comment by fireundubh** [comment]
Looks like BSA support was patched out.

**Comment by zilav** [comment]
I guess this is closed now.
