### ISSUE TITLE
FO4Edit: MapMarker TNAM name list

### ISSUE THREAD

**Issue by Fl0Wn** [TES5Edit/TES5Edit#285]
On my work on my mod, i made some notes on the map marker type names. Maybe this can help to improve FO4Edit with the unknown map marker type names.
The map marker names are taken form the pipboy_mappage.swf file. The order of the list is the same as they appear in the SWF file. The icons in the SWF have all the suffix "Marker", i think this word can be removed for the FO4Edit Map Marker name. I used "TMM 1,0,1" to show all map markers and then compared the icons from the swf to the pipboy map icons. 

(SWF Map Marker type name) - (current FO4Edit type name) - (Example Worldmap location)  - (FormID)

VaultMarker - Mine - Vault 111 - 0009f272
USSConstitutionnMarker - Custom 64 - USS Constitution - 00074BE0  
UrbanRuinsMarker - Landmark - Harbormaster Hotel - 001493EF
TownRuinsMarker - Grove - West Everett Estates - 0002bfcf
TownMarker - ??? -  - NOTE: not found on the pipboy worldmap 
SnyhtHeadMarker - ??? -  -  NOTE: not found on the pipboy worldmap  (faction smybol?)
SwanPondMarker - Morthal Castle - Swan's Pond - 0001e306
SubmarineMarker - ??? -  -  NOTE: not found on the pipboy worldmap
ShipwreckMarker - Winterhold Castle - Wreck of the FMS Northern Star - 0002bc1a
SewerMarker - Wood Mill - Fens Street Sewer - 0002c949
SettlementMarker - Farm - Lynn Woods - 0002c2af
SentinelMarker - Custom 63 - Sentinel Site - 000adda4
SchoolMarker - Markarth Capitol - University Point  - 0002c810
SatelliteMarker - Custom 62 - USAF Satellite Station Olivia  -0002bc66
SancHillsMarker- Dragon Lair - Sanctuary - 00072a48
SalemMarker - Markarth Castle - Museum of Witchcraft - 000b3cba
RailroadMarker - Custom 61 - Bedford Station  -0003df66
RailroadFactionMarker - ??? (lantern symbol) -  - NOTE: not found on the pipboy worldmap (faction smybol?)
RadioTowerMarker - Solitude Capitol - Relay Tower 0DB-521 - 001ac2e1
RadioactiveAreaMarker - "DLC02 - Raven Rock" - Mass Fusion Building - 0002b83e
QuarryMarker - Whiterun Capitol - Dunwich Borers - 0002c241
PrydwenMarker - Custom 59 - The Prydwen -00090e59
PondLakeMarker - Whiterun Castle - Murkwater Construction Site - 000c9bbe
PoliceStationMarker - "DLC02 - To Solstheim" -  East Boston Police Station - 00186bd0
PierMarker - Windhelm Capitol - Kingsport Lighthouse - 0002c26e
OfficeMarker - Shipwreck - Salem  - 000beb22
ObservationMarker - ??? -  -  NOTE: not found on the pipboy worldmap
MonumentMarker - Camp - Fraternal Post 115 - 0002b7ca
MinutemanMarker -??? -  -  NOTE: not found on the pipboy worldmap  (faction smybol?)
MilitaryBaseMarker - Nordic Ruins - Fort Hagen - 00024f9a
MetroMarker - Fort - Medical Center Metro - 00194fb6
LowRiseMarker - "DLC02 - Tel Mithryn" - Wilson Atomatoys Corporate HQ  - 000252e9
LibertaliaMarker - "DLC02 - Beast Stone" - Liberitalia - 0002b967
LandmanMarker - Dwemer Ruin - Spectacle Island - 0002cf9e
JunkyardMarker - Riften Capitol - Rotten Landfill - 0002c4d4
IrishPrideMarker - Riften Castle - Irish Pride Industries Shipyard - 0002b9dc
InstituteMarker - ??? -  -  NOTE: not found on the pipboy worldmap
IndustrialStacksMarker - Docks - Corvega Assembly Plant -  NOTE: this uses the same icon as "FactoryMarker", icon #135 
IndustrialDomeMarker - Nordic Dwelling - Weston Water Treatment Plant - 0010985e
HospitalMarker - Nordic Tower - Greater Mass Blood Clinic - 0002b859
GraveyardMarker - Shack - Wildwood Cemetery  - 0002c10f
GoodneighborMarker - -  - NOTE: not found in the FO4Edit yet
ForestMarker - Orc Stronghold - Robotics Pioneer Park -0002c5f0
FillingStationMarker - Lighthouse - Fort Hagen Filling Station - 0022f204
FarmMarker - Rock - The Slog  - 0002ba8f
FaneuilHallMarker - Altar - Faneuil Hall  - 0002bba3
FactoryMarker - - - NOTE: this uses the same icon as "IndustrialStacksMarker", icon #135
EncampmentMarker - Settlement - Gorski Cabin  - 0002bfcf
ElevatedHighwayMarker - Pass - Mass Pike Interchange  - 0002c802
DriveInMarker - Clearing - Starlight Drive In - 00024f95
DiamondCityMarker -??? -  - NOTE: not found in the FO4Edit yet
SkyscraperMarker - "DLC02 - Raven Rock" - Garden Terrace - 0006f322
CustomHouseMarker - Imperial Tower - Custom House Tower - 0002bb61
CountryClubMarker - ??? -  -  NOTE: not found on the pipboy worldmap
CityMarker - City - Monsignor Plaza - 000a970c
ChurchMarker - Smelter - Hopesmarch Pentecostal Church  - 000add8e
CaveMarker - None - Cave - 000add93
CastleMarker - "DLC02 - Temple of Miraak" - The Castle  - 0002bca5
CarMarker - Wheat Mill - Tucker Memorial Bridge - 00248478
CamperMarker - Doomstone - Rocky Narrows Park - 0002c5bd
BunkerMarker - Dawnstar Capitol - Recon Bunker Theta - 000ba83b
BunkerHillMarker - Stormcloak Camp - Bunker Hill - 0002b880
BrownstoneMarker - Dawnstar Castle - Back Street Apparel - 0002bc0b
BoSMarker - -  -  NOTE: not found on the pipboy worldmap  (faction smybol?)
AirfieldMarker - Imperial Camp - Boston Airport - 00084beb

**Comment by zilav** [comment]
Are they unordered in SWF file? Strange that marker index 64 comes second.

**Comment by Sharlikran** [comment]
Updated
