### ISSUE TITLE
FO4Edit: Decoding FURN SNAM - Unknown

### ISSUE THREAD

**Issue by isathar** [TES5Edit/TES5Edit#286]
Testing results:

This appears to be a list of location/rotation offsets (as floats) for each of a furniture object's active markers. Each active Sit X marker entry point defined by FURN - MNAM should have a corresponding offset (exception: Sit 23).

Changing the values results in moving the place a character interacting with the object is standing and the direction it's facing while playing the animation. 

Examples:

-- FURN 0008674C: WorkshopScavengingStation 

Active Marker Flags: Sit 0, Unknown 31

SNAM
[00 00 B2 42] [00 00 48 C2] [00 00 00 00] [FC 22 AD 40] 00 00 00 00 FF FF FF FF

00 00 B2 42 = 0x42B20000 = 89.0               - x offset
00 00 48 C2 = 0xC2480000 = -50.0              - y offset
00 00 00 00 = 0.0                                         - z offset
FC 22 AD 40 = 0x40AD22FC = 5.410521    - z rotation
00 00 00 00 FF FF FF FF = ?

-- FURN 000A46FC: WorkshopCaravanHitchingPost 

Active Marker Flags: Sit 0, Sit 1, Unknown 31

SNAM
[00 00 00 00] [00 00 60 C3] [00 00 00 00] [00 00 00 00] 98 37 01 00 FF FF FF FF
[00 00 44 C2] [00 00 F4 42] [00 00 00 00] [DB 0F 49 40] 94 37 01 00 EF FF FF FF

Sit 0:
00 00 00 00 = 0.0                                   - x offset
00 00 60 C3 = 0xC3600000 = -224.0      - y offset
00 00 00 00 = 0.0                                    - z offset
00 00 00 00 = 0.0                                    - z rotation
98 37 01 00 FF FF FF FF = ?

Sit 1:
00 00 44 C2 = 0xC2440000 = -49.0          - x offset
00 00 F4 42 = 0x42F40000 = 122.0          - y offset
00 00 00 00 = 0.0                                      - z offset 
DB 0F 49 40 = 0x40490FDB = 3.141593   - z rotation
94 37 01 00 EF FF FF FF = ?

-- FURN 001C176D: NpcTablePicnicSit01

Active Marker Flags: Sit 0-3, Unknown 31

SNAM
[00 00 00 42] [00 00 70 C2] [00 00 00 00] [00 00 00 00] 00 00 00 00 F0 FF FF FF 
[00 00 20 42] [00 00 70 42] [00 00 00 00] [DB 0F 49 40] 00 00 00 00 F0 FF FF FF 
[00 00 10 C2] [00 00 70 42] [00 00 00 00] [DB 0F 49 40] 00 00 00 00 F0 FF FF FF 
[00 00 20 C2] [00 00 70 C2] [00 00 00 00] [00 00 00 00] 00 00 00 00 F0 FF FF FF

Sit 0:
00 00 00 42 = 0x42000000 = 32.0        - x offset
00 00 70 C2 = 0xC2700000 = -60.0      - y offset
00 00 00 00 = 0.0                                  - z offset
00 00 00 00 = 0.0                                  - z rotation
00 00 00 00 F0 FF FF FF = ?

Sit 1:
00 00 20 42 = 0x42200000 = 40.0             - x offset
00 00 70 42 = 0x42700000 = 60.0             - y offset
00 00 00 00 = 0.0                                      - z offset
DB 0F 49 40 = 0x40490FDB = 3.141593   - z rotation
00 00 00 00 F0 FF FF FF = ?

Sit 2:
00 00 10 C2 = 0xC2100000 = -36.0           - x offset
00 00 70 42 = 0x42700000 = 60.0             - y offset
00 00 00 00 = 0.0                                       - z offset
DB 0F 49 40 = 0x40490FDB = 3.141593   - z rotation
00 00 00 00 F0 FF FF FF = ?

Sit 3:
00 00 20 C2 = 0xC2200000 = -40.0       - x offset
00 00 70 C2 = 0xC2700000 = -60.0       - y offset
00 00 00 00 = 0.0                                   - z offset
00 00 00 00 = 0.0                                   - z rotation
00 00 00 00 F0 FF FF FF = ?

Notes:
Z rotation appears to be in radians and always >= 0.0. (Based on the picnic table's 180 degree rotation for two of the sit markers being roughly equal to pi, 180.0/pi = ~57.3 degrees = ~1.0 rad)

The last block (usually FFFFFFFF) doesn't appear on some furniture records that have only one marker entry point and offset specified and look like they are only used by NPCs:
(NPCInvGroundSit [FURN:000299C2], NPCInvChairSit [FURN:00032575], BloodBugGroundInvFeed01 [FURN:0004944E], a few others).

Some records have more offsets than defined active markers, but each of them has enough Marker Entry Points defined:
(FaceGenBarberChair "Barber Chair" [FURN:000306FF], NpcBenchFederalistSit01OneSlot "Bench" [FURN:0011807C], NpcBenchDinerIntBoothSit01WithTable02 "Bench" [FURN:002321AC], NpcBenchDinerIntBoothSit01WithTable03 "Bench" [FURN:002321B3], WorkshopNpcBedGroundSleep01 "Mattress" [FURN:00020C40], WorkshopNpcBedGroundSleep01NoEdit "Mattress" [FURN:00246985], WorkshopNpcBedGroundSleep02NoEdit "Mattress" [FURN:0024980E], MQ206BeamEmitter "Molecular Beam Emitter" [FURN:001E077F], MQ206ReflectorPlatform "Stabilized Reflector Platform" [FURN:001E0782], FaceGenSurgeryChair "Surgery Chair" [FURN:00052812], MS11Workbench "Workbench" [FURN:00091FD5])

**Comment by zilav** [comment]
Updated, thanks.
