### ISSUE TITLE
FO4Edit: ARMO - INRD Unknown and INNR - Instance Naming Rules - Unknowns

### ISSUE THREAD

**Issue by isathar** [TES5Edit/TES5Edit#287]
WEAP and ARMO - INRD references an INNR form as a ruleset for procedurally generated names.

INNR Unknowns:

UNAM - Unknown:
I'm not sure about the data type on this, but it's set to 1D000000 for forms with armor names and 2B000000 for weapon names. The first byte could be an int, or the whole thing could be a float, but I'd rather not guess on something like this.

Unknown list(s):
Prefixes and name replacements for procedurally named weapons and armor by keywords in their records and in records of any object modifications added to them. 

Words picked appear in the order they are found in the weapon/armor's INNR, from the top. If any of the defined keywords in a rule are found, the corresponding word is added to its name. An item's entire name can be generated like this.
If a rule has the replacement text set to * and has no keywords, the base name of the item will be used at the position specified by the list's order.

Legendary name prefixes are defined first, followed by any prefixes added by modifications, with any replacements of the base name last. Postfixes/other words following the base name can be defined if other rulesets follow after the one containing it (or *).

It looks like there are multiple lists in each form to define where spaces appear in the name.

EDIT: The names of instances in the saved game before changing their INRD will have to be regenerated by switching modifications or respawning.

List Structure:

Unknown - Naming Rulesets
----Unknown - Naming Ruleset X - one per word position to be added to the name
--------VNAM - Count - number of rules in Naming Rules
--------Unknown - Naming Rules - one per possible word at this position in the name
------------Unknown - Naming Rule Y
----------------WNAM - Replacement/Added Text
----------------KSIZ - Keyword count
----------------KWDA - Keywords - conditions for this word to appear in the name
	(the other 9 naming rulesets)

Example:
	
Applying a INNR form with the following rulesets to an Institute Laser's INRD will change the names of its instances to variations of '(Weak/Powerful/Stupidly Overpowered) (Accurate) Synth Gun (That Shoots Fire)'.

Rulesets -
----Naming Ruleset 0 -
--------VNAM: 3
--------Naming Rules -
------------Rule 0
----------------WNAM: 'Stupidly Overpowered'
----------------KWDA: dn_HasReceiver_MoreDamage3 [KYWD:00163042]
------------Rule 1
----------------WNAM: 'Powerful'
----------------KWDA: dn_HasReceiver_MoreDamage1 [KYWD:0016303D]
------------Rule 2
----------------WNAM: 'Weak'
----------------KWDA: dn_HasReceiver_Standard [KYWD:00163038]
----Naming Ruleset 1 -
--------VNAM: 1
--------Naming Rules -
------------Rule 0
----------------WNAM: 'Accurate'
----------------KWDA: dn_HasScope [KYWD:0002095D]
----Naming Ruleset 2 -
--------VNAM: 1
--------Naming Rules -
------------Rule 0
----------------WNAM: 'Synth Gun'
----------------KWDA: ma_InstituteLaserGun [KYWD:001289BB]
----Naming Ruleset 3 -
--------VNAM: 1
--------Naming Rules -
------------Rule 0
----------------WNAM: 'That Shoots Fire'
----------------KWDA: HasLegendary_Weapon_IncendiaryBullets [KYWD:001E7175]

edited for formatting

**Comment by zilav** [comment]
Thanks, I already had a general idea how it worked. But I'll probably still leave them as "unknowns" because they will need to be updated anyway once CK is out. We prefer to use official namings in xEdit so Creation Kit documentation and other sources of modding information could still apply. The same for other records and values.
Right now we are more interested in decoding hex arrays.

**Comment by zilav** [comment]
Fixed.
