### ISSUE TITLE
FO4Edit - Switching from HasKeyword to HasPerk in existing condition doesn't update to new list

### ISSUE THREAD

**Issue by pootthedestroyer** [TES5Edit/TES5Edit#288]
When altering an existing (already saved) condition's Function from HasKeyword to HasPerk, the dropdown list (which should be dynamically labeled either "Keyword" or "Perk") does not update properly, leaving the user with a long list of invalid selections that will cause an error.

While I have managed to "idiot brute force" my way out of the problem by mashing buttons until the program let me go copy-paste something valid from elsewhere, in theory it seems that this error should persist, locking the user out of the rest of the program, unless the user is clever enough to find a perk name and value and format it correctly to give the program what it's expecting.

Note that this behavior does not occur if you create a new condition, set the Function to HasPerk/HasKeyword, select a valid entry, then go back and switch the Function to the other of the pair. The dropdown properly switches over. Thus, it seems to be an issue with an effect/condition that's already been saved and then reloaded upon (re)starting FO4Edit.

**Comment by zilav** [comment]
I copied `co_mod_InstituteLaserGun_Receiver_ArmorPiercing2 [COBJ:00027F33]` to a new plugin as a test since it already has HasPerk condition, changed to HasKeyword, changed param to random keyword from the list, saved, reloaded, changed keyword again. I don't see anything wrong.

**Comment by pootthedestroyer** [comment]
Can't reliably reproduce in all situations. Good to close for now, will
attempt to better document if it happens again. The exception I received
did not appear in the bug report log file, so it's a ghost for now.
