### ISSUE TITLE
FO4Edit: QUST - VTCK reference

### ISSUE THREAD

**Issue by wmrojer** [TES5Edit/TES5Edit#289]
Quest > Aliases > Alias > VTCK can reference FACT

Not sure if it's a bug in Fallout4.esm but it prevents "copy as override" for a lot of QUST record.

**Comment by zilav** [comment]
Skyrim didn't use FACT records in VTCK forced voice options, and FO4Edit currently is largely based on Skyrim definitions. I can add FACT. Do you have examples of such records?

**Comment by wmrojer** [comment]
MinRecruit01 "Raider Troubles at <Alias=ActualLocation>" [QUST:00098136]

**Comment by zilav** [comment]
Added to the list of allowed Forms. Thanks.
