### ISSUE TITLE
FO4Edit: VMAD not preserved in non-Simple Records mode

### ISSUE THREAD

**Issue by smangham** [TES5Edit/TES5Edit#290]
It appears that when copying an NPC form with Simple Records off, the VMAD entry is changed even if no edits are made to it. This is shown in the screenshots below for a mod that just copies-as-override some NPC forms and adds a single keyword.

Comparisons-
**Simple Records:** http://i.imgur.com/pd3aJag.jpg
**Non-simple Records:** http://i.imgur.com/N4MJCBL.png
ESP in question, if it's any help-
https://www.mediafire.com/?gq194d2zfe2cbcj

I appreciate the VMAD stuff is *very* alpha and only works for simple enough forms but the problem is figuring out which ones are too complex- would it be possible to get a warning of some kind on forms where FO4Edit can't handle it? So we know to switch back to Simple Records?

**Comment by zilav** [comment]
Scripts and properties are sorted by xEdit for better conflicts detection like in Skyrim because official editor shuffles them in random order. This is intended and doesn't affect how scripts work in game.
