### ISSUE TITLE
FO4Edit: Decoding AMMO

### ISSUE THREAD

**Issue by VirtualTim** [TES5Edit/TES5Edit#291]
Hey, not sure if this is the right place for this, but the value of ammo is stored under Data - Unknown, stored in reverse order. So "01 02 03 04" is equal to a value of 04030201<sub>(16)</sub>, or 67305985<sub>(10)</sub>.
Or for a real example Fusion cores (75FE4) cost 200<sub>(10)</sub>, or C8 00 00 00<sub>(16)</sub>.
Pretty minor, but figured it was worth mentioning.

**Comment by zilav** [comment]
Thanks, updated.
