### ISSUE TITLE
xEdit Feature Request: Choose Script Folder

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#292]
Currently, you can select only scripts in the Edit Scripts folder to run.

I have hundreds of my own scripts, and then there's mator's scripts, and then there's your scripts, so I'd like to use subfolders rather than adding prefixes to the names.

To make things easy, can a "choose folder" button be added to the Apply Script window?

It would look like this:

![Screenshot](http://i.imgur.com/Df1QTZo.png)

The button label would change based on the last directory in the path:

![Screenshot](http://i.imgur.com/aKVvJ1e.png)

That would help with organization.

I'm not saying this is how it should be implemented, but I have very simple, working code for this:

```delphi
procedure TfrmScript.btnActiveFolderClick(Sender: TObject);
begin
  with TFileOpenDialog.Create(nil) do
    try
      Options := [fdoPickFolders];
      if Execute then begin
        Path := FileName + '\';
        btnActiveFolder.Caption := ExtractFileName(ExcludeTrailingPathDelimiter(Path));
        lblActiveFolderPath.Caption := Path;
        ReadScriptsList;
      end;
    finally
      Free;
    end;
end;

procedure TfrmScript.FormShow(Sender: TObject);
begin
  btnActiveFolder.Caption := ExtractFileName(ExcludeTrailingPathDelimiter(Path));
  lblActiveFolderPath.Caption := Path;
  ReadScriptsList;
end;
```

You'd probably need a fallback for Windows XP support [per StackOverflow](http://stackoverflow.com/questions/7422689/selecting-a-directory-with-topendialog/7422764).

A `LastUsedPath` setting would also be ideal for some persistence.

**Comment by zilav** [comment]
I added checkbox to list scripts from subdirectories. Your version is more functional, but that's too many new controls that could confuse ordinary users. I never expected scripting feature to become so popular and only intended for a few expert users and programmers. But now with increasing popularity of some scrits on Nexus a lot of newbies visit that form and so I want to avoid making big changes here.

You can always keep your own version locally and use it yourself.

**Comment by fireundubh** [comment]
I don't see your checkbox anywhere in the new build. By the way, am I to understand that the checkbox will merely include scripts from subfolders in the dropdown? In that case, are scripts displayed in the dropdown with their folder name (e.g., `Edit Scripts\Worldspace Browser`)? That would be cool, if not.

**Comment by zilav** [comment]
Yes they are in dropdown list including subfolders.
https://github.com/TES5Edit/TES5Edit/commit/3cd743f9f7d53379774abed7b6052bf7a901581b

**Comment by fireundubh** [comment]
Hmm. For some reason, TortoiseSVN isn't downloading the latest revision despite saying so. I had to download the ZIP directly from GitHub to get the latest revision.

**Comment by Sharlikran** [comment]
If you can open a shell, navagate to the Git folder where you store your TES5Edit files use these commands.

git remote -v <- to see what the upstream is set to

If you only have origin then add a new remote

git remote add upstream https://github.com/TES5Edit/TES5Edit.git

The use these commands

git fetch upstream --prune
git checkout sharlikran-fo4dump
git rebase upstream/sharlikran-fo4dump
git push -f

**Comment by fireundubh** [comment]
I installed [TortoiseGit](https://tortoisegit.org/), which I didn't know existed, and updated [Git for Windows](https://git-for-windows.github.io/).

Everything's working well now.

**Comment by fireundubh** [comment]
@zilav Can you implement saving the checkbox state for the current session?

**Comment by zilav** [comment]
Done.
