### ISSUE TITLE
FO4Edit: Split RACE Tint Template Groups into Male and Female

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#295]
`wbTintTemplateGroups` should be split into `wbTintTemplateGroupsMale` and `wbTintTemplateGroupsFemale`.

Ultimately:

We need unique names for both (i.e., `Male Tint Template Groups` and `Female Tint Template Groups`.)

Without unique names, writing scripts to handle FO4's huge RACE records is a bit challenging.

**Comment by zilav** [comment]
I know, will add grouping later when RACE is fully decoded once CK is out. Right now my aim was to make them copyable hence I simplified the structure.
