### ISSUE TITLE
FO4Edit: COBJ INTV\Unknown is Priority (primary key)

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#296]
`Priority` is the primary key for the menu order of crafting recipes. The game uses this value first.

## Sort Order

1. A-Z; `Priority`
2. A-Z; `CNAM\FULL`
3. A-Z; `Form ID`

`Priority` is used in TES5 for other things, so that's probably an ideal label.

## Example Tables

* I padded `Priority` because Delphi doesn't have native natural number sorting.
* I stripped spaces from `CNAM\FULL` because `TStringList.Sort` doesn't sort spaces correctly.
* `EDID` is included just for verification.
* Verified in-game.

### Connectors & Switches

Priority | CNAM\FULL | Form ID | EDID
--- | --- | --- | ---
`000` | PowerPylon | `0015F0DA` | `workshop_co_PowerPylon01`
`000` | PowerPylon-Large | `0013A3E2` | `workshop_co_PowerPylon02`
`005` | PowerConduit | `00240A72` | `workshop_co_PowerConnectorFloor01`
`010` | PowerConduit | `000C01C7` | `workshop_co_PowerConnectorWall01`
`020` | PowerConduit | `0005A0CC` | `workshop_co_PowerConnectorCeiling01`
`040` | SwitchedPowerPylon | `0013A3E4` | `workshop_co_PowerPylonSwitch01`
`050` | SwitchedPowerPylon-Large | `00147595` | `workshop_co_PowerPylonSwitch02`
`060` | Switch | `0005680D` | `workshop_co_PowerSwitchbox01`
`070` | PressurePlate | `00147596` | `workshop_co_PressurePlate01`
`080` | LaserTripwire | `001E9927` | `workshop_co_WorkshopTripwireLaser`
`100` | DelayedOffSwitch | `0022335D` | `workshop_co_PowerSwitchDelay02`
`100` | DelayedOnSwitch | `0022335E` | `workshop_co_PowerSwitchDelay01`
`100` | IntervalSwitch | `000B1033` | `workshop_co_PowerSwitchInterval01`
`110` | PowerCounter | `002128AD` | `workshop_co_PowerCounter01`

### Lights

Priority | CNAM\FULL | Form ID | EDID
--- | --- | --- | ---
`000` | Lightbulb | `0005A0D2` | `workshop_co_Lightbulb`
`020` | IndustrialWallLight | `000C01C4` | `workshop_co_WorkshopIndCatLight`
`050` | ConstructionLight | `00057DC3` | `workshop_co_WorkshopConstructionSpotlight01`
`080` | CeilingFan | `0003A2A2` | `workshop_co_WorkshopCeilingFanLight01`
`080` | Lamp | `00238448` | `workshop_co_HighTechLightFloor07_On`
`090` | HighTechLights | `0022D2D8` | `workshop_co_Hightechlights`
`090` | MirrorBall | `0022DC3F` | `workshop_co_WorkshopMirrorBall01`
`100` | StrobeLight | `0022D9D9` | `workshop_co_WorkshopStrobeLight01`

### Turrets

Priority | CNAM\FULL | Form ID | EDID
--- | --- | --- | ---
`030` | MachinegunTurret | `00076AB9` | `workshop_co_TurretTripod`
`032` | HeavyMachinegunTurret | `0022B59F` | `workshop_co_TurretTripodHeavy`
`040` | LaserTurret | `000D34D2` | `workshop_co_TurretLaser`
`040` | ShotgunTurret | `0022B175` | `workshop_co_TurretShotgun`
`040` | Spotlight | `0022B18E` | `workshop_co_TurretSpotlight`
`042` | HeavyLaserTurret | `0022B59E` | `workshop_co_TurretLaserHeavy`
`100` | MissileTurret | `0022B176` | `workshop_co_TurretMissile`

**Comment by zilav** [comment]
Updated, thx.
