### ISSUE TITLE
FO4Edit: Destructible\DAMC Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#297]
Per @Hugues92 in #294, I looked at `Destructible\DAMC`.

I didn't see what he saw re: `CVPA`. There are four damage types but three stages.

I could also find only one record that had this field.

### Destructible\DAMC

```
83 0A 06 00 // dtCryo [DMGT:00060A83]
64 00 00 00 // 100 (integer meaning 100%?)
84 0A 06 00 // dtPoison [DMGT:00060A84]
64 00 00 00 // 100 (integer meaning 100%?)
85 0A 06 00 // dtRadiationExposure [DMGT:00060A85]
64 00 00 00 // 100 (integer meaning 100%?)
86 0A 06 00 // dtRadiationIngestion [DMGT:00060A86]
64 00 00 00 // 100 (integer meaning 100%?)
```

**Comment by Hugues92** [comment]
It's not a formID, so maybe not a count either, but the array element structure should be a pair of int 32.:
    wbStruct(DAMC, 'Unknowns', 'Unknown', [
      wbInteger('Unknown', itU32),
      wbInteger('Unknown', itU32)
    ]),

**Comment by Hugues92** [comment]
The first int 32 is a FormID (it gets resolved during InitItem).

so:
    wbStructs(DAMC, 'Unknowns', 'Unknown', [
      wbFormIDck('Damage Type?', [DMGT, NULL]),
      wbInteger('Unknown', itU32)
    ]),

The second could effectively be a percentage
