### ISSUE TITLE
FO4Edit: IncludeScriptsFromSubDir setting blocks Apply Script window from opening

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#298]
I've encountered an issue that's blocking the Apply Scripts window from opening.

1. I updated to the latest build.
2. Tried to open the Apply Scripts window.
3. Apply Scripts window opened, and I ran a script.
4. Tried to open the Apply Scripts window again.
5. Result: `Error: Cannot focus a disabled or invisible window`
6. Restarted xEdit.
7. Tried to open the Apply Scripts window.
8. Result: `Error: Cannot focus a disabled or invisible window`

**Comment by Hugues92** [comment]
It's working fine for me. Try deleting the settings file and try again.

**Comment by fireundubh** [comment]
Where is that file?

**Comment by matortheeternal** [comment]
@fireundubh `%appdata%\..\Local\Skyrim\Plugins.tes5viewsettings`

**Comment by fireundubh** [comment]
Turns out that setting `IncludeScriptsFromSubDir` to `1` in the settings file causes this error.

This is the setting that @zilav recently added per my request to save the checkbox state.

**Comment by zilav** [comment]
Did you update your frmScriptForm.pas, I added check there `if Self.Active then`?

**Comment by fireundubh** [comment]
If you updated `frmScriptform.pas`, you didn't commit the change.

**Comment by zilav** [comment]
Happens :) Updated.
