### ISSUE TITLE
FO4Edit: EFSH DNAM Byte Array and Form Versions

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#299]
I didn't know how else to lay this information out, so here's a spreadsheet:

[All EFSH Records, All Form Versions, All DNAM Byte Arrays](https://docs.google.com/spreadsheets/d/1RqWrvvSCvra2GWv-oQwCDfR-eatB-TkaQs5h0KL_aTc/pubhtml?gid=0&single=true)

Most of what's in the DNAM byte array are floats, but there's a Form ID in v109+, too.

**Comment by zilav** [comment]
When CK is out we'll be able to define only the new format, so I guess the old long ones will just stay as hex arrays. No a big deal since there are no FormIDs there iirc.

**Comment by fireundubh** [comment]
These are the records that use the old form versions.

Form Version | Form ID | Notes
--- | --- | ---
63 | `BrokenFXSforBug [EFSH:000305A1]` | Unused
63 | `destWetFXS [EFSH:00036902]` | Used by `destWetEffect [MGEF:00036904]` for `destEnchWater [ENCH:000368FF]`, which is unused
100 | `StealthBoyInvisibilityEffect [EFSH:00102B7E]` | Unused

**Comment by zilav** [comment]
Updated.
