### ISSUE TITLE
Next Object ID increments regardless of whether a new form is created

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#300]
I noticed that the Next Object ID increments whenever you go to add a new form but regardless of whether you actually go through with the process.

### Steps to Reproduce

1. Create a new blank plugin.
2. Observe `Next Object ID` in File Header. (2048)
3. Add any record group.
4. Right-click the record group and select `Add > Signature`.
5. New FormID prompt displays a corresponding Form ID. (2048 = 02000800)
6. Instead of clicking OK, click Cancel.
7. Observe Next Object ID. (2049)

### Expected Result

* Next Object ID should not be incremented when generating a new Form ID. Use a temporary variable if needed.
* Next Object ID should not be incremented when the process is canceled because the new Form ID based on the Next Object ID is unused.
* Next Object ID should be incremented only when the user actually uses the new Form ID.

When Next Object ID is incremented needlessly, you end up with gaps between Form IDs, especially if you copy records as new and delete them, or go to create a new record and decide against doing so.

Not a "severe" bug but those of us who are OCD about number lines would appreciate a fix.

**Comment by zilav** [comment]
Done.
