### ISSUE TITLE
FO4Edit: wbCTDAFunctions Update

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#301]
edit: Removed bad information.

I switched ParamType2 and ParamType3 around here:

```delphi
    (Index: 576; Name: 'GetEventData'; ParamType1: ptEvent; ParamType2: ptNone; ParamType3: ptEventData),  // fireundubh: Event Function, Event Member, Event Data (FO4)
```

I still don't know what kind of param type "Event Member" is, so I left that at ptNone.

**Comment by zilav** [comment]
Doesn't make sense, some of those functions must have parameters and they have it in Skyrim, like IsLimbGone for example. What limb? GetObjectiveFailed, what objective? Etc.
Try to find please usage of those functions in master file and check if they indeed don't have parameters they should have, and had in Skyrim.

**Comment by fireundubh** [comment]
Hmm. You're right about pretty much all of those. Sorry. It was late and I confused "Comparison Value" with a parameter. A better name would be "Return Value." ;)

What about IsInCombat though? Gibbed's [functions dump](http://mod.gib.me/fallout4/functions.html) says `IsInCombat` has an optional `ptInteger` parameter, but `ref.IsInCombat(int)` doesn't make sense to me. You had the optional parameter in the TES5 definition, too, because the CK allowed you to change the optional parameter; however, the only information I could find about that integer was a thread suggesting the optional parameter was unused.

**Comment by Hugues92** [comment]
if the parameter is not null, then IsInCombat will test the ActorProcessManager before returning true.
Same in Skyrim

**Comment by fireundubh** [comment]
All right. Thanks.
