### ISSUE TITLE
FO4Edit: EXPL DATA Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#303]
*Note: Wherever I say "flags," think flags or enum.*

# Byte Array Length

The length of the `DATA\Unknown` byte array varies with the form version.

Form Versions | Byte Array Length
--- | ---
63 | 8
71, 73, 86, 88 | 12
95 | 16
99, 109 | 20
112, 119, 120, 122, 124, 126, 127, 128, 129, 130, 131 | 40

# Form Version 63

All of the v63 records.

Form ID | Flags | Flags
--- | --- | ---
<pre>0002FC46</pre> | <pre>43 00 00 00</pre> | <pre>02 00 00 00</pre>
<pre>0002FC47</pre> | <pre>43 00 00 00</pre> | <pre>02 00 00 00</pre>
<pre>00046518</pre> | <pre>05 00 00 00</pre> | <pre>01 00 00 00</pre>

# Form Versions 71-88

All of the v71, v73, v86, and v88 records.

Form ID | Flags | Flags | Unknown
--- | --- | --- | ---
<pre>00080152</pre> | <pre>01 02 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>000822D8</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>000822DB</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>000896FE</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>00089700</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>00089701</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>00089703</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>00089704</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>00089706</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>000B9269</pre> | <pre>43 00 00 00</pre> | <pre>02 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>000C1C15</pre> | <pre>43 00 00 00</pre> | <pre>02 00 00 00</pre> | <pre>00 00 00 00</pre>

# Form Version 95

The only v95 record.

Form ID | Flags | Flags | Unknown | Unknown
--- | --- | ---| --- | ---
<pre>000DB85B</pre> | <pre>63 00 00 00</pre> | <pre>02 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre>

# Form Versions 99-109

All of the v99 and v109 records.

Form ID | Float | Flags | Flags | Unknown | Flags
--- | --- | ---| --- | --- | ---
<pre>000A8AFD</pre> | <pre>00 00 00 00</pre> | <pre>43 01 00 00</pre> | <pre>02 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>000E7319</pre> | <pre>00 00 00 00</pre> | <pre>41 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>0016D546</pre> | <pre>CD CC CC 3D</pre> | <pre>4F 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>02 00 00 00</pre>

# Form Versions 112+

A small selection of the available v112+ records.

Form ID | Float | Flags | Flags | Float | Flags | Unknown | Float | Float | Float | Flags
--- | --- | ---| --- | --- | --- | ---| --- | --- | --- | ---
<pre>00062BE7</pre> | <pre>9A 99 99 3E</pre> | <pre>53 04 00 00</pre> | <pre>03 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>0011E675</pre> | <pre>CD CC CC 3D</pre> | <pre>5F 05 00 00</pre> | <pre>02 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>04 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre>
<pre>001B88DA</pre> | <pre>00 00 00 00</pre> | <pre>41 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>02 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 80 3F</pre> | <pre>00 00 20 43</pre> | <pre>02 00 00 00</pre>
<pre>0012B40A</pre> | <pre>00 00 00 00</pre> | <pre>4D 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 80 3F</pre> | <pre>00 00 00 00</pre> | <pre>00 00 F0 41</pre> | <pre>01 00 00 00</pre>
<pre>00186DE2</pre> | <pre>00 00 00 00</pre> | <pre>52 00 00 00</pre> | <pre>01 00 00 00</pre> | <pre>00 00 20 41</pre> | <pre>02 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre> | <pre>00 00 00 00</pre>

**Comment by zilav** [comment]
The first 4 bytes of unknown is not a FormID, doesn't resolve to anything. Looks like a float to me
      IS Radius: 786.000000
      Vertical Offset Mult: 0.000000
      abcd: [3E99999A] < Error: Could not be resolved >

**Comment by fireundubh** [comment]
Yeah, I have that column labeled Float. ;)

**Comment by zilav** [comment]
I thought it is the first field in Unknown :)
Updated.
