### ISSUE TITLE
Script adapter missing TPerlRegEx.Replacement property and others

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#304]
# TPerlRegEx.Replacement

Add to `TPerlRegEx` section in `wbScriptAdapterMisc.pas`:

```delphi
procedure TPerlRegEx_Read_Replacement(var Value: Variant; Args: TJvInterpreterArgs);
begin
  Value := String(TPerlRegEx(Args.Obj).Replacement);
end;

procedure TPerlRegEx_Write_Replacement(const Value: Variant; Args: TJvInterpreterArgs);
begin
  TPerlRegEx(Args.Obj).Replacement := String(Value);
end;
```

Add to `RegisterJvInterpreterAdapter` procedure in `wbScriptAdapterMisc.pas`:

```delphi
    AddGet(TPerlRegEx, 'Replacement', TPerlRegEx_Read_Replacement, 0, [varEmpty], varEmpty);
    AddSet(TPerlRegEx, 'Replacement', TPerlRegEx_Write_Replacement, 0, [varEmpty]);
```

# Other missing properties

### TPerlRegEx.Compiled

```delphi
// True if the RegEx has already been compiled.
```

### TPerlRegEx.Studied

```delphi
// True if the RegEx has already been studied
```

### TPerlRegEx.State

```delphi
// State of Subject

// type
//   TPerlRegExState = set of (
//     preNotBOL,         // Not Beginning Of Line: ^ does not match at the start of Subject
//     preNotEOL,         // Not End Of Line: $ does not match at the end of Subject
//     preNotEmpty        // Empty matches not allowed
//   );
```

### TPerlRegEx.OnMatch
```delphi
// Triggered by Match and MatchAgain after a successful match
```

### TPerlRegEx.OnReplace
```delphi
// Triggered by Replace and ReplaceAll just before the replacement is done, allowing you to determine the new UTF8String
```

**Comment by zilav** [comment]
Updated except for events. Unfortunately they don't work on TPerlRegEx, JvIntterpreter probably supports only events of TPersistent class descendants. Don't have time nor will to go and debug it.

**Comment by darkconsole** [comment]
not to sound dumb, but on the 3.1.3 alpha build im still getting undefined identifiers for Replacement.

```pascal
		Reg := TPerlRegex.Create();
		Reg.RegEx := '\b(light|heavy|cloth)\n';
		Reg.Options := [ preCaseLess ];
		Reg.Subject := FormGetName(Form);
		Reg.Replacement := 'whatwhy';
```

**Comment by zilav** [comment]
I tested and this works using the latest build from FO4 Nexus
```
function Process(e: IInterface): Integer;
var
  Reg: TPerlRegEx;
begin
  Reg := TPerlRegEx.Create;
  Reg.Replacement := 'whatwhy';
  Reg.Free;
end;

**Comment by fireundubh** [comment]
@darkconsole This is how I've implemented a few TPerlRegEx helper functions in [dubhFunctions.pas](https://github.com/fireundubh/xedit/blob/master/lib/dubhFunctions.pas):

https://gist.github.com/fireundubh/d1ac11377255d84def30de495b5996df

**Comment by darkconsole** [comment]
@zilav is correct. it does work in the 3.1.3 build on fallout nexus. that is super strange that it did not work on the 3.1.3 build in the release tab here on github.

**Comment by darkconsole** [comment]
ah, i see what happened. the release build here on github the exe is named fo4edit by default, so my tes5edit.exe never got updated. thats weird because it still reported 3.1.3 EXPERIMENTAL in the Title bar.
