### ISSUE TITLE
FO4Edit: AMDL\DNAM Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#305]
Testing out my new TPerlRegEx-powered byte array parser and Markdown generator! ;)

The `AMDL\DNAM\[0]` byte array is a float. All are floats. See!

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>083</pre> | <pre>00022FBE</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>086</pre> | <pre>000BB845</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>CD CC 4C 3E</pre> | <pre>0.2</pre>
<pre>087</pre> | <pre>000BDB77</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>095</pre> | <pre>000E48C9</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3E</pre> | <pre>0.25</pre>
<pre>098</pre> | <pre>000EB4B1</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>CD CC CC 3D</pre> | <pre>0.1</pre>
<pre>098</pre> | <pre>000FC3EB</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>CD CC 4C 3E</pre> | <pre>0.2</pre>
<pre>099</pre> | <pre>000F6D07</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.0</pre>
<pre>099</pre> | <pre>000FF304</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.0</pre>
<pre>100</pre> | <pre>00101287</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 00</pre> | <pre>NULL</pre>
<pre>106</pre> | <pre>00121AC1</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 20 41</pre> | <pre>10.0</pre>
<pre>109</pre> | <pre>00136259</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 20 41</pre> | <pre>10.0</pre>
<pre>109</pre> | <pre>0015B07C</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 00</pre> | <pre>NULL</pre>
<pre>111</pre> | <pre>00198150</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 40</pre> | <pre>5.0</pre>
<pre>112</pre> | <pre>0019E157</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 40</pre> | <pre>5.0</pre>
<pre>119</pre> | <pre>00108173</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>0A D7 23 3C</pre> | <pre>0.01</pre>
<pre>119</pre> | <pre>00150791</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 00</pre> | <pre>NULL</pre>
<pre>120</pre> | <pre>0001F641</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 40</pre> | <pre>3.0</pre>
<pre>120</pre> | <pre>00029479</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>120</pre> | <pre>0003A75D</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 60 40</pre> | <pre>3.5</pre>
<pre>120</pre> | <pre>0003D85B</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>120</pre> | <pre>0005D4D4</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>120</pre> | <pre>00067345</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>120</pre> | <pre>000C3151</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C0 40</pre> | <pre>6.0</pre>
<pre>120</pre> | <pre>000C536B</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>120</pre> | <pre>0019E14F</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 20 40</pre> | <pre>2.5</pre>
<pre>120</pre> | <pre>0019E150</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>120</pre> | <pre>0019E151</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 20 40</pre> | <pre>2.5</pre>
<pre>120</pre> | <pre>0019E153</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>120</pre> | <pre>0019E154</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 60 40</pre> | <pre>3.5</pre>
<pre>120</pre> | <pre>0019E155</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 40</pre> | <pre>3.0</pre>
<pre>120</pre> | <pre>0019E156</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>120</pre> | <pre>0019E158</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 60 40</pre> | <pre>3.5</pre>
<pre>120</pre> | <pre>001A7604</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 40</pre> | <pre>5.0</pre>
<pre>126</pre> | <pre>0019E152</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>127</pre> | <pre>00013AEA</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>127</pre> | <pre>0001F63A</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>127</pre> | <pre>0006FF4B</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>127</pre> | <pre>000E0302</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>
<pre>127</pre> | <pre>0018887B</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>128</pre> | <pre>0001F63E</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 41</pre> | <pre>12.0</pre>
<pre>128</pre> | <pre>0002947B</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>128</pre> | <pre>00125CA7</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>128</pre> | <pre>0012C009</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 20 41</pre> | <pre>10.0</pre>
<pre>128</pre> | <pre>0016429D</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>128</pre> | <pre>001888E1</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>128</pre> | <pre>0019967C</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 41</pre> | <pre>12.0</pre>
<pre>128</pre> | <pre>0019E159</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.0</pre>
<pre>128</pre> | <pre>00212DB3</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3E</pre> | <pre>0.25</pre>
<pre>128</pre> | <pre>00215E05</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 60 40</pre> | <pre>3.5</pre>
<pre>128</pre> | <pre>0022BC46</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.0</pre>
<pre>128</pre> | <pre>0022BC92</pre> | <pre>AMDL\DNAM\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.0</pre>

**Comment by zilav** [comment]
Updated.
