### ISSUE TITLE
FO4Edit: AECH DNAM Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#307]
AECH is an interesting record.

There are three KNAMs that control the length of the associated DNAM byte array:

ID | KNAM | DNAM Length
--- | --- | ---
K32A | `4F 7B 83 18` | 32 bytes
K32B | `7F 5F 57 EF` | 32 bytes
K40 | `BE 04 48 86` | 40 bytes

No form version differences, so I just used the latest one.

# K32A DNAM

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>002476BB</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>0</pre> | <pre>01 00 00 00</pre> | <pre>Not resolvable</pre>
<pre>131</pre> | <pre>002476BB</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>1</pre> | <pre>52 B8 9E 3E</pre> | <pre>0.31</pre>
<pre>131</pre> | <pre>002476BB</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>2</pre> | <pre>99 99 19 3E</pre> | <pre>0.15</pre>
<pre>131</pre> | <pre>002476BB</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>3</pre> | <pre>64 00 00 00</pre> | <pre>Not resolvable</pre>

# K32B DNAM

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>0008BBB9</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>0</pre> | <pre>01 00 00 00</pre> | <pre>Not resolvable</pre>
<pre>131</pre> | <pre>0008BBB9</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>1</pre> | <pre>00 40 1C 45</pre> | <pre>2500.0</pre>
<pre>131</pre> | <pre>0008BBB9</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>2</pre> | <pre>00 00 80 3F</pre> | <pre>1.0</pre>
<pre>131</pre> | <pre>0008BBB9</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>32</pre> | <pre>3</pre> | <pre>01 00 00 00</pre> | <pre>Not resolvable</pre>

# K40 DNAM

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>0024945E</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>40</pre> | <pre>0</pre> | <pre>01 00 00 00</pre> | <pre>Not resolvable</pre>
<pre>131</pre> | <pre>0024945E</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>40</pre> | <pre>1</pre> | <pre>41 22 0A 3E</pre> | <pre>0.13</pre>
<pre>131</pre> | <pre>0024945E</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>40</pre> | <pre>2</pre> | <pre>1C 4F 77 3F</pre> | <pre>0.97</pre>
<pre>131</pre> | <pre>0024945E</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>40</pre> | <pre>3</pre> | <pre>EF 3B 35 3F</pre> | <pre>0.71</pre>
<pre>131</pre> | <pre>0024945E</pre> | <pre>AECH\Effects\Effect\DNAM</pre> | <pre>40</pre> | <pre>4</pre> | <pre>87 18 36 3E</pre> | <pre>0.18</pre>

**Comment by zilav** [comment]
Looks like DNAM values should be unions depending on KNAM, but unless we know for sure what KNAM means nothing can be updated here in definitions.

**Comment by fireundubh** [comment]
Hmm. Well, this is the best I can do for KNAM. Value is `UINT32 LE`.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>002476BB</pre> | <pre>AECH\Effects\Effect\KNAM[03]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>4F 7B 83 18</pre> | <pre>411269967</pre>
<pre>131</pre> | <pre>002476BB</pre> | <pre>AECH\Effects\Effect\KNAM[00]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>7F 5F 57 EF</pre> | <pre>4015480703</pre>
<pre>131</pre> | <pre>002476BB</pre> | <pre>AECH\Effects\Effect\KNAM[01]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>BE 04 48 86</pre> | <pre>2252866750</pre>

**Comment by zilav** [comment]
Better wait for CK here, not much we can do.
