### ISSUE TITLE
FO4Edit: ARMO DATA Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#308]
`DATA\[2]` is Damage Resistance exclusively for Power Armor. That's the DR with the Shield icon.

These are all of the ARMO records that have a value here, and they're all power armor items.

Possible labels:

* Ballistic Damage Resist
* Physical Damage Resist
* Health
* Durability
* Condition

I would bet on Health or Durability, as power armor is the only item type that has durability, and its physical damage resistance is effectively durability as well. Once we can easily test this field, we might be able to give other non-PA items durability, in which case I think that would confirm the label.

Plus, it would make sense for Durability to be under DATA, rather than for this field to be another DR separate from FNAM.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>Armor_Power_Raider_ArmLeft [ARMO:00140C52]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_Raider_ArmRight [ARMO:00140C53]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_Raider_Helm [ARMO:00140C54]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_Raider_LegLeft [ARMO:00140C55]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_Raider_LegRight [ARMO:00140C56]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_Raider_Torso [ARMO:00140C57]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>64 00 00 00</pre> | <pre>100</pre>
<pre>131</pre> | <pre>Armor_Power_T45_ArmLeft [ARMO:00154ABD]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_T45_ArmRight [ARMO:00154ABE]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_T45_Helm [ARMO:00154ABF]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_T45_LegLeft [ARMO:00154AC0]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_T45_LegRight [ARMO:00154AC1]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>32 00 00 00</pre> | <pre>50</pre>
<pre>131</pre> | <pre>Armor_Power_T45_Torso [ARMO:00154AC2]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>C8 00 00 00</pre> | <pre>200</pre>
<pre>131</pre> | <pre>Armor_Power_T51_ArmLeft [ARMO:00140C4C]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>50 00 00 00</pre> | <pre>80</pre>
<pre>131</pre> | <pre>Armor_Power_T51_ArmRight [ARMO:00140C4D]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>50 00 00 00</pre> | <pre>80</pre>
<pre>131</pre> | <pre>Armor_Power_T51_Helmet [ARMO:00140C4E]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>50 00 00 00</pre> | <pre>80</pre>
<pre>131</pre> | <pre>Armor_Power_T51_LegLeft [ARMO:00140C4F]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>50 00 00 00</pre> | <pre>80</pre>
<pre>131</pre> | <pre>Armor_Power_T51_LegRight [ARMO:00140C50]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>50 00 00 00</pre> | <pre>80</pre>
<pre>131</pre> | <pre>Armor_Power_T51_Torso [ARMO:00140C51]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>40 01 00 00</pre> | <pre>320</pre>
<pre>131</pre> | <pre>Armor_Power_T60_ArmLeft [ARMO:00140C3D]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_ArmLeft_Danse [ARMO:0024984B]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_ArmRight [ARMO:00140C45]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_ArmRight_Danse [ARMO:0024984C]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_Helm [ARMO:00140C4A]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_LegLeft [ARMO:00140C49]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_LegLeft_Danse [ARMO:0024984D]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_LegRight [ARMO:00140C3F]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_LegRight_Danse [ARMO:0024984E]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>6E 00 00 00</pre> | <pre>110</pre>
<pre>131</pre> | <pre>Armor_Power_T60_Torso [ARMO:00140C42]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>B8 01 00 00</pre> | <pre>440</pre>
<pre>131</pre> | <pre>Armor_Power_T60_Torso_Danse [ARMO:0024984F]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>B8 01 00 00</pre> | <pre>440</pre>
<pre>131</pre> | <pre>Armor_Power_X01_ArmLeft [ARMO:00154AC3]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_ArmLeft_Danse [ARMO:00249850]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_ArmRight [ARMO:00154AC4]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_ArmRight_Danse [ARMO:00249851]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_Helm [ARMO:00154AC5]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_LegLeft [ARMO:00154AC6]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_LegLeft_Danse [ARMO:00249852]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_LegRight [ARMO:00154AC7]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_LegRight_Danse [ARMO:00249853]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8C 00 00 00</pre> | <pre>140</pre>
<pre>131</pre> | <pre>Armor_Power_X01_Torso [ARMO:00154AC8]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>30 02 00 00</pre> | <pre>560</pre>
<pre>131</pre> | <pre>Armor_Power_X01_Torso_Danse [ARMO:00249854]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>30 02 00 00</pre> | <pre>560</pre>
<pre>131</pre> | <pre>DN015_Armor_Power_Torso [ARMO:001C0382]</pre> | <pre>ARMO\DATA\Unknown</pre> | <pre>8</pre> | <pre>0</pre> | <pre>C2 01 00 00</pre> | <pre>450</pre>

**Comment by zilav** [comment]
Thx, updated as "Power Armor Health".
