### ISSUE TITLE
FO4Edit: NPC_ MSDK and MSDV Byte Arrays

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#309]
I don't know what MSDK represents, but these Ints look familiar somehow. They look like products of Sig2Int().

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>000</pre> | <pre>B2 35 EF 36</pre> | <pre>921646514</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>001</pre> | <pre>11 36 EF 36</pre> | <pre>921646609</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>002</pre> | <pre>D6 35 EF 36</pre> | <pre>921646550</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>003</pre> | <pre>15 36 EF 36</pre> | <pre>921646613</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>004</pre> | <pre>D3 35 EF 36</pre> | <pre>921646547</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>005</pre> | <pre>C4 34 EF 36</pre> | <pre>921646276</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>006</pre> | <pre>D5 35 EF 36</pre> | <pre>921646549</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>007</pre> | <pre>0C 36 EF 36</pre> | <pre>921646604</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>008</pre> | <pre>97 35 EF 36</pre> | <pre>921646487</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>009</pre> | <pre>D8 34 EF 36</pre> | <pre>921646296</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>010</pre> | <pre>78 34 EF 36</pre> | <pre>921646200</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDK</pre> | <pre>96</pre> | <pre>011</pre> | <pre>D4 35 EF 36</pre> | <pre>921646548</pre>

On the other hand, MSDV is a dynamically sized array of floats that corresponds to the length of MSDK.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>000</pre> | <pre>8F C2 75 3F</pre> | <pre>0.96</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>001</pre> | <pre>00 00 80 3F</pre> | <pre>1.0</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>002</pre> | <pre>41 C4 5B BE</pre> | <pre>-0.21</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>003</pre> | <pre>00 00 80 3F</pre> | <pre>1.0</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>004</pre> | <pre>1F 85 6B 3E</pre> | <pre>0.23</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>005</pre> | <pre>F6 28 DC 3E</pre> | <pre>0.43</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>006</pre> | <pre>C8 3F 8D BE</pre> | <pre>-0.28</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>007</pre> | <pre>00 00 80 3F</pre> | <pre>1.0</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>008</pre> | <pre>00 00 80 3F</pre> | <pre>1.0</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>009</pre> | <pre>85 EB 11 3F</pre> | <pre>0.57</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>010</pre> | <pre>CD CC CC BD</pre> | <pre>-0.1</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\MSDV</pre> | <pre>96</pre> | <pre>011</pre> | <pre>3D 0A 57 3E</pre> | <pre>0.21</pre>

**Comment by zilav** [comment]
MSDK are not signatures for sure, defined them as separate 4 bytes arrays to correspond to float values. They are probably enumerations just like other face morph data. Updated.
