### ISSUE TITLE
FO4Edit: IPCT FNAM Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#310]
Only two records have an FNAM value, which appears to be a Float.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>130</pre> | <pre>FSTSentryRightRollImpactGeneric [IPCT:0022DA4A]</pre> | <pre>IPCT\FNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 80 BB 44</pre> | <pre>1500.000</pre>
<pre>130</pre> | <pre>FSTSentryLeftRollImpactGeneric [IPCT:0022DA4B]</pre> | <pre>IPCT\FNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 80 BB 44</pre> | <pre>1500.000</pre>

**Comment by zilav** [comment]
Updated, thx.
