### ISSUE TITLE
FO4Edit: MSWP CNAM Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#311]
Floats ahoy! CNAM is an array of floats.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>116</pre> | <pre>001A0342</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>CD CC 4C 3F</pre> | <pre>0.800</pre>
<pre>116</pre> | <pre>001A0343</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>9A 99 19 3E</pre> | <pre>0.150</pre>
<pre>116</pre> | <pre>001A0344</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>33 33 B3 3E</pre> | <pre>0.350</pre>
<pre>116</pre> | <pre>001A0345</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>116</pre> | <pre>001A0349</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 3F</pre> | <pre>0.750</pre>
<pre>118</pre> | <pre>000D15EC</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>EE 7C BF 3E</pre> | <pre>0.374</pre>
<pre>118</pre> | <pre>000D15ED</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>A4 70 FD 3E</pre> | <pre>0.495</pre>
<pre>118</pre> | <pre>000D15EE</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>118</pre> | <pre>000D15EF</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>118</pre> | <pre>000D15F0</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>52 B8 3E 3F</pre> | <pre>0.745</pre>
<pre>118</pre> | <pre>000D15F6</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>77 BE 5F 3F</pre> | <pre>0.874</pre>
<pre>118</pre> | <pre>000D15F7</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>DB F9 1E 3F</pre> | <pre>0.621</pre>
<pre>118</pre> | <pre>000D1601</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>EE 7C BF 3E</pre> | <pre>0.374</pre>
<pre>118</pre> | <pre>000D16BC</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>A4 70 FD 3E</pre> | <pre>0.495</pre>
<pre>118</pre> | <pre>0014F6D7</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>DB F9 1E 3F</pre> | <pre>0.621</pre>
<pre>118</pre> | <pre>0014F6D9</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>CD CC CC 3E</pre> | <pre>0.400</pre>
<pre>118</pre> | <pre>0014F6DE</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>CD CC CC 3E</pre> | <pre>0.400</pre>
<pre>120</pre> | <pre>001B5ECE</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 3F</pre> | <pre>0.500</pre>
<pre>120</pre> | <pre>001B5ECF</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3E</pre> | <pre>0.250</pre>
<pre>120</pre> | <pre>001B5ED0</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 3F</pre> | <pre>0.750</pre>
<pre>121</pre> | <pre>001C359C</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>124</pre> | <pre>001CF01B</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>77 BE 5F 3F</pre> | <pre>0.874</pre>
<pre>124</pre> | <pre>001CF01C</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 3F</pre> | <pre>0.750</pre>
<pre>126</pre> | <pre>001E03CC</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>DB F9 1E 3F</pre> | <pre>0.621</pre>
<pre>126</pre> | <pre>001E03CC</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 00</pre> | <pre>NULL</pre>
<pre>128</pre> | <pre>001BE2DE</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>AE 47 E1 3D</pre> | <pre>0.110</pre>
<pre>128</pre> | <pre>001BE2DE</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>AE 47 E1 3D</pre> | <pre>0.110</pre>
<pre>128</pre> | <pre>001BE2DE</pre> | <pre>MSWP\Unknown\Unknown\CNAM[2]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>7B 14 2E 3E</pre> | <pre>0.170</pre>
<pre>128</pre> | <pre>0022DD20</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>29 5C 4F 3F</pre> | <pre>0.810</pre>
<pre>128</pre> | <pre>0022DD21</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>7B 14 2E 3F</pre> | <pre>0.680</pre>
<pre>128</pre> | <pre>0022DD22</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>29 5C 0F 3F</pre> | <pre>0.560</pre>
<pre>128</pre> | <pre>0022DD23</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>F6 28 DC 3E</pre> | <pre>0.430</pre>
<pre>128</pre> | <pre>0022DD24</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>52 B8 9E 3E</pre> | <pre>0.310</pre>
<pre>128</pre> | <pre>0022DD25</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>EC 51 38 3E</pre> | <pre>0.180</pre>
<pre>128</pre> | <pre>0022DD26</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>8F C2 75 3D</pre> | <pre>0.060</pre>
<pre>128</pre> | <pre>0022E2CB</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 3F</pre> | <pre>0.500</pre>
<pre>128</pre> | <pre>0022E2CB</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 3F</pre> | <pre>0.500</pre>
<pre>128</pre> | <pre>0022E2CB</pre> | <pre>MSWP\Unknown\Unknown\CNAM[2]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>CD CC 4C 3E</pre> | <pre>0.200</pre>
<pre>129</pre> | <pre>001A0346</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>9A 99 19 3E</pre> | <pre>0.150</pre>
<pre>129</pre> | <pre>001A0348</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 3F</pre> | <pre>0.500</pre>
<pre>129</pre> | <pre>001B5ED1</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 3F</pre> | <pre>0.750</pre>
<pre>129</pre> | <pre>001B5ED2</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3E</pre> | <pre>0.250</pre>
<pre>129</pre> | <pre>001B5ED3</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 3F</pre> | <pre>0.500</pre>
<pre>131</pre> | <pre>001A0347</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>9A 99 99 3E</pre> | <pre>0.300</pre>
<pre>131</pre> | <pre>001C2070</pre> | <pre>MSWP\Unknown\Unknown\CNAM[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 00</pre> | <pre>NULL</pre>
<pre>131</pre> | <pre>001C2070</pre> | <pre>MSWP\Unknown\Unknown\CNAM[1]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 3F</pre> | <pre>0.750</pre>
<pre>131</pre> | <pre>001C2070</pre> | <pre>MSWP\Unknown\Unknown\CNAM[2]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 3F</pre> | <pre>0.750</pre>
<pre>131</pre> | <pre>001C2070</pre> | <pre>MSWP\Unknown\Unknown\CNAM[3]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 3F</pre> | <pre>0.750</pre>

**Comment by zilav** [comment]
Updated.
