### ISSUE TITLE
FO4Edit: RACE PTOP and NTOP Byte Arrays

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#312]
PTOP and NTOP are floats. Not arrays of floats this time. Just floats.

# PTOP

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>00013746</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>0001A009</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>0001D31E</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>0001D698</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>0001D810</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 40</pre> | <pre>5.000</pre>
<pre>131</pre> | <pre>0001DB4A</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>0002047E</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 20 41</pre> | <pre>10.000</pre>
<pre>131</pre> | <pre>00023FFC</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>0002456D</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>00029463</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>0003578A</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>000359F4</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 E0 40</pre> | <pre>7.000</pre>
<pre>131</pre> | <pre>0004716C</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 40</pre> | <pre>3.000</pre>
<pre>131</pre> | <pre>0005FBB1</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>000636AB</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 40</pre> | <pre>5.000</pre>
<pre>131</pre> | <pre>00064C60</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>0006B4EC</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>0007ED1D</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>00090C33</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>000A0F2F</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.000</pre>
<pre>131</pre> | <pre>000A563A</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>000A96BF</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>000AE0B7</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>000B7F91</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>000BB7D9</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>000C9ACF</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.000</pre>
<pre>131</pre> | <pre>000D77E3</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>000D8417</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>000D9804</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 E0 40</pre> | <pre>7.000</pre>
<pre>131</pre> | <pre>000DFB33</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>000E12A6</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 40</pre> | <pre>3.000</pre>
<pre>131</pre> | <pre>000E8D09</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>000EAFB6</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>00108019</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>0010BD65</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>0011D83F</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>0011EB96</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>00166729</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>
<pre>131</pre> | <pre>00184C4D</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>00187AF9</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>002261A4</pre> | <pre>RACE\PTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 70 41</pre> | <pre>15.000</pre>

# NTOP

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>00013746</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>0001A009</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>0001D31E</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.000</pre>
<pre>131</pre> | <pre>0001D698</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.000</pre>
<pre>131</pre> | <pre>0001D810</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.000</pre>
<pre>131</pre> | <pre>0001DB4A</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C0 40</pre> | <pre>6.000</pre>
<pre>131</pre> | <pre>0002047E</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>00023FFC</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 40</pre> | <pre>3.000</pre>
<pre>131</pre> | <pre>0002456D</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.000</pre>
<pre>131</pre> | <pre>00029463</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.000</pre>
<pre>131</pre> | <pre>0003578A</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 40</pre> | <pre>4.000</pre>
<pre>131</pre> | <pre>000359F4</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.000</pre>
<pre>131</pre> | <pre>0004716C</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>0005FBB1</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>000636AB</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 F0 41</pre> | <pre>30.000</pre>
<pre>131</pre> | <pre>00064C60</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>0006B4EC</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>0007ED1D</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 41</pre> | <pre>12.000</pre>
<pre>131</pre> | <pre>00090C33</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 40</pre> | <pre>3.000</pre>
<pre>131</pre> | <pre>000A0F2F</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 41</pre> | <pre>12.000</pre>
<pre>131</pre> | <pre>000A563A</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>000A96BF</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>000AE0B7</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.000</pre>
<pre>131</pre> | <pre>000B7F91</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 40</pre> | <pre>5.000</pre>
<pre>131</pre> | <pre>000BB7D9</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.000</pre>
<pre>131</pre> | <pre>000C9ACF</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 20 41</pre> | <pre>10.000</pre>
<pre>131</pre> | <pre>000D77E3</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>000D8417</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 A0 41</pre> | <pre>20.000</pre>
<pre>131</pre> | <pre>000D9804</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>000DFB33</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 41</pre> | <pre>8.000</pre>
<pre>131</pre> | <pre>000E12A6</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 40 41</pre> | <pre>12.000</pre>
<pre>131</pre> | <pre>000E8D09</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>000EAFB6</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>00108019</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>0010BD65</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>0011D83F</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>0011EB96</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>00166729</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>
<pre>131</pre> | <pre>00184C4D</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 00 40</pre> | <pre>2.000</pre>
<pre>131</pre> | <pre>00187AF9</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C0 40</pre> | <pre>6.000</pre>
<pre>131</pre> | <pre>002261A4</pre> | <pre>RACE\NTOP[0]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 C8 41</pre> | <pre>25.000</pre>

**Comment by zilav** [comment]
Updated.
