### ISSUE TITLE
FO4Edit: SOPM ATTN Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#313]
The first four sets of 4 bytes are floats.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>063</pre> | <pre>0005BA91</pre> | <pre>SOPM\ATTN[0]</pre> | <pre>48</pre> | <pre>0</pre> | <pre>00 40 1C 45</pre> | <pre>2500.000</pre>
<pre>063</pre> | <pre>0005BA91</pre> | <pre>SOPM\ATTN[0]</pre> | <pre>48</pre> | <pre>1</pre> | <pre>00 C0 5A 45</pre> | <pre>3500.000</pre>
<pre>063</pre> | <pre>0005BA91</pre> | <pre>SOPM\ATTN[0]</pre> | <pre>48</pre> | <pre>2</pre> | <pre>00 A0 8C 45</pre> | <pre>4500.000</pre>
<pre>063</pre> | <pre>0005BA91</pre> | <pre>SOPM\ATTN[0]</pre> | <pre>48</pre> | <pre>3</pre> | <pre>00 80 BB 45</pre> | <pre>6000.000</pre>
<pre>063</pre> | <pre>0005BA91</pre> | <pre>SOPM\ATTN[0]</pre> | <pre>48</pre> | <pre>4</pre> | <pre>19 32 4B 5F</pre> | <pre>1598763545</pre>
<pre>063</pre> | <pre>0005BA91</pre> | <pre>SOPM\ATTN[0]</pre> | <pre>48</pre> | <pre>5</pre> | <pre>32 19 0A 00</pre> | <pre>661810</pre>

**Comment by zilav** [comment]
Updated.
