### ISSUE TITLE
FO4Edit: WATR DNAM Byte Arrays

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#314]
`DNAM\[7]` and `DNAM\[13]` are floats.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>001BA679</pre> | <pre>WATR\DNAM\Unknown[7]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>24 28 7E 3F</pre> | <pre>0.993</pre>
<pre>131</pre> | <pre>001BA679</pre> | <pre>WATR\DNAM\Unknown[13]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>48 50 7C 3E</pre> | <pre>0.246</pre>
<pre>131</pre> | <pre>001BDDB1</pre> | <pre>WATR\DNAM\Unknown[7]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>00 00 80 3F</pre> | <pre>1.000</pre>
<pre>131</pre> | <pre>001BDDB1</pre> | <pre>WATR\DNAM\Unknown[13]</pre> | <pre>8</pre> | <pre>0</pre> | <pre>A1 45 56 3F</pre> | <pre>0.837</pre>

**Comment by zilav** [comment]
Updated.
