### ISSUE TITLE
FO4Edit: NPC_ FMRS Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#315]
FMRS is an array of floats. I checked all of the records.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\Unknown\Unknown\FMRS[00]</pre> | <pre>72</pre> | <pre>0</pre> | <pre>D1 F6 4A 3C</pre> | <pre>0.0124</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\Unknown\Unknown\FMRS[00]</pre> | <pre>72</pre> | <pre>1</pre> | <pre>29 5C 4F BF</pre> | <pre>-0.8100</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\Unknown\Unknown\FMRS[00]</pre> | <pre>72</pre> | <pre>2</pre> | <pre>EB 51 38 3E</pre> | <pre>0.1800</pre>
<pre>131</pre> | <pre>00000007</pre> | <pre>NPC_\Unknown\Unknown\FMRS[00]</pre> | <pre>72</pre> | <pre>3</pre> | <pre>0A D7 A3 3D</pre> | <pre>0.0800</pre>

**Comment by zilav** [comment]
Updated.
