### ISSUE TITLE
FO4Edit: NPC_ MRSV Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#316]
MRSV is an array of floats.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>131</pre> | <pre>00248618</pre> | <pre>NPC_\MRSV[00]</pre> | <pre>40</pre> | <pre>0</pre> | <pre>71 3D 4A BF</pre> | <pre>-0.790000 [float]</pre>
<pre>131</pre> | <pre>00248618</pre> | <pre>NPC_\MRSV[00]</pre> | <pre>40</pre> | <pre>1</pre> | <pre>F6 28 1C BF</pre> | <pre>-0.610000 [float]</pre>
<pre>131</pre> | <pre>00248618</pre> | <pre>NPC_\MRSV[00]</pre> | <pre>40</pre> | <pre>2</pre> | <pre>00 00 40 3F</pre> | <pre>0.750000 [float]</pre>
<pre>131</pre> | <pre>00248618</pre> | <pre>NPC_\MRSV[00]</pre> | <pre>40</pre> | <pre>3</pre> | <pre>00 00 80 3F</pre> | <pre>1.000000 [float]</pre>
<pre>131</pre> | <pre>00248618</pre> | <pre>NPC_\MRSV[00]</pre> | <pre>40</pre> | <pre>4</pre> | <pre>E1 7A 54 3F</pre> | <pre>0.830000 [float]</pre>

**Comment by zilav** [comment]
Updated.
