### ISSUE TITLE
FO4Edit: OVIS DATA Byte Array

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#317]
DATA is an array of floats.

Ver | Record | Path | Size | Index | Bytes | Value
--- | --- | --- | --- | --- | --- | ---
<pre>128</pre> | <pre>00000027</pre> | <pre>OVIS\Unknown\Unknown\DATA[00]</pre> | <pre>48</pre> | <pre>0</pre> | <pre>42 8F 62 C3</pre> | <pre>-226.559601 [float]</pre>
<pre>128</pre> | <pre>00000027</pre> | <pre>OVIS\Unknown\Unknown\DATA[00]</pre> | <pre>48</pre> | <pre>1</pre> | <pre>04 8B E9 C2</pre> | <pre>-116.771515 [float]</pre>
<pre>128</pre> | <pre>00000027</pre> | <pre>OVIS\Unknown\Unknown\DATA[00]</pre> | <pre>48</pre> | <pre>2</pre> | <pre>00 80 A9 C2</pre> | <pre>-84.750000 [float]</pre>
<pre>128</pre> | <pre>00000027</pre> | <pre>OVIS\Unknown\Unknown\DATA[00]</pre> | <pre>48</pre> | <pre>3</pre> | <pre>C1 70 2C 43</pre> | <pre>172.440445 [float]</pre>
<pre>128</pre> | <pre>00000027</pre> | <pre>OVIS\Unknown\Unknown\DATA[00]</pre> | <pre>48</pre> | <pre>4</pre> | <pre>06 15 F1 42</pre> | <pre>120.541061 [float]</pre>
<pre>128</pre> | <pre>00000027</pre> | <pre>OVIS\Unknown\Unknown\DATA[00]</pre> | <pre>48</pre> | <pre>5</pre> | <pre>00 80 D6 42</pre> | <pre>107.250000 [float]</pre>

**Comment by zilav** [comment]
Updated.

**Comment by fireundubh** [comment]
There are 6 floats per byte array. Do you think these are Position X/Y/Z and Rotation X/Y/Z?

**Comment by zilav** [comment]
Looks like object bounds for me.

**Comment by fireundubh** [comment]
That makes more sense, as they're not references. Totally forgot about OBND.
