### ISSUE TITLE
ECZNs Flag 

### ISSUE THREAD

**Issue by Karel2016** [TES5Edit/TES5Edit#319]
Encounter Zones are flagged with an < Unknown: 3 > Flag, This flag marks them as a settlement, and is only attached to Encounter Zones that are Settlements.

**Comment by Karel2016** [comment]
![settlement](https://cloud.githubusercontent.com/assets/16566845/12130330/2b8f0be8-b3cf-11e5-8d0a-3dce03e7438a.png)
![settlement2](https://cloud.githubusercontent.com/assets/16566845/12130331/2db7e96c-b3cf-11e5-82ae-c40032d09270.png)
![settlement3](https://cloud.githubusercontent.com/assets/16566845/12130332/2fbc3ea2-b3cf-11e5-84e1-e804625d355e.png)

**Comment by zilav** [comment]
Added it as "Settlement" flag for now.
