### ISSUE TITLE
Fo4Edit: NPC Level Flag Incorrect

### ISSUE THREAD

**Issue by Karel2016** [TES5Edit/TES5Edit#320]

**Comment by Karel2016** [comment]
Noticed this problem in NPCs, The Stamina Offset is actually the LEvel of the NPC, and the Flag marked as Level does not affect the level of the NPC at all.

![notworking](https://cloud.githubusercontent.com/assets/16566845/12143327/429dab52-b445-11e5-88ec-8b713bed2200.png)

**Comment by fireundubh** [comment]
The record used by @Karel2016 was `EncMinutemen08 [NPC_:001BF0C1]`. I spawned that actor at the start of the game and used GetLevel. I can confirm that "Stamina Offset" is Level, at least when the NPC has no other flags as above.

**Comment by zilav** [comment]
Updated.
