### ISSUE TITLE
FO4Edit: Cell PCMB Unknown and XCRI Unknown

### ISSUE THREAD

**Issue by Nverjos** [TES5Edit/TES5Edit#321]
PCMB-Unknown - Appears to operate like a boolean value controlling whether or not a cell loads the physics data for combined object meshes. Removal stops the game from loading _physics.nif file from meshes/precombined for that particular cell.

XCRI-Unknown - Contains the reference information for combined object meshes. Unsure about the first 8 bytes, however the rest breaks up into a list of combined mesh file names, after which starts a list of REF ID's for objects in that cell that get disabled and replaced with a combined mesh.

SanctuaryExt (cell dd60) for example: XCRI Field broke down.

1A 00 00 00 D0 03 00 00 - First 8, unsure what they control, different every cell, manipulating the data hasn't shown any significant or visible changes. 1A is however 26 and that's the number of combined mesh objects in this cell, perhaps Array setup.

6E 65 B8 01 6A 37 82 0A FB 94 5B 13 D1 CE 59 19 5F 09 92 1B 65 5F 47 1F AC F5 76 27 72 53 EA 2B A3 9D B3 32 17 0C AD 34 C9 AA 31 38 7F 12 B2 3B 7D 3B 2F 3E 6A 37 82 4A D1 CE 59 59 AC F5 76 67 72 53 EA 6B A3 9D B3 72 C9 AA 31 78 7D 3B 2F 7E D1 CE 59 99 AC F5 76 A7 72 53 EA AB A3 9D B3 B2 C9 AA 31 B8 AC F5 76 E7- List of all combined objects for that cell the first one being 6e 65 b8 01, which is mesh 0000dd60_01b8656e_oc.nif in meshes/precombined

Shortened this next snippit as it's a repeat of REF ID for Placed Object and Combined Object ID till end of field:
7F 3D 08 00 A3 9D B3 72 F5 3E 08 00 D1 CE 59 59 4C 33 05 00 AC F5 76 27

7f 3d 08 00 is ref id 00083d7f for placed object in the cell, the following bits are a3 9d b3 72 are the combined mesh that ref id belongs too, in this case 0000dd60_72b39da3_oc.nif

Then begins next ref id and combined object id and so on till all combined object references are accounted for in that cell.

Removal of the combined meshes from XCRI stops the game from loading combined meshes, however their collision data and physics is still present in game till toggled off with PCMB. PCMB will also toggle off the loading of combined meshes all together for a cell.

Sorry for the jumbled mess, hope any of that makes sense.
-Nver

**Comment by zilav** [comment]
Thanks, updated. Very valuable and interesting information.
The first 8 bytes are 2 integer counters for following arrays: meshes and references.
