### ISSUE TITLE
FO4Edit

### ISSUE THREAD

**Issue by DragoWhooves** [TES5Edit/TES5Edit#323]
would be possible to add a "deselect all" button on the mod chooser?
this is more if you want to work on one mod so you don't have to either deselect all of the others that you don't need manually

**Comment by fireundubh** [comment]
Right-click the list and click `Select None`.

**Comment by zilav** [comment]
If you want to load only a single mod and it's masters, just double-click on it.

**Comment by DragoWhooves** [comment]
@fireundubh thank you I did't know that you could do that, I guess that this can be closed then
