### ISSUE TITLE
FO4Edit: GLOB FNAM should have a dropdown for selecting the variable type

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#326]
The `FNAM` field should have a dropdown for selecting the variable type.

Currently, you have to use integers:

```Delphi
Ord('s'): Result := 'Short';   // Hex: 73; Int: 115
Ord('l'): Result := 'Long';    // Hex: 6C; Int: 108
Ord('f'): Result := 'Float';   // Hex: 66; Int: 102
Ord('b'): Result := 'Boolean'; // Hex: 62; Int:  98
```

I don't have these memorized, so what I do is convert string to hex to integer, which is a bit much for other folks, especially considering that you have to search the definitions to figure out which strings to convert.

The alternative is finding a `GLOB` record with the desired `FNAM` and copying that record to a new plugin.

**Comment by zilav** [comment]
Updated.
