### ISSUE TITLE
FO4Edit: Adding Combination from scratch doesn't add OBTF and FULL fields

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#332]
In `NPC_`, `WEAP`, and maybe other records, there's an `Unknown` subrecord structured like so:

```
Unknown
--> OBTE - Count
--> Combinations
-->--> Combination
-->-->--> OBTF - Boolean True
-->-->--> FULL - Name
-->-->--> OBTS - Object Mod Template Item
-->-->-->--> Parts A Count
-->-->-->--> Parts B Count
-->-->-->--> Unknown <dtByteArray>
-->-->-->--> Keywords
-->-->-->--> Unknown <dtByteArray>
-->-->-->--> Parts A
-->-->-->--> Parts B
--> STOP
```

When you add a `Combination`, what you get is this:

```
Unknown
--> OBTE
--> Combinations
-->--> Combination
-->-->--> OBTS
-->-->-->--> Parts A Count
-->-->-->--> Parts B Count
-->-->-->--> Unknown <dtByteArray>
-->-->-->--> Keywords
-->-->-->--> Unknown <dtByteArray>
-->-->-->--> Parts A
-->-->-->--> Parts B
--> STOP
```

The `OBTF` and `FULL` fields are missing.

While we're here, you also can't

* remove the first `Keyword` or `Part` if they're the only children, or
* unassign the `Keywords` and `Parts` elements, although they default to unassigned.

`Keywords` and `Parts` should probably be sorted, too.

**Comment by zilav** [comment]
Fixed.
