### ISSUE TITLE
FO4Edit: AMMO DNAM Unknown

### ISSUE THREAD

**Issue by isathar** [TES5Edit/TES5Edit#333]
The second Unknown in AMMO - DNAM appears to be the charge/condition value for charge-based ammo types (fusion core). If the ammo record contains the isPowerArmorBattery [KYWD:0005BDAA] keyword, the charge will be displayed in the inventory menu as a percentage. 

I'm not sure if the whole block is an int value or if it's only the first two bytes since there is no way (that I know of) besides using the ammo and checking the inventory to see its current charge. Using a large number that took up all 4 bytes did add a large amount of charges while I was testing.
I made some ammo variations with different charges to test, and it's working so far.

Example:
AmmoFusionCore "Fusion Core" [AMMO:00075FE4],
AmmoFusionCoreNoSteal "Fusion Core" [AMMO:001BBFCA]:

DNAM Unknown (2): F4 01 00 00 = 0x000001F4 = 500 (same amount as the Gatling Laser's capacity)

00 00 00 00 for all single-use and NPC-specific ammo.

**Comment by Sharlikran** [comment]
Updated
