### ISSUE TITLE
Tes5edit Compare & Copy CLoud Layer Alphas error

### ISSUE THREAD

**Issue by Mangaclub** [TES5Edit/TES5Edit#335]
I am trying to copy Values of the CLoud Layer Alphas in Tes5edit via Compare selected  and the "Copy to selected records" to different Weathers. The resoult is that tes5edit wont overwrite the values as expected but createing a new Cloud layer at the bottom with the values i wanted to copy.

**Comment by zilav** [comment]
Because it is an array and copying array elements means adding them to the destination. Select both records, right click, compare selected, drag&drop.
Or use Weather Editor script Ctrl+W, it also has some copy functions.
