### ISSUE TITLE
FO4Edit: Placed Objects Reference

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#336]
SCOL references need to be added to the list of expected references for the "Name - Base" field.

Currently, Check for Errors reports it as an error, which makes finding a problem in a mod like Spring Cleaning (i.e. mods with many Place Object changes) a huge pain in the ass.

**Comment by Sharlikran** [comment]
This is for TES5Edit of FO4Edit?

**Comment by VlitS** [comment]
FO4Edit

**Comment by zilav** [comment]
Fixed.
