### ISSUE TITLE
TES5Edit: Endorsement Pop-Up Causes the Program To Hang

### ISSUE THREAD

**Issue by leafonthewind7** [TES5Edit/TES5Edit#337]
Was in the middle of editing a plugin, and a pop-up message appears saying something along the lines of "You have been using this program for a while, please take the time to endorse this program on the Skyrim Nexus." The program then hangs, and was only closable through the task manager.

**Comment by zilav** [comment]
Fixed some time ago, it should not appear right in the middle of editing or dragging.
