### ISSUE TITLE
Feature Request: Multiline string editor with increased max length

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#340]
In `frmViewMain.pas` at lines 8139-8141:

```delphi
	// string editor
	else if not InputQuery('Edit Value', 'Please change the value:', EditValue) then
		Exit;
```

`InputQuery()` has a max length of 256 characters, which is too short for some strings (e.g., `TERM\UNAM`) and will result in truncation. With existing long strings, removing any characters means you won't be able to add any characters unless the length of the string is below 256 characters. Scripts also cannot bypass the max length and will generate truncated strings. (This subsequently makes writing a terminal menu editor kind of hard.)

`InputQuery()` also does not support multiline strings, although you can use a script to replace a character sequence (e.g., `<br>`) in a string with the respective decimal codes (e.g., `#13#10`) to produce newlines, but this is clunky.

Can you instead perhaps adapt `ViewElementsFrm.pas` to accept input, and multiline input, as a new form and call that form?

**Comment by zilav** [comment]
Why just not Shift+DblClick?

**Comment by fireundubh** [comment]
Ha! I didn't know about that, but I think that should be the default then.

`InputQuery()` shouldn't be used for editing strings unless you can somehow determine which fields accept multiline input.

**Comment by zilav** [comment]
Majority of fields are simple short values like FormIDs, integers, floats. InputQuery is fine for that. It was Elminster's decision to make xEdit hotkey driven without corresponding UI elements, and I got used to it. And I know a lot of people are too, especially those that started with TES4Edit modding many years ago.

I heard that Blender is also heavily hotkey oriented and you can't do much unless you know and remember them, so xEdit is definitely not unique in this design approach. All hotkeys are covered in Training Manual, but... well, we are living in the age where reading is not encouraged to say the least. I was actually thinking about implementing short startup tips during plugin selection that will cover usage of all hotkeys and menues, this is a common approach nowadays. Need to think more about details :)
