### ISSUE TITLE
FO4Edit: Assertion failure on trying to add Conditions to Menu Item element in TERM via script

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#341]
Affected path: `TERM\Menu Items\Menu Item\Conditions`

* Add() produces the assertion failure.
* ElementAssign(HighInteger) does not produce an error but also does not create the element.
* ElementAssign(LowInteger)  does not produce an error but also does not create the element.

> Assertion failure (D:\Projects\xEdit\wbImplementation.pas, line 13277)

**Comment by zilav** [comment]
```
function Process(e: IInterface): integer;
var
  item, conds: IInterface;
begin
  item := ElementByPath(e, 'Menu Items\Menu Item');
  conds := ElementAssign(item, 6, nil, False); // 6 is the index of Conditions in Menu Item
end;

```

**Comment by fireundubh** [comment]
Ah, I see. I forgot there were more options than just LowInteger and HighInteger. Thank you.

**Comment by fireundubh** [comment]
Got around to testing this.

`ElementAssign(item, 6, nil, False)` doesn't return the child "Condition" element.

**Comment by zilav** [comment]
ElementAssign() returns the element that's been added, in this case "Conditions" array.
