### ISSUE TITLE
Access violation when dragging-and-dropping VMAD properties in Compare mode

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#342]
> Access violation at address 007033E1 in module 'FO4Edit.exe'. Write of address 039204CF.

Dragging-and-dropping properties actually works though. It just produces that error most of the time.

edit: Although you do roll the dice on whether the plugin is corrupted.

**Comment by zilav** [comment]
That's why adding properties is disabled. Overwriting properties uses the same parts of code so it is unsafe either.

**Comment by fireundubh** [comment]
Well, after a lot more testing, corruption (i.e., the plugin is reduced to zero bytes) seems to only occur when using the "Copy to selected records" feature; otherwise, dragging-and-dropping properties works fine, except for the error prompt.

**Comment by eFrysTon** [comment]
@fireundubh I think all issues in this regard should be fixed in the current experimental version. I'll close the issue. Please test again and reopen if you still see any problems.
