### ISSUE TITLE
Record Decoding Improvement

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#344]
This should be valid for Fallout 3 and New Vegas. Unsure about previous or subsequent engine revisions.

It appears in the Navmesh records that NVDP (Navmesh Door Portal) is a pointer to the triangle to which the door portal is linked. The XNDP (Door Portal) of door references correlates this and contains the same triangle pointer.

**Comment by zilav** [comment]
I copied door triangle definition and check from TES5/FO4, navmeshes work the same way across all games. Even found few wrong triangle links in vanilla FNV with "Check for errors".
