### ISSUE TITLE
FO4Edit: NPC NAM4 "Unknown" = "Scale"

### ISSUE THREAD

**Issue by Supierce** [TES5Edit/TES5Edit#347]
Sets NPC size relative to default.

**Comment by zilav** [comment]
How is it different to "NAM6 - Height"?
Actually, regarding labels, we are waiting for CK to name unknown fields accordinly, so please open issues only if you have insight for unknown undecoded hex data.

**Comment by Supierce** [comment]
This is resolved in the latest xEdit version. Thanks!
