### ISSUE TITLE
TES5Edit inner manual script: Renumber FormID error

### ISSUE THREAD

**Issue by PUOjACKz** [TES5Edit/TES5Edit#348]
Hi, I was manually renumbering the FormIDs of Temptress/Vixen mod, in order to merge it in a batch .esp, while I have find out that using the script on the "Head part" section of the mod, causes a wrong renumbering on the other referenced sections. In other words, before renumbering various entries are "referenced" to other records. After running the script, none of such references get involved with the records changed, causing the .esp to CTD while loading the main game.

**Comment by zilav** [comment]
Please create a test plugin with few records to replicate the issue and steps to reproduce.

**Comment by PUOjACKz** [comment]
I'm unable to produce a test plugin useful for this issue. I'm going to close the ticket.
