### ISSUE TITLE
FO4Edit: dialogue topics

### ISSUE THREAD

**Issue by pavelhoral** [TES5Edit/TES5Edit#350]
I am pretty sure about these fields:

* Action/PTOP - Positive Reaction Topic
* Action/NTOP - Negative Reaction Topic
* Action/NETO - Neutral Reaction Topic
* Action/QTOP - Question Reaction Topic

I am trying to figure out how the dialogues work. Let me know if it makes sense updating this issue with any additional information or if it is not useful and you are just waiting for the Creation Kit.

**Comment by zilav** [comment]
Yes, at this point we are waiting for CK to give fields proper labels. But thanks anyway.
