### ISSUE TITLE
Update Keywords for Settlement Mods

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#352]
```Delphi
{
  Hotkey: F8
}
{
  This script will add keywords to the keywords list of selected weapons.
  Almost no practical use, just a demo.
}
unit UserScript;

var
  slKeywords: TStringList;

function Initialize: integer;
begin
  // keywords to add
  slKeywords := TStringList.Create;
  slKeywords.Add('03000AAC'); // WeapMaterialSteel
  // instead can also load keywords from a text file (one keyword per line)
  // ProgramPath - path were xEdit exe file is
  // DataPath    - path to game's Data folder
  // slKeywords.LoadFromFile(ProgramPath + 'keywords.txt');
end;
    
function Process(e: IInterface): integer;
var
  kwda, k: IInterface;
  i, j, c: integer;
  exists: boolean;
begin
  Result := 0;

  // apply only to weapons
  if Signature(e) <> 'COBJ' then
    Exit;

  // get existing keywords list or add a new
  kwda := ElementBySignature(e, 'FNAM');
  if not Assigned(kwda) then
    kwda := Add(e, 'FNAM', True);
    
  // no keywords subrecord (it must exist) - terminate script
  if not Assigned(kwda) then begin
    AddMessage('No keywords subrecord in ' + Name(e));
    Result := 1;
    Exit;
  end;

  
  for j := 0 to slKeywords.Count - 1 do begin // iterate through each FormID in slKeywords
	  // check if our keyword already exists
	  exists := false;
      AddMessage('False...');
	  for i := 0 to ElementCount(kwda) - 1 do begin // iterate through each FormID in FNAM

        AddMessage('The if...' + IntToHex(GetLoadOrderFormID(LinksTo(ElementByIndex(kwda, i))), 8));
        AddMessage('The if...' + slKeywords[j]);
        if IntToHex(GetLoadOrderFormID(LinksTo(ElementByIndex(kwda, i))), 8) = slKeywords[j] then begin
          AddMessage('True...');
          exists := true;
        end;
		
		AddMessage('Begin...');
		// skip the rest of code in loop if keyword exists
		if exists then begin
		
			AddMessage('Before...');
			// CK likes to save empty KWDA with only a single NULL form, use it if so
			if (ElementCount(kwda) = 1) and (GetNativeValue(ElementByIndex(kwda, 0)) = 0) then begin
  			  AddMessage('Set It ...');
			  SetEditValue(ElementByIndex(kwda, 0), slKeywords[j])
			end else begin
			  // add a new keyword at the end of list
			  // container, index, element, aOnlySK
			  k := ElementByIndex(kwda, i);
			  if Assigned(k) then begin
				AddMessage('Removing...');
				Remove(k);
				Exit;
			  end;
				AddMessage('Can''t add keyword to ' + Name(e));
			end;

		end;		

	end;
	
  end;
  
  // update KSIZ keywords count
  // if not ElementExists(e, 'KSIZ') then
  //  Add(e, 'KSIZ', True);
  // SetElementNativeValues(e, 'KSIZ', ElementCount(kwda));
  
  AddMessage('Processed: ' + Name(e));

end;

function Finalize: integer;
begin
  slKeywords.Free;
end;

end.
```

Since you wrote the script it works to add a FormID indicated.  I can't remove one.

SetEditValue(k, slKeywords[i]); sets the keyword and according to the wiki it is element : IwbElement , value : string.  Why is there no DeleteEditValue or RemoveEditValue?

Does IndexOf get the formid of slKeywords[i] so I can RemoveByIndex?

**Comment by Sharlikran** [comment]
@matortheeternal maybe I should make two separate scripts one for COBJ and one for ARTO?

**Comment by Sharlikran** [comment]
```Delphi
{
  Hotkey: F8
}
{
  This script will remove keywords to the keywords list of selected weapons.
  Almost no practical use, just a demo.
}
unit UserScript;

var
  slKeywords: TStringList;

function Initialize: integer;
begin
  // keywords to add
  slKeywords := TStringList.Create;
  slKeywords.Add('00118F5B'); // VendorItemWeapon
  // instead can also load keywords from a text file (one keyword per line)
  // ProgramPath - path were xEdit exe file is
  // DataPath    - path to game's Data folder
  // slKeywords.LoadFromFile(ProgramPath + 'keywords.txt');
end;
    
function Process(e: IInterface): integer;
var
  kwda, k: IInterface;
  i, j: integer;
  exists: boolean;
begin
  Result := 0;

  // apply only to weapons
  if Signature(e) <> 'COBJ' then
    Exit;

  // get existing keywords list or add a new
  kwda := ElementBySignature(e, 'FNAM');
  if not Assigned(kwda) then
    kwda := Add(e, 'FNAM', True);
    
  // no keywords subrecord (it must exist) - terminate script
  if not Assigned(kwda) then begin
    AddMessage('No keywords subrecord in ' + Name(e));
    Result := 1;
    Exit;
  end;

  // iterate through additional keywords
  for i := 0 to slKeywords.Count - 1 do begin
  
    // check if our keyword already exists
    exists := false;
    for j := 0 to ElementCount(kwda) - 1 do
      if IntToHex(GetNativeValue(ElementByIndex(kwda, j)), 8) = slKeywords[i] then begin
        exists := true;
        Break;
      end;
    AddMessage('here 1');
    // skip the rest of code in loop if keyword exists
    if exists then Begin
    
		// CK likes to save empty KWDA with only a single NULL form, use it if so
		// if (ElementCount(kwda) = 1) and (GetNativeValue(ElementByIndex(kwda, 0)) = 0) then
		//  SetEditValue(ElementByIndex(kwda, 0), slKeywords[i])
		//else 
		begin
		  // add a new keyword at the end of list
		  // container, index, element, aOnlySK
          AddMessage('here 2');
		  k := ElementAssign(kwda, HighInteger, nil, False);
		  SetEditValue(ElementBySignature(k, 'KYWD'), slKeywords[i]);
		  if Assigned(k) then begin
			AddMessage('Can''t add keyword to ' + Name(e));
			Remove(k);
			Exit;
		  end;
		  AddMessage('here 3');
		end;

	end;
  
  end;
  
  // update KSIZ keywords count
  // if not ElementExists(e, 'KSIZ') then
  //  Add(e, 'KSIZ', True);
  // SetElementNativeValues(e, 'KSIZ', ElementCount(kwda));
  
  AddMessage('Processed: ' + Name(e));

end;

function Finalize: integer;
begin
  slKeywords.Free;
end;

end.
```

Since you wrote the script it works to add a FormID indicated.  I can't remove one.

SetEditValue(k, slKeywords[i]); sets the keyword and according to the wiki it is element : IwbElement , value : string.  Why is there no DeleteEditValue or RemoveEditValue?

Does IndexOf get the formid of slKeywords[i] so I can RemoveByIndex?

**Comment by zilav** [comment]
Remove(k)

**Comment by Sharlikran** [comment]
I updated my post.  When I run that it doesn't work.  Nothing is removed.

WorkshopRecipeFilterResource02Power03Lights04CeilingLights "Ceiling Lights" [KYWD:03000C1C]

**Comment by Sharlikran** [comment]
IntToHex(GetNativeValue(ElementByIndex(kwda, i)), 8) returns 01000AAC but I want 03000AAC.  

The wiki says that GetNativeValue needs an IwbElement and that GetEditValue needs an IwbElement.  So why do I get a type mismatch with IntToHex(GetEditValue (ElementByIndex(kwda, i)), 8)?

**Comment by zilav** [comment]
Because GetEditValue() returns string which you try pass into IntToHex() function that expects an integer. To get load order corrected FormID, you must get the actual record first, then get it's load order

IntToHex(GetLoadOrderFormID(LinksTo(ElementByIndex(kwda, i))), 8)

**Comment by Sharlikran** [comment]
In my defense when I read the wiki and finally noticed it was returning a string, I did try StrToHex...  :P

**Comment by Sharlikran** [comment]
Okay I updated my post.  It is working much better but I am still missing something.  Is it because of how I change the loop to iterate through the count of slKeywords and the the count of KYWD entries?

[Apply Script done]  Processed Records: 1, Elapsed Time: 00:00
Applying script...
False...
The if...00118F5B
The if...03000AAC
Begin...
The if...03000AAC
The if...03000AAC
True...
Begin...
Before...
Removing...
[Apply Script done]  Processed Records: 1, Elapsed Time: 00:00

The text just tells me where the script is for debugging.  The FormID isn't removed.  Is there anything else I need to change?

**Comment by Sharlikran** [comment]
Wait I tried ```ElementByIndex(kwda, i)``` and I updated my code.  Starting at the comment ```// add a new keyword at the end of list``` is that correct? Is there any code there that doesn't need to be because of my changes?

**Comment by fireundubh** [comment]
I uploaded my "Keymaster" script to: [/fireundubh/xedit-scripts/tree/master/all](/fireundubh/xedit-scripts/tree/master/all)

Keymaster allows you to use .csv files to:

* execute a global find and replace on keywords,
* add specific keywords to specific records, and/or
* delete specific keywords from specific records.

You can run this script on a single record, or hundreds of records simultaneously.

1. Copy Keymaster.pas and the Keymaster folder to the Edit Scripts directory.
2. Read the comments in Keymaster.pas.
3. Configure the .csv files in the Keymaster directory as needed.
4. Select all of the records you want to modify in xEdit and apply the script.
5. When prompted, enter the shared path to, or signature of, the Keywords parent element. The prompt will accept an indexed path as well.

This script does everything Sharlikran's script is meant to do. It works with all record types and any keywords parent element, but you have to set up the .csv files, and you need dubhFunctions and mteFunctions. I wrote it for Sharlikran to use and modify.

**Comment by Sharlikran** [comment]
Is this the correct version of [dubhFunctions.pas](https://github.com/TES5Edit/xEditScripts/blob/master/Scripts/dubhFunctions.pas)

**Comment by fireundubh** [comment]
This one is: [/fireundubh/xedit-scripts/blob/master/lib/dubhFunctions.pas](/fireundubh/xedit-scripts/blob/master/lib/dubhFunctions.pas).

**Comment by Sharlikran** [comment]
I skimmed through the keymaster but didn't see it.

0400081D=00249F27

Which is which?  Fine 0400081D and replace with 00249F27?

**Comment by Sharlikran** [comment]
// ----------------------------------------------------------------------------------------------------------------------------
// lsKeywordsToReplace.csv Structure: name=value
// - Name: Form ID of keyword to find
// - Value: Form ID of keyword to replace
// ----------------------------------------------------------------------------------------------------------------------------
// NOTE: This function is a global find and replace.
// ----------------------------------------------------------------------------------------------------------------------------
I saw that of course

**Comment by Sharlikran** [comment]
oh wait sill me I see it now

**Comment by Sharlikran** [comment]
Can I put comments in the file like

0400081A=00249F2B // Concrete Walls

**Comment by Sharlikran** [comment]
It want's a path I have no idea what that means

**Comment by Sharlikran** [comment]
Well I typed FNAM and just said woo hoo see what it does, it seemed to work.  I have no idea what a path is.  Like I just put FNAM but should it be "COBJ \ FNAM" ?

**Comment by fireundubh** [comment]
`FNAM` is the path to (and signature of) the top-level parent Keywords element in a COBJ record.

`Menu Items\Menu Item\FNAM` would be the path to the parent Keywords element in a TERM record, if each menu item had a keywords field.

I think all Keywords fields are top-level elements, however, but just in case I'm wrong, you can use a path. If I'm not wrong, then the script can be simplified further, you can get rid of the query, and you can add definitions like:

```
if Signature(e) = 'COBJ' then
	aParent := ElementBySignature(e, 'FNAM')
else if Signature(e) = 'KWDA') then
	aParent := ElementBySignature(e, 'KWDA');
```

**Comment by Sharlikran** [comment]
Okay that's must be why it worked.  I hate the Keywords the people chose for this file.  I was going to change two Campfires so I added that to the csv file and it changed all the Misc lights to campfires.  So I guess some things are easier to change like the concrete prefabs, but others have to be done by hand :(

**Comment by Sharlikran** [comment]
That is pretty cool though.  I appreciate the file.

**Comment by fireundubh** [comment]
You can edit your comments to update them. ;)

**Comment by Sharlikran** [comment]
Hmmmm I think there is something else wrong

0400081D=00249F27
04000819=00249F28
0400081C=00249F29
04000821=00249F2A
0400081A=00249F2B
0400086A=00249FB1

So that is my file so far.  I click on the the 1C plugin in my load order.  When I run the script 

See 04 is SettlementKeywords.esm so I want to find the references to that since it's also a master of the file I applied the script to.

workshop_co_WorkshopCeilingFanLight01 [COBJ:0003A2A2]
  -- Replaced keyword [KYWD:001D2A91] with [KYWD:0400B041]

Why did it change that FormID?

**Comment by Sharlikran** [comment]
No that was an old entry for the campfire I didn't save the csv file.  My bad,

**Comment by fireundubh** [comment]
By the way, if you hadn't noticed already, each .csv uses a different delimiter.

- The find and replace .csv uses the = sign.
- The add keyword .csv uses the + sign.
- The delete keyword .csv uses the - sign.

The script will use all .csv files unless you delete or empty the ones you're not using.

**Comment by Sharlikran** [comment]
I'm also noticing that with some of the settlement patches they have a patch like OCD-SK Patch.  It has COBJ, FLST, KYWD records in it so users can't use it or it breaks the menus since I fixed them all.  Is there a default xEdit script that says replace from file [15] OCD-SK Patch.esp into 16 OCDecorator.esp all the KYWD in FNAM of COBJ?  Kind of the restore names from masters file?

I ask because I have 5 values in those key files and it seems to be working if I delete the entries in the other files.  Now to add hundreds of values might take a while.  I kind wish I could just copy what the author did for the patch...  Or wait...  Hmmm.... I have to look at those files.  I wonder which ones have FLST and KYWD but if I remove those Top Groups would the rest still be in tact since the FormID is from another master.

**Comment by Sharlikran** [comment]
Do you use Wrye Flash with fallout fireundubh?  If so the 307.10 on the nexus handles the new load order with the * asterisk.

**Comment by zilav** [comment]
Open again if this is still a problem.
