### ISSUE TITLE
Feature Request: Reorder plugins in Master/Plugin Selection dialog

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#353]
Any chance that a feature can be added where you can reorder plugins in the Master/Plugin Selection dialog?

![sshot-166](https://cloud.githubusercontent.com/assets/1261664/14856265/435757dc-0c4c-11e6-855c-17d9b46612c0.png)

You could reorder plugins prior to loading them -- the order would be temporary unless you clicked the Save button.

Or, you could reorder plugins and then just click Save & Exit.

So, you'd have three buttons -- Save, Save & Exit, and Load (OK) -- plus Up and Down arrow icons for reordering, Ctrl+Up and Ctrl+Down hotkeys, as well as drag-and-drop-to-reorder functionality. Closing the dialog would exit as normal but without saving a new order.

**Comment by Hugues92** [comment]
No. XEdit is not a mod manager. The order has to be the same as the one used by the runtime.

So if xEdit doesn't show the plugins in the same order as how the engine interpret the work of your Mod manager then xEdit should be corrected and not the other way around.

**Comment by Hugues92** [comment]
I did not really intended to cut that short and close the issue, sorry.

**Comment by fireundubh** [comment]
For Fallout 4, the order is determined by plugins.txt, which xEdit already loads, reads, and parses. It's only a small step from there to being able to reorder plugins prior to loading and processing the plugins.

By the way, Fallout 4 is a game, but it is also now a mod manager. Things can be more than one thing. ;)

**Comment by Hugues92** [comment]
No it is not, and we have no intention of making it one.

**Comment by fireundubh** [comment]
I don't know what you're referencing.

- That plugin order is determined by plugins.txt?
- That going from reading to also writing is a small step?
- That Fallout 4 is an entire game and a mod manager?

Also, I didn't ask for xEdit to "become a mod manager." I asked for a feature that would allow you to reorder plugins, which is similar but not quite the same. Switching back and forth between multiple programs, or in this case, loading up Fallout 4 to adjust load order or to change masters is a pain. It doesn't make any sense to not implement plugin reordering at the plugin selection stage, especially if/when the framework for doing that is already there. (You would know best about that.)

**Comment by zilav** [comment]
I'm against that too. While it can be useful very occasionally for experienced users, it'll be detrimental for general public usage. People will start mentioning on forums and in guides how to move plugins around in xEdit when cleaning/merging/patching for whatever reasons and I can already foresee how horrible it'll end up.

**Comment by fireundubh** [comment]
Ugh! General public usage...
