### ISSUE TITLE
Handling unexpected references

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#354]
While running wbCopyElementToFile(), this error stopped my script:

> Found a PMIS reference, expected: REFR [this error can be traced to 0000E30D]

We need a way to handle these situations. There's try-except, of course, but I'd rather have xEdit copy the element, stripped of the unexpected reference, and throw a warning rather than a fatal error. Is a native solution possible?

**Comment by zilav** [comment]
This is intended and will fix itself when we'll update all definitions.

**Comment by zilav** [comment]
Updated.
