### ISSUE TITLE
External Exception C0FB007E

### ISSUE THREAD

**Issue by knowidee** [TES5Edit/TES5Edit#355]
used to use this perfectly (Thanks by the way, excellent Application) & Upon a ReInstall of My Windows I can No longer use the app!

 

I receive : External Exception C0FB007E error

 

Bug Report :

date/time          : 2016-05-02, 16:42:51, 554ms
computer name      : DAW-GMR-MEDIA
user name          : DAW <admin>
registered owner   : 
operating system   : Windows 10 x64 build 10586
system language    : English
system up time     : 4 hours 29 minutes
program up time    : 857 milliseconds
processors         : 6x AMD Phenom™ II X6 1100T Processor
physical memory    : 5746/8190 MB (free/total)
free disk space    : (C:) 99.83 GB
display mode       : 1920x1080, 32 bit
process id         : $af8
allocated memory   : 45.08 MB
largest free block : 1.99 GB
executable         : FO4Edit.exe
exec. date/time    : 2016-04-21 13:29
version            : 3.1.3.0
compiled with      : Delphi XE
madExcept version  : 4.0.12
callstack crc      : $3ff3c5cb, $9b1a6345, $bd5e2d87
exception number   : 1
exception class    : EExternalException
exception message  : External exception C0FB007E.

main thread ($b58):
7500dad8 +048 KERNELBASE.dll                       RaiseException
0040bbb4 +0fe FO4Edit.exe    System       1044  +0 @_delayLoadHelper

-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=
**_004f50a5 +005 FO4Edit.exe    UxTheme               dll

Could this be the issue (Its a modified Theme DLL to allow for Dark / shades of Grey Windows Themes)

- - THIS CAUSED NO ISSUE ON PREVIOUS WIN 10 BUILD - -_**
-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--=-=-=-=--=-=--= 

0050e2c6 +08e FO4Edit.exe    Controls              TWinControl.WMPaint
00509024 +2d4 FO4Edit.exe    Controls              TControl.WndProc
0050d8e8 +568 FO4Edit.exe    Controls              TWinControl.WndProc
0050cf88 +02c FO4Edit.exe    Controls              TWinControl.MainWndProc
004c71cc +014 FO4Edit.exe    Classes               StdWndProc
77c08e54 +034 ntdll.dll                            KiUserCallbackDispatcher
757083ed +03d user32.dll                           UpdateWindow
756f69d2 +092 user32.dll                           CallWindowProcW
0050d9e8 +0d8 FO4Edit.exe    Controls              TWinControl.DefaultHandler
00509024 +2d4 FO4Edit.exe    Controls              TControl.WndProc
0050d8e8 +568 FO4Edit.exe    Controls              TWinControl.WndProc
0050cf88 +02c FO4Edit.exe    Controls              TWinControl.MainWndProc
004c71cc +014 FO4Edit.exe    Classes               StdWndProc
77c08e54 +034 ntdll.dll                            KiUserCallbackDispatcher
756f5ede +13e user32.dll                           SendMessageW
0057666c +01c FO4Edit.exe    ComCtrls              TCustomTabControl.SetTabIndex
0057835e +00a FO4Edit.exe    ComCtrls              TPageControl.SetTabIndex
00577d18 +068 FO4Edit.exe    ComCtrls              TPageControl.SetActivePage
00bbfef7 +0eb FO4Edit.exe    frmViewMain  3371 +16 TfrmMain.DoInit
00bedccd +025 FO4Edit.exe    frmViewMain 13096  +6 TfrmMain.tmrStartupTimer
00556317 +00f FO4Edit.exe    ExtCtrls              TTimer.Timer
005561fb +02b FO4Edit.exe    ExtCtrls              TTimer.WndProc
004c71cc +014 FO4Edit.exe    Classes               StdWndProc
756f62fb +00b user32.dll                           DispatchMessageW
005b44f7 +0f3 FO4Edit.exe    Forms                 TApplication.ProcessMessage
005b453a +00a FO4Edit.exe    Forms                 TApplication.HandleMessage
005b4865 +0c9 FO4Edit.exe    Forms                 TApplication.Run
00c08268 +068 FO4Edit.exe    TES5Edit       86  +8 initialization
76e438f2 +022 KERNEL32.DLL                         BaseThreadInitThunk

thread $2c8:
76e438f2 +22 KERNEL32.DLL  BaseThreadInitThunk

thread $16c4:
76e438f2 +22 KERNEL32.DLL  BaseThreadInitThunk

thread $16f0:
76e438f2 +22 KERNEL32.DLL  BaseThreadInitThunk

thread $acc (TWorkerThread):
74ffe1cb +8b KERNELBASE.dll                      WaitForSingleObjectEx
74ffe12d +0d KERNELBASE.dll                      WaitForSingleObject
005d45ad +19 FO4Edit.exe    VirtualTrees 6308 +3 TWorkerThread.Execute
00474e47 +2b FO4Edit.exe    madExcept            HookedTThreadExecute
004c4506 +42 FO4Edit.exe    Classes              ThreadProc
00407588 +28 FO4Edit.exe    System       1044 +0 ThreadWrapper
00474d29 +0d FO4Edit.exe    madExcept            CallThreadProcSafe
00474d93 +37 FO4Edit.exe    madExcept            ThreadExceptFrame
76e438f2 +22 KERNEL32.DLL                        BaseThreadInitThunk
>> created by main thread ($b58) at:
005d4495 +19 FO4Edit.exe    VirtualTrees 6251 +1 TWorkerThread.Create

thread $1268:
76e438f2 +22 KERNEL32.DLL  BaseThreadInitThunk

thread $2d8:
76e438f2 +22 KERNEL32.DLL  BaseThreadInitThunk

thread $1370:
7500a4e4 +104 KERNELBASE.dll           WaitForMultipleObjectsEx
00474d29 +00d FO4Edit.exe    madExcept CallThreadProcSafe
00474d93 +037 FO4Edit.exe    madExcept ThreadExceptFrame
76e438f2 +022 KERNEL32.DLL             BaseThreadInitThunk
>> created by main thread ($b58) at:
7533493b +000 combase.dll

thread $11ec:
76e438f2 +22 KERNEL32.DLL  BaseThreadInitThunk

thread $3c8:
76e438f2 +22 KERNEL32.DLL  BaseThreadInitThunk
 

 

 

If Anyone Can Help it'd Be Appricated , Thanks

**Comment by zilav** [comment]
I replied you on nexus already. This is an external exception which occures outside of xEdit and caused by your system. You have to find out and fix yourself, we can't do anything on our part.
