### ISSUE TITLE
FO4 Definition Updates

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#356]
Please keep this open.
- AECH updated in commit: e091edb0b3f9e6036cf9e9730320dae456a88af7
- BNDS updated in commit: e091edb0b3f9e6036cf9e9730320dae456a88af7

[Update details snipped.]

**Comment by fireundubh** [comment]
# AECH

This one is interesting, but I don't know how to implement it.

There are three effect types:

Effect Type | Hex
--- | ---
BSOverdrive | `BE 04 48 86`
BSStateVariableFilter | `7F 5F 57 EF`
BSDelayEffect | `4F 7B 83 18`

Each effect type has unique effect data:

Effect Type | Effect Data | Type of Value
--- | --- | ---
BSOverdrive | Input Gain | Float
BSOverdrive | Output Gain | Float
BSOverdrive | Lower Threshold | Float
BSOverdrive | Upper Threshold | Float
BSStateVariableFilter | Center Freq | Float
BSStateVariableFilter | Q Value | Float
BSStateVariableFilter | Filter Mode | Dropdown (Band Pass, High Pass, Low Pass, Notch)
BSDelayEffect | Delay MS | Integer
BSDelayEffect | Feedback % | Float
BSDelayEffect | Wet Mix % | Float

The first 4 bytes of DNAM is a boolean that indicates whether the effect is installed in the effect chain.

So, you have sort of a base template that looks like so:

```
  wbRecord(AECH, 'Audio Effect Chain', [
    wbEDID,
    wbRArray('Effects',
      wbRStruct('Effect', [
        wbUnknown(KNAM),
        wbStruct(DNAM, 'Effect Data', [
          wbInteger('Enabled', itU32, wbEnum(['False', 'True'])),
          wbFloat('Value'),
          wbFloat('Value'),
          wbFloat('Value')
        ], cpNormal, False, nil, 16)
      ], [])
    )
  ]);
```

**Comment by fireundubh** [comment]
# AORU\AOR2

Object Rule is called Attraction Rule.

Index | Value
--- | ---
0 | Radius
1 | Min Delay
2 | Max Delay
3 | (Checkboxes) Requires Line of Sight, Combat Target

# ASTP

DATA is actually just a checkbox for Family Association.

# CAMS\DATA

Index | Value
--- | ---
9 | Location Spring
10 | Target Spring
11 | Rotation Offset X
12 | Rotation Offset Y
13 | Rotation Offset Z

# CLFM

CNAM[3] = Remapping Index (radio button; if not 3F, then use Raw Color)

Unknown 2 flag = Extended LUT

# CPTH\DATA

Index | Value
--- | ---
4 | Default, Must Have Camera Shots, Dynamic Camera Times
5 | Disable, Must Have Camera Shots, Dynamic Camera Times
6 | Shot List, Must Have Camera Shots, Dynamic Camera Times
64 | Default, Must Have Camera Shots, Randomize Paths
65 | Disable, Must Have Camera Shots, Randomize Paths
66 | Shot List, Must Have Camera Shots, Randomize Paths
68 | Default, Must Have Camera Shots, Dynamic Camera Times, Randomize Paths
69 | Disable, Must Have Camera Shots, Dynamic Camera Times, Randomize Paths
70 | Shot List, Must Have Camera Shots, Dynamic Camera Times, Randomize Paths
132 | Default, Dynamic Camera Times
133 | Disable, Dynamic Camera Times
134 | Shot List, Dynamic Camera Times
192 | Default, Randomize Paths
193 | Disable, Randomize Paths
194 | Shot List, Randomize Paths
196 | Default, Dynamic Camera Times, Randomize Paths
197 | Disable, Dynamic Camera Times, Randomize Paths
198 | Shot List, Dynamic Camera Times, Randomize Paths

# DEBR

Models\Model\DATA\Flags is a single checkbox.

# DMGT

There are two dropdowns:

- Resistance: populated with AVIFs
- Spell: populated with SPELs

# ECZN

1. When an NPC_ Owner is used, Required Rank is not available.
2. When a FACT Owner is used, Required Rank is available.

# EFSH\DNAM

Index | Value
--- | ---
23 | Holes - Alpha Test Animation - Start Time
24 | Holes - Alpha Test Animation - End Time
25 | Holes - Alpha Test Animation - Start Val
26 | Holes - Alpha Test Animation - End Val
30 | ???
31 | Color Key 1 - Scale
32 | Color Key 2 - Scale
33 | Color Key 3 - Scale
34 | Color Key 1 - Time
35 | Color Key 2 - Time
36 | Color Key 3 - Time
38 | Texture Scale - U
39 | Texture Scale - V

**Comment by fireundubh** [comment]
# REFR

XPDD: Projected Decal
* Width Scale: Float ([0] 4 bytes)
* Height Scale: Float ([1] 4 bytes)
* Uses Box Primitive: Checkbox/Boolean (???)

XBSD: Spline
* Slack: Float ([0] 4 bytes)
* Thickness: Float ([1] 4 bytes)
* Wind - Detached End: Checkbox/Boolean (???)

XAMC: Extra - Ammo Count (Float)

XASP: Acoustic Restriction

**Comment by fireundubh** [comment]
# AMDL

- Cone of fire - Min angle
- Cone of fire - Max angle
- Cone of fire - Increase per shot
- Cone of fire - Decrease per sec
- Cone of fire - Decrease delay MS
- Cone of fire - Sneak multiplier
- Recoil - Diminish spring force
- Recoil - Diminish sights mult
- Recoil - Max per shot
- Recoil - Min per shot
- Recoil - Hip mult
- Runaway - Recoil shots
- Recoil - Arc
- Recoil - Arc rotate
- Cone of fire - Iron Sights Multiplier
- Stability - Base Stability

**Comment by zilav** [comment]
I finished with updating definitions more or less. Can you please better outline XPDD and XBSD in REFR and check on vanilla records dump? Right now I made them hex arrays.
Also don't know what to do with OVIS and NOCM records, no idea how to name them and modify in CK.

**Comment by fireundubh** [comment]
Here's XBSD.

```
    wbStruct(XBSD, 'Spline', [
      wbFloat('Slack'),
      wbFloat('Thickness'),
      wbFloat('Unknown'), // not shown in editor
      wbFloat('Unknown'), // not shown in editor
      wbFloat('Unknown'), // not shown in editor
      // flags or bool? there's only one checkbox.
      wbInteger('Wind - Detached End', itU32, wbBoolEnum)
      //wbInteger('Flags', itU32, wbFlags(['Wind - Detached End']))
    ]),
```

**Comment by fireundubh** [comment]
Here's XPDD.

```
    wbStruct(XPDD, 'Projected Decal', [
      wbFloat('Width Scale'),
      wbFloat('Height Scale')
      // Uses Box Primitive Checkbox does the following:
      // 1. "Rounds" above floats (probably due to floating point precision)  [DIRTY EDITS?]
      // 2. "Rounds" DATA\Position floats (probably due to floating point precision)  [DIRTY EDITS?]
      // 3. Creates an XPRM subrecord (this is the "Primitive" tab in the editor)
      // 4. Fills out Primitive data:
      //    4a. Primitive type: Box
      //    4b. Collision layer: XTRI subrecord = 15
      //    4c. Bounds (XYZ): 256.0, 215.0, 256.0
      //    4d. Color (RGB): 0, 128, 128
      //    4e. Unknown: 0.4
    ]),
```

**Comment by zilav** [comment]
Thanks!

**Comment by zilav** [comment]
Hmm cheking for errors in DLCCoast.esm Cells group produces errors for that XBSD definition, the last flag is probably not an itU32 or at a bad position.

**Comment by fireundubh** [comment]
>  the last flag is probably not an itU32 or at a bad position.

It's smaller. One byte.

![Screenshot](http://i.imgur.com/6un3zif.png)

**Comment by fireundubh** [comment]
> Also don't know what to do with OVIS and NOCM records, no idea how to name them and modify in CK.

I received a message from Ziegfelding:

> Those are unrelated to precombine and previs data. They look to hold data for two systems I'm not overly familiar with. Some sort of obstacle manager (maybe precalced NIF data for obstacle cutting navmesh?) and an object visibility manager which I think AI may use for line of sight. Whatever they are though they have no effect on precalc data.

So, you can call them:

* OVIS: Object Visibility Manager
* NOCM: NavMesh Obstacle Manager

But they don't seem to be editable with the CK.

**Comment by zilav** [comment]
Thx.

**Comment by eFrysTon** [comment]
Everything listed here seems to have been acted upon already, so I assume the issue can be closed?

**Comment by zilav** [comment]
Yes.
