### ISSUE TITLE
Error: No strings file for Istring ID ...

### ISSUE THREAD

**Issue by Dominator56** [TES5Edit/TES5Edit#359]
Okay, so first of all, I'm very sorry if this has been addressed before, but here is my issue:

![Issue](http://puu.sh/p01s8/4c531135b6.PNG)

As you can see, FO4Edit cannot find the strings for pretty much everything.
I tried making a mod that changed some weapons, and the weapon name was 

> Error: No strings file for Istring ID blabla.

My game is in french and I believe this is the reason why it cannot find the strings.

I can provide the strings file if needed.

BTW, is there a guide somewhere to compile TES5Edit/FO4Edit? I would be really interested to know.

**Comment by zilav** [comment]
Right Click -> Other -> Localization
Or add -l:fr command line parameter to shortcut.

**Comment by Dominator56** [comment]
Thanks alot, works like a charm.
Also, would love to know how to compile TES5Edit. :dancer: 

I will close this.

**Comment by zilav** [comment]
Install Jedi VCL library
Install VirtualEditTree component (bundled with xEdit)
Select the "Light" build mode if you don't have DevExpress components
Compile xEdit
