### ISSUE TITLE
FO3/FNV Definition Updates

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#360]
REFR

XSRF - Special Rendering Flags

02 = Imposter
04 = Use Full Shader in LOD

XSRD - Special Rendering Data

Values still undecoded

**Comment by zilav** [comment]
I need the size in bytes for those.

**Comment by RoyBatty64** [comment]
both are a dword (4 bytes)

**Comment by zilav** [comment]
Updated.
