### ISSUE TITLE
Problem with Combinations: FO4Edit

### ISSUE THREAD

**Issue by midnightvoyager** [TES5Edit/TES5Edit#362]
https://github.com/TES5Edit/TES5Edit/issues/332

I found this while searching for help with this particular issue. The problem I have is just as described. I try to make a new Combination and it does not give me OBTF or FULL. This means I also can't copy over a combination WITH those fields in place. I can't find any way to add those fields to a new Combination either.

**Comment by fireundubh** [comment]
Does #332 describe your issue?

**Comment by midnightvoyager** [comment]
Sorry, that's what I meant to link. I don't know why it linked 356. It does,

**Comment by zilav** [comment]
Right now you can drag&drop a combination with needed elements form other records.

**Comment by midnightvoyager** [comment]
I'm having trouble with that though. If there's no empty space for it, it will overwrite another record that I don't want to overwrite. If I add a new record to overwrite, it refuses to overwrite that because it lacks those two fields. Is there a way around that?

**Comment by zilav** [comment]
Drag over the Object Template root node, the one you click to add new entries.

**Comment by midnightvoyager** [comment]
Ah, thank you, that worked like a charm.
