### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#363]
Could you guys add 00000007 and 00000014 to the exe dat's (the player and the player ref)

This is needed for checking references to the player and the player ref.

**Comment by zilav** [comment]
Player [NPC_:00000007] is a valid existing record in all Beth games inside the game master file.
00000014 is a hardcoded FormID in xEdit, if it is missing as a valid record in some places then list them, I'll add it there.

**Comment by RoyBatty64** [comment]
My bad with 00000007, forgot it was in the master.

00000014 however is not anywhere in the esm's, so it should be in the .dat file so you can view references to the form. For E.X. enable parents set to the player. Currently I had to make a hacky esp to check those, this is something xEdit can do that GECK cannot do.

**Comment by zilav** [comment]
As I said 00000014 is handled as a hardcoded form in xEdit executable. Don't know why Elminster made it so originally, maybe it happened before .dat files addition. You can always add it to your own .dat file yourself along with other missing records if any.

**Comment by RoyBatty64** [comment]
And how can I add it? I don't know the format of this file, it's not exactly like a regular plugin from what I see.
I had to hack the esp I use with a hex editor.
That addition would certainly benefit others and also I don't see where it would cause any harm?

**Comment by zilav** [comment]
This is an ordinary plugin. Copy to Data folder and rename to esp, modify, copy and rename back.

**Comment by RoyBatty64** [comment]
Managed to hack this in with a hex editor because xEdit won't let you do that with the player's ref id.
Building reference info for them doesn't work. The plugin I made works in GECK however and I can check the usage info. Seems like a bug because there is thousands of references to that id.

**Comment by eFrysTon** [comment]
Already implemented...
