### ISSUE TITLE
LVLI - ONAM subrecord does not acknowledge capitalization changes

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#365]
Changing the text in the ONAM (Override Name) in a leveled list entry does not acknowledge a change in capitalization. This results in the record getting marked as an ITM when it really isn't.

See image:

![capitalizationerror](https://cloud.githubusercontent.com/assets/1762652/16114358/a24b2818-3375-11e6-8da3-afe347065d89.jpg)

**Comment by Hugues92** [comment]
I made that one case sensitive. I think are at least two cases of ONAM as string that could be change also. Anyway, I'll need to test at home with the English strings.

**Comment by Hugues92** [comment]
The alternate texts in DOOR are displayed to the users ?

**Comment by Arthmoor** [comment]
Yes, those are user visible too.

**Comment by eFrysTon** [comment]
I assume this issue is long resolved and the issue just didn't get closed?

**Comment by Arthmoor** [comment]
I'll double check that when I get back to the PC later.

**Comment by Arthmoor** [comment]
Yep, somewhere along the way this did get fixed.
