### ISSUE TITLE
TES5Edit not saving changes made to mods

### ISSUE THREAD

**Issue by Sexyowl** [TES5Edit/TES5Edit#366]
I installed TES5Edit for use with Skyrim. I have used it before and this is the first time I am getting the following message:
**Cannot create file "C:\Users\SexyOwl\AppData\Local\Skyrim\Plugins.tes5viewsettings". Access is denied.**
The file in question is there but has no records in it. I have uninstalled and re-installed the program with the same results. I use MO but the issue occurs whether run through MO or not.
As a consequence (I believe) any changes made to mod records etc within TES5Edit are not being saved. The application would not close unless I do so within the pop-up window which informs me of the bug and back-up plugins are not created. I am attaching a .txt file containing the bug report.
[TES5Edit_bugreport.txt](https://github.com/TES5Edit/TES5Edit/files/330606/TES5Edit_bugreport.txt)

**Comment by zilav** [comment]
Fix access writes for TES5Edit. This is the problem with your system and not a bug.
Cannot create file "C:\Users\SexyOwl\AppData\Local\Skyrim\Plugins.tes5viewsettings". Access is denied
