### ISSUE TITLE
[FO4] DESC fields that should be case sensitive.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#369]
OMOD record DESC (and FULL) subrecord should be set to case sensitive.

**Comment by Hugues92** [comment]
FULL is already case sensitive.

**Comment by Arthmoor** [comment]
Ok, cool. Wasn't sure but figured I'd mention it anyway.

**Comment by Arthmoor** [comment]
Looks like this issue got fixed somewhere along the way and can be closed now.
