### ISSUE TITLE
CTD with No Explanation

### ISSUE THREAD

**Issue by FoxPhoenix** [TES5Edit/TES5Edit#372]
I'm at a complete loss on this one.

-Used 3.1.2 without issue for several weeks
-Suddenly gave me what I'll describe as a CTD (Launched TES5Edit but then immediately hid it with no way to bring it forward)
-Ensured my TES5Edit was launching with Admin Privileges
-Still CTD
-Uninstalled and reinstalled with new 3.1.3 version
-Try to start up
-Still CTD
-Elevate to Admin Privileges
-Still CTD

I have absolutely no idea what has happened or why exactly it won't work for me. I've read all the posts and looked through the bug reports and no one else has reported it. I don't know if I can recreate it and I don't know how to generate a Log to see what's going on behind the scenes.

**Comment by FoxPhoenix** [comment]
![wtf is going on](https://cloud.githubusercontent.com/assets/20530977/16939943/b73099d0-4d4b-11e6-8502-32ff220ec573.png)

**Comment by FoxPhoenix** [comment]
![wtf is going on](https://cloud.githubusercontent.com/assets/20530977/16939962/e58b4adc-4d4b-11e6-868a-cbe2acdad8f9.png)

**Comment by zilav** [comment]
Hold Shift while starting TES5Edit, looks like it saved position outside of visible area from the previous run which happens in multimonitor setups. Then post what is written in the log.

**Comment by FoxPhoenix** [comment]
Thanks. No log was written but it showed back up.
