### ISSUE TITLE
Bug with Prefix renaming

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#373]
When copying multiple records as new records and replacing the prefix, if one of the forms has the whole name specified as a prefix such as a leveled list, that form will not be renamed.

To reproduce: Use FalloutNV.esm, select the Leveled Lists LootAmmo308 LootAmmo308Double LootAmmo308Half and select copy as new record into a new plugin, when prompted to remove the Prefix enter LootAmmo308 , use anything for Prefix to add and none for suffix. Only the Double and Half entries will be renamed.

**Comment by zilav** [comment]
It is not a bug, there is a check to not perform any renaming if EditorID is empty after removing prefix. I suppose it is done on purpose if user entered wrong prefix to remove which causes original EditorID to be fully lost.
