### ISSUE TITLE
Static NVNM 

### ISSUE THREAD

**Issue by robboten** [TES5Edit/TES5Edit#374]
Don't know how to do things with repositories and stuff so I'll leave this here.

Under statics Navmesh Geometry where it says flags, the first there is actually Height (float). Have tried and confirmed this. Like this (wbDefinitionsFO4.pas):  

else
    wbNVNM := wbStruct(NVNM, 'Navmesh Geometry', [
      wbInteger('Unknown', itU32),
      wbByteArray('Unknown', 4),
      wbFormIDCk('Parent Worldspace', [WRLD, NULL]),
      wbFormIDCk('Parent Cell', [CELL]),
      wbArray('Vertices', wbStruct('Vertex', [
        wbFloat('X'),
        wbFloat('Y'),
        wbFloat('Z')
      ]), -1),
      wbArray('Triangles', wbStruct('Triangle', [
        wbInteger('Vertex 0', itS16),
        wbInteger('Vertex 1', itS16),
        wbInteger('Vertex 2', itS16),
        wbInteger('Edge 0-1', itS16),
        wbInteger('Edge 1-2', itS16),
        wbInteger('Edge 2-0', itS16),

```
   wbFloat('Height'),              //Default = Max
```

Last part of the NVNM block struct is: 

 wbArray('Waypoints',  wbStruct('Coords', [  
          wbFloat('X'),
          wbFloat('Y'),
          wbFloat('Z'),
          wbInteger('Unknown', itU32),     //could be triangle or edge ref
          wbInteger('Unknown', itU16)      //always 0?
          ]), -1),

//        wbStruct(NVGD, 'NavMesh Grid', [
        wbStruct('NavMesh Grid', [
          wbInteger('NavMeshGrid Divisor', itU32),
          wbFloat('Max X Distance'),
          wbFloat('Max Y Distance'),
          wbFloat('Min X'),
          wbFloat('Min Y'),
          wbFloat('Min Z'),
          wbFloat('Max X'),
          wbFloat('Max Y'),
          wbFloat('Max Z'),
          wbArray('Cells', wbArray('Cell', wbInteger('Triangle', itS16), -1))
        ])

The 3 blocks in between these I'm still not 100% sure of. Think one is cover edges and flags for it. But it's nested somehow.

**Comment by zilav** [comment]
Thanks, I updated Triangles. But for the rest I need the exact definitions. However there are no FormIDs in that part (on static meshes), so it doesn't really matter for xEdit to work properly. The full decoding is only useful if you want to create navmehses for statics outside of CK for some reason.
