### ISSUE TITLE
Automatic script execution

### ISSUE THREAD

**Issue by philippejer** [TES5Edit/TES5Edit#376]
Hello,

First, thanks for this awesome tool!

I have a small request regarding the automatic script execution: I have made a very crude script that dumps all records in some sort of JSON format and it would help me a lot to be able to batch it from the command line like this:

```
TES5Edit.exe -script:myscript.pas -module:mymodule.esp
```

Currently unless I'm mistaken (very possible) it seems the "-script" switch makes it run on all dependent modules (like skyrim.esm)?

**Comment by zilav** [comment]
When you run in a "script" mode, you should control yourself what to process. For example this will handle only weapon records in a single plugin

```
function Initialize: integer;
var
  i: integer;
  f, g, r: IInterface;
begin
  for i := 0 to FileCount - 1 do begin
    f := FileByIndex(i);
    if not SameText(GetFileName(f), 'mymodule.esp') then
      Continue;
    g := GroupBySignature(f, 'WEAP');
    for j := 0 to ElementCount(g) - 1 do begin
      r := ElementByIndex(g, j);
      AddMessage('Processing weapon ' + Name(r));
    end;
  end;
end;

```
If you want to pull something from command line like plugin(s) to process, you have access to ParamCount and ParamStr standard Delphi functions to work with a command line.
Treat "script" mode like "load plugins for me and I'll do the rest myself my own way".

**Comment by philippejer** [comment]
That's exactly what I needed, thanks a lot for the pointers and the quick reply (and sorry for the basic questions I hadn't even realized you could pick records outside of Process(), I should have studied the existing scripts better ;) )

Jeremy

**Comment by vensko** [comment]
I use MO2 profiles, where are only enable files, that need to be patched.

**Comment by zilav** [comment]
@vensko MO is not supported.

**Comment by vensko** [comment]
@zilav That was just a workaround for the issue.

**Comment by zilav** [comment]
There is no issue here, xEdit works as intended.
