### ISSUE TITLE
Improved Record Definition

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#379]
Engine FO3/NV

Package, Conditions, value in Unused field after Run On field is a reference, dword.

http://i.imgur.com/iZPuNYT.jpg

**Comment by Hugues92** [comment]
How did you create those conditions? The original did not have any there.

**Comment by RoyBatty64** [comment]
Uhm yes they are there, I created nothing. I have at least 11 broken packages in TTW because of this.

http://i.imgur.com/KtQRVWP.jpg

Untouched vanilla Fallout3.esm

**Comment by Hugues92** [comment]
It look like I am having an issue with the FO3 GECK (and another with the FNV one also).
At least I discovered you can type a FormID in the GECK filter box.

Anyway there is no way to fill this field with the GECK on a GetStage condition when the RunOn is not an explicit reference. I would say it is a bug in the GECK not to clear that field when entering conditions.

**Comment by RoyBatty64** [comment]
Hrm strange that they point to references that directly correlate. Also strange that the engine is reading and reporting an error about these fields if they are not used. Bug in both now I think, since you pointed it out. Still they might be causing some issues I have noticed, so I will 0 them out.

Also yes, the search box can find just about anything in the plugins.
