### ISSUE TITLE
BUG: CELL Data - Flags

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#385]
## Summary

It appears that for Skyrim SE (I don't know about Skyrim) there are 8 bit and 16 bit DATA fields for CELL Flags.  I made a file with the CK and named it TestCellChange.esp.  When I look at the exact size of the Data filed in the plugin provided (TestCellChange.esp) the size is a 16 bit integer.  If I search for the FormIDs listed in TES5CON_Skyrim.txt the DATA Field is an 8 bit integer.  

If I load the plugin created with the CK (TestCellChange.esp) and change XCWT to Something Else with SSEEdit  then it will be a 32 bit integer like in the file TestCellChange_32.zip.  If I load that file into the CK it will truncate the size to a 16 bit integer.  The result file is attached as TestCellChange_16.zip which is how the CK dealt with the size difference.

I am not sure which record, if any has a 32 bit integer for the DATA in CELL.  However, commit d398ba82bd65d4058ed19fb34b0ab8f9d810d4a6 is expanding the size to 32 bits.  Is it possible to read 1, 2, or 4 bytes, and then not expand it and write out 1, 2, or 4 bytes just like xEdit read it?  Do you know of any 32 bit DATA fields in CELL from Skyrim.esm, Update.esm, or the DLC?

## CK Error
`````Auto
MASTERFILE: ===========================================================
FORMS: Chunk size 4 too big in chunk DATA_ID in form CELL_ID (00016D72).
Max size is 2, data truncated to "#".
`````

### Files for reference

[TES5CON_Skyrim.txt](https://github.com/TES5Edit/TES5Edit/files/546934/TES5CON_Skyrim.txt)
[TestCellChange.zip](https://github.com/TES5Edit/TES5Edit/files/546936/TestCellChange.zip)
[TestCellChange_32.zip](https://github.com/TES5Edit/TES5Edit/files/546954/TestCellChange_32.zip)
[TestCellChange_16.zip](https://github.com/TES5Edit/TES5Edit/files/546969/TestCellChange_16.zip)

#### Arthmoor's Screenshot

![cellchange](https://cloud.githubusercontent.com/assets/1912426/19633781/fde605ee-9969-11e6-80f4-d8cc0d9d747b.jpg)

**Comment by zilav** [comment]
Ok I'll make it 16 bits.
I assumed 32 bits flags based on your first report of unused data in cell flags.

**Comment by zilav** [comment]
Reverted back to 16 bits CELL flags.

**Comment by Sharlikran** [comment]
Thanks
