### ISSUE TITLE
Form Version 44 Decoding

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#387]
Form version 44 decoding and issues resulting from the new record format.  Please add any comments or inconsistencies to this issue.  It is acceptable to not use this data in xEdit until Behtesda makes changes.  However, please track the information for reference and verification.

 - REFR 'Placed Object'

**Comment by Sharlikran** [comment]
Error: record REFR contains unexpected (or out of order) subrecord XRNK 4B4E5258
Errors were found in: [REFR:11001834] (places SpellTomeFlamesDUPLICATE001j "Spell Tome: Improved Flames" [BOOK:11000D6E] in GRUP Cell Temporary Children of WinterholdCollegeArchMageQuarters "Arch-Mage's Quarters" [CELL:000CAB92])
Contained subrecords: NAME XOWN XRGD XRNK DATA

**Comment by Sharlikran** [comment]
Error: record REFR contains unexpected (or out of order) subrecord XRNK 4B4E5258
Errors were found in: [REFR:11001834] (places SpellTomeFlamesDUPLICATE001j "Spell Tome: Improved Flames" [BOOK:11000D6E] in GRUP Cell Temporary Children of WinterholdCollegeArchMageQuarters "Arch-Mage's Quarters" [CELL:000CAB92])
Contained subrecords: NAME XOWN XRGD XRNK DATA

**Comment by zilav** [comment]
Normally XRNK should follow XOWN. Maybe better to just split Ownership structure into separate subrecords, this is not the first time I see such issues.

**Comment by Sharlikran** [comment]
What I don't like is this is the same as MHDT in that the CK puts it there when it wants to.  I added a new reference of the exact same book causing the error and there wasn't any rag doll data added.

**Comment by zilav** [comment]
I added XRGD to be skipped when between XOWN and XRNK, but if you discover more similar cases, then we should just split it up.

**Comment by eFrysTon** [comment]
Is there anything more that needs to be done or is this issue resolved?

**Comment by zilav** [comment]
Noone reported any issues with it so far after my update, so resolved I think.
