### ISSUE TITLE
[Bug] Navmesh References

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#391]
In Fallout 3 and NV mode Navmeshes should be added to the reference pool for scripts because they can be enabled and disabled via script.

**Comment by zilav** [comment]
What records and fields exactly?

**Comment by RoyBatty64** [comment]
navi records in cells/worldspaces

**Comment by zilav** [comment]
I mean what should be able to reference them?

**Comment by RoyBatty64** [comment]
Any script or embedded result script. script, dialogue, terminal, package, quest stage, there's at least one other I can't remember what it is...

**Comment by zilav** [comment]
SCRO in SCPT already allows any type of record to be set.

**Comment by RoyBatty64** [comment]
Open Fallout3.esm in FO3Edit, build references. Put BE880 in the FormID Box and search, select references tab. RCExBridge1SCRIPT with FormID 72021 should show up here but does not.

**Comment by zilav** [comment]
FormID is hardcoded inside the script and is not referenced via script's local variables as it should be nirnally, xEdit doesn't analyze scripts source code and has no idea what's inside.

**Comment by RoyBatty64** [comment]
I see, the records have no SCRO. Which means Navmeshes cannot be References. Apologies zilav, someone fed me false information about that.
