### ISSUE TITLE
[Bug] Fallout 3/NV Package Flags

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#392]
The "Enable Fallout Behavior" flag is missing.

http://imgur.com/8G8Irp6

Test Plugins https://drive.google.com/open?id=0ByyDLPnmgtNVSkk4eW9lQklDWms

Binary compare of the plugins shows a single bit difference when this flag is checked/unchecked.

**Comment by zilav** [comment]
I can see "Skip fallout behaviour" flag in PKDT\General Flags
It probably has the opposite meaning, there are some flags that when checked are actually removing some bit, hence the inverted flag name.

**Comment by RoyBatty64** [comment]
Yes it must have the opposite meaning but that is confusing because GECK has no "Skip Fallout Behavior" in it.

**Comment by zilav** [comment]
Well I can rename it to "Not Enable Fallout Behaviour".
xEdit doesn't show flags that don't physically exist even though they are displayed as "checked" in official editors.

**Comment by RoyBatty64** [comment]
It does exist.

bool (0) = Enable (all) Fallout Behavior 
bool (1) = Use individual flags for behavior

The flag is represented incorrectly. It's a parent to the other flags.

**Comment by zilav** [comment]
Bool 0 means the flag is not set and there is nothing to display. All I can do is rename the label when this flag bit is actually set,

**Comment by RoyBatty64** [comment]
No, 0 means the flag IS set. It's inverted.

**Comment by zilav** [comment]
I know it is inverted, but xEdit only displays flags that are set.

**Comment by RoyBatty64** [comment]
Well nothing to be done about that then I guess, since the UI has been programmed with that assumption.
Use Fallout Behavior Flags would make sense.

**Comment by zilav** [comment]
Well, nothing to change then.
