### ISSUE TITLE
Loading plugins outside of the data directory

### ISSUE THREAD

**Issue by matortheeternal** [TES5Edit/TES5Edit#395]
Issue when loading plugins outside of the data directory with load order/master file detection.

**Comment by matortheeternal** [comment]
Hmm...  I'm getting mixed results actually.  It seems to work sometimes.

**Comment by zilav** [comment]
xEdit loads plugins by absolute path if provided.

**Comment by matortheeternal** [comment]
> xEdit loads plugins by absolute path if provided.

I think there may be an issue with master detection, however.  Sometimes I get a report that Skyrim.esm must be loaded before the plugin because it's a master, when Skyrim.esm IS loaded before the plugin, but the plugin is not located in the data directory.  I'll see if I can learn more about the issue.

**Comment by zilav** [comment]
I fixed that https://github.com/TES5Edit/TES5Edit/commit/ce0a6e926836b42a2a7006b3bf562767498c9c37
No idea what causes that, probably some 3rd party apps like MO. Never had such issues on my PC.

**Comment by matortheeternal** [comment]
Ah, that's a recent commit.  I'll pull that into ModDump and see if that fixes my issue.

**Comment by matortheeternal** [comment]
It doesn't work at all now.  Getting the following in ModAnalyzer:

```
== LOADING PLUGINS ==
Loading Skyrim.esm...
[C:\SteamLibrary\steamapps\common\Skyrim\data\Skyrim.esm]
Loading Update.esm...
[C:\SteamLibrary\steamapps\common\Skyrim\data\Update.esm]
Loading ETaC - RESOURCES.esm...
[C:\SteamLibrary\steamapps\common\Skyrim\data\ETaC - RESOURCES.esm]
Loading ETaC - Rorikstead.esp...
[C:\SteamLibrary\steamapps\common\Skyrim\data\ETaC - Rorikstead.esp]
Loading Dawnguard.esm...
[C:\SteamLibrary\steamapps\common\Skyrim\data\Dawnguard.esm]
Loading HearthFires.esm...
[C:\SteamLibrary\steamapps\common\Skyrim\data\HearthFires.esm]
Loading Dragonborn.esm...
[C:\SteamLibrary\steamapps\common\Skyrim\data\Dragonborn.esm]
Loading Alternate Start - Live Another Life.esp...
[C:\SteamLibrary\steamapps\common\Skyrim\data\Alternate Start - Live Another Life.esp]
Loading ETaC - Rorikstead AS-LAL Patch.esp...
[C:\SteamLibrary\steamapps\common\Skyrim\Tools\ModAnalyzer2\extracted\ETaC - Modular - Patches-13608-14-2-8.7z\01 Alternate Start LAL - Rorikstead\ETaC - Rorikstead AS-LAL Patch.esp]
Exception loading C:\SteamLibrary\steamapps\common\Skyrim\Tools\ModAnalyzer2\extracted\ETaC - Modular - Patches-13608-14-2-8.7z\01 Alternate Start LAL - Rorikstead\ETaC - Rorikstead AS-LAL Patch.esp
EOSError => System Error.  Code: 2.
The system cannot find the file specified
```

The file is present at the specified path, the path item ending in .7z is a directory - not an archive.

**Comment by zilav** [comment]
Debug and check where and why.

**Comment by eFrysTon** [comment]
Is there still a problem here or can this issue be closed?

**Comment by matortheeternal** [comment]
I never got this issue resolved, but I do think the issue is stale.  I can come up with a simple limited test to demonstrate the problem if it's still occurring if that would help.  @eFrysTon

**Comment by eFrysTon** [comment]
any testing you do should be based on the dev-elminster branch. If you have a reproducable testcase that I can debug, I can have a look...

**Comment by matortheeternal** [comment]
OK, I'll see what I can do.  Crazy busy at the moment so it may take me a few days to get something put together.  :+1:
