### ISSUE TITLE
Exception when adding a master causes file header to be clobbered and CleanMasters assertion failure

### ISSUE THREAD

**Issue by matortheeternal** [TES5Edit/TES5Edit#396]
Smash calls CleanMasters on generated patch plugins after patching is completed.  CleanMasters is raising [this assertion error](https://github.com/matortheeternal/smash/blob/master/lib/xedit/wbImplementation.pas#L2203) for [one of my users](https://gist.github.com/anonymous/a4ce9dd866eed989eb099a17017ef8e9) when generating a smashed patch for a Skyrim load order.

Under what circumstances would this assertion fail?  Smash does not manually remove master file elements from the File Header, but [it does add A LOT of masters](https://github.com/matortheeternal/smash/blob/master/frontend/msSmash.pas#L94-L128) to it for the purpose of generating the patch.  The [master adding code](https://github.com/matortheeternal/smash/blob/master/lib/mte/mteBase.pas#L697-L706) is pretty straightforward, and the masters should be sorted per plugin load order.

**Comment by matortheeternal** [comment]
Actually, I think I may see the problem...

**Comment by matortheeternal** [comment]
I think I've found the issue.  Smash was swallowing any exception during the add masters operation without reporting it, and continuing to smash the plugins.  The exception is actually occurring when we are adding masters, which means that things could be pretty clobbered in the plugin's file header by the time `CleanMasters` comes along.

**Comment by matortheeternal** [comment]
Here's what that code would look like:

```pascal
// wbImplementation.pas, @procedure TwbFile.AddMasters(aMasters: TStrings);
    try
      AddMaster(aMasters[i]);
    except
      on x: Exception do begin
        Rec.Remove;
        raise x;
      end;
    end;
```

**Comment by zilav** [comment]
There are at least 4 exceptions that can occure before master is added, and another bunch after for various reasons but at the point where removing new master entry is too late. This won't work.
Also exception during addition of masters is indication that something has been done wrong before that point. You can apply that patch in your local copy if it really helps in your particular case, but definitely not going into the main branch.

**Comment by matortheeternal** [comment]
OK, was just a thought.  The cause of the issue was indeed an issue in the user's load order.
