### ISSUE TITLE
FO4Edit: Hardcoded DAT Update

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#399]
I noticed there were some unknown AVIF references, so I updated the hardcoded .dat.

**Version:**
Fallout 4 v1.8.7

**Process:**
1. AVIF records were duplicated with the CK into a new plugin. EDID, AVFL, and NAM1 remained intact.
2. Form IDs and EDIDs were copied from the CK as a name-value pair list using SysExporter.
3. Using a script to process the list, the Form IDs were changed accordingly.
4. Using a script, the records were pared down to only AVIF records without masters.

**Attached:**
[Fallout4.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.zip](https://github.com/TES5Edit/TES5Edit/files/711162/Fallout4.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.zip)

**Comment by zilav** [comment]
Thanks!
Not sure when the new version will be out though.

**Comment by Hugues92** [comment]
Uploaded to the repository.
