### ISSUE TITLE
Copying forms to new plugin sets Version Control Master FormID to 0

### ISSUE THREAD

**Issue by Marcurios** [TES5Edit/TES5Edit#402]
Hi,

Like the title says, when copying forms to new plugin, Version Control Master FormID info in form headers gets lost (set to 0), resulting in no longer being able to use Version Control anymore, cause when merging new esp's into the new file, VC starts bashing forms corrupting the plugin for use with Version Control.

I understand that this can't be fixed internally, but maybe provide a script that has this funtionality along with xedit ?
So that when i use compare function i can transfer Version Control Master FormID from old plugin into new one ?
Maybe a checkbox in the options menu ?

**Comment by zilav** [comment]
This is done on purpose because official editor does the same - when creating or modifying the existing forms, version control info is nulled. I got PM from Roy about such script, so will resolve that in private.

**Comment by Marcurios** [comment]
I can understand why you didn't bother with it, cause there is no way for you to know what the VCMID must be if multiple plugins get merged with xedit.
But your answer isn't correct, VC never nullifies this info, it never did with me, so that must have been a bug if you encountered that. Nullifying this info results in VC bashing forms, corrupting the esm file.

But i found a workaround, so it doesn't matter, i can safely work with both programs withhout the need for the VCMID.

**Comment by zilav** [comment]
Offcial editor and VC are different kind of systems even if VC is a part of it. Editor itself when working on plugins nullifies VC info in modified and new forms. My answer is correct.

**Comment by Marcurios** [comment]
in esp files you're right GECK does that indeed, esm files merged with VC get merge id's.

but it isn't a real problem, we'll manage a script that can repair those VCMID's

**Comment by Marcurios** [comment]
Thanks for the script Zilav, you're the master !
