### ISSUE TITLE
[Feature Request] Filter

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#403]
When filtering by Base Record Signature, and option to filter by formid of the record type.

 Useful for filtering by base record types which have no way to be filtered. Examples are room bounds, collision markers, xmarkers and so on. Also useful for isolating instances of containers which have no name defined.

**Comment by zilav** [comment]
That's the reason why I added scripted filtering http://pastebin.com/raw/uMWSq3AD

**Comment by RoyBatty64** [comment]
The scripted filtering system is of course awesome.

That little feature seems like it should be there in the UI by default since it can already do so by editorid, and it would be quicker and easier for users.

**Comment by zilav** [comment]
I uploaded new build on afkmods, you'll find details there.
