### ISSUE TITLE
Bizzare Issue with TESVEdit and an empty Strings folder

### ISSUE THREAD

**Issue by Ratione** [TES5Edit/TES5Edit#407]
Whenever I launch TESVEdit from Mod Organizer with a Strings folder included in any of my mods, even when that folder is empty, I get this: 

Fatal: Error loading plugin list: <EAccessViolation: Access violation at address 70A0F26D in module 'MSVCR120.dll'. Read of address 01328000>

And Loot refuses to load aswell. I dont know if this is an xEdit problem, or what is going on, but if i include even an empty strings folder when trying to use xEdit, I get that error. That same folder in the skyrim/data dir produces no error. IDK whats going on.

**Comment by Ratione** [comment]
For the record, this includes making a mod that *only* contains an empty strings folder, and trying to run the aforementioned programs.

**Comment by zilav** [comment]
xEdit doesn't use MSVCR (Microsoft Visual C++ Runtime Library) because it is written using different language and software. But MO is written in C++ and does use it, so this is likely an MO issue.
