### ISSUE TITLE
Double Click Behavior

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#408]
Would make double click behavior edit by default, opening up an uneditable window is pretty useless when you can ctrl+c a field to copy it. Slow clicking to edit liike in windows file explorer can cramp the workflow a lot.

**Comment by zilav** [comment]
I suppose Elminster wanted to differentiate the viewing and editing modes to prevent occasional modifications from users hence the addition of big yellow warning window too. Don't want to change that logic, but I can add that as an option which will be off by default, or maybe just tie it to the existing IknowWhatImDoing switch.

**Comment by RoyBatty64** [comment]
Yes please, that would be great.

**Comment by zilav** [comment]
Implemented c79c77194551683ac60a63ee199bf06e46d80072
