### ISSUE TITLE
Check box behavior

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#409]
Sometimes you can missclick a checkbox and set/unset it which immediately closes the selection window. Any dialogue which has the checkbox list is affected by this. This is undesirable behavior.

**Comment by zilav** [comment]
How can you missclick the double click? :)

I use it myself all the time and don't want to remove that feature. Maybe your mouse if broken and produces double clicks which is a common problem for old used mouses.

**Comment by RoyBatty64** [comment]
No the mouse isn't broken, I said I missclick sometimes. What would be ideal is being able to shift and ctrl select the list like in the main tree view for updating forms, and not using the same thing as the plugin selection dialogue. Not sure how difficult that would be though, or if you could add some quicker way to select many forms while rejecting others.

**Comment by zilav** [comment]
If right click menu options for selection are not enough, you can simply create your own plugins.txt files and pass them in command line so xEdit will automatically select predefined plugins
`-P:"C:\xEdit\TTWSelection.txt"`

**Comment by RoyBatty64** [comment]
You didn't read what I said, you reused this menu for the updating subsequent references when renumbering a base form. This can be hundreds or even thousands of checkbox clicks. The plugin selection menu is fine.

**Comment by zilav** [comment]
Implemented 76d35f329674a5ee37b11823417fd1724c9e3a74
