### ISSUE TITLE
Static Collection Ordering

### ISSUE THREAD

**Issue by robboten** [TES5Edit/TES5Edit#410]
The SCOL parts should be an ordered list since the order is of importance when exporting the SCOLs. The last item selected turns into the pivot for the whole generated mesh. As it is now it reorders itself based on name if I'm correct. That is a bit weird in this regard. I hope u can fix this since it would make it a lot easier to make correct scols for me (and hopefully others).

**Comment by zilav** [comment]
Made them unsorted a94833dc4fc8cf22a771c5e0b40e6f4cb6c16810
