### ISSUE TITLE
[00:01:39] (ERROR) Load: "ArmorKeywords.esm" requires master "DLCRobot.esm" to be loaded before it.

### ISSUE THREAD

**Issue by Seipherwood** [TES5Edit/TES5Edit#421]
Using ProgramVersion 2.3.1.0 and still getting this error.

**Comment by zilav** [comment]
The latest released xEdit version is 3.2.1

**Comment by Freso** [comment]
I'm guessing that's what they meant, as any 2.x.x version of xEdit would not have had support for Fallout 4 at all. (Also, where is xEdit 3.2.1 available at? I see 3.2(.0) as the latest release on https://github.com/TES5Edit/TES5Edit/releases )

**Comment by InsanePlumber** [comment]
@Freso 
https://afkmods.iguanadons.net/index.php?/topic/3750-wipz-tes5edit/

**Comment by Sharlikran** [comment]
Current release is [SSEEdit-6557c88](https://github.com/TES5Edit/TES5Edit/releases/tag/SSEEdit-6557c88)
