### ISSUE TITLE
[FO4] Freeze when applying filter for cleaning on AGOMBz.esp

### ISSUE THREAD

**Issue by Freso** [TES5Edit/TES5Edit#423]
When trying to "Apply Filter for Cleaning" with [AGOMBz.esp](http://www.nexusmods.com/fallout4/mods/25762) in the list, FO4Edit (3.2) will freeze. I'm thinking this might be related to the mod not providing string files, as FO4Edit also shows a bunch of "<Error: No strings file for lstring ID 0000000E>".

I'm not entirely sure how string files actually work (or are supposed to work), but according to the mod author it should work fine, as the string files are provided by the DLC .esm:

> FO4Edit, Wrye Bash not see string files packed in archives for esp. For DLC (esm) sees. This is not a bug in mod. This is a limited programs functionality.

**Comment by InsanePlumber** [comment]
For me "Apply Filter for Cleaning" on Attackers - Get Off My Buildzone works without problems. ( xEdit ver. 3.2.1 ee96388 )
Download xEdit ver. 3.2.1 from AFKMods forum.

**Comment by zilav** [comment]
Kaspersky is known to cause such issues, maybe other antivirus/antimalware software does that too.

**Comment by Freso** [comment]
I will try with 3.2.1 and report back. (I don't have Kaspersky or any other antivirus software installed, besides what Win10 has natively.)

**Comment by Sharlikran** [comment]
Current version https://github.com/TES5Edit/TES5Edit/releases/tag/SSEEdit-6557c88 should not have that issue.

**Comment by Freso** [comment]
Using FO4Edit v3.2.3q EXTRA EXPERIMENTAL special build by @eFrysTon it didn't freeze applying the cleaning filter on AGOMBz.esp, so I reckon whatever caused this has been fixed along the way.
