### ISSUE TITLE
Wanted: TES5Dump

### ISSUE THREAD

**Issue by Iloei** [TES5Edit/TES5Edit#429]
(motivation and context for this request in parenthesis here.)

(Ideally, it would be nice to be able to dump a .esp / .esm to text, and then rebuild the orginal file from the data there. That would allow some simple automation tools to be built to work on mods. But that probably requires a level of effort beyond what anyone wants to invest.)

(Still, even without that, some things would be much much easier if we could dump the .esp to file and work with that. For example, when looking at a large quest record in TES5Edit, you wind up having to scroll through a huge batch of material and you can't even copy and paste it out for searching purposes, and the built in search is quite limited. Or, at least, I do not know how to do these things....)

Having TES5Dump (or instructions how to build it - though that might be difficult for someone like me that does not know how to obtain the build dependencies...) would make some mod debugging work possible which currently seems hard.

So: please, could we get TES5Dump for download (here, or somewhere pointed to from here)?

**Comment by Hugues92** [comment]
I did some work for that as scripts available in some of the alternate branches. Those do not reliably reconstruct a plugin though, they can only update existing elements not create or delete one, so they are not usable as is.

**Comment by Sharlikran** [comment]
All files for xEdit can be renamed. If there is a copy of xxxxDump in releases, simply rename it to TES5Dump.
