### ISSUE TITLE
FO4Edit: Not enough parameters error on using ADD(e, 'CVPA')

### ISSUE THREAD

**Issue by Valgard** [TES5Edit/TES5Edit#430]
if i want add a **new** CVPA Record to a MISC record then i get a "Not enough parameters." error.

My (reduced to the most important) Script:
    unit userscript;

      function Initialize: integer;
      var
        plugin, element, components : IInterface;
      begin

        for i := 0 to FileCount - 1 do begin
            search := FileByIndex(i);
            s := GetFileName(search);

            if SameText(s, 'plugin.esp') then begin
                plugin := FileByIndex(i);
                break;
            end;
        end;

        element := RecordByFormID(plugin, $002492E2, , false);
        components := ElementByPath(element, 'CVPA');
        if not Assigned(components) then begin
            components := Add(element, 'CVPA');
        end;

      end;

    end.

Bug report fom FO4Edit:
[TES5Edit_bugreport.txt](https://github.com/TES5Edit/TES5Edit/files/1364553/TES5Edit_bugreport.txt)

**Comment by zilav** [comment]
It has 3 parameters, the 3rd one is boolean but it only matters when adding new records. Just set it to True Add(element, 'CVPA', True)

**Comment by Valgard** [comment]
Thanks. That's help  me. ;) 

In the examples I have found, there were always only two parameters.

**Comment by Valgard** [comment]
A little bit off-topic, but how i can add a new component to the CVPA record?

I have tried with:

    components := Add(element, 'CVPA', false);
    // remove null reference
    Remove(ElementByIndex(componentsNew, 0));
    for i := 0  to [count of components] do begin
        component := Add(components, 'Component', false);
        SetElementEditValues(component 'Component', [value]);
        SetElementEditValues(component, 'Count', [value]);
    end;

and with 

    components := Add(element, 'CVPA', false);
    // remove null reference
    Remove(ElementByIndex(componentsNew, 0));
    for i := 0  to [count of components] do begin
        SetElementEditValues(component 'Component\Component', [value]);
        SetElementEditValues(component, 'Component\Count', [value]);
    end;

but this will not add an new component to the CVPA record :|

**Comment by zilav** [comment]
You don't need to delete the default element at index 0
```
for i := 0  to [count of components] do begin
    if i = 0 then
      component := ElementByIndex(components, 0)
    else
      component := ElementAssign(components, HighInteger, nil, False); // add a new one

    SetElementEditValues(component 'Component', [value]);
    SetElementEditValues(component, 'Count', [value]);
end;
```

**Comment by Valgard** [comment]
Many Thanks. 

You saved my ass. XD
