### ISSUE TITLE
[FO4Edit] Access violation at address 00B2539B in module 'FO4Edit.exe'. Read of address 00000008.

### ISSUE THREAD

**Issue by Valgard** [TES5Edit/TES5Edit#431]
When i check the TShiftState in a onMouseDown callback then i get the following access violation:

Access violation at address 00B2539B in module 'FO4Edit.exe'. Read of address 00000008.

Code:

    procedure lblVersionOnMouseDown(Sender: TObject; Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
    begin
        if (ssCtrl in Shift) then begin
            // do somthing
        end;
    end;

[TES5Edit_bugreport.txt](https://github.com/TES5Edit/TES5Edit/files/1366909/TES5Edit_bugreport.txt)

**Comment by zilav** [comment]
JvInterpreter doesn't support 'in' operator iirc, try to use
```if Shift = [ssLeft, ssCtrl] then```

**Comment by zilav** [comment]
Of course it won't work, you are checking for right mouse button + left mouse button + ctrl at the same time. Either remove ssLeft or mbRight check.

**Comment by Valgard** [comment]
Ah, okay. I thought ssLeft stands for LEFT CONTROL. ;)
I will try it tomorow.

**Comment by Valgard** [comment]
With

    if Shift = [ssRight, ssCtrl] then begin
        // do someting
    end;

it works. :)
