### ISSUE TITLE
[xEdit] [Feature Request]  Add support for Windows.MessageBeep

### ISSUE THREAD

**Issue by Valgard** [TES5Edit/TES5Edit#432]
Add support Windows.MessageBeep to play error sound in scripts

**Comment by zilav** [comment]
What for? xEdit scripts can launch external apps, so just execute something that plays what you need. Check Lodgen.pas for example.

**Comment by Valgard** [comment]
I want play the default error sound from windows and don't want start an extra tool to do this.

It should be simple to implement this, because you had include the windows unit already,

Sources:
https://www.askingbox.com/tutorial/delphi-play-system-sounds
http://www.delphipraxis.net/55097-windows-systemsounds-abspielen.html
