### ISSUE TITLE
Creation Club ESLs should be loaded automatically like the primary ESMs

### ISSUE THREAD

**Issue by Silarn** [TES5Edit/TES5Edit#434]
Most plugin tools (and the game itself) do not write the new implicity-loaded ESLs (ie ccqdrsse001-survivalmode.esl) to the plugins.txt file.

This is causing problems with xEdit - which is moving these to the bottom of the load order since they are not present in the plugins.txt.

This will, of course, break loading any other plugins which have one of these ESLs set as a master.

**Comment by zilav** [comment]
Fixed.
https://github.com/TES5Edit/TES5Edit/commit/e7ac032da386b3cc30130e90c62c6576abf134ab
