### ISSUE TITLE
Lazarus and FPC support (instead of, or along side Delphi).

### ISSUE THREAD

**Issue by StochasticTinkr** [TES5Edit/TES5Edit#435]
I'd love to be able to contribute to this project, but AFAICT, I'd have to pay $1500 to get a Delphi license. To be honest, I don't know much about pascal, so I might be asking the impossible. 

I'm sad this wasn't written in C++ or Java. ;-)

**Comment by StochasticTinkr** [comment]
Okay, I didn't see they had a free Delphi version when I looked last time. I'm going to try that ;-)

**Comment by Manic020** [comment]
Have you been able to set up Delphi to work properly for xEdit?

**Comment by Hugues92** [comment]
That is not easy. You need to download a version of the VirtualTree that is compatible with the version of Delphi you use. Then you need to extract the VirtualEditTree source files that comes with the VirtualTree in xEdit sources and add it to the new package and rebuild. Personally I chose to use the VirtualTree package unchanged and then create a second package only for VirtualEditTree. I still have some errors when opening the main window in Delphi 10.1 so... I don't do that. :)

**Comment by StochasticTinkr** [comment]
I did get it to work.  Honestly, it was a pain. I had to manually install JCL and JVCL, modify the VirtualTrees directory, update the libraries, and use DebugLite as the release type.   Importantly, follow the [delphiD24.txt](https://github.com/TES5Edit/TES5Edit/blob/dev/delphiD24.txt) instructions in the repo.  I missed a few things the first time through, and it is *all* relevant.
