### ISSUE TITLE
Tes4Edit Kill Idle animation tree

### ISSUE THREAD

**Issue by GBRPlus** [TES5Edit/TES5Edit#438]
Open some ESM file with Tes4edit, I tested on Mart's Monster Mod.esm.
Edit one or two Idle animations for example its conditions, save file.

Now ESM file is broken, you can see this in game or just open CSE, I have log like this:
[CS]	Could not find previous idle (01000EDC) for IDLE Form 'CreaturesMMMMidasUberhulkIdleAnimsgetupright' (01000EDB).
[CS]	Could not find previous idle (01000EDF) for IDLE Form 'MMMPTCreaturesFiredemonIdleAnimsgetupfaceup' (01000EDE).

All idle animations are broken...

**Comment by zilav** [comment]
This means they either were broken from the start, you you made wrong edits.
