### ISSUE TITLE
[FNVEdit] 3.2.1 Throws NPE while building references for FalloutNV.esm

### ISSUE THREAD

**Issue by clampi** [TES5Edit/TES5Edit#439]
Version used: 3.2.1 of xEdit

Replication steps:
1) Load just FalloutNV.esm in xEdit
2) right click and build reference information for FalloutNV.esm
3) Observe the error shown
4) xEdit window is now unresponsive and process must be forcefully terminated.

Expected behavior:
xEdit should build the reference info successfully and continue operating as normal.

Additional info:
The error was introduced in 3.2.1, doing the same steps with 3.2 worked as expected.
There is no crash log to attach as it does not generate one.
I am using east-european steam version of the game.
xEdit was ran through MO, but that shouldn't affect it as only FalloutNV.esm was indexed.
![xedit3 2 1_npe](https://user-images.githubusercontent.com/10470629/32686855-0423e284-c6b7-11e7-82bc-dfe8fab0d22e.png)

**Comment by zilav** [comment]
It works fine, the error is in your system. Maybe antivirus software, MO, overclocked unstable CPU, failing HDD or something else.
