### ISSUE TITLE
ESL counts to plugin limit

### ISSUE THREAD

**Issue by mycumycu** [TES5Edit/TES5Edit#440]
ESL files shouldn't be included in 254 limit count.
When sum of selected ESM/ESL/ESP files exeeds plugin limit, "Too many plugins selected. Adding XXX files would exceed the maximum index of 254" message appears, although ESM+ESP count is lower then 255.

**Comment by zilav** [comment]
They should because CK counts them too. xEdit is an edition tool, not the game.

**Comment by mycumycu** [comment]
So it is not possible to open for example 250 ESM/ESP and 30 ESL files simultaneously in xEdit to track conflicts?

**Comment by zilav** [comment]
There is no point in loading that many ESL plugins simultaneously.

**Comment by mycumycu** [comment]
Have to disagree.
I have almost 50 plugins converted to ESL format and some records are overwritten by ESP plugins.
So there is a strong point to load them simultaneously.

My current load order (https://pastebin.com/x1FLP65p) can't be handled with xEdit at once, but game engine has no problem with it.

**Comment by zilav** [comment]
Because the game automerges all ESL plugins into a single one in memory. xEdit on the other hand has to treat all plugins separately because they are separate files, and they must be saved separately too if you are going to edit them.

In summary - no, the plugins limit will stay.

**Comment by mycumycu** [comment]
Ok, thanks for explanation.
