### ISSUE TITLE
[TES5] PERK definition

### ISSUE THREAD

**Issue by seberoth** [TES5Edit/TES5Edit#447]
Hi,

I think the PERK definition is wrong:
https://github.com/TES5Edit/TES5Edit/blob/dev/wbDefinitionsTES5.pas#L8624
I think its uint16 instead of uint8.

Some quest have stages higher then 254 and in this cases the first "unused" byte after uint8 is also used.

For Example:
  Expected Quest Stage: 520 (08 02)
  Your Quest Stage: 8 (08)
  Unused: (02 80 3F)

**Comment by zilav** [comment]
Yes you are right, I'll fix that.

**Comment by zilav** [comment]
Fixed.

**Comment by zilav** [comment]
Actually I won't be fixing this. The problem is with the game engine - PERK uses a byte to store quest stage despite it being 2 bytes in the quest itself. PERKs can't use large stage indices at all, blame Bethesda.
