### ISSUE TITLE
Small UI feature request

### ISSUE THREAD

**Issue by ryobg** [TES5Edit/TES5Edit#448]
Hello,

let me first congratulate you about the impressive work. Helps really a lot. I would pass this ticket usually, but your app, popped-up a message box asking for feedback. So here I come.

A quite common use case, I think, is to create and update merge patches at the end of the list. This basically is the following procedure:

1. Applying a filter to show conflicts.
2. For each conflict record
2.1. Right click one column (i.e. mod) header to select it as a base
2.2. Choose "_Copy as override into..._"
2.3. Scroll down to your (e.g. SSEEditMerged) patch.
2.4. Double-click or mark and select ok
3. Proceed with custom tunings if any
4. Go to point (2).

What I suggest is: spare clicking and time by introducing the notion of "last selected file". Basically on step (2.2.) add the option "_Copy as override into the last selected file_".

I see it can be a small improvement, but when you have to do it a lot it adds up.

Hope it is clear and best wishes!

**Comment by eFrysTon** [comment]
@ryobg, how about if the selection dialog would remember your last choice. That is, when it opens a 2nd time, it would already have your previously selected file checked, so you just need to click ok?

**Comment by eFrysTon** [comment]
In the latest version, the Module Selection Dialog for "Copy as [X] into" now pre-selects whatever was checked in the previous use of the form, so that simply hitting Enter is enough.

**Comment by ryobg** [comment]
Hey, thanks for the care. It is appreciated. May others benefit from it too  ^^
