### ISSUE TITLE
Request Permissions to Contribute to TES5Edit for jchamlin

### ISSUE THREAD

**Issue by jchamlin** [TES5Edit/TES5Edit#450]
Sharlikran,

First, I wanted to say thank you for all you have done for the community. You have contributed a great deal! Especially by working with Elminster to provide continuing support for xEdit! So, thank you!

Now, Zilav and I have been working together to add support for using the Delphi IDE to edit xEdit scripts. Zilav updated xEdit to be able to recognize and ignore interface/implementation and process the uses clause and ignore system libraries. I created a well documented xEditAPI.pas file (driven from the Wiki at https://www.creationkit.com/index.php?title=TES5Edit_Scripting_Functions and also discovered other API functions not documented there by looking at the scripts in Delphi). When editing a script in Delphi, xEditAPI.pas can be used by script authors to be able to compile their scripts to check for syntax, and also to get auto-complete and in-line documentation on the xEdit API functions available. I updated the wiki with information about how to use Delphi for xEdit scripting: https://www.creationkit.com/index.php?title=TES5Edit_Scripting_Functions#Using_the_Delphi_IDE_to_Edit_TES5Edit_Scripts

Here are Zilav's commits related to our work:
https://github.com/TES5Edit/TES5Edit/commit/0b328547161c26f5145f53f771def8c11d0ec8ed
https://github.com/TES5Edit/TES5Edit/commit/08fc00c73c3a1cebb4fd13e2b3deaf0450c09412
https://github.com/TES5Edit/TES5Edit/commit/f0edabce059fbc5887dee2075d8d3b21096bd534

Zilav suggested that I get in contact with you to get permission to contribute to the xEdit repository. I plan on committing updates to xEditAPI.pas as I improve it (both documentation and missing methods). I have also added a Delphi project file and support for opening all the other scripts in the Edit Scripts directory to Delphi. And I'll work with Zilav to review that too and get it included at some point.

The Delphi support is great, and it works. But there's also a few minor outstanding issues left with the Delphi support that Zilav said he would get to (they all have workarounds for now). But if I had commit rights, I could save Zilav some time and make the changes myself to be reviewed by Zilav:
(1) processes both the interface uses clause and the implementation uses clause properly
(2) process System.UITypes so no stub is needed
(3) process multiline uses clauses
(4) handle the uses "in" clause

Thank you!

-J.C.

**Comment by Sharlikran** [comment]
You were already added a while back. If you have issues making commits let me know.
