### ISSUE TITLE
[FNVEdit] ESP files flagged as masters listed at the end of the load list instead of where they should be

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#452]
A picture is worth a thousand words:

https://i.imgur.com/OTePgbE.png

Ran into that while testing patch builds for Wrye Bash.

**Comment by zilav** [comment]
xEdit doesn't check any flags, sorting is done purely by extension. Has been so since 2008.

**Comment by Arthmoor** [comment]
So why does it get the order right in Skyrim and FO4 but not NV?

**Comment by zilav** [comment]
Because they use plugins.txt for ordering and NV doesn't. Did you order NV plugins (modifed dates) in WB?

**Comment by Arthmoor** [comment]
I suppose not, but I can't recall this ever being a problem before where a flagged ESM file was listed in the wrong block.

**Comment by zilav** [comment]
You have bad memory then :)
Elminster never made any ESM flag checks, nor did I. xEdit kind of relies on the proper sorting from a mod manager here.

**Comment by Arthmoor** [comment]
Yes, but as I showed in the screenshot, Wrye Bash has the mod in the correct location in the load order. In any case, if there's nothing to be done about it, I guess that's that.

**Comment by RoyBatty64** [comment]
Wrye Flash only partially supports F3/NV as it is missing a great many tags and record types, also with the load order you have there a bash patch is not needed. Make your patch manually in xEdit if needed.

As zilav said, plugins.txt is only used to enable/disable mods and time/date stamps control load order. If they are showing different in Wrye and xEdit then Wrye has a bug.

**Comment by Arthmoor** [comment]
This is actually being tested on a new update for the main branch so it's had quite a lot of work done and seems to support pretty much all the tags and record types it needs to.

Output in the plugins.txt file agrees with what Bash says btw:

> FalloutNV.esm
> DeadMoney.esm
> HonestHearts.esm
> OldWorldBlues.esm
> LonesomeRoad.esm
> GunRunnersArsenal.esm
> ClassicPack.esm
> MercenaryPack.esm
> CaravanPack.esm
> TribalPack.esm
> D.E.I.M.O.S..esm
> NVWillow.esp
> YUP - Base Game + All DLC.esm
> Vurt's WFO.esp
> VertibirdCrashSites.esp
> AFKEmServRailStationHome.esp
> Bashed Patch, 0.esp

I am well aware of the timestamp issue since it was always there for Oblivion too. I see no indication here that Wrye Bash has a bug.

**Comment by zilav** [comment]
Check modified date on NVWillow.esp, it is hidden on your screenshot. Make sure it is greater than the last ESM and less than the first ESP. The order of plugins in plugins.txt is irrelevant.

**Comment by Arthmoor** [comment]
Apparently the game does not believe the order is irrelevant because the save headers match the order I see in Wrye Bash.

**Comment by zilav** [comment]
Show me the same screenshot from above but without xEdit window infront so I can modified dates on all plugins.
Old Fallouts work the same as Oblivion regarding load order, and you know that the order in plugins.txt is completely irrelevant there.

**Comment by Arthmoor** [comment]
Got one here with both the load order screen and the save header that resulted when I finished chargen.

https://imgur.com/a/GaQ3f

As you can see they both agree on placement. So despite assertions, yes, the order specified in plugins.txt DOES matter for these games. They simply get written there by way of their timestamps instead of arbitrarily.

**Comment by zilav** [comment]
I repeat again - order in plugins.txt doesn't matter.

The only issue here is that both the game and WB check the ESM flag inside plugins and group master files together, but xEdit doesn't and groups by extension only. That's all.

Redate plugins in WB so they have sequential modified dates and it will work fine in xEdit. I will need to add ESM flag check too at some point, but this will require overhauling of how load order is handled internally and I'm too busy with other stuff right now.

xEdit has been ordering plugins that way for 10 years, it can wait for another few months.

**Comment by Sharlikran** [comment]
I don't think Valda's versions for FO3/FNV would work any better, but I really don't know. I test and fiddle with 307 and FO3/FNV but honestly I use Valda's versions. You might try it Arthmoor but the .dat files are not the same, so I'd delete them and then start from scratch.

**Comment by eFrysTon** [comment]
The code in df8b8a20afc1afeca4844f2f11efb73524b0383e should also resolve this issue (all files with ESM flag in the header will be sorted before files without it). Someone please test that for FO3/FNV and let me know...

**Comment by Sharlikran** [comment]
I have never been able to compile this myself but I'm trying to get it set up using delphiD24.txt.

**Comment by Sharlikran** [comment]
@Arthmoor See if [SSEEdit-df8b8a2](https://github.com/TES5Edit/TES5Edit/releases/tag/SSEEdit-df8b8a2) fixes this issue.

**Comment by eFrysTon** [comment]
The order was only a problem in xEdit if they files were in the wrong order on disk. (For FO3/FNV that's sort order by modification date of files).

**Comment by Arthmoor** [comment]
I'll check it out later when I get back. Not at the PC right now.

**Comment by Arthmoor** [comment]
Yep, looks like this has been fixed. Thanks.
