### ISSUE TITLE
[Feature] Exclude plugins that do not alter same records as selected plugin(s)

### ISSUE THREAD

**Issue by mycumycu** [TES5Edit/TES5Edit#454]
Regarding to [jchamlin's comment](https://github.com/TES5Edit/TES5Edit/issues/449#issuecomment-357528324) on 14 Jan:
> When doing conflict resolution: there are many plugins that only reference other plugins but do not actually override any items in the game, and those can be left out of loading in xEdit. If it becomes really tedious to deselect a bunch of plugins that do not override anything, maybe zilav could just add another context menu item to the select plugins popup window to exclude plugins that do not have any overrides and are not referenced by other plugins.

Would it be possible to add such functionality?
Or maybe even better an context menu item on xEdit load to exclude plugins that do not alter same records as selected plugin(s)?

This way it would allow us to resolve conflicts with more than 254 active plugins.

**Comment by zilav** [comment]
Until all plugins are loaded such information is not available for xEdit. So inspect plugins yourself, reload xEdit and uncheck the ones you are not interested in.

**Comment by mycumycu** [comment]
That's what I'm doing now, but with 394 active plugins it becomes real pain.

**Comment by zilav** [comment]
That's the only way.
