### ISSUE TITLE
Support for Skyrim VR

### ISSUE THREAD

**Issue by ThomasBrixLarsen** [TES5Edit/TES5Edit#456]
I would make a pull request for this myself if I could compile this project.

The SSE version works as-is it just needs to be updated with the new paths:
My Games\Skyrim VR (has SkyrimPrefs.ini)
AppData\Local\Skyrim VR
SkyrimVR.exe
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Skyrim VR

**Comment by zilav** [comment]
I need to know where does it store the list of vanilla BSA archives if Skyrim.ini (where it is in the original Skyrim) is missing.

**Comment by ThomasBrixLarsen** [comment]
A search for sResourceArchiveList on C: only turns up this:
steamapps\common\SkyrimVR\Skyrim.ini

[Archive]
sResourceArchiveList=Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Interface.bsa, Skyrim - Animations.bsa, Skyrim - Meshes0.bsa, Skyrim - Meshes1.bsa, Skyrim - Sounds.bsa
sResourceArchiveList2=Skyrim - Voices_en0.bsa, Skyrim - Textures0.bsa, Skyrim - Textures1.bsa, Skyrim - Textures2.bsa, Skyrim - Textures3.bsa, Skyrim - Textures4.bsa, Skyrim - Textures5.bsa, Skyrim - Textures6.bsa, Skyrim - Textures7.bsa, Skyrim - Textures8.bsa, Skyrim - Patch.bsa
bLoadArchiveInMemory=1
sArchiveToLoadInMemoryList=Skyrim - Animations.bsa

**Comment by zilav** [comment]
Thanks.
Do SkyrimVR and Fallout4 VR have Creation Club?
Do they support ESL plugins (if you try to use one from ordinary games)?
I also heard there is an extra vanilla ESM included with the game, can you please show me the list of vanilla files in the Data folder for both games.

**Comment by zilav** [comment]
Also regarding SkyrimVR - does it have "Large Objects Distance" option in the launcher Advanced settings like Skyrim Special Edition?

**Comment by ThomasBrixLarsen** [comment]
There is no official mod support so I doubt they have creation club.
They do support ESL.

Skyrim VR data:
![skyrimvrdata](https://user-images.githubusercontent.com/7152480/38302138-f4a86e94-3801-11e8-8ad2-6fccc19baac9.jpg)

Fallout 4 VR data:
![fo4vrdata](https://user-images.githubusercontent.com/7152480/38302145-fa648958-3801-11e8-8ffe-f75b808fbbea.jpg)

There is no launcher for the VR versions of the two games.

**Comment by zilav** [comment]
No launcher? Hmm I guess this is why there is no ini in MyGames. Alright, but is SkyrimVR based on the old Skyrim or newer Special Edition? Does it have other new SE features like water flows, godrays, sparkling snow shader? If yes, then it probably also has Large Objects too.

**Comment by zilav** [comment]
Follow up question - does SkyrimVR.esm have Update.esm as a master? Need to know where to put it in load order.

**Comment by ThomasBrixLarsen** [comment]
It is based on the Special Edition.

Yes the masters of SkyrimVR.esm are:
Skyrim.esm
Skyrim.exe
Update.esm

**Comment by ThomasBrixLarsen** [comment]
**Skyrim VR**
Used paths are correct.
SkyrimVR.esm can be loaded.
Errors: https://pastebin.com/VYHikN26
LODGen (used Indistinguishable Billboards for Skyrim SE): https://pastebin.com/fNhiXswk

**Fallout 4 VR**
Used paths are correct.
Fallout4_VR.esm can be loaded.
Errors: https://pastebin.com/hpiKtnuf

**Comment by zilav** [comment]
Thanks a lot! Everything looks normal. The only new VR changes are a couple of DOBJ settings which I will add.
Btw don't use that generated LOD, need to fix incorrect game mode there too. Should be SSE instead of TES5VR, or just update lodgen.exe to support new modes.

**Comment by ThomasBrixLarsen** [comment]
Yeah I found out using that LOD was a bad idea when the wall to the inn in Helgen was intact so I couldn't jump through.

**Comment by zilav** [comment]
Uploaded new build as a public one, you can get from here https://afkmods.iguanadons.net/index.php?/topic/3750-wipz-tes5edit/

Added missing DOBJ VR settings.

**Comment by ThomasBrixLarsen** [comment]
I think the esm files are being loaded in the wrong order. SkyrimVR.esm needs to overwrite the Warmaster perk so it should be the last loaded.

**Comment by zilav** [comment]
After all DLCs? Can you upload it somewhere and PM me on Nexus? Want to check myself.
