### ISSUE TITLE
TES4Edit ignores load order

### ISSUE THREAD

**Issue by blacksparrow123** [TES5Edit/TES5Edit#457]
Hello
For some reason TES4Edit ignores mod load order list.

For example, mine looks like this:
Oblivion.esm
Unofficial Oblivion Patch.esp
UOP Vampire Aging & Face Fix.esp
Oblivion Citadel Door Fix.esp
DLCShiveringIsles.esp
Unofficial Shivering Isles Patch.esp
DLCHorseArmor.esp
DLCHorseArmor - Unofficial Patch.esp
DLCOrrery.esp
DLCOrrery - Unofficial Patch.esp
DLCVileLair.esp
DLCVileLair - Unofficial Patch.esp
DLCMehrunesRazor.esp
DLCMehrunesRazor - Unofficial Patch.esp
DLCSpellTomes.esp
DLCSpellTomes - Unofficial Patch.esp
DLCThievesDen.esp
DLCThievesDen - Unofficial Patch.esp
DLCThievesDen - Unofficial Patch - SSSB.esp
DLCBattlehornCastle.esp
DLCBattlehornCastle - Unofficial Patch.esp
DLCFrostcrag.esp
DLCFrostcrag - Unofficial Patch.esp
Knights.esp
Knights - Unofficial Patch.esp

But order in TES4Edit looks like this:
[![image.png](https://s14.postimg.org/l3oe154ip/image.png)](https://postimg.org/image/nxrjel6ot/)

And i can't edit files do to order error.
[00:06] Background Loader: Fatal: <Exception: "DLCVileLair - Unofficial Patch.esp" requires master "Unofficial Oblivion Patch.esp" to be loaded before it.>

**Comment by zilav** [comment]
TES4Edit uses modified date of plugin files to sort load order, make sure they are set correctly in sequential order you want.
