### ISSUE TITLE
TES5Edit never allows me to remove an entry in the manual cleaning guide

### ISSUE THREAD

**Issue by ceridwen** [TES5Edit/TES5Edit#458]
I am trying to follow the [Manual Cleaning Guide](https://bethesda.net/community/topic/31060/guide-manual-cleaning-skyrim-and-skyrim-se-master-files).
When I get to the step where I'm supposed to remove, 
"CELL 00016BCF: Remove XEZN subrecord referring to RiftenRatwayZone [ECZN:0009FBB9]", I click remove and the "Yes I'm absolutely sure" counter never advances.  Messages indicate background loading is done, and I've already applied the filter for cleaning.  The same is true for the other edits in that section.  The counter *does* work for the earlier steps involving "Identical to master" and "undelete and disable references".

I'm using version 3.2-25859-3-2 with Mod Organizer running under Wine on Linux.

**Comment by zilav** [comment]
xEdit removes XEZN subrecord correctly, just tested myself. What should happen next according to 3rd party guides is out of scope of what I can do. Speak with the authors of guides.
