### ISSUE TITLE
SSEEdit - ESLs not sorted correctly

### ISSUE THREAD

**Issue by Pickysaurus** [TES5Edit/TES5Edit#460]
I had a rude dismissive response on: https://github.com/TES5Edit/TES5Edit/issues/459

Original post:
"ESLs should sort between ESM and ESP but instead appear after ESPs meaning that you cannot modify an ESP patch with an ESL master in xEdit"

I have been unable to find any duplicate bugs or mention of this issue. I'm not exactly sure why it was dismissed so harshly :S

**Comment by zilav** [comment]
Because it's been fixed long time ago.
