### ISSUE TITLE
Access violation at address 0040B0BD in module 'SSEEdit.exe'

### ISSUE THREAD

**Issue by Ecotone123** [TES5Edit/TES5Edit#461]
I have a script that filters all non-two handed weapons and does some things. Everything is working until it gets to the end of the items when I get the access violation. I simplified the script down to the just filter and the process function that doesn't do anything and I'm testing it on the Skyrim mod only. 

<unit ApplyCustomScripted;

function Filter(e: IInterface): Boolean;
var
	etypStr : string;

begin
	etypStr := GetElementEditValues(e, 'ETYP');
	Result := ((etypStr <> '') and (etypStr <> 'BothHands [EQUP:00013F45]'));
end;

procedure SetFilter();
begin
	FilterConflictAll := False;
	FilterConflictThis := False;
	FilterByInjectStatus := False;
	FilterInjectStatus := False;
	FilterByNotReachableStatus := False;
	FilterNotReachableStatus := False;
	FilterByReferencesInjectedStatus := False;
	FilterReferencesInjectedStatus := False;
	FilterByEditorID := False;
	FilterEditorID := '';
	FilterByName := False;
	FilterName := '';
	FilterByBaseEditorID := False;
	FilterBaseEditorID := '';
	FilterByBaseName := False;
	FilterBaseName := '';
	FilterScaledActors := False;
	FilterByPersistent := False;
	FilterPersistent := False;
	FilterUnnecessaryPersistent := False;
	FilterMasterIsTemporary := False;
	FilterIsMaster := False;
	FilterPersistentPosChanged := False;
	FilterDeleted := False;
	FilterByVWD := False;
	FilterVWD := False;
	FilterByHasVWDMesh := False;
	FilterHasVWDMesh := False;
	FilterBySignature := True;
	FilterSignatures := 'WEAP';
	FilterByBaseSignature := False;
	FilterBaseSignatures := '';
	FlattenBlocks := False;
	FlattenCellChilds := False;
	AssignPersWrldChild := False;
	InheritConflictByParent := False; // color conflicts
	FilterScripted := True; // use custom Filter() function

	ApplyFilter;
	AddMessage('Done appplying filter');
end;

function Initialize: Integer;
begin
	SetFilter();
end;

function Process(e: IInterface): integer;
begin
AddMessage('Process: next item');
	try 
		AddMessage('PROCESSING = ' + Name(e));
	except
		AddMessage('unknown object error');
	end;
end;

function Finalize: integer;
begin
AddMessage('Finalize');
	RemoveFilter;
end;

end.>

It processes the last weapon in the filter then I get the access violation before the Finalize function is run.  Here is the last few lines of the log.

<
.
.
.
Process: next item
PROCESSING = StaffIcySpear "Staff of Icy Spear" [WEAP:0010FCF7]
Process: next item
PROCESSING = SummonedDaedricMaceFire06 "Daedric Mace of the Inferno" [WEAP:0010FD5E]
Exception in unit  line -1: Access violation at address 0040B0BD in module 'SSEEdit.exe'. Read of address FF4C5203
[Apply Script done]  Processed Records: 1338, Elapsed Time: 00:17
>

_Note: the insert code function on this editor isn't working._

**Comment by zilav** [comment]
You can't have `Process()` function in the script after calling `ApplyFilter` because `Process()` tries to iterate over records which are gone after filtering. Either do your stuff in a separate script, or don't use filtering if your need to handle only specific records. Just put your condition at the top of `Process()`
```
function Process(e: IInterface): Integer;
var
  etypStr: string;
begin
  if Signature(e) <> 'WEAP' then
    Exit;

  etypStr := GetElementEditValues(e, 'ETYP');
  if (etypStr = '') or (etypStr = 'BothHands [EQUP:00013F45]') then
    Exit;

  // code which handles non two handed weapons

end;
```

**Comment by Ecotone123** [comment]
Thanks.  After further testing I found that out.

**Comment by Ecotone123** [comment]
Thanks. After further testing I found that out.
