### ISSUE TITLE
Question about TESVEdit script

### ISSUE THREAD

**Issue by Chriswog** [TES5Edit/TES5Edit#463]
Hello, I'm not sure where to ask this, so I picked here.

I'm using the Automation Tools scripts found here:
https://www.nexusmods.com/skyrim/mods/49373/

I've used them successfully thus far, but now I'm trying to use the Quick Change/Element Assign option and things are going weird.

I put in the path and the value I want, and TESV edit reports back it has successfully added element to the record.

But there's nothing there. No change at all. I don't get that. Either it works and I'm good or it fails and I get an error, right?

I've run tests, I know I have my inputs correct. Using the same inputs, I can use the Remove option and it will find the element I tell it to at the path I put in. 

Specifically, I'm trying to add races to the Additional Races section of the Armor Addons.

I'm not a coder, so digging into the guts of the script won't help me. I just can't tell if TESVEdit just can't add elements this way, if the script is flawed in some way or if there is yet something else I can't even imagine.

If there's anyone here who can help me make sense of this, I'd really appreciate it.

**Comment by zilav** [comment]
You'd better ask the author about that https://github.com/matortheeternal/TES5EditScripts

**Comment by Chriswog** [comment]
Thank you. I was under the impression the author had moved on to greener pastures. I'll contact him, thank you!
