### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by OldBrunny** [TES5Edit/TES5Edit#465]
Love SSEEdit, but often find mods are based on base Skyrim and miss the updates from USSEP.  Would like to have the option to inherit a section from a higher order mod.  Not the whole record just the section of the record.  ie when editing an NPC have option to inherit the tint layers.  This would be really useful for the VMAD section.

Regards
OldBrunny

**Comment by zilav** [comment]
Drag&drop changes manually, or write a custom script
https://www.creationkit.com/index.php?title=TES5Edit_Scripting_Functions

There are plentry of scripts included with xEdit which already do similar things.
