### ISSUE TITLE
AV Cleaning with dev-elminster

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#470]
ESP Used; [Thunderchild - Epic Shouts and Immersion](https://www.nexusmods.com/skyrimspecialedition/mods/1460?tab=files)

Load ESP and let xEdit load masters
Apply Filter for cleaning
Remove ITMs

Error:

![av cleaning](https://user-images.githubusercontent.com/1912426/42886167-ba6fdfe8-8a57-11e8-9b00-6193ddb97378.png)

[00:07] Background Loader: finished
[Update.esm] Filtered 15,227 of 15,262 records
[Dawnguard.esm] Filtered 95,402 of 95,428 records
[Dragonborn.esm] Filtered 178,650 of 178,652 records
[Filtering done]  Processed Records: 1162291 Elapsed Time: 01:52
[Filtering done]  Processed Records: 1222410 Elapsed Time: 00:06
Removing: DLC2Init "Init quest" [QUST:03016E02]

# Cleaning with SSEEdit-6557c88

This works and the log is a bit too long to post.

**Comment by eFrysTon** [comment]
Should be fixed with ee738d5be700ce5e8918529a13743bf470a320e8

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/42923711-d1021530-8adb-11e8-832e-cfa15231a5c7.png)

Exact same results cleaning with 3.2.3d and Zilav's last build SSEEdit at f39199fbf719b4d4ef18ec16dba303d563132774.

**Comment by eFrysTon** [comment]
I can translate that to "it's fixed"?

**Comment by Sharlikran** [comment]
Yep! Crossing fingers. :smile:
