### ISSUE TITLE
Adding new cells in worldspaces

### ISSUE THREAD

**Issue by zilav** [TES5Edit/TES5Edit#472]
Ability to add new cells in worldspaces with the proper block/subblock structure.

Check if there is a persistent cell already in worldspace, and if not ask which cell to add - persistent or temporary, and if temporary - ask for X,Y to calc block/subblock. Would be nice if it'll be a separate function with 4 params:
`function (const aWorldspace: IwbMainRecord; aPersistent: Boolean; X, Y: Integer): IwbMainRecord;`
so it can be easily called from scripts to create heightmap -> plugin converter for example.

**Comment by eFrysTon** [comment]
The commit referenced above should fully implement adding of worldspace CELLs using the normal Add menu in the UI.

For scripts, it's possible to call the equivalent of WRLDMainRecord.Add('CELL[P]') or WRLDMainRecord.Add('CELL[10,-5]') to add persistent or temporary CELLs. (The call may return existing CELLs or may find a matching CELL in a master and copy as override it automatically).

It's also possible to call CELLMainRecord.Add('LAND') with the same logic of returning an existing record if possible.
