### ISSUE TITLE
[Feature request + Bug report] Ability to copy all Weathers settings with a single button to multiple Weather items. Bug: Copy to selected records breaks structure in Weathers.

### ISSUE THREAD

**Issue by Arindel** [TES5Edit/TES5Edit#477]
Hi,

**1. Feature request:**
One of my gripes when working on Weathers is that I'm not able to copy the entire Weather settings to other Weather items easily. Right now I have to select multiple Weather items and then use **Copy to selected records** while going through each value. It's rather mind numbing.

If possible, can an option that copies all records (except Editor ID) of an item to other selected items be added?

---
**2. Bug report:**
Version: SSEEdit 3.2.1

Using **Copy to selected records** on specific individual values in Weather items such as **DALC-Sunrise** (found in Weathers at bottom) removes the other values, breaking the structure of that area.

I've made a video of the issue on how to replicate: 
[Youtube link](https://www.youtube.com/watch?v=Uibe7jS6_PU)

The same bug happens inside **Cloud Speed**.

---
Another issue with using **Copy to selected records** in Weathers on individual values of **PNAM - Cloud Colors** or **JNAM - Cloud Alphas** is that instead of copying the values, it creates a new Layer with those values.

**Comment by eFrysTon** [comment]
/me points at the "eFrysTon added a commit that referenced this issue 15 hours ago: Issue #477: Ability to copy all Weathers settings with a single butto… "

**Comment by Sharlikran** [comment]
@Arindel When you have time can you test the fix please. Use this version [SSEEdit-cd11f73](https://github.com/TES5Edit/TES5Edit/releases/tag/SSEEdit-cd11f73).

**Comment by Arindel** [comment]
Gladly. Here's my results.
**Copy multiple to selected records** seems to work as intended. Many thanks for this!
**Copy to selected records** is no longer working, not sure why. Because of this I can't test if it breaks the structure when copying a specific part like DALC - Sunrise.

**Comment by eFrysTon** [comment]
Please provide exact, reproducible step by step descriptions of what you are doing, what you expect to happen, and what happens instead.

**Comment by eFrysTon** [comment]
"Copy to selected records" should be working again in the above listed commit.

**Comment by eFrysTon** [comment]
When you use "Copy [multiple] to selected records", do you use "Compare Selected" first?
I think I can see the problem when I use it without doing "Compare Selected" first. 

And I'm not sure if I can work around that easily. 

Is using "... to/from selected" operations without being in "Compare Selected" mode common? Or would it be an acceptable "fix" to hide the "... to/from selected" operations when not in "Compare Selected" mode?

**Comment by Arindel** [comment]
No, I don't use Compare Selected, I didn't even notice it until today. LOL.
Maybe it can be worked around by removing all statics and cloud textures and then use Copy multiple to selected records? I understand it'd be a more special case since I assume Copy multiple to selected records it's supposed to be used in more areas, not just weathers.

I'm going to write a more lengthy post in a bit with more issues that occured as I tested furthermore + videos.

**Comment by eFrysTon** [comment]
Anything you may have to report while not in "Compare Selected" mode is unfortunately not very meaningful.  "Copy multiple to selected" depends on the work that the UI does when generating the View, and can't work correctly when not using "Compare Selected".

The same is true for the fix I did to "Copy to selected".

In both cases a lot of processing is being done when activating "Compare Selected" to line up the elements from the different records. This is hard to replicate currently without actually using the UI code inside the view.

**Comment by Arindel** [comment]
It's a bit hard to convey the steps of repro without a bit of context so I made videos to help, but I'll post text as well when I can. I found more issues along the way, each having a video I'll post below.

**_Note: I always considered the "last selected item" as "source to copy from"._**

---
**1.** As reported before, textures and statics aren't removed when using **Copy multiple to selected records** between 2 weathers that have different textures in different layers and statics.

**Repro steps:** 
- Select 2 different weathers (with textures in different layers and/or different Statics)
- Use **Copy multiple to selected records**

**Expected:**
Cloud textures and statics to be identical between the 2 weathers, without additional textures/statics.

**Result:**
Cloud textures and statics not used by the Weather copied from aren't removed.

Video: https://www.youtube.com/watch?v=yFSBFpB8SUk

---

**2.** Using Copy multiple to selected records between items found in different plugins marks the last selected as edited if the last selected item is in a plugin above the other.

**Repro steps:** 
- Select 2 items that aren't found in same plugin
- Make sure last selected item is in a plugin above the other
- Use Copy multiple to selected records
- Press OK without deselecting anything

**Expected:**
Last selected item not marked as edited.

**Result:** 
Last selected item is marked as edited.

Video: https://www.youtube.com/watch?v=w4uF9txtgyo

---

**3.** Using Copy multiple to selected records between items found in different plugins to restore settings from an item in a plugin above the other makes changes to last selected item.

Video of repro: https://www.youtube.com/watch?v=AOXavIkQxzw

**Expected:**
Last selected item not changed and the other item to be made identical to last selected item.

**Result:** 
Last selected item is changed using settings from the other selected item. The other selected item is not changed.

_I'm sorry for my murky english when it comes to detailing issues as much as possible._

**Comment by eFrysTon** [comment]
Thanks for the detailed steps. Unfortunately, as I said, the function can't work correctly if you don't use "Compare Selected". Please test with https://github.com/TES5Edit/TES5Edit/blob/d3774585ef6ae34d2a0135ee5aa61c3a3bb27bd3/TES5Edit.exe (which removed the ability to call the function wrongly without using Compare Selected first) and let me know if you are still seeing problems with that.  TIA.

**Comment by Arindel** [comment]
Ah, I'm an idiot about the issue 2 and 3 from my last post.

I'm so used to "last selected item as source to copy from" that I didn't pay attention to where I right-click when I want to use **Copy to selected records**. With the dev version I got from here, the column I right click on seems to be considered the source to copy from. This is a change people who used **Copy to selected records* will have to get used to. =)

**Comment by eFrysTon** [comment]
"Copy to selected records" is supposed to, and as far as I know has always, copied the specific value that's under the mouse when you opened the context menu.

"Copy multiple to selected records" works exactly the same (just that it's the whole column you right-click on, not just the one specific field).

Let's summarize, do you still see any issues when using the "Copy [multiple] to selected records" function when used while in "Compare Selected" mode?

About having to do "Compare Selected" manually, how about a setting in Options "Auto Compare Selected" that can be turned on?

**Comment by Arindel** [comment]
Yeah, last selected item was always what's shown on right side when using **Copy to selected records**, but with **Copy multiple to selected records** I thought the rule still applied, that the last item selected would act as source and simply needed to click **Copy multiple to selected records**. This was before I learned about **Compare Selected** as in that page it matters where I click as I learned just now.

As of now, no more issues. Having Compare Selected required for Copy is a good thing, others might have come with same reports later.

Auto Compare Selected option is pretty good too, I like it.

Thank you again for **Copy multiple to selected records** by the way. As someone who needs to copy a lot of numbers to other items, it's a great thing to have!

**Comment by eFrysTon** [comment]
Great. Glad to hear it all works for you now. I'll have a look at that "auto compare selected" in a moment...

**Comment by eFrysTon** [comment]
Auto Compare Selected is implemented in 01c5d039c902d6c19c45d95ac66224f222492f1f
The commit contains a new binary build that you can use for testing.

**Comment by Arindel** [comment]
Works great, thank you!

**Comment by eFrysTon** [comment]
You are welcome. I'll close this issue then.

Also, please keep in mind that the current test version is highly experimental (large scale internal changes to support ESL, massive changes to the treeview control by updating it from 5.0.1 to 7.x, completely new load order handling, theme support, ...) and there is a good chance it'll shred your module files into confetti.

Still, any feedback about it is welcome.
