### ISSUE TITLE
Using Theme makes color tiles in Weather Editor script invisible

### ISSUE THREAD

**Issue by Arindel** [TES5Edit/TES5Edit#479]
**As shown here:**
![image](https://user-images.githubusercontent.com/21239038/43045219-2273b76e-8dbd-11e8-814d-67b9228330e4.png)

Not using a Theme makes color tiles visible again.

**Repro steps:**
- Enable a Theme
- Select a Weather and press Ctrl+W
- Switch to Weather Colors tab

**Expected:**
All color tiles visible

**Result:**
Color tiles aren't visible

**Comment by eFrysTon** [comment]
The weather editor is not actually part of xEdit. It's a script. I've committed a change to the script (see above) to have it opt-out of theme support for the panels it uses to show the weather colours.
