### ISSUE TITLE
Experimental Theme bugs

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#480]
I'm having an issue where the themes don't work correctly on my system except for the default Windows one. My operating system is Windows 7 and I use classic shell.

The font and/or background colors are not always updated when switch back and forth and always remain black. Also the font for the FormIDs and REFR type are in a different font than the one I have set.

All my fonts are set to 7 point Tahoma and column width of 256 with row height of 12.

https://cdn.discordapp.com/attachments/315643230328717312/471277057624768522/allthemesbutdefault.PNG
https://cdn.discordapp.com/attachments/315643230328717312/471277059008626689/allthemesbutdefault2.PNG
https://cdn.discordapp.com/attachments/315643230328717312/471277556822441994/weirdfont.PNG

**Comment by RoyBatty64** [comment]
This can be closed, it's incompatible with disabled desktop composition. Re-enabling it fixes it.

**Comment by Scrivener07** [comment]
On discord we found out that an `Aero` theme must also be used on Windows 7. I was using the windows basic theme which does not support Aero FXs.
