### ISSUE TITLE
Improved Definition

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#484]
Signature PERK - Perk

Subrecord CTDA - Condition

Field Function

Value 10247 = TTW_GetEquippedWeaponSkill

Runs on Perk Owner

Comparison Values are the same as IsWeaponSkillType which are the Actor Variables

https://i.imgur.com/Mtwn4NS.png

**Comment by Sharlikran** [comment]
Is there an NVSE DLL for this?

**Comment by RoyBatty64** [comment]
Yes, do you need it?

**Comment by Sharlikran** [comment]
Yes, I don't have any clue how to add all the parameters and HLP has some kind of DLL to look for them and add all the proper xEdit stuff. If I try to guess I'll be at it all day or guess wrong. Also, I can add it to Wrye Flash.

**Comment by Sharlikran** [comment]
Should be fixed in https://github.com/TES5Edit/TES5Edit/commit/091eac60b037a527a632425700fd1d5d542f4385
