### ISSUE TITLE
Improved Record Definition [FO3/FNV]

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#491]
The perk function "Set Value" is a typographical error in GECK and it's actually "Subtract Value".

I will fix this in GECK extender as well.

**Comment by RoyBatty64** [comment]
Additional information,this seems to be the case when Modify Damage Threshold (defender) or Modify Damage Threshold (attacker) entry point is being used, otherwise it is Set Value.

**Comment by RoyBatty64** [comment]
Some clarification for incomplete info.

Signature PERK
Subrecord PRKE

Type: Entry Point(s)

Modify Damage Threshold (attacker)
Modify Damage Threshold (defender)
Modify Weapon Strength Req

Function

old = Set Value, new = Subtract Value

Examples

FalloutNV.esm, ShotgunSurgeon "Shotgun Surgeon" [PERK:0016578B]
FalloutNV.esm, BondsOfSteel "Bonds of Steel" [PERK:0017714E]
FalloutNV.esm, WeaponHandling "Weapon Handling" [PERK:00146097]

**Comment by eFrysTon** [comment]
Should be fixed with the commit referenced above.
