### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#492]
Ability to copy individual flags to all selected records without overwriting existing flags.

**Comment by eFrysTon** [comment]
Please be a bit more expansive in your description of EXACTLY what you want to do and what you expect to happen (vs. what happens currently)

**Comment by RoyBatty64** [comment]
I want to copy an individual record flag like "random anim start" to all selected references. Currently doing so will remove any other flags which are already set.

**Comment by eFrysTon** [comment]
ok.. that's going to be a bit tricky, but I'll see what I can do. 
The issue here is that the individual rows you see for individual flags doesn't exist in the file It's just different bits in one integer...

**Comment by RoyBatty64** [comment]
Yep, I figured it would be a tricky mass OR operation. Conversely removing flags with a mass AND operation would also be cool.

**Comment by eFrysTon** [comment]
the operation as such is not tricky... getting it from the UI all the way to the internal objects and doing what you want there is the tricky part

**Comment by eFrysTon** [comment]
The commit listed above should fix this issue (no new binary build yet).
Removing a flag from multiple files is already possible using "remove from selected records" in the context menu when opened on a specific flag.
