### ISSUE TITLE
[Feature Request] Merge overrides into master

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#493]
Would like to see the functionality of this script integrated into the context menu.

It allows to copy overrides into a master overwriting forms already present. Currently I have to copy injected records as overrides, then run the script to merge overrides of existing forms, and twice on navmeshes to get all of it merged into the master. I would very much like to be able to do this with a single operation. This is using the merge up by injection method.

I really prefer to merge manually in xEdit than try to use version control as VC can cause a lot of unintentional edits I have to search for and fix afterwards.

"merge overrides into master.pas" is the script in question.

The desired functionality is to merge all injected records and overrides into the master with a single context menu operation.

The feature should probably be enabled with IKWID switch.

**Comment by eFrysTon** [comment]
the commit referenced above should solve this issue. please read the commit comments for details.
