### ISSUE TITLE
FNVEdit Modulates Voice Flag Incorrect

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#494]
[Relevant post](https://forums.nexusmods.com/index.php?/topic/248639-fnvedit/?p=62464127)

If you select Modulates Voice under the flag list it will not correctly process the armor user's voice ingame. Instead, you have to change the ? field under DNAM from '00 00 00 00' to '01 00 00 00'. This correctly flags the armor in the GECK and ingame.

**Comment by eFrysTon** [comment]
Should be fixed with https://github.com/TES5Edit/TES5Edit/compare/b0b26f410e0f...f2f1bf703a09
