### ISSUE TITLE
clearesm and setesm requires a file name for Tool Mode

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#496]
Current syntax required `-setesm <filename>` or `-clearesm <filename>` which isn't what is implied. Implied syntax `xEdit.EXE -setesm` or `xEdit.EXE -clearesm`.

Just `-setesm` will not go to the plugin selection screen where you can then select any plugins you want to alter. However, `-setesm test.esp` will take you to the plugin selection screen where you can check which files you want altered.

**Comment by eFrysTon** [comment]
-clearesm is a "mode" parameter, like -edit or -view

you can also trigger it by renaming the exe appropriately

As such, I do not think your proposed syntax change is applicable.

**Comment by Sharlikran** [comment]
Then it doesn't work correctly. This is the error I get when I just add it as a "mode"

![image](https://user-images.githubusercontent.com/1912426/43683756-2814fa72-9847-11e8-8076-20a5ba5a5af6.png)

Then when it loads then I have this:

![image](https://user-images.githubusercontent.com/1912426/43683761-4cf47994-9847-11e8-9143-04278228e217.png)

**Comment by Sharlikran** [comment]
It only works if I add `-clearesm test.esp` or `-setesm test.esp`

**Comment by eFrysTon** [comment]
well, yes, just because you don't have to specify the -clearesm anymore if it's in the filename doesn't remove the fact that it checks for a plugin name on the command line

**Comment by Sharlikran** [comment]
So expected behaviour is `-clearesm test.esp` or `-setesm test.esp` and then choose the files you want to alter rather then just `SSEEdit.exe -clearesm` or `SSEEdit.exe -setesm test.esp`, correct?

**Comment by eFrysTon** [comment]
I do now know what the intention was of whoever added these modes. If the intention was not to show the module selection, then that 's a bug that needs to be fixed. Check how 3.2.1 behaves please.

**Comment by Sharlikran** [comment]
No problem. I just downloaded it and 3.2.1 behaves the same.

**Comment by eFrysTon** [comment]
it might still be a bug, depends on what was originally intended. I think this is from @Hugues92  Check with him.

**Comment by Sharlikran** [comment]
Okay changed name, and description.

**Comment by Sharlikran** [comment]
@Hugues92 When I change this line in wbInterface.pas to:
`  wbPluginModes : TwbSetOfMode = [ tmSortAndCleanMasters, tmCheckForErrors,
                    tmCheckForITM, tmCheckForDR ];  // Auto modes that require a specific plugin to be provided.
`
I no longer need to specify a filename. However, Elminster made changes to the plugin selection screen so it will default to having active modules checked. Which is okay I can just deselect them. I don't know if there is a flag or mod to start up with no plugins selected.

**Comment by Hugues92** [comment]
For those automated functions, the intent was to show the message pane and only it, run the function and then close the message pane unless an error occurred in which case the message pane would have remained. It did work like that at the time of introduction but I haven't had the need for those since so I don"t know how it was behaving lately.

**Comment by eFrysTon** [comment]
So anything in:
  wbPluginModes : TwbSetOfMode = [ tmESMify, tmESPify, tmSortAndCleanMasters,
                                   tmCheckForErrors, tmCheckForITM, tmCheckForDR ];
should try to only load the specific plugin that as specified (and it's masters) without showing a module selection, correct?

**Comment by Hugues92** [comment]
yes please. Those modes are intended to be called from batch files.

**Comment by eFrysTon** [comment]
should be fixed...
