### ISSUE TITLE
[Bug] Plugin selection dialog

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#497]
3.2.11 Experimental

In the plugin selection window, right clicking and then select none doesn't uncheck some esps.

**Comment by Sharlikran** [comment]
Do you have a screenshot of an example of which ESP files?

**Comment by RoyBatty64** [comment]
After selecting none, these ones way down in the list are not deselected

https://i.imgur.com/fWfPYVR.png

**Comment by eFrysTon** [comment]
I have a setup with 200 mods and select none works correctly for me. I don't really have a good way to do anything about this issue if I can't reproduce it.

**Comment by RoyBatty64** [comment]
I have 173 plugins in there but only 37 are active.

**Comment by Freso** [comment]
FWIW, I've also seen this issue. I'll try to provide more information next time I see it.

**Comment by Freso** [comment]
https://imgur.com/a/gyinI7t

[FO4Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/2273208/FO4Edit_log.txt)

(Also, can someone rename the issue to something more descriptive please?)

**Comment by eFrysTon** [comment]
great... so we can put this one to bed...
