### ISSUE TITLE
VirtualTrees\Delphi\VirtualTreesD15PG.groupproj

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#498]
What happened to `VirtualTrees\Delphi\VirtualTreesD15PG.groupproj`?

I cannot compile xEdit in XE1 anymore.

**Comment by eFrysTon** [comment]
I assume you didn't update/init submodules in git.

I see @Sharlikran has started pushing some of the changes from the dev-elminster branch to the main dev branch: https://github.com/TES5Edit/TES5Edit/compare/a7cad7632afa...6443cea30af2

Also, please be advised that with the availability of the Delphi 10.2.3 Community Edition, all further development work for xEdit will happen in Delphi 10.2.3 Tokyo and there are no guarantees anything older will be able to compile the codebase or produce the expected behavior if it does.

**Comment by fireundubh** [comment]
Well, I guess I'll update. I was only using XE1 because that was zilav's preferred environment.

Thanks!

**Comment by eFrysTon** [comment]
Because there was no easily available alternative for him. The new Delphi Community Edition: https://www.embarcadero.com/products/delphi/starter/free-download is now completely identical to the full Delphi Professional, the only limitation is the license which restricts commercial use.

**Comment by fireundubh** [comment]
Here's what zilav told me a few years ago:

**Sent 15 November 2015 - 02:46 PM**
> I don't know, sitting myself on older namespaces XE version. If I'm going to install the newer one, I'll update all project files for sure. But I don't plan to any time soon since there are no useful changes for me in newer versions.

**Sent 16 November 2015 - 12:32 AM**
>  Do you know the difference between XE and XE10? Here they are:
> - x64 support - not needed
> - FireMonkey framework for iOS and Android development - not needed
> - a couple of misc libraries which I won't use like FireDac and FastReport - not needed
> - bugfixing - didn't encounter many bugs with XE myself, nothing serious

> They release a new XE version every 6 months and ask money as a full version, while in reality they are just minor updates that other companies release for free, even including greedy Microsoft. I don't encourage such money grabbing, and a lot of Delphi devs don't upgrade on purpose.

**Sent 16 November 2015 - 12:36 AM**
> Oh and by the way, that greedy money grabbing behaviour actually failed for them, they are getting sold. Good riddance.
> https://www.idera.com/about/news/pressreleases/2015/idera-announces-intent-to-acquire-embarcadero

Also, zilav could have easily upgraded to XE10 then since Embarcadero made all releases available for download, but he chose to stay with XE for the reasons above.

**Comment by zilav** [comment]
A lot has changed since then, they released full featured free Delphi version now. So there is no point not to use the latest version. I'm going to switch myself too after upgrading hardware.

**Comment by fireundubh** [comment]
Cool, man! Excited to see how the new XE feels.

Going to close this now since it's resolved.

**Comment by eFrysTon** [comment]
if you want to see the currently latest development, use the dev-elminster branch until it all gets merged down into dev...

**Comment by fireundubh** [comment]
I'm getting this error when trying to build xEdit after installing the VirtualEditTree Package.

`[dcc32 Fatal Error] TES5Edit.dpr(75): F1026 File not found: 'VirtualTrees.pas'`

I vaguely remember a similar error in 2015, but I don't remember the solution. Help?

**Comment by Sharlikran** [comment]
@fireundubh no the code in dev is not the current working branch. Since for right now Elminster is making the changes he is working out of dev-elminster.  When Elminster feels the code is fairly stable, then I'll do some rebaseing and cherry pick commits into dev.

**Comment by fireundubh** [comment]
Thanks! Switching to the dev-elminster branch did the trick. @eFrysTon @Sharlikran

**Comment by eFrysTon** [comment]
careful right now, I messed something up by committing some source files as UTF16, which gave git a hissy fit and which we are correcting right now

**Comment by fireundubh** [comment]
Yeah, I saw that and almost posted an issue, but it seems you fixed it while I was typing. 😄
