### ISSUE TITLE
[Bug] Double clicking on record results in access violation

### ISSUE THREAD

**Issue by ApoAlaia** [TES5Edit/TES5Edit#499]
**What is the version of xEdit you are using?**
3.2.13

**Describe the bug**
In every 'production' version of xEdit if you double click on a record it opens a new window with the path on the header and the value on the window itself. In the experimental version it results in an access violation error.

**To Reproduce**
1. Any record.
2. Double click on it.
3. ...
4. Profit.

**Expected behavior**
Same as in the production versions of xEdit.

**Screenshots**
Production version:
https://imgur.com/SDHYiZj

Experimental version:
https://imgur.com/yXOHilF

**Additional context**
The error seems to be 'agnostic' - it doesn't matter what type of record you try this on it still happens.

**Comment by eFrysTon** [comment]
Can't reproduce, works fine for me:

https://cdn.discordapp.com/attachments/474114115414261760/475971967493734400/unknown.png

Anybody else seeing this problem?

**Comment by ApoAlaia** [comment]
Forgot to add I tried this on two different machines. Both W10 Pro x64 but one is a VM.

Same result on both.

**Comment by eFrysTon** [comment]
Try resetting all settings. Hold Ctrl+Alt+Shift while starting xEdit, it should ask you if you want to reset ALL settings.

**Comment by ApoAlaia** [comment]
Same result, sorry.

https://imgur.com/LuD9Upb

**Comment by eFrysTon** [comment]
Please try https://github.com/TES5Edit/TES5Edit/commit/981aecfdcee61c7a9052d861583e6f9932cb28c9 and see if it makes any difference.

**Comment by ApoAlaia** [comment]
It does.

In this version if I click here I still get the error:

https://imgur.com/DYPKHr7

However if I click on the actual value - either the master or the override - I get the popup (neat that you get now tabs for the different plugins that may alter that record by the by.)

https://imgur.com/lEtwYdB

**Comment by ApoAlaia** [comment]
Woohoo! Yep, that fixed it, thanks! 👍

And... ahem... *blushes* I have never noticed the tabs before.
