### ISSUE TITLE
Improved Record Definitions [FO3/NV]

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#502]
The following forms are hard coded in the exe

00000455 AVIF EditorID SpeedMult
000005E8 AVIF EditorID ElectricResist
000005E9 AVIF EditorID FrostResist
000005EB AVIF EditorID EmpResist
000005ED AVIF EditorID AVVariable02
000005EE AVIF EditorID AVVariable03
000005F0 AVIF EditorID AVVariable05
000005F1 AVIF EditorID AVVariable06
000005F2 AVIF EditorID AVVariable07 
000005F3 AVIF EditorID AVVariable08
000005F4 AVIF EditorID AVVariable09
000005F5 AVIF EditorID AVVariable10

**Comment by eFrysTon** [comment]
can you provide updated hardcoded .dat? (copy the existing ones to .esp and you can edit them)

**Comment by RoyBatty64** [comment]
Done

https://drive.google.com/open?id=1-6h_bh4-94Xz5Zo7B9v5IzP_PGfjJb_P
https://drive.google.com/open?id=1vrJcykc_TukId-ZEYXZ_3SigUPQiRqMP

**Comment by eFrysTon** [comment]
Updated files included with the commit referenced above.
