### ISSUE TITLE
Improved Record Definition [FO3/NV]

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#505]
Signature: SOUN - Sound

Subrecord: SNDD - Sound Data

x = Loop Start
y = Loop End

These values are in samples, not sure if that is relevant or not.

Example record

FalloutNV.esm, WPNFlamerFire3DLPM [SOUN:00050F8E]

**Comment by Sharlikran** [comment]
What is displaying in xEdit is the same as the GECK

![image](https://user-images.githubusercontent.com/1912426/45609080-37e59700-ba0b-11e8-9163-6dc7b53b1b0f.png)
