### ISSUE TITLE
Minor document typo, Experimental 3.2.23

### ISSUE THREAD

**Issue by kanguru-au** [TES5Edit/TES5Edit#506]
Regarding the Github release page for xedit-3.2.23 Experimental

Section "New Create ModGroup function" in the example says:
{+ModC.esp ; must be after ModA and before ModE; order in relation to ModC and ModD doesn't matter
{ModD.esp ; must be after ModA and before ModE; order in relation to ModC and ModD doesn't matter
shouldn't it say:
{+ModC.esp ; must be after ModA and before ModE; order in relation to **ModB** and ModD doesn't matter
{ModD.esp ; must be after ModA and before ModE; order in relation to **ModB** and **ModC** doesn't matter
or have I misunderstood the way grouping has been designed?

**Comment by eFrysTon** [comment]
You are correct

**Comment by Sharlikran** [comment]
https://github.com/TES5Edit/TES5Edit/commit/3bd84117fa65f3fa729b27813648a0c9de7c1b3d had that in the commit from Elminster.

**Comment by Sharlikran** [comment]
Corrected
