### ISSUE TITLE
No logging for Mod Groups disabling in SSEEdit 3.2.23 (86237b6)

### ISSUE THREAD

**Issue by WeAreAllMadeOfStars** [TES5Edit/TES5Edit#507]
Current version:
1. Use SSEEdit 3.2.23 (86237b6) and create SSEEdit.modgroups:
```
[Group with mismatched CRC32]
Update.esm
Dawnguard.esm:12345678
[Group with wrong load order]
Dragonborn.esm
HearthFires.esm
```
2.  Launch SSEEdit 3.2.23 and check Skyrim.esm, Update.esm, Dawnguard.esm, HearthFires.esm Dragonborn.esm. Click "OK".
![sseedit-3 2 23-plugins](https://user-images.githubusercontent.com/20096144/43941406-54be2a18-9c74-11e8-9a76-cb38f24a06b1.png)
3. After loading you will not see any messages about modgroups.
[SSEEdit-3.2.23_log.txt](https://github.com/TES5Edit/TES5Edit/files/2276780/SSEEdit-3.2.23_log.txt)
![sseedit-3 2 23-afterload](https://user-images.githubusercontent.com/20096144/43941405-54a3ca6a-9c74-11e8-9f78-94cee5525b25.png)

Previous version:
1. Use SSEEdit 3.2.15 (6615ef6) and use the same SSEEdit.modgroups.
2. Launch SSEEdit 3.2.15 and check the same plugins. Click "OK".
![sseedit-3 2 15-plugins](https://user-images.githubusercontent.com/20096144/43941404-54678d98-9c74-11e8-8b19-3c16a6ef478d.png)
3. After loading you will see two messages in the beggining of the log (highlighted on screenshot):
```
Ignoring ModGroup [Group with mismatched CRC32] (from SSEEdit.modgroups): CRC of plugin "Dawnguard.esm" (141BE1E5) is not in the list of valid CRCs
Ignoring ModGroup [Group with wrong load order] (from SSEEdit.modgroups): plugins are not in the correct order
```
[SSEEdit-3.2.15_log.txt](https://github.com/TES5Edit/TES5Edit/files/2276779/SSEEdit-3.2.15_log.txt)
![sseedit-3 2 15-afterload](https://user-images.githubusercontent.com/20096144/43941403-544bc770-9c74-11e8-82b2-98d15e26e757.png)

Please, bring back these messages or indicate it via recently implemented dialog of modgroups selection! I've used ModGroups for a long time with hand-written modgroups files and without these messages I just cannot use in anymore: if some mod would change ESP (and it's sum), or if I would mess load order - SSEEdit will just silently disables it's group, without any notification. I have dozens of groups - I will need time to even simply notice something is wrong.

**Comment by Sharlikran** [comment]
Modgroups has it's own editor now and can be loaded while xEdit is open.

The editor is located here. I had to select two mods though.

![image](https://user-images.githubusercontent.com/1912426/43944360-7339394c-9c33-11e8-9ae2-3b6a0d064a35.png)

Once you have a group defined and it qualifies, then you should see this screen. You will also see that screen after selecting plugins and after xEdit has built/loaded the references, as long as they qualify.

![image](https://user-images.githubusercontent.com/1912426/43944248-29324a78-9c33-11e8-9437-7c18ece2b677.png)

Hopefully that's handy for the future. I am sure if this is possible it can be added again. Thanks for posting as requested.

**Comment by eFrysTon** [comment]
Crc support for modgroups is not finished implementing properly. The messages about why modgroups have been excluded will come back

**Comment by eFrysTon** [comment]
Above referenced commit should give you validation messages for modgroups again (not exactly the same, but covering the same conditions at a minimum).

**Comment by WeAreAllMadeOfStars** [comment]
Thank you guys for all your hard work!

**Comment by eFrysTon** [comment]
You are welcome.
Have you had a chance to try out the modgroup creation/editing/deletion from inside xEdit?

Feel free to drop by our new discord: https://discord.gg/5t8RnNQ
