### ISSUE TITLE
Add CTRL + D to deselect from Module Selection

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#509]
![image](https://user-images.githubusercontent.com/1912426/43943981-4556a0ba-9c32-11e8-845d-59d15c148950.png)

CTRL A selects all, then I can press space to check or unchek them all. Would you be willing to implement CTRL D to deselect please?

**Comment by Freso** [comment]
I'd prefer something like Ctrl+Shift+A (Ctrl+A selects all, `Shift` changes/reverses function). I don't know if there's an established "unselect all" keyboard shortcut out there, but that might be an alternative.

**Comment by eFrysTon** [comment]
There is no general unselected shortcut that I'm aware of. It's generally not needed, because just pressing cursor up or down will deselect

**Comment by Sharlikran** [comment]
I can work with that
