### ISSUE TITLE
[FO4] Potential new ITM detection: MSDKs and MSDVs

### ISSUE THREAD

**Issue by Freso** [TES5Edit/TES5Edit#510]
**What is the version of xEdit you are using?**
FO4Edit 3.2.23 (86237b60925e3f28b1c0c341b22a67a21a294994)

**Describe the feature request**
If you open an actor in the CK but do not actually change anything about them, the CK may shuffle their Morph Keys (`MSDK`s) around. Compare e.g. the values from [Brahmin Barons v1.1](https://www.nexusmods.com/fallout4/mods/30436) to its masters:
![billede](https://user-images.githubusercontent.com/177659/43954980-ad8b2c98-9c9e-11e8-8279-be98cfec39e9.png)

I know a similar thing was recently done for navmeshes for some other games, and this seems like essentially the same thing: the end result will be exactly the same, just the order of the "dictionary"/mapping is different.

**Comment by eFrysTon** [comment]
implemented in the commit referenced above
