### ISSUE TITLE
Save Script Source editor Window settings

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#511]
Please make the size of the Script Source window (editing something like SCPT:SCTX for FNVedit save the size the user resized the window to so they don't have to keep resizing it each time they use it.

![image](https://user-images.githubusercontent.com/1912426/43998423-4f99d276-9daa-11e8-9ce6-2c9870b6674a.png)

**Comment by eFrysTon** [comment]
Should be implemented with above referenced commit.
