### ISSUE TITLE
xEdit gives AV when Appdata folder doesn't exist

### ISSUE THREAD

**Issue by Sharlikran** [TES5Edit/TES5Edit#512]
![image](https://user-images.githubusercontent.com/1912426/43997537-171947cc-9d93-11e8-8b8e-b4dabb66dc37.png)

If you just installed a game such as FNV, and never ran the games's launcher for the first time, xEdit tries to make the settings file. If the folder doesn't exist it will cause an error. If you run the game launcher and let it make the folder then xEdit has no issue.

**Comment by eFrysTon** [comment]
Should be fixed in commit referenced above
