### ISSUE TITLE
Warning timer doesn't advance properly under Wine

### ISSUE THREAD

**Issue by Capostrophic** [TES5Edit/TES5Edit#516]
Didn't want to necro #458.

I experienced exactly the same issues as the reporter of that issue when running xEdit under Wine 3.13-staging on Fedora 28. When "are you absolutely sure" message appears if you want to, for example, remove ITMs in a plugin, the timer advances properly and you can proceed to the operation. However, if the first thing you did was an attempt to modify or remove a record or a group of records the timer in that message never advances and you have to do something else to make it go away. Obviously Windows doesn't have such issue.

Other Wine-specific issue I have is that when you remove any subfields in subrecords you get an access violation error and nothing seemingly happens until you try to open the record view again and get another error, after which the subfield appears to be removed, and the next time you try to remove a subfield it only visually gets updated when you open the record view again. After doing that and exiting xEdit you get a couple more access violation errors even if you don't save the plugin (I don't dare to do that and possibly have a corrupted plugin). And now I can't make the error messages other than those appearing on program exit come up again. Argh. It might be a pain to figure out what Wine or xEdit do wrong.

**Comment by Sharlikran** [comment]
You may try any of the releases we have posted. However, xEdit is compiled for Windows using Delphi from Embarcadero. Unless they specifically add support for Wine (I have no idea, you could ask them?) then there is probably nothing that can be done.

Sometimes I feel Wine should be called Winwe. "Wine is not Windows either"

**Comment by eFrysTon** [comment]
Wine is not an official development target. If the program works under wine, great, be happy. If not... *shrug*

**Comment by Freso** [comment]
If a program/feature works under Windows but doesn't under Wine, the issue is with Wine, not the program. You should file bug reports with Wine so they can improve and work better for all programs, not just xEdit.
