### ISSUE TITLE
[Request] More Filtering Options

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#520]
Add two more check boxes to add the ability to change the behavior of the By Record Signature and by Base Record signature so that entire groups of record types can be hidden completely when filtering.

**Comment by eFrysTon** [comment]
I mentioned your issues are usually a bit terse, right? case in point.

**Comment by RoyBatty64** [comment]
I'm not sure how to explain things at times...

So when checking a record type or sub record type it would be what I don't want to see, instead of what I want to see.

**Comment by eFrysTon** [comment]
how is that different from simply inverting your selection?

**Comment by RoyBatty64** [comment]
Less clicks for faster workflow.

**Comment by eFrysTon** [comment]
I don't want to add additional filter options for this, as it would complicate the filter code. But what I've done in f3fd28a82c873d07cb52683b2e473622e09af4df is to now support pressing * while while one of the check list boxes in the form has the focus to invert the current selection (along with + and - for select all/none, and the already existing context menus with the same functions).

So you can simply select what you want and then press * (or press + and then deselect what you want).
