### ISSUE TITLE
At Plugin select, update scroll location at list of plugins along with results after search/filter

### ISSUE THREAD

**Issue by GioGr** [TES5Edit/TES5Edit#522]
Version 3.2.31

At plugin select, update scroll location at list of plugins along with results after search/filter
because it is like no results are found

**To Reproduce**
Required big list of plugins and scrolling to bottom 
![image](https://user-images.githubusercontent.com/12425911/44078872-48761b82-9fb0-11e8-8a53-1e6593715811.png)
searching something that will result in very few results
![image](https://user-images.githubusercontent.com/12425911/44078731-efc39c08-9faf-11e8-8b20-c2fbb47b38dc.png)
![image](https://user-images.githubusercontent.com/12425911/44078933-6d88f034-9fb0-11e8-906e-763bf0cc2e23.png)

2* maybe add a button to clear search/filter context?

**Comment by eFrysTon** [comment]
this should be fixed for all locations where filtering is possible with the commit referenced above
