### ISSUE TITLE
[Feature Request] XML import/export

### ISSUE THREAD

**Issue by dhk-room101** [TES5Edit/TES5Edit#523]
Hi, would it be possible to implement an XML import/export in xEdit?

Based on a random comment I saw on the Internet, I wanted to see if it's possible to port formatted data from a non-Bethesda engine to Skyrim (in my tests).

I managed to successfully port 395 items (armor, weapons, ingredients, etc.) and 563 quests, with stages and objectives. I used xEdit to validate the results, and there were no warnings/errors and all data was correctly displayed including the updated string files.

I used Snip C# as my starting point, and after minor changes to VMAD handling and an updated RecordStructure.XML it worked fine as an XML export.

XML Examples:
NPC_ Irileth https://1drv.ms/u/s!AvsYtfWzlHUVaQIX1v-2I4h1pL4
QUST MQ101 https://1drv.ms/u/s!AvsYtfWzlHUVal28eaCUuN2Hma8

Unfortunately, there are a couple of issues I can see with my approach:
1. I use Snip instead of xEdit, and although Snip performs fine for what I need, I think making xEdit the all in one solution for all our modding needs is the correct way to go.
2. I'm a hobbyist and my code, albeit functional, it's simplistic and naïve (read non-MVC spaghetti code all over the place).

Thanks!

PS: Is there a forum or a discord server I can join to discuss in real-time?

**Comment by zilav** [comment]
You can export in whatever format using a custom script.

**Comment by Hugues92** [comment]
As for importing it's a lot more complex than selecting a format.

**Comment by dhk-room101** [comment]
Thank you for your replies!
Perhaps I wasn't too clear, and I apologize for that. I will try again.

@zilav I currently use a custom script to export to XML written in C# on top of Snip. 
It does the job, but my hope is that we can add a similar feature into xEdit. Like a menu option or similar. 

Metaphorically, xEdit coding is like Mona Lisa, whereas my coding is like playing with putty in the playground. 

I cannot be the only person who sees the benefits of bulk import/export. Doesn't have to be XML, can be Json as well. 

I happen to not be able to use Pascal and Delphi properly. My scripts in C# work fine for me only, but assuming that there are benefits for import/export in XML, perhaps it's worth considering adding such feature to such a robust platform like xEdit for the benefit of modding community.

@Hugues92 As for importing data, what I mean is that is the responsibility of the modder to find an apples to apples linkage between the third-party data and Bethesda data. But once the XML data was transferred from the third-party structure to the Bethesda structure, the resulting XML should have an easy way to be serialized. Again, my C# scripts do the job fine for me only, but I'm hoping an import/export XML feature can be beneficial for the modding community.

Honestly, I am somewhat confused that importing hundreds of records from third-party to Bethesda format doesn't make obvious the benefits. I did this in my private lab tests, but because I don't trust my skills, I'd rather have a robust platform such as xEdit implementing such features in a professional manner for all to use.

Please let me know. Thanks!

**Comment by Sharlikran** [comment]
Will be considered but not a project target.
