### ISSUE TITLE
Right pane update no longer works

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#525]
**Version**

FNVEdit 3.2.32

The right pane no longer updates when scrolling through forms with the arrow keys when holding one down. Only the very next form is displayed and subsequent ones do not until the key is let go.

**To Reproduce**

expand form lists
select the first one with the mouse
use the keyboard down arrow key to scroll down through the records, this also happens when scrolling up.

**Expected behavior**

the pane should update on every record as you scroll

**Comment by eFrysTon** [comment]
WAD
