### ISSUE TITLE
Asset Manager do not recognize package scripts fragment for Skyrim

### ISSUE THREAD

**Issue by Kestatwala** [TES5Edit/TES5Edit#527]
**What is the version of xEdit you are using?**
TES5Edit 3.2.33 EXTRA EXPERIMENTAL (F95D3FA8) starting session 2018-08-16 21:36:30

**Describe the bug**
Asset Manager Script do not recognize package scripts fragments. (stored in PACK -> VMAD)

**To Reproduce**
Run asset manager on any plugin having package fragments. Export list of referenced assets. Ctrl+F for the name of one of the fragment (they should all contains "PF_" as default prefix from the CK)

**Expected behavior**
Package scripts fragments are recognized as any other asset.

**Comment by zilav** [comment]
Remove PACK from sSkipSignatures constant.

**Comment by Kestatwala** [comment]
That explain things!

Thanks

**Comment by Sharlikran** [comment]
Please @ Zilav on the xEdit discord for these things. Then if it's determined it's a bug it may be fixed or Elimnster may ask to post it here. That way when helpful information to alter functionality resolves the issue it's not reported as a bug.
