### ISSUE TITLE
Overflow when using Renumber FormID script

### ISSUE THREAD

**Issue by ApoAlaia** [TES5Edit/TES5Edit#528]
xEdit 3.2.36

When selecting multiple records and applying the 'Renumber FormID' script it returns an error:

'Overflow while converting variant of type (Cardinal) into type (Integer)'

I have tried to reset xEdit but the result is the same.

I have tried this in a different VM with a much 'lighter' load order and cannot reproduce there.

Screenshots of the error and the exception log:

https://imgur.com/Vff8zVK
https://imgur.com/cKbg9x4
https://imgur.com/seOuj0A

**Comment by zilav** [comment]
Because of signed/unsigned assignment. Use on plugins loaded lower than 80xxxxxx, you are not supposed to use such script on full load order. Load only plugin(s) you are working with.

**Comment by ApoAlaia** [comment]
Thanks for the clarification.

I don't usually do that but hey, sometimes I like to test the limits of my own stoopidity.

**Comment by awtr** [comment]
Some fix:
1) declare variable i (or anything you like):
`function Process(e: IInterface): integer;`
`var`
`  OldFormID: Cardinal;`
`i: integer; // <- here`
2) find **SetLoadOrderFormID(...)** at the bottom and replace it with:
`  i := (integer)(NewFormID and  $7FFFFFFF);`
`  if NewFormID and $80000000 <> 0 then begin`
`    i := i xor $7FFFFFFF;`
`    i := -i -1 ;`
`  end`
`  SetLoadOrderFormID(e, i);`

Worked for esl mods
