### ISSUE TITLE
[Feature request] Subrecords copy to

### ISSUE THREAD

**Issue by dhk-room101** [TES5Edit/TES5Edit#529]
Hi, I'm playing with NPCs porting in my lab, and I migrated 2456, and while doing so I realized that there are certain scenarios where a mix-and-match of sub records may be beneficial. 

For example I wanted to create a follower who is two-handed and a wood elf, therefore I created a quick script that takes the ACBS sub record from an existing follower template, takes the Faction Configuration from other, and skills from yet another one.

This way I was able to seamlessly and easily create random mix-and-match of sub records for potential followers. I was wondering if would be beneficial to add a sub records copy feature to xEdit so that modders can select only the desired sub records to merge/overwrite/create on other new/records of the same type.

Thanks!

**Comment by zilav** [comment]
"Copy to selected" right click menu option in the right view does exactly that when you have several records selected.

**Comment by dhk-room101** [comment]
Oh, my bad! Thanks!
