### ISSUE TITLE
Font size and 1360x768

### ISSUE THREAD

**Issue by elderscrollerr** [TES5Edit/TES5Edit#531]
Last version from github. "OK" button in "Apply filter" window doesn't fit on workspace of screeen. resolution 1360x768
Font size reduction in settings does not affect this window. My display doesn't support other resolution modes.
https://imgur.com/a/DjY6sBn
![default](https://user-images.githubusercontent.com/26716013/44334787-8b53dc00-a483-11e8-8184-23eb79c64c0f.png)

**Comment by eFrysTon** [comment]
the commit referenced above should fix that issue. it will automatically scale any non-sizable window to be smaller than the work area (size of primary monitor minus taskbar)
