### ISSUE TITLE
References window fails to redraw when hitting back button/mouse4.

### ISSUE THREAD

**Issue by jbostrus** [TES5Edit/TES5Edit#533]
**What is the version of xEdit you are using?** 
Copy the first line from you xEdit messages window.

Tried with 2 different releases. Game mode did not seem to matter. Also tried with FO3 and FO4 modes.
SSEEdit 3.2.44 EXTRA EXPERIMENTAL (00D21865) starting session 2018-08-22 01:29:18
TES5Edit 3.2.3m EXPERIMENTAL (0AFDC518) starting session 2018-08-22 01:38:14

**Describe the bug**

The references window does not properly refresh with the references when going back records using the back button or mouse4.

**To Reproduce**
1. Load game plugin of choice and build references.
2. Navigate to a record with references.
3. Choose the references tab to see them.
4. Double click one to open that record in the spreadsheet view.
5. In the forward record any view *other* than references tab hit the back button or mouse 4 to go back to the previous record.
6. The view will switch back to references but the window will be blank.

**Expected behavior**

I expect the references of the previous record to be visible when going back from a forward chosen record.

**Screenshots**
The starting record.
![01 starting record](https://user-images.githubusercontent.com/12855515/44452841-6e66f800-a5ac-11e8-8a64-9d7810b91b32.png)
After double clicking the record.
![02 forward record](https://user-images.githubusercontent.com/12855515/44452843-70c95200-a5ac-11e8-834e-10c48ae1f9d1.png)
After hitting the back button or mouse 4. Put back on the references tab but view is empty.
![03 back still on references tab](https://user-images.githubusercontent.com/12855515/44452851-73c44280-a5ac-11e8-9fb2-3fe7d9f711e8.png)

**Additional context**

It is correctly displayed if when on the forward record you are viewing it's references before hitting back. Then the previous record references window redraws with the references visible.

If the window is blank, switching the tab off references and then back will cause it to redraw the proper references.

**Comment by eFrysTon** [comment]
the commit referenced above should fix that issue (binary build coming sometime later today)
