### ISSUE TITLE
Doesn't like 'Deirdre' (FormID 0003F23B)

### ISSUE THREAD

**Issue by ApoAlaia** [TES5Edit/TES5Edit#535]
I have noticed this in the last two iterations of the application - still present in 3.2.53.

When trying to load this specific NPC record the following error will occur:

<Error reading float in " \ [00] Fallout4.esm \ [39] GRUP Top "NPC_" \ [310] Deirdre "Deirdre" [NPC_:0003F23B] \ [29] MSDV - Morph Values \ [0] Value #0": [EInvalidOp] Invalid floating point operation>

This also occurs with 'Value #2' and 'Value #4'

The error occurs loading Fallout4.esm on its own as well as part of a bigger load order.

I can reproduce the error in two different installations, one of them 'untouched' (the VM I use as 'control group' for those times I am being an ass.)

Being stubborn and trying to load that record regardless of xEdit's protests will eventually result in a more general error.

I only noticed this because it dumped it in the log - I wasn't trying to edit this record specifically.

**Comment by eFrysTon** [comment]
There is nothing new here except for the fact that xEdit now reports the problem where it previously just silently ignored it.

The file contains broken values.

**Comment by ApoAlaia** [comment]
Thanks for the reply. I shall silently ignore it too ;)

**Comment by eFrysTon** [comment]
297a03e2e9af25c022197995e714d8936c697f94 should be a lot more forgiving when encountering float errors. No repaint problems, and only reports the error once for the lifetime of the element object.

**Comment by ApoAlaia** [comment]
Thank you very much!

The behaviour implemented in this new build is far less unnerving ;)
