### ISSUE TITLE
Error when converting localization of Strings folder does not pre-exist.

### ISSUE THREAD

**Issue by jbostrus** [TES5Edit/TES5Edit#540]
**What is the version of xEdit you are using?**
SSEEdit 3.2.57 EXPERIMENTAL (08D5177A) starting session 2018-09-01 22:13:40

**Describe the bug**
When choosing to convert a normal plugin to a localized plugin xEdit gives a cannot find path error. Not creating the folder when it doesn't exist would be fine except that it saves the plugin with string index ids therefore being a "corrupted" plugin of sorts. You then have to create the Strings folder and attempt to re-save them before closing xEdit. If you don't you have to find the backup plugin file (assuming you left that option on) and restore it. This leaves usage prone to error from less knowledged users.

**To Reproduce**
1. Ensure there is no Strings folder in the Data folder for the game mode xEdit is in.
2. Open a plugin that is not localized.
3. Convert it to localized via right click | Options | Localization | Localize Plugin.

**Expected behavior**
I would expect one of 2 things to happen. Either xEdit creates the missing folder in order to facilitate the save. Or alternatively if not going to, or if it fails to create it, revert the save back to the prior state automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/12855515/44952534-f911e780-ae35-11e8-9301-683ee631675a.png)

**Additional context**
Personal opinion here, but in the situation where it had unsaved edits prior to trying to convert the localization it would make sense to do 2 saves. Preferably warn the user and ask them to save before converting. Then after they save allow the conversion either by manually choosing to do so again, or automatically continuing into the conversion and subsequent save. Therefore if it utterly failed there was a stable point of return to roll back with any edits one might have done.

**Comment by eFrysTon** [comment]
The above commit will fix the issue where the required path doesn't exist. It does not force a save before doing the localization. You can do that manually currently by pressing Ctrl+S.
