### ISSUE TITLE
improvement suggestion

### ISSUE THREAD

**Issue by blood-stone** [TES5Edit/TES5Edit#551]
One of the issues I have encountered with a number of mods, is that for some reason the texture paths are incorrect. I am not sure if Tes5edit can have a script that can load every nif file that is referenced and verify that a texture file exists, at that location. even if all I got was xxxxx.nif has invalid yyyy.dss file listed that could fix a number of issues with large mod packs. I know its most likely one of those things as a nice to have. the other thing would be if a file is never listed that it tells you and offers to remove it from the pack.

Thank you for the great tool!

**Comment by zilav** [comment]
Assets Manager script allows you to check for missing assets (nifs, textures, materials) including textures used in referenced nif meshes and Fallout4 material files.

**Comment by eFrysTon** [comment]
I assume the answer above is sufficient and will close this issue...
