### ISSUE TITLE
Field labeled "Unused" in Dialogue Topic conditions is actually used

### ISSUE THREAD

**Issue by Qwinn1** [TES5Edit/TES5Edit#556]
**What is the version of xEdit you are using?**
SSEEdit 3.2.70 EXPERIMENTAL

**Describe the bug**
In a Dialogue Topic CTDA condition block, just below "Run On" is a field labeled "Unused".  It is unused if the "Run On" field is set to "Subject" or "Target", but if it is set to "Reference", then you place the formid of the object you're referring to in that field.  

See below:

![github sseedit unused](https://user-images.githubusercontent.com/35168918/46125599-d639df80-c1f7-11e8-85ea-866bd063162d.png)

**Comment by zilav** [comment]
Are you selecting the column with "Reference" type? Because field labels change depending on the selected context, they are not the same across all overriding plugins.

**Comment by Qwinn1** [comment]
You're quite correct!  Clicking on the third record Run On value set to "Reference" does in fact change the label on the next field from Unused to Reference.  My bad!  Never noticed those labels could be dynamic like that.  I only added the issue because I mentioned it to Elminster on the Discord and he asked me to add it so he could look at it later.  I'll close the issue, thanks for the reply.
