### ISSUE TITLE
Error: Could not be resolved Highlight request

### ISSUE THREAD

**Issue by Ghostwalker71** [TES5Edit/TES5Edit#557]
I recently ran across an issue where I had several instances of Error: Could not be resolved in one of my mods, The cause was absolutely between the chair and keyboard.
This did however bring to mind an improvement possibility. If lines containing "Error: Could not be resolved" Could be highlighted in color, it would make finding these lines much easier, especially for persons with poor eyesight, making resolving the issues much faster.
Thank in advance for considering this request.

**Comment by Ghostwalker71** [comment]
Sorry for not being clear, I didn't mean to highlight the text itself I was meaning to highlight the lines that contain the (could not resolve) error in the same manner that the conflict lines are highlighted in yellow and red.

**Comment by eFrysTon** [comment]
![](https://cdn.discordapp.com/attachments/474114115414261760/499158391038672907/unknown.png)
While highlighting with colours would be difficult (there are already a lot of colors and such used for other purposes), you can simply filter for "error" and will directly see all the relevant elements.
