### ISSUE TITLE
Range Check Error TES5Edit

### ISSUE THREAD

**Issue by 1shoedpunk** [TES5Edit/TES5Edit#568]
Whenever I run the lodgen script included with the 3.2.79 experimental release on the full Beyond Skyrim BSHeartland worldspace (large, over 64x64 cells including surrounding landscape) I get a range check error. I get a similar error when changing the name to TES5Lodgen and running it that way.

Not sure if the image is going to come through but the line is: Exception in unit xLODGen line 309: Range check error

**Comment by 1shoedpunk** [comment]
I initially tried to leave it there but I can't access that site for some reason.

**Comment by Sharlikran** [comment]
Yes, the site has been mentioning that they are moving the site. I don't have any affiliation with that site but I remember someone mentioning a [Facebook link](https://www.facebook.com/STEP-Skyrim-Total-Enhancement-Project-175289219235392/) so I googled it.

**Comment by Sharlikran** [comment]
```
Specifically, under Windows 10
1. Edit C:\Windows\System32\drivers\etc\hosts (need to open editor with admin privileges)
2. Add this line to bottom: 142.93.179.251 forum.step-project.com wiki.step-project.com
3. Save/exit
4. Clear browser cache
5. Shouldn't need to, but try flushing DNS from admin command prompt: c:> ipconfig /flushdns
```
That is what the Facebook page suggests and I have not tried it but I put 142.93.179.251 and it worked. So those steps should work if you have windows 10

**Comment by Sharlikran** [comment]
I did step 1-5 but I skipped 4.

http://forum.step-project.com/forum/101-shesons-dyndolod-support/

I was able to go there, and all I had to do was refresh the page whenever there was an error

**Comment by ElminsterAU** [comment]
This problem should be gone in 3.3.0 BETA.
