### ISSUE TITLE
Fallout76 Support

### ISSUE THREAD

**Issue by Icoss** [TES5Edit/TES5Edit#571]
Please add the support for Fallout 76.
Also i would like to have an ability to export the data from the form tree in the xlsm or xml format, if possible.

**Comment by SMB92** [comment]
And I'd like a million bucks. O.o.

Truly, hasn't even been 24hrs since the files were unlocked!

**Comment by Sharlikran** [comment]
I would appreciate it if people would not use any content from Fallout 76 for Fallout 4. It is not allowed and goes against general policy that content can't be taken from one game and used elsewhere.

Bethesda is on heightened awareness and will be looking for stolen content from Fallout 76. I will not appreciate it if Bethesda has to have a chat with us.
