### ISSUE TITLE
stick to row doesn't work with alt+navigation

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#574]
**What is the version of xEdit you are using?**
FO4Edit 3.3.0 BETA (CF9EFC02) starting session 2018-11-05 07:18:48

**Describe the bug**
more of an annoyance, but stick to row doesn't work if alt+arrow is used to navigate through records instead of regular navigation. if you browse normally the window position adapts to show the focused row, but if you try to do it quickly from within the record while using alt+arrow the window position doesn't change, moving the desired row out of view if the other record has more or less data.

**Expected behavior**
when using alt+up/down arrow, the stick to row activates the same way it would without alt. the cursor position adjusts to visually stay on the same line as in previous record to make quicker editing of multiple records easier.

**Comment by ElminsterAU** [comment]
If I can manage to reproduce this exactly I'll probably be able to fix it. Will have a look later.

**Comment by yarrmateys** [comment]
easiest to reproduce is to go to fallout4.esm, weapon tree, then tag one of the bottom-most lines like INAM - Impact Data Set and then scroll through, normally first, then with alt. the difference will be immediately noticable.

**Comment by ElminsterAU** [comment]
Ok. Thanks, I'll try that

**Comment by ElminsterAU** [comment]
Ok, I think I got a fix, but I don't want to push out a new official release yet. If you drop by the Discord, I'll have an interim test version for you to see if this now works the way you expect.

**Comment by ElminsterAU** [comment]
3.3.1 should fix this issue.
