### ISSUE TITLE
Record flags aren't copied correctly when dragged and dropped

### ISSUE THREAD

**Issue by Gr3yStar** [TES5Edit/TES5Edit#576]
**What is the version of xEdit you are using?**
SSEEdit 3.3.0 BETA (CF9EFC02) starting session 2018-11-05 15:44:31

**Describe the bug**
Record flags on records aren't copied correctly when dragged and dropped

**To Reproduce**
Steps to reproduce the behavior: For this example you need Cutting Room Floor and Open Cities Skyrim
1. Apply filter for cleaning.
2. Go to Open Cities Skyrim
3. Click on Cell, Block 2, Sub-Block 8, 000CCDAA, Persistant, 000CE20F
4. Scroll down to Record Flags (sorted) and drag the Initially Disabled Flag from Cutting Room Floor into the spot next to it in Open Cities Skyrim.
5. See that the Record Flags (sorted) now only shows Unknown 0 in Open Cities Skyrim.

**Expected behavior**
Dragging Initially Disabled from Cutting Room Floor to Open Cities Skyrim should add Initially Disabled instead of removing all records from Open Cities Skyrim and adding Unknown 0.

**Screenshots**
https://i.imgur.com/1Q7yKeu.png
https://i.imgur.com/Y9pMSGE.png

**Additional context**
I've encountered this bug in the past with other combinations of record flags as well, so I don't think it's specific to the Initially Disabled flag.

**Comment by ElminsterAU** [comment]
Thanks for your report.
The commit referenced above should fix this issue. It is planned for including in 3.0.1
