### ISSUE TITLE
Data flags aren't copied when dragged and dropped

### ISSUE THREAD

**Issue by Gr3yStar** [TES5Edit/TES5Edit#577]
**What is the version of xEdit you are using?**
SSEEdit 3.3.0 BETA (CF9EFC02) starting session 2018-11-05 15:44:31
**Describe the bug**
Data flags aren't copied when dragged and dropped

**To Reproduce**
Steps to reproduce the behavior: For this example you need Cutting Room Floor and Open Cities Skyrim
1. Apply filter for cleaning.
2. Go to Open Cities Skyrim
3. Click on Cell, Block 2, Sub-Block 4, 00071FFE
4. Locate Data - Flags (sorted) and drag the Public Area Flag from Cutting Room Floor into the spot next to it in Open Cities Skyrim.
5. The Public Area flag isn't copied over and the flags are unchanged for that record in Open Cities Skyrim.

**Expected behavior**
The Public Area Flag is added to Open Cities Skyrim for that record.

**Comment by ElminsterAU** [comment]
Thanks for your report.
The commit referenced above should fix this issue. It is planned to be included in 3.0.1
