### ISSUE TITLE
Edited scripts not marked as not modified when manually saved

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#583]
### Summary 

When you edit a script and click the Save button, the script is not marked as "not modified," so when you attempt to run the script or switch to another script, you get a confirmation prompt asking whether you want to save.

### Steps to Reproduce

1. Edit a script.
2. Click the Save button.
3. Click the OK button to run the script, or select another script from the Script dropdown menu.

### Version
FO4Edit 3.3.0 BETA (CF9EFC02) starting session 2018-11-07 21:28:15

**Comment by ElminsterAU** [comment]
Should be fixed with the commit referenced above. Will be in 3.3.2.
