### ISSUE TITLE
deleting things from use template actors (sorted) sometimes moves two entries down instead of 1

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#584]
**What is the version of xEdit you are using?**
FO4Edit 3.3.1 BETA (D381084A) starting session 2018-11-08 08:39:17

**Describe the bug**
deleting things from use template actors (sorted) sometimes moves two entries down instead of just 1. i have a full list of use template actors (sorted), and when i delete one entry instead of skipping to the second it goes to the third.

**To Reproduce**
set up a list of use template actors (sorted), ex. traits, stats, factions, spell list. delete one by one. deleting traits will focus on factions instead of stats which is under it.

**Expected behavior**
focus on the next value, such as when deleting traits focus on stats instead of factions.

**Comment by ElminsterAU** [comment]
Should be fixed with commit referenced above. Will be included in 3.3.2
