### ISSUE TITLE
xEdit doesn't remember which monitor it was last placed on in certain situations.

### ISSUE THREAD

**Issue by Gr3yStar** [TES5Edit/TES5Edit#585]
**What is the version of xEdit you are using?**
SSEEdit 3.3.1 BETA (D381084A) starting session 2018-11-08 10:03:16

**Describe the bug**
xEdit doesn't remember which monitor it was last placed on if opened and dragged to another monitor, maximized and then closed. Opening xEdit once more will revert xEdit to its previous position and window state on the other monitor.

**To Reproduce**
1. Open xEdit and load some esps.
2. Drag xEdit to another monitor and maximize the window
3. Close xEdit.
4. Open xEdit once more.

**Expected behavior**
xEdit should remember that it was positioned and placed on another monitor.

**Additional context**
xEdit works as intended by remembering the monitor it's on as long as the window isn't maximized before closing.

**Comment by ElminsterAU** [comment]
Should be fixed with the commit above, will be part of 3.3.2.
Drop by the Discord if you want an interim build to test it.
