### ISSUE TITLE
keyboard selection in dropdown lists doesn't work

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#586]
**What is the version of xEdit you are using?**
FO4Edit 3.3.1 BETA (D381084A) starting session 2018-11-08 14:02:25

**Describe the bug**
i'm setting up a flst, and when i type a few letters i get the dropdown list, but i can't actually use it. no matter which position i pick, it gives an error once i press enter because it ignores the dropdown menu if you use keyboard instead of mouse to select the entry.

**To Reproduce**
1) start typing something, like LvlSupermutantm
2) it autofills it to LvlSupermutantMelee
3) press down twice to get LvlSupermutantMeleeAggro512 and press enter
4) LvlSupermutantMelee will be selected either way.

**Expected behavior**
the moment user starts using the dropdown menu, currently selected item should be filled into the entry box so pressing enter will end up with desired option instead of only what was written or autofilled. those should stay only for as long as the user doesn't start using the dropdown menu.

**Comment by ElminsterAU** [comment]
Should be fixed with commit referenced above. Will be included in 3.3.2
