### ISSUE TITLE
modified bold font doesn't fully get removed on direct save

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#587]
**What is the version of xEdit you are using?**
FO4Edit 3.3.1 BETA (D381084A) starting session 2018-11-08 14:02:25

**Describe the bug**
when saving while -AllowDirectSaves is used, the modified indicator (bold font) doesn't fully get removed.

**To Reproduce**
1) modify a record
2) save the mod
3) record tree and currently viewed record don't turn back to unmodified state while others do

**Expected behavior**
everything changes from modified to unmodified on save.

**Comment by ElminsterAU** [comment]
Should be fixed with commit referenced above. Will be included in 3.3.2
