### ISSUE TITLE
dropdown in a specific part of omod's properties doesn't work.

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#588]
**What is the version of xEdit you are using?**
FO4Edit 3.3.1 BETA (D381084A) starting session 2018-11-08 14:02:25

**Describe the bug**
trying to modify the properties for an omod's data>properties(sorted)>formid doesn't work. the dropdown list doesn't open.

**To Reproduce**
1. Go to an object modification, in a chosen record data > properties(sorted), and have one or two properties with formid, int, ADD, keywords or enchantment.
2. try to open the dropdown menu for the property.

**Expected behavior**
the dropdown list opens.

**Comment by ElminsterAU** [comment]
Should be fixed with commit referenced above. Will be included in 3.3.2
