### ISSUE TITLE
dropdown list's horizontal scrollbar covers up the bottommost entry

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#589]
**What is the version of xEdit you are using?**
FO4Edit 3.3.1 BETA (D381084A) starting session 2018-11-08 14:02:25

**Describe the bug**
in FLST when you try to add a record to the list (f2, then scroll down) the bottommost entry will be covered up with the horizontal scrollbar.

**To Reproduce**
1) press f2 to open dropdown list in record such as FLST
2) use cursors to move down

**Expected behavior**
the scrollbar to be below rather than inside the dropdown.

**Comment by ElminsterAU** [comment]
Should be fixed with commit referenced above. Will be included in 3.3.2
