### ISSUE TITLE
alt+cursor movement defaults to descriptions column if out of bound

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#590]
**What is the version of xEdit you are using?**
FO4Edit 3.3.1 BETA (D381084A) starting session 2018-11-08 14:02:25

**Describe the bug**
in case varying amounts of columns appear and user switches from a column/file that overrode a record to one where the said column doesn't exist, the cursor will default to the descriptions column. 

**To Reproduce**
stick to row, enter a record that has several overrides, stay at the rightmost one
alt+scroll up or down to one with less overrides

**Expected behavior**
either stick to specific file or/and default to rightmost column if absent.

**Comment by ElminsterAU** [comment]
Should be fixed with commit referenced above. Will be included in 3.3.2
