### ISSUE TITLE
Question about the reuse faces script

### ISSUE THREAD

**Issue by epsilon-0** [TES5Edit/TES5Edit#599]
I wanted to know how the reuse faces script provided in the SSEEdit scripts folder works.

Do you need to regenerate the FaceGen still even when it is supposed to be reusing faces?
I hope that is not the case....

Thanks.

**Comment by zilav** [comment]
Yes. It copies the facegen data in plugins only, not the facegen files.

**Comment by epsilon-0** [comment]
Damn.... need to do templating then....
Hope that works.
