### ISSUE TITLE
Reporting a null xEdit app version number, which breaks xEdit scripts

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#600]
**What is the version of xEdit you are using?**
TES5Edit 3.3.3b BETA (1DBC0947) starting session 2018-11-13 23:43:05

**Describe the bug**
The app reports a version number of 0.0.0, which causes the failure of any script that checks for a minimum version (so you don't run the script in an ancient version of the app which can't work with the script).

This is probably easy to fix in the script by removing or commenting out the version-checking code, of course, but I have no idea how many scripts this might affect.

**To Reproduce**

Attempt to use any script with such a version check, such as Merge Plugins Script (I prefer it over the stand-alone app version).

You get an error like this: https://ibb.co/nCBtx0

**Expected behavior**

App should report its actual version number, in a format that such checks will not choke on.

**Screenshots**

https://ibb.co/nCBtx0

**Additional context**

Here's the script code that triggered this:

  // check version
  try
    k := wbVersionNumber;
    version := GetVersionString(k);
    AddMessage(version);
    RemoveFilter();
  except on Exception do
    k := 0;
  end;
  // terminate script unless version is 3.0.33 or newer
  if (k < 50340096) then begin
    AddMessage('');
    EditOutOfDate('3.0.33 svn 1898', 'http://www.nexusmods.com/skyrim/mods/25859');
    FreeMemory;
    exit;
  end;

It's from  "Merge Plugins Script v1.9.6 GZ - Unofficial Patch" by GalenZ, a minor Mod Organizer compatibility tweak of "Merge Plugins xEdit Script 1.9" (actually 1.9.5, if you look in it) by matortheeternal.

**Comment by ElminsterAU** [comment]
The app has currently no version resource.
Scripts shouldn't do silly things.

**Comment by Darklocq** [comment]
But they will.  It's kind of weird for the app to not tell what it's version number is, isn't it?  What's the secret?  Heh.

**Comment by Sharlikran** [comment]
Once there is a full version such as 4.0 then the version will be present. Until then, remove the version check from the script.
