### ISSUE TITLE
ITM cleaned by -quickautoclean but not by old process

### ISSUE THREAD

**Issue by seanmb0** [TES5Edit/TES5Edit#603]
**What is the version of xEdit you are using?**
SSEEdit 3.3.4 BETA

**Describe the bug**
Loot reports:
Vigilant.esp 1.3.0 2E278EC6
SSEEdit v3.2.84 EXPERIMENTAL found 52 ITM records. A guide for running Quick Auto Clean can be found here.

When I try to clean this in the normal manner in SSEEdit 3.3.4 BETA does not remove any ITM records. 
Using -quickautoclean the records are found and removed.  (nice feature by the way saves time)
Is this the intended the the -quickautoclean method to be able to identify and clean ITMs that the old method cannot? 

**To Reproduce**
1) Have Vigilant.esp (from Vigilant SE - Nexus Mod ID 11849) in your load order.
2) Run current version of LOOT (see message I posted above)
3) Launch SSEEDit without -quickautoclean
4) Attempt to clean by selecting vigilant.esp from the load list. Once loaded 'Apply Filter for Cleaning' and after filter is applied 'Remove "Identical to Master" records'
5) In the message pane I see 0 ITMs removed
6) Launch SSEEDit -quickautoclean
7) Select vigilant.esp
8) It will find and clean 52 ITMs

**Expected behavior**
For both method to have the same outcome, or documentation to direct use of -quickautoclean as the preferred/approved method

**Additional context**
On other ESPs that can be cleaned by the normal method LOOT reports:
ArtifactsOfBoethiah.esp  BEA0B2DA
SSEEdit found 3 ITM records. A cleaning guide is available here.

Both this and the vigilant error above were reported at the same time in LOOT.

**Comment by ElminsterAU** [comment]
These are almost guaranteed to be new additional NAVM ITMs that xEdit is now able to recognize after having gotten smarter in understanding that certain types of shuffling data around that the CK does has no impact on the information that the record represents.

This requires "Simple Records" to be turned off.

-quick[auto]clean automatically makes sure that "Simple Records" is off.

If you turn "Simple Records" off, the old method will find and remove these ITMs.
