### ISSUE TITLE
How do i use xedit corretly with fallout76 whilst being able to actually edit with it and use some of the options available

### ISSUE THREAD

**Issue by flash241** [TES5Edit/TES5Edit#605]
**What is the version of xEdit you are using?**
Copy the first line from you xEdit messages window.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ElminsterAU** [comment]
You can use xEdit with fallout 76 by starting it with `-fo76` as parameter or renaming it to `fo76edit.exe`. fallout 76 itself does not support mods and checks the crc of SeventySix.esm. Until that changes, all you can use fo76edit for is to look at SeventySix.esm.
