### ISSUE TITLE
FO4Edit Exception log created

### ISSUE THREAD

**Issue by anakha3263** [TES5Edit/TES5Edit#606]
**What is the version of xEdit you are using?**
FO4Edit 3.3.5 BETA (5CCC5F60) starting session 2018-11-22 02:11:22

**Describe the bug**
FO4Edit Exception log generated

**Screenshots**
Exception log link:
https://puu.sh/C6414.log

**Comment by ElminsterAU** [comment]
I don't see anything wrong here? The presence of an exception log does not indicate on its own that anything is wrong. Exceptions are logged the moment they are raised. They may later be caught and handled. This exception is raised inside a windows API call and handled internally before that call ever returns.
