### ISSUE TITLE
[Skyrim LE/SSE] Next Script Fragment Index - Unknown field

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#608]
Using xEdit 3.3.6. Minor record update for VMAD. At the top of every fragment based script is a comment that looks like this:

;BEGIN FRAGMENT CODE - Do not edit anything between this and the end comment
;NEXT FRAGMENT INDEX 2

That index number corresponds to an Unknown field in the fragment data. On the screenshot, the field is selected in the rectangle.

https://i.imgur.com/6QNpliJ.png

**Comment by Arthmoor** [comment]
Hmm. Ok. It sure looked like the index count, but Fragment Version is more likely given the information provided.

**Comment by eckserah** [comment]
Explanation in #813
