### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by SimonTheCat** [TES5Edit/TES5Edit#610]
**What is the version of xEdit you are using?**
FNVEdit 3.3.8 BETA (56B9D6BA) starting session 2018-11-30 23:06:05

**Describe the bug**
Cyrillic characters are displayed incorrectly and it is not possible to enter any text in Russian.
Here (in screenshots section) is screenshots of line in GECK, it look in xEdit, writing same text in esp and following result.

**To Reproduce**
Open any .esp with Russian names of any entries and look at it (it will be something like this Îêðåñòíîñòè), or just enter russian text as name and you will have "??????" as name.

**Expected behavior**
Correctly displayed text in Cyrillic and the ability to enter it. Like it was in FNVEdit 3.1.0 for example.

**Screenshots**
![2018-11-30_212755](https://user-images.githubusercontent.com/43502347/49315033-fe460780-f4f4-11e8-85ba-657db68a5a37.png)
![2018-11-30_212809](https://user-images.githubusercontent.com/43502347/49315034-fe460780-f4f4-11e8-848d-e970fda655e5.png)
![2018-11-30_212823](https://user-images.githubusercontent.com/43502347/49315035-fe460780-f4f4-11e8-90d0-c4a29b3ea25e.png)
![2018-11-30_230540](https://user-images.githubusercontent.com/43502347/49315036-fede9e00-f4f4-11e8-8f9a-bb1cac2ac6c2.png)

**Comment by ElminsterAU** [comment]
Please read the following information that is part of the "What's New" document that xEdit shows on start: 

https://github.com/TES5Edit/TES5Edit/blob/dev-elminster/whatsnew.md#improved-language-support

https://github.com/TES5Edit/TES5Edit/blob/dev-elminster/whatsnew.md#setting-codepage-for-language-in-settings-file

https://github.com/TES5Edit/TES5Edit/blob/dev-elminster/whatsnew.md#codepage-override-using-description-in-file-header
