### ISSUE TITLE
Filter bugs out when .esps are already expanded.

### ISSUE THREAD

**Issue by Gr3yStar** [TES5Edit/TES5Edit#611]
**What is the version of xEdit you are using?**
SSEEdit 3.3.9 BETA (FA6C756D) starting session 2018-12-02 15:44:28

**Describe the bug**
Using filter while having some esps expanded/opened causes the filter view to become slightly garbled... other esp trees are blended together a bit.

**To Reproduce**
1. Load all your plugins.
2. expand the tree on a couple esps.
3. Apply filter for cleaning.
4. filter for an esp that isn't expanded.
5. See error

**Expected behavior**
filter should only be showing the tree structure of filtered plugins.

**Screenshots**
https://imgur.com/a/gj789Py

**Additional context**

**Comment by ElminsterAU** [comment]
please confirm that 3.3.10a here: https://discordapp.com/channels/471930020454072348/518048160526893057/518906344091156525 fixes the problem for you

**Comment by Gr3yStar** [comment]
I've confirmed that 3.3.10a fixes it. thanks again.

**Comment by ElminsterAU** [comment]
Great, thanks for confirming. It's a bug deep in the tree view control that I can't really fix right now. But I've worked around it by using a different method to hide the filtered nodes...
