### ISSUE TITLE
Edit Script to detect ESL capable plugins too restrictive.

### ISSUE THREAD

**Issue by undertheSkyrim** [TES5Edit/TES5Edit#612]
**What is the version of xEdit you are using?**
SSEEdit 3.3.10 BETA (C9BB14F9)

**Describe the bug**
The Edit Script "ESP plugins which could be turned into ESL.pas" reports all plugins that have any records besides overrides as requiring FormID renumbering to be converted to .esl even when this is not necessary.

**To Reproduce**
Create a new plugin with a single new record inside the allowed FormID range for .esl files (for example xx000800) and run the script. It will claim that the plugin "requires FormID renumbering".

**Expected behavior**
The script should inform that no FormID renumbering is required for applicable plugins.

**Additional context**
The culprit seems to be the constant on line 8, which is compared to the highest new FormID in the plugin:
`  iESLMaxFormID = $3ff; // max allowed FormID number in ESL`
Which as far as I know should be $fff instead.

**Comment by zilav** [comment]
Yes it should be $fff
