### ISSUE TITLE
Mod Organizer 2.1.5 & SSEEdit

### ISSUE THREAD

**Issue by daenun666** [TES5Edit/TES5Edit#613]
**What is the version of xEdit you are using?**
Copy the first line from you xEdit messages window.
SSEEdit 3.3.7 BETA (91842337) starting session 2018-12-04 18:23:07
**Describe the bug**
I want to set XEdit to work with my MO2 Local Profile
**To Reproduce**
1. Go to Mo2 interface
2. Click on "Pick a Progran to run" - <Edit...> 
3. Scroll down to SSEEdit - arguments
4. See error:
-SSE -o:C:\Games\SSEModOrganizer\overwrite -I:C:\Games\SSEModOrganizer\profiles\Lola\Skyrim.ini -P:C:\Games\SSEModOrganizer\profiles\Lola\plugins.txt -moprofile:C:\Games\SSEModOrganizer\profiles\Lola
Default SSEEdit is 
**Expected behavior**
Default SSEEdit is:
SSEEdit 3.3.7 BETA (91842337) starting session 2018-12-04 18:23:07
Using Skyrim Special Edition Data Path: C:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\
Using Backup Path: C:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\SSEEdit Backups\
Using Cache Path: C:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\SSEEdit Cache\
Using ini: C:\Users\++++\Documents\My Games\Skyrim Special Edition\Skyrim.ini
Using save path: C:\Users\++++\Documents\My Games\Skyrim Special Edition\__MO_Saves\
Using Creation Club Content list: C:\Games\Steam\steamapps\common\Skyrim Special Edition\Skyrim.ccc
Using plugin list: C:\Users\++++\AppData\Local\Skyrim Special Edition\Plugins.txt
Using settings file: C:\Users\++++\AppData\Local\Skyrim Special Edition\Plugins.sseviewsettings
Using language: English
Using general string encoding: 1252 (ANSI - Latin I)
Using translatable string encoding: 1252 (ANSI - Latin I)
Using VMAD string encoding: 65001 (UTF-8)
Loading active plugin list: C:\Users\++++\AppData\Local\Skyrim Special Edition\Plugins.txt

NEW log With -"arguments" in launcher can't find my profile.

 Can i change the defaults for execution of XEdit?

**Comment by ElminsterAU** [comment]
You don't need any of these parameters. It's MO2's job virtualize these files and make them appear in the right place. xEdit is working fine with MO2.

**Comment by daenun666** [comment]
oki.
it was just one thing i wanted to get out of my head, thanks :)
XEdit has been working fine in all my 4 installs 
it's just that i recently read about a setting in LOOT for redirecting it to my profile inside MO2, and that seems to be working fine.
Just wanted to know if Xedit would be ok if i have my inis and plugins.txt stored locally

**Comment by ElminsterAU** [comment]
There is no need to do anything. Simply run xEdit from MO2.
