### ISSUE TITLE
Still bugs with codepage

### ISSUE THREAD

**Issue by GBRPlus** [TES5Edit/TES5Edit#616]
**What is the version of xEdit you are using?**
Trying new 4.0.0 x64

**Describe the bug**
Its just visual bug, codepage translation works, but I need jump to base record for translation.
![default](https://user-images.githubusercontent.com/26788026/49700810-5fa06180-fbec-11e8-94fe-7dbc5c65359f.png)
![default](https://user-images.githubusercontent.com/26788026/49700818-75ae2200-fbec-11e8-9544-2d4dbafabcf0.png)
![default](https://user-images.githubusercontent.com/26788026/49700823-8199e400-fbec-11e8-814b-b58406355ecc.png)

**Comment by ElminsterAU** [comment]
Please provide proper exact steps to reproduce, including any needed files.

**Comment by GBRPlus** [comment]
Ok. my settings are: C:\OblivionLM\TES4Edit.exe -AllowMasterFilesEdit  -IKnowWhatImDoing  -l:russian -cp-general:1251 (trying without -cp-general:1251, same thing)
[Knights.zip](https://github.com/TES5Edit/TES5Edit/files/2660845/Knights.zip)

Just load this file, bug is everywere.

**Comment by ElminsterAU** [comment]
I don't see any problems when loading that file:
![](https://cdn.discordapp.com/attachments/474114115414261760/521389852168552459/unknown.png)

**Comment by GBRPlus** [comment]
Hm strange, maybe other build?

**Comment by ElminsterAU** [comment]
Your problem came from the fact that you managed to create a ref cache file while using the wrong codepage.

**Comment by GBRPlus** [comment]
Works ok

**Comment by ElminsterAU** [comment]
ok, fix will be part of the final 4.0.0 that goes on NexusMods.
