### ISSUE TITLE
Crash when editing INstance Naming Rules

### ISSUE THREAD

**Issue by Keleigh3000** [TES5Edit/TES5Edit#617]
**What is the version of xEdit you are using?**
FO4Edit 3.3.11 BETA (E9F15818) starting session 2018-12-09 13:23:32

**Describe the bug**
After making extensive changes to an instance naming rule, FO4Edit will sometimes crash when saving the esp. Opening the saved esp I find that some rulesets are repeated, others missing. 

**To Reproduce**
It's inconsistent, but it seems like the more edits I make to the innr, the greater the chance of this happening. Add or remove rulesets, copy rulesets from from another esp, change their order, that sort of thing.

**Expected behavior**
To save the work I did. 

**Screenshots**
Hard to do, sorry.

**Additional context**
If it helps, I tried the same operation with 3.2.1 and it saved successfully with no issues.

When it crashed, it made this:
[FO4EditException.log](https://github.com/TES5Edit/TES5Edit/files/2661015/FO4EditException.log)

**Comment by ElminsterAU** [comment]
Please try with https://cdn.discordapp.com/attachments/512837488922984458/521392199896924163/TES5Edit_4.0.0_ref_cache_codepage_fix.7z and let me know if you still see the problem.

Unfortunately, the exception log contains no information pointing to the origin of the issue.

If the version above still has the problem, I'll need some way to reliably reproduce the issue myself to be able to do anything about it.

**Comment by Keleigh3000** [comment]
I tried the same edits that were crashing 3.3.11 with 4.0, several times. So far so good. No Crashes, no errors. Thanks.
