### ISSUE TITLE
Assertion failure when running REPLACE MODEL FILE NAME  script

### ISSUE THREAD

**Issue by Jim-Fever** [TES5Edit/TES5Edit#619]
**What is the version of xEdit you are using?**
4.0.0 x64

**Describe the bug**
A assertion failure message displays after running the script, either on a single record or on multiple selected records (hence, breaking the script and preventing it to run more than a single record).
So as a result the script can be launched only "record by record" to work and can no longer run on multiple item. (and kinda become pointless)
The issue didnt existed with the previous .exe Xedit version. Restoring previous script's version doesnt solve the issue so the issue seems to be linked to that Xedit version 4.0.0, if not x64... (?)

**To Reproduce**
1. Select one or more ARMO records
2. Right clic, select APPLY SCRIPT, select "Replace model file name script"
3. Enter an existing path  in the record's meshes paths in the first input substring (sReplaceWhat = ')(example  'armor\shitty" beeing the mesh model path (minus the filename.nif) for female world model.
just get sure you enter something that will be recognised by the script for a valid modification in the record(s) = a path string that exist in at least one record, preferably several of them...
4. Enter whatever new path you want in the second (sReplaceWith = ' ...) substring. (example 'myCompilation\cbbe\shitty"). this beeing the new path you want the nif to be found by the ESP.
5 Click ok. Click yes or no for the script to be saved (doesnt matter here). See " the Assertion failure (P:\TES5Edit\wbimplementation.pas, line 16598 "message and the script stoping to run after the first record.

Note : no idea what is that path, i dont have a P:\ drive personnaly.

**Expected behavior** : 
All matching input (sReplaceWhat) substring paths should be modified, as on previous xEdit version. Since the error breaks the script execution, you can longer treat multiple records successfully.

**Screenshots**
None.

**Additional context**
Tested on several Skyrim SE valid (form44) ESPs that were previously edited, for some of them, with that same working script (before 4.0.0)
Not tested on 32 bits version.
I used that script on hundreds records successfully on previous xEdit version with no error message ever.
Tested the backup i had of that script with the 4.0.0 x64 version, in case it were modified, the issue is exactly the same.

**Comment by ElminsterAU** [comment]
Please test that https://cdn.discordapp.com/attachments/518048160526893057/522791515035009034/TES5Edit_4.0.0e.7z (you can rename the exe to whatever you need) resolves your problem. TIA.

**Comment by Jim-Fever** [comment]
It works like a charm again.

Thanks a lot Elminster !  That was fast :)

**Comment by Jim-Fever** [comment]
Nice. closing the issue with a bit of delay then :p GJ again !
