### ISSUE TITLE
File handles don't seem to get closed

### ISSUE THREAD

**Issue by Targuinius** [TES5Edit/TES5Edit#622]
**What is the version of xEdit you are using?**
TES5Edit 4.0.0 x64 (AF25EAB6) starting session 2018-12-17 21:35:50

**Describe the bug**
I was looking into settings Emacs' ediff as comparison tool and noticed I couldn't delete a temporary directory I had created. A quick search in the Resource Monitor revealed TES5Edit had a handle on this directory, even though I already closed everything except the main window for TES5Edit.

It also seems odd to me it locks these files in the first place, since it should need to read or write from/to it.

**To Reproduce**
1. Double click a record
2. In the popup, use the dropdown menu next to "Compare", then "Configure external tool"
3. You then get a Explorer window. Click around a bit to random directories.
4. Open Resource Monitor and go to "CPU"
5. Under "Processes", find TES5Edit64.exe and mark the checkbox in front of it.
6. Then under "Associated Handles" you can see handles on directories you opened earlier.

**Expected behavior**
I would think TES5Edit doesn't need to lock these files/directories, or at least close these handles after the dialogue is closed.

**Comment by ElminsterAU** [comment]
I've reviewed the relevant code. xEdit does absolutely nothing beyond calling the windows shell function to show an open dialog. 

Any handles that might get acquired and not released are done so by the windows shell and not xEdit. If there is any bug, then it's in the windows shell or any of the countless third party shell extension dlls that the windows shell loads. 

The way windows works is that for showing something like the standard file open dialog the windows shell gets loaded into the process as a .dll. Any misbehavior by the shell or it's countless third party shell extension dlls is then wrongly attributed to the hosting process.
