### ISSUE TITLE
Wrong codepage in scripts window

### ISSUE THREAD

**Issue by GBRPlus** [TES5Edit/TES5Edit#623]
Use version 4.0.1
![default](https://user-images.githubusercontent.com/26788026/50373437-efc8a880-05e7-11e9-8352-e76c80ae6d6e.png)
My settings (-l:russian -IKnowWhatImDoing -AllowMasterFilesEdit)
[BATTLE.zip](https://github.com/TES5Edit/TES5Edit/files/2705003/BATTLE.zip)

**Comment by ElminsterAU** [comment]
Nothing about the how the script window handles text has been changed between 3.2.1 and now.

**Comment by GBRPlus** [comment]
Here is 3.2.1
![default](https://user-images.githubusercontent.com/26788026/50373564-a4af9500-05e9-11e9-8978-22d34121e4be.png)

**Comment by ElminsterAU** [comment]
Ok, I was thinking you were talking about the xEdit apply script window, didn't look closely enough.

No, the error here is with your script and not xEdit. Scripts are not "translatable" text. These shouldn't ever have contained cyrillic characters to start with.

scripts are "general strings" not "translatable" or "localizable" strings.

**Comment by GBRPlus** [comment]
Strange, how to fix this? As you see 3.2.1 is ok for me.
