### ISSUE TITLE
DATA - Data - Subtype shows conflict when there is none.

### ISSUE THREAD

**Issue by Gr3yStar** [TES5Edit/TES5Edit#624]
**What is the version of xEdit you are using?**
FO4Edit 4.0.1 x64 (9D8D2E22) starting session 2018-12-22 16:00:10

**Describe the bug**
DATA - Data - Subtype shows conflict when there is none.

**To Reproduce**
1. Load up your mods. This example includes the Unofficial Fallout 4 Patch.esp and VisibleCompanionsAffinity.esp.
2. Click on VisibleCompanionAffinity.esp, Quest, 001A6274, 001A63A2
3. Scroll down to DATA - Data, Subtype.
4. See that there is a conflict for Custom when there shouldn't be.

**Expected behavior**
No conflicts should be shown for this since there aren't any conflicts.

**Screenshots**
https://i.imgur.com/qWTVjlD.png

**Comment by ElminsterAU** [comment]
This is not a bug.

There are 2 different integer values which are labeled "Custom":

```pascal
      wbInteger('Subtype', itU16, wbEnum([
        { 0} 'Custom',  //<-- HERE
        { 1} 'ForceGreet',
        { 2} 'Rumors',
        { 3} 'Custom',  //<-- HERE
        { 4} 'Call',
        { 5} 'Follow',
        { 6} 'Move',
```

**Comment by Gr3yStar** [comment]
In that case, I wasn't able to get it to update and fix the conflict based on drag and drop. maybe it's still user error on my part.

**Comment by ElminsterAU** [comment]
You could try setting the "Show values of flags and enumerations" option.
