### ISSUE TITLE
CTD after launching

### ISSUE THREAD

**Issue by KhadaDjin** [TES5Edit/TES5Edit#628]
4.0.1 
TES5Edit crashes half second after launching, no error, nothing
i used older versions, no result
i made myself sure i use admin privileges, no result
i've seen one thread where deleting Plugins.tes5viewsettings in appdata/local/skyrim folder solved problem, for me, no result
downloading again, no result
each time log ends after loading active plugin.

this one overcame me :/
[TES5Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/2717425/TES5Edit_log.txt)

**Comment by ElminsterAU** [comment]
To make sure you really removed the correct settings, try holding CTRL+ALT+SHIFT when starting, it should ask you if you want to reset settings.

If that doesn't help, please check if there is an exception log beside the .exe, if yes, please upload it here.

**Comment by Sharlikran** [comment]
@KhadaDjin Do you have a TES5EditException.log or TES5EditException[username].log ?

**Comment by KhadaDjin** [comment]
I'm sorry. Reseting settings using Ctrl+Alt+Shift solved problem ^^

**Comment by Sharlikran** [comment]
@KhadaDjin Manually deleting the settings file should have done the same thing. I am glad that fixed it.

**Comment by KhadaDjin** [comment]
Ty for help i'm closing this issue
