### ISSUE TITLE
[Fallout 4] Fail at copy Audio Effect Chain data

### ISSUE THREAD

**Issue by paladinkolovrat** [TES5Edit/TES5Edit#630]
Tool cannot copy because of data type
https://i.imgur.com/qzpqe8a.jpg

**Comment by ElminsterAU** [comment]
Try turning off the option to show flag and enum values to see if that helps

**Comment by paladinkolovrat** [comment]
It works now. But this is a little bug after all. Thanks for help!

**Comment by ElminsterAU** [comment]
"show flag and enum values"  option is purely for debugging purposes and not meant for normal use. It has already been banned to the experts tab in 4.0.2.
