### ISSUE TITLE
Docedit Info Refined

### ISSUE THREAD

**Issue by FelesNoctis** [TES5Edit/TES5Edit#635]
Active:
feles-docedit-live (current edits)
feles-docedit-sandbox (don't use, experiments)

Rebased:
Wrye-Bash-Collection: feles-docedit-rebased-live

Dead:
feles-docedit (not sure why this still exists. It was renamed to sandbox, and was checked on gitk and GitHub. I blame CptMcSplody :P)

Current status:
- All HTML formatted and corrected to HTML5 (readme left at HTML3(?) due to unknown bash compatibility)
- CSS extracted, work files converted to SCSS, refined, and re-exported as CSS.
- Floats created to reduce unnecessary white space 
- Original JavaScript corrected (removed function declaration in loop, fixed skipping first image in slideshow).

TODO:
- Compare individual CSS files for duplications and unnecessary similar colors, then collate into single stylesheet.
- Update images where needed for current content.
- Float all section images.
- Add comment notes to CSS for float use and flow instructions.
- Tentative: Build sections for new content, gather necessary.

Plan on finishing all updates tonight. Please post any info needed for esl+fomod update.

**Comment by ElminsterAU** [comment]
Are you sure this went into the correct repo?

**Comment by FelesNoctis** [comment]
Updated first post.

**Comment by CptMcSplody** [comment]
yeah wrong repo @FelesNoctis :)

**Comment by FelesNoctis** [comment]
I swear one of these days I'm going to find whoever designed the mobile version of Github and do terrible things to them. Someone needs to go back and retake their webdesign classes.

Sorry about that guys.
