### ISSUE TITLE
[Skyrim SSE] Adding a script fragment to a Quest's VMAD record doesn't update the fragmentCount field

### ISSUE THREAD

**Issue by Ralgor** [TES5Edit/TES5Edit#636]
**What is the version of xEdit you are using?**
SSEEdit 4.0.1 (40732B8C) starting session 2019-01-20 20:26:49

**Describe the bug**
See title. Additionally, copying the correct count over causes sseedit to save successfully. Otherwise, the quest aliases will get corrupted, and the fragment you added won't show up either. Note that if there are no quests aliases, then everything will look fine, it will just lose your fragment.

**To reproduce**
1. Right click on Script Fragments, then click Add.
2. Save the plugin.
3. Reload SSE Edit
4. See that quest aliases are gone, replaced with invalid data.
5. Also see that the fragment you added isn't showing.

**Expected behavior**
fragmentCount should be recalculated when a fragment is added or removed, so that saving won't corrupt the plugin.

**Comment by ElminsterAU** [comment]
Should be fixed by the commit referenced above and should have been included in 4.0.2 already. Not sure why this issue hasn't been closed before.
