### ISSUE TITLE
[Fallout 4] TTEB - Unknown in Race record

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#637]
For Fallout 4, TTEB- Unknown is the same as the Blend Operation Sub-record for tint colors, but is used for tints that don't have color options. So the values it can have are: 
Empty:          Default
01 00 00 00 : Multiply
02 00 00 00 : Overlay
03 00 00 00 : Soft Light
04 00 00 00 : Hard Light(edited)
00 00 00 00 would probably also work as Default, but if you select default, even if you have selected something else first, it will show up in xEdit as empty.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
