### ISSUE TITLE
Doesn't remove REFR ITMs in New Vegas

### ISSUE THREAD

**Issue by gutfuckllc** [TES5Edit/TES5Edit#639]
The program doesn't remove REFR ITMs of DLCs in New Vegas. Tested on 'More Perks for Dead Money.esm'

[Screenie 1](https://i.imgur.com/EZYwOlB.png)
[Screenie 2, masters](https://i.imgur.com/7JWtqVT.png)

Seems like unintended behavior. Thoughts?

**Comment by ElminsterAU** [comment]
There are no ITM shown in these screenshots

**Comment by gutfuckllc** [comment]
Seems like unintenional behavior since these act exactly like ITMs in this case...  What would you call them?

**Comment by VlitS** [comment]
I would call it a mod carrying over a change that a DLC implemented. The DLC moved whatever that REFR was from its position in the base game, the mod kept that change. 

ITM = Identical to master. The master, FalloutNV.esm, is not identical to the DLC.

**Comment by gutfuckllc** [comment]
Gotcha. It's an ITPO record, I'll add this information to the loot info table then since the script does the job I want it to.

**Comment by ElminsterAU** [comment]
"master" in this context is always the record all the way in on the left. The winning override is not identical to that. So there is no ITM here.
