### ISSUE TITLE
Request - Find ESP plugins which could be turned into ESL - Exclude existing ESLs

### ISSUE THREAD

**Issue by enderandrew** [TES5Edit/TES5Edit#640]
**What is the version of xEdit you are using?**
SSEEdit 4.1.1 EXTREMELY EXPERIMENTAL (4D67F2C9)

**Describe the bug**
The people who need to convert plugins to ESLs (or add an ESL header) likely are running 200+ plugins. It would be nice if the output from the "Find ESP plugins which could be turned into ESL" script would exclude plugins that already have an ESL header to only show new plugins that should be converted.

**To reproduce**
Run "Find ESP plugins which could be turned into ESL" script

**Expected behavior**
Ignore plugins that already have an ESL header

**Comment by ElminsterAU** [comment]
The script has been rewritten for 4.0.2
