### ISSUE TITLE
[Skyrim SE] Cleaning cause Alchemist Shack makes CTD 

### ISSUE THREAD

**Issue by FACTI0N3R** [TES5Edit/TES5Edit#643]
I just spoted while fixing my game andjust discovered that cleaning game cause Alchemist Shack reads
wrongly by game,
Thanks for answer

**Comment by ElminsterAU** [comment]
Cleaning, it itself, does not cause CTD or damage the file. If cleaning anything causes CTDs, then there are much bigger issues in the files involved that are causing this which is just being exposed now. But the underlying issues have been there before.
