### ISSUE TITLE
Quick Auto Clean will not always be the solution - manual steps sometimes required

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#648]
This will be a fatal problem sometimes: "Manual Cleaning functions ('Apply Filter for Cleaning', 'Undelete and Disable References', and 'Remove "Identical to Master" records' are considered obsolete with the introduction of 'Quick Auto Clean' mode and will now only show a message explaining this."

There are various times that UDR or RITM steps need to be done individually.  While the AFC step was always kind of pointless (picking UDR or RITM should just do it for you - and thank you so much for not making us manually set AFC flags in a form any longer!), and most of the time UDR and RITM should both be done, there are numerous mods that require not cleaning a UDR or ITM for a specific reason. I think xEDIT's own documentation even goes into this.  E.g., if you have a mod the whole point of which is to delete something annoying, then UDR-cleaning it will break it, but it might actually need an ITM fix.  Meanwhile, there are sometimes obscure reasons to have an ITM, e.g. multiple gear mods with a record to inject the same Complete Crafting Overhaul Remade keyword into Skyrim.esm, so the gear can be used with or without CCOR actually installed.

I don't care if the separate UDR and RITM cleaning options are in a submenu, or even not available without a setting being turned on, as long as they still "live" somewhere.

**Comment by ElminsterAU** [comment]
The functions are still available for people that Know What They Are Doing.

**Comment by Darklocq** [comment]
Huzzah!

**Comment by ElminsterAU** [comment]
If you haven't found it yet, be sure to read the What's New, especially the section about "Expert Options" and ALL the way at the end of the What's New.

**Comment by Darklocq** [comment]
It shall be so.
