### ISSUE TITLE
Right pane filter bug

### ISSUE THREAD

**Issue by JonnyWang33** [TES5Edit/TES5Edit#649]
**SSE 4.0.1 and 4.0.1m**

**Describe the bug**
Filter doesn't stay when editing PNAM - Cloud Colors, JNAM - Cloud Alphas, or Cloud Speed

**To reproduce**
1. Go to any weather record. 
2. Filter by name "layer #"
3. Edit any value of PNAM - Cloud Colors, JNAM - Cloud Alphas, or Cloud Speed

**Expected behavior**
The window to remain unchanged as it does when you typically use the filter. 

**Screenshots**
https://cdn.discordapp.com/attachments/473350149306056714/547122580449001514/unknown.png

https://cdn.discordapp.com/attachments/473350149306056714/547122699684544526/unknown.png

https://cdn.discordapp.com/attachments/473350149306056714/547122834498125825/unknown.png

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
