### ISSUE TITLE
TES5Edit Cache files treated as non-matching between 32- and 64-bit version

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#653]
**What is the version of xEdit you are using?**
TES5Edit 4.0.1 x64 (AAEA6B67) starting session 2019-02-21 17:27:39

**Describe the bug**

More of a mis-feature than a bug.  After you run the 32-bit app and have it generate cached references files in "Data\TES5Edit Cache" (or whatever, for some other game like FO3), if you then start up the 64-bit version, from the same release, it treats the cache files as being from an old version and wants to re-make them all.  Unless this is strictly necessary (i.e., because the cache files really are different),  Same if you do it vice-versa, and create cache with 64, but then run 32.

I would think this re-caching should be avoided, since it defeats the purpose of caching it.  At a guess, it's using the entire version string including "32" or "64" instead of truncating it to something shorter but shared between the two apps.  If it's working on a string like "TES5Edit 4.0.1 x64 (AAEA6B67)", I s'pose it would need to break these out into portions, and use just the the major version number (I just checked, and the build number is different between the 32- and 64-bit versions that came in the same 4.0.1 package, so using that won't work).  If "4.0.1" wouldn't actually be specific enough, maybe another node of numbering, like "4.0.1.3"?

**Comment by ElminsterAU** [comment]
The cache files use the CRC of the exe in their name. The 32 and 64bit versions have different CRCs. This is not going to change.
