### ISSUE TITLE
Check for Errors: reports error when a region / object list has SCOL entries

### ISSUE THREAD

**Issue by thomasandersen** [TES5Edit/TES5Edit#654]
**What is the version of xEdit you are using?**

FO4Edit 4.0.1

**Describe the bug**

Not sure if this is a bug, but the Error Check reports errors when a region (REGN)/Object entries has one or more entries of static collections (SCOL)

Creation Kit's region generator allows static collections entries.

**To reproduce**
1. Using CK, create a new region (Menu > World > Region)
2. In the Objects tab, check allow objects and add a static collection to the list.
3. Save the data file and close CK.
4. Open plugin in FO4Edit and run Check for Errors on the plugin / root.

**Expected behavior**

Not sure ;), but since Creation Kit allows SCOL in region records without warnings or errors or any apparent issues I guess SCOL is a valid entry. 

Also, I guess this affects MergePlugins more as an author can not proceed if the file has errors. 

Temporary copying the region tool configuration to another file, delete the data and move the data back after operations is one workaround

I can provide a test esp file if needed.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
