### ISSUE TITLE
BSArch does not generate BSL for Archive

### ISSUE THREAD

**Issue by fireundubh** [TES5Edit/TES5Edit#657]
When writing a BSA, BSArch produces an invalid BSA with gibberish file names. (Versions tested: 0.6, 0.7)

Below, on the left is an Archive-packed BSA and on the right is a BSArch-packed BSA.

![2019-02-26 14_42_15](https://user-images.githubusercontent.com/1261664/53452029-184c9480-39d5-11e9-87e7-a9cbad648d47.jpg) ![2019-02-26 14_42_54](https://user-images.githubusercontent.com/1261664/53452041-1da9df00-39d5-11e9-9b0b-a2686cd066d0.jpg)

The Bethesda Archive Extractor will read the file names in the BSArch-packed BSA correctly.

![2019-02-26 14_56_21](https://user-images.githubusercontent.com/1261664/53452645-b5f49380-39d6-11e9-9622-599af1c57998.jpg)

However, the game (in this case, SSE) will fail to find the scripts in the BSA.

**Comment by fireundubh** [comment]
After more testing, this

> However, the game (in this case, SSE) will fail to find the scripts in the BSA

isn't true.

The gibberish file names issue is the result of BSArch not producing a BSL for Archive.

**Comment by ElminsterAU** [comment]
As BSL files are not required by anything that's relevant, I'll be closing this issue.
