### ISSUE TITLE
[Bug Report] When comparing records, right-clicking to Expand All produces a contextual menu that hangs the Expand All functionality

### ISSUE THREAD

**Issue by BelmontBoy** [TES5Edit/TES5Edit#659]
**What is the version of xEdit you are using?**
xEdit 4.0.1

**Describe the bug**
(Extremely minor bug!) Normally in Record View, right-clicking the top left sector expands records so that all data is visible (while left-clicking fits record data to screen). When Comparing Selected records, right-clicking the top left sector produces a contextual menu featuring "Create ModGroup", which prevents the compared records from expanding until the contextual menu is dismissed.

**To reproduce**
1. Compare any number of records using the "Compare Selected" option from the right-click contextual menu in tree view.
2. Right-click the top left section of the record view.

**Expected behavior**
I expected the records to expand & show all data immediately, as they do when right-clicking the top left section in record view while viewing a single record.

**Screenshots**
https://imgur.com/iWphbsR

**Additional context**
I should note that the "Create ModGroup..." function already displays when right-clicking any of the compared record headers, so I propose that this contextual menu be disabled when clicking specifically in that top left section for expanding data.

Thanks for your hard work!

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
