### ISSUE TITLE
[Bug Report][FO4Edit] Repeated EAccess Violation errors when trying to save & exit

### ISSUE THREAD

**Issue by ahs4016** [TES5Edit/TES5Edit#660]
**What is the version of xEdit you are using?**
4.0.1

**Describe the bug**
Repeated errors of the following:
ExceptionCode: $C0000005 = EXCEPTION_ACCESS_VIOLATION - The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Exception: EAccessViolation
Message: Access violation at address 004071B5 in module 'FO4Edit.exe'. Read of address 0000000C

**To reproduce**
I start xEdit, either straight from its directory or through Mod Organizer 2. In both cases, the programs are run with admin privileges. I select the loaded esp in question that I wish to modify and perform the desired action(s) - most recently I am attempting to mark multiple entries within esps as modified because they are throwing multiple "unused data" errors.
Upon finishing whatever it is I want to do upon the esp, I hit the x to close, unselect the "create backups" option if it is not already so, and confirm. At that point the error(s) - multiple ones if working with more than 1 esp - pop in the message feed. All of them are the same, i.e. an EAccessViolation at address xxxxx in module FO4Edit.exe. Read of address is always the same - 0000000C.

**Expected behavior**
I expected xEdit to save the file(s) edited and exit the application as is customary for it. In my particular case, I tend to create backups manually and will thus disallow xEdit permissions to create its own backups (bottom left checkbox left unmarked).

**Screenshots**
FO4Edit Log - https://pastebin.com/9jFpNmzQ
Exception Log - https://pastebin.com/Kc8AFvZD

**Additional context**
Win10x64 system
Mod Organizer 2 used - portable version
This issue persists irrespective of files selected to load into xEdit. Issue is preset in 4.0.0, 4.0.1, and 4.0.1n_RC4_for_4.0.2.7z (latest on discord) versions.
Issue is preset both within a mod manager setting - xEdit launched from MO - and when xEdit is launched on its lonesome.
Issue persists even when xEdit is launched as standalone and operating on files dropped into base game directory
UAC has been disabled, file ownership has been set to user, full rwx permissions are held
xEdit and MO have been added as exceptions to Windows Defender - no other AV present
MO filepath - C:\Mod Organizer 2
xEdit filepath - C:\FO4Edit
Issue persists when xEdit is dropped into Fallout 4 and MO2 directories

I've exhausted my limited knowledge in troubleshooting this. As far as I can tell, FO4Edit thinks that it doesn't have permission to save anywhere. Bizarrely enough, the backup files do appear in the Overwrite folder and I did try - admittedly only once - to create a random merge patch which succeeded.
Even more bizarre is the fact that I *was* able to create two successful cleans - two times out of the hundred-odd attempts xEdit successfully saved and exited without complaint. But I cannot fathom why, especially considering that any subsequent attempts I made after those two successes all failed. It just worked once and then failed several dozen times before working once more and then failing again.

**Comment by ElminsterAU** [comment]
The provided exception log does not show a single case where you used 4.0.1n.
The stack trace looks very much like an error that was specifically fixed between 4.0.1 and 4.0.1n.
Please provide an exception log created with 4.0.1n that shows the error.

**Comment by ahs4016** [comment]
Sorry, must've removed that particular entry when I was deleting lines to make room in pastebin. Regardless, here's the logs, downloaded a fresh copy of FO4Edit from the FO4 nexus and overwrote with v4.0.1n from the Discord
Same directory for xEdit - C:\FO4Edit

Didn't bother running it through MO2, instead booted xEdit as standalone and ran it on the esp files I dropped into the FO4 game directory. I figure if it doesn't work in that setup then it won't work through MO2.
Same errors

FO4Edit Log - https://pastebin.com/nDgQf7hu
Exception Log - https://pastebin.com/WYqpty0A

**Comment by ElminsterAU** [comment]
No version of xEdit magically changes it's icon when it's being renamed. (It can't, Windows doesn't have any mechanism for that.) There are two different builds of xEdit uploaded to NexusMods, one with the TES icon and one with the FO icon.

**Comment by ElminsterAU** [comment]
Ok.. I'm unable to reconstruct the cause of the exception from the logs alone. To figure out what's going on I'll need to actually reproduce the crash under the debugger. For that I'll need all required files and *exact* step by step instructions how to make this error appear.

**Comment by ElminsterAU** [comment]
Actually, before you do that, please make sure to resave HotMamaVault81B.esp with CK first and see if that fixes the problem. Based on the errors in the normal log, it's very likely that this file simply isn't a valid FO4 module file.

**Comment by ahs4016** [comment]
So...opening the esps and re-saving them in the CK fixed it...at least for all the files I was trying to mess with. Granted, they all came from the same author so my test case is somewhat biased.
Nevertheless, the files can now be messed with and edited.

If you don't mind me asking, what exactly was the issue with the files?
Also, when I opened them in the CK, the log tab threw several hundred errors for each file - the Far Harbour one had close to 950 errors alone. Is this something I should be concerned about? Or is this like the Skyrim CK where no matter what you open, you'll have to click past multiple error popups?

Thanks regardless. I was going absolutely mental trying to troubleshoot this on my own.
Cheers mate

**Comment by ElminsterAU** [comment]
I'm not sure what exactly was wrong with the file, but the fact that you got 100s if not 1000s of errors during the loading in xEdit clearly points at something being very wrong.

**Comment by ahs4016** [comment]
Well, they were all the same error, the "unused data" thing which, according to my internet research, I can remove by using xEdit's "mark modified" option.
That said, would it be a good idea to use a different mod or is this "unused data" business harmless enough? I'll be merging all the files in that respective subgroup in the end

**Comment by ElminsterAU** [comment]
It means that whatever data was in that file, it's format did not conform to the record definitions used by xEdit.

**Comment by ahs4016** [comment]
Ah. Sounds harmless enough then, at least as far as game stability is concerned.
In any event, thanks for the help and the solution. Appreciate your willingness in giving up your time and coding knowledge to scrublords such as me
