### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by havredave** [TES5Edit/TES5Edit#662]
I've noticed a missing SkyrimSE Game Setting that could be added to xEdit: iTrainingNumAllowedPerLevel. Easy enough to add with the Creation Kit, after which it is seen in my mod using xEdit, but it does not show the master Skyrim.esm entry at all. Thanks!

**Comment by ElminsterAU** [comment]
Because it doesn't exist in skyrim.esm

**Comment by havredave** [comment]
Ah, Skyrim.exe I see. Thank you for the helpful answer.
