### ISSUE TITLE
Fallout4: Damage magic effects mislabeled subrecord

### ISSUE THREAD

**Issue by Keranos89** [TES5Edit/TES5Edit#670]
**What is the version of xEdit you are using?**
FO4Edit 4.0.2 (9D0B47A5)

**Describe the bug**
For Magic Effect (MGEF) records in FO4Edit with the damage Archetype, the subrecord "Assoc. Item" becomes labeled "Unused". This is inaccurate. For damage magic effects, this subrecord is used to define a damage type (DMGT).

**To reproduce**
1. Go to Fallout4.esm > Magic Effect
2. Click on mod_Lining_FieldGen_EMP_MagicEffect "FieldGen EMP Damage" [MGEF:000BA45E]
3. Subrecord located between "Base Cost" and "Magic Skill (unused)" labeled "Unused"
4. Compare to mod_Lining_FieldGen_Radiation_CloakEffect_2 "FieldGen Radiation Cloak 2" [MGEF:000BA45D]

**Expected behavior**
Should be labeled "Assoc. Item" like the subrecord is for other archetypes that use it, such as Light or Cloak.

**Comment by Sharlikran** [comment]
EDIT: Although preliminary support is being worked on.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
