### ISSUE TITLE
[Bug Report] Invalid ITMs when form versions differ

### ISSUE THREAD

**Issue by RoyBatty64** [TES5Edit/TES5Edit#674]
Overrides are misdetected as ITM when the form version of the master and override differ.

https://cdn.discordapp.com/attachments/512906058532913185/557768551126269952/zTTWFixups211.esp

**Comment by ElminsterAU** [comment]
xEdit 4.1.2c EXTREMELY EXPERIMENTAL in #xedit-builds on the Discord should fix this. Please confirm.

**Comment by eFrysTon** [comment]
is fixed with commit referenced above
