### ISSUE TITLE
[Fallout 4] VISI and PCMB subrecords 

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#679]
The VISI and PCMB subrecords are timestamps that can be decoded the same way the Version Control Info 1 subrecord is decoded. 

They are compared against the VC Info 1 subrecord of precombined REFRs in that cell, and if the VISI/PCMB timestamp is older than the newest VC Info 1 timestamp for any precombined REFRs then precombineds and previs get automatically disabled for that cell. 

I would recommend making the VISI and PCMB subrecords still be edited as hex, or use some method to keep people from putting an invalid value in those subrecords.

**Comment by Sharlikran** [comment]
I am all for having this decoded but it's the time date stamp. So to me it isn't decoding things that users would normally use or that the CK allows us to modify. None the less it would be nice to have all these decoded if possible.

**Comment by VlitS** [comment]
I mainly want it decoded so it is easier to compare to the VC Info 1 value of the contained REFR records, for the reason mentioned in the initial post. The CK lets you modify it indirectly (with the Update Timestamps option), which changes those two values, just not in a way you can directly edit.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2j)
