### ISSUE TITLE
Editable List of body slots (First Person Flags, AKA BSDismemberSkinInstance partitions)

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#680]
**What is the version of xEdit you are using?**
Stable version: `TES5Edit 4.0.1 x64 (AAEA6B67)` – I'm not using the bleeding-edge stuff yet.

**Describe the bug**
Feature request, not a bug.  Would be nice if xEdit read in a list of names for body slots. Ideally, XML and in the same format as NIFSkope's `nif.xml`, so we can just copy-paste from it, but I'll take what I can get.  It's difficult to remember which add-on item slot 53 usually is, etc., or that horses use 45 for saddles, and so on.  An alternative (for Skyrim and SSE, anyway) might be to hard-code the list provided at http://wiki.tesnexus.com/index.php/Skyrim_bodyparts_number (established by modder consensus ca. 2012, at discussions linked from that page).

**Expected behavior**
The list you get when you pick "Edit" on "First Person Flags (sorted)" (under "BODT - Body Template" in ARMA, and "BOD2 – Biped Body Template" in ARMO) would show user-defined names, where specified, in place of all the "Unnamed" entries.

I suppose the dialog that pops up to present this list would need to auto-expand for width, or be expandable manually, or show a horizontal scroll bar, in the case of long input.

**Comment by zilav** [comment]
This list is defined in the RACE record. xEdit can already do that (read it directly from the RACE) but it is not implemented since absolute majority of mod edits are done with the human race.

**Comment by Darklocq** [comment]
I'm not sure I understand.  This seems to suggest that if I create a mod that does nothing but tweak RACE records, then I'll be able to customize this. However, that would take up a mod slot (unless I forced these changes into something else near the end of my load order).   However, there's not a single "human" race. I'm guessing I would make such a change in the DefaultRace's RACE record.  I'm not certain it's safe to change RACE records in mid-game; doesn't that cause greyface?  Even altering something as simple as an NPC's eye color does that (you end up having to re-export their heads in the CK).

Anyway, I was just thinking it'd be simpler to have this be a config option, since these body slot names have no purpose inside the game itself, just in viewing the ESP/ESM data as a modder.

**Comment by zilav** [comment]
The list of body slots is unique to race, defined in the RACE record. xEdit uses hardcoded list for a human because it is the most commonly used one in modding. You are not supposed to edit that list in the RACE though.
xEdit also shows the biped slot numbers which are unique, and any modder knows what these numbers mean because they are used in nif meshes. Idk how giving them some arbitrary labels will change anything.

**Comment by Darklocq** [comment]
I'm basically seeking to match the behavior of NIFSkope, Outfit Studio, and other tools, which (for Skyrim, anyway) give nthese names/descriptions as well as numbers. They're not "arbitrary" but agreed upon since around 2012, and documented at [Nexus](http://wiki.tesnexus.com/index.php/Skyrim_bodyparts_number), LoversLab, and other sites.  Modders are not going to have them all memorized (I certainly don't) because there's a whole lot of them, and they're not really in any particular order. This is why NIFSkope, et al., bothered with adding names/descriptions.

And they do matter. If you throw together some clothing mod that uses random slots, your gear will not be easily mix-and-matchable with anyone elses (your leggings with conflict with everyone else's cloaks, your right pauldron won't be wearable with anyone else's left rings, etc.).

I still don't know what you mean by " xEdit uses hardcoded list for a human", as there is no "Human" race (in Skyrim, at least).  I think you're telling me that it picks one of the human races by default as where to get these slots IDs from (I would think it's DefaultRace, but maybe Nord, I dunno).  Or maybe you mean that xEdit is creating its own "Human" race record on the fly and reading that, or ... I'm not sure.

I'll come back to my theme that being able to just specify (for a list of humanoid races) names for the slots in an external text file would be handy.  Otherwise I may have to do an "end of load order" ESP that has nothing but overrides for race records with this info and some other tweaks in it.  (I need to do this anyway to fix various old mods that are undoing Update.esm and Dawnguard and USLeEP's race tweaks and resetting things back to the original 2012 Skyrim.esm values.  I didn't know they were doing that, but it explains several minor issues I've encountered.)

**Comment by zilav** [comment]
If you can't memorize some arbitrary names instead of using slot numbers, then get the free Delphi Community Edition, rename slots as you please and build your own xEdit for personal needs.

Skyrim definitions already support loading list names from external optional text files, but this is done for lists that get extended by modders like map markers primarily with purpose to define additional values beyond vanilla ones, not to rename existings entries.

But I honestly lost any interest in this topic the moment you mentioned LoversLab. So if you can't build xEdit yourself, maybe someone else will implement similar feature for body slots.

**Comment by Darklocq** [comment]
Argh. Don't shoot the messenger, please.  I know that LL also assigned additional things to these slots (they generally seem consistent with the Nexus definitions, as to body area) simply because it comes up in a Google search for "Skyrim body slots".  The main list is the Nexus one, which hasn't significantly changed since 2012.

It's not a matter of "can't memorize some arbitrary names", it's about perfectly memorizing a long list of such names and exactly which numbers they correspond to, which is not something most people's minds are suited to, especially for very part-time hobbyist stuff like making some Skyrim armors.

I don't need to build my own TES5Edit; I can do what I need to do for my own convenience locally by editing the RACE records in my "end of the mod list race-cleanup" ESP.  This is about accepting the Nexus community-established conventions for these slots (since 2012) the way other tools like NIFSkope and BodySlide do, so that people put similar gear in similar slots and make less of a mess for all mod users.

**Comment by Darklocq** [comment]
PS: This _**is**_ records "that get extended by modders ... to define additional values beyond vanilla ones, not to rename existings entries."  They're just undefined in the vanilla game.

**Comment by Darklocq** [comment]
Update: I did some tests, and changing the RACE record (of DefaultRace, Nord, or anything else) has no effect on this at all.  The list really is hard-coded, and I have to suggest it would be more sensible to either use the list found for the race in question in the "winning" ESM/ESP in the load list (or else these Biped Object Name entries in the RACE record serve no purpose), or at least let us override the hard-coded list via a config file (presumably just a replacement list, though I suppose it could also be per-race).  Honestly, it seems like its almost more work that the app is doing to avoid using what the ESM/ESPs say and use its hard-coded thing rather than to just use what the ESMs/ESPs say like it does with everything else.  Kind of a localization issue, too.

I note that the hard-coded list isn't even using the same names as what is in the vanilla records, as it is providing names for Tail, DecapitateHead, and Decapitate and these are not present in Skyrim.esm (or Update.esm, etc.).  So, we're right back to what I said above: This _is_ records "extended by modders to define additional values beyond vanilla ones, not to rename existing entries".

I looked inside TES5Edit\Hardcoded\Skyrim.esp, hoping that's where it was hard-coded, but no luck. It seems to be in the actual compiled code.  Perhaps if it were moved into this Skyrim.esp that basically would serve as the config file for over-riding (though I suspect the contents of that ESP might change over time, as xEdit does new stuff).

**Comment by zilav** [comment]
Open any armor in CK, start changing Default Race to see how the list of slots below it gets updated accordinly. I have no idea what test and in what application you've made.

**Comment by SWE-DivX** [comment]
Update on this?

**Comment by ElminsterAU** [comment]
No

**Comment by Darklocq** [comment]
I don't understand zilav's response above, "Open any armor in CK, start changing Default Race to see how the list of slots below it gets updated accordinly. I have no idea what test and in what application you've made."  I've already played around with every discoverable way to try to address this, and filed as detailed a set of results-reporting here as I think I can muster.

Let's' summarize:
* The application itself is hardcoding this list, in compiled code. It is ignoring what is in the ESM/ESP records.
* These labels are not accessible for editing, in any configuration files.
* The stated condition way up top that TES5Edit will "load... list names from external optional text files, but [only] for lists that get extended by modders ... with [the] purpose to define additional values beyond vanilla ones, not to rename existing entries" is EXACTLY the case here.
* Not doing it for this particular set of names has lead to conflicting results/behavior between TES5Edit and other tools (NIFSkope, BodySlide, Outfit Studio, etc.), and is contributing to the problem of body-slot incompatibility between mods, despite efforts by the modding community to prevent this problem, starting way back in 2012.
* The app's hard-coding of a list of names for body slots is not just problematic and unnecessary, it's actually going out of the project's way to do something obtuse and inflexible, when the entire point of xEdit is help game editors get around the obtuseness and inflexibility of ESP/ESM and of the original tools for working with the format.

I'm not sure what else there is to say about the matter.  I'll reiterate that resistance, encountered above, to dealing with this problem seems to be predicated on a single developer having a personal negative reaction to anyone even mentioning LL in passing, despite it NOT being the source of the body-slot-naming community conventions but just another collective user of them.  What does it take to get past this stonewall?  We're asking you to remove pointless "obstruction" code and just allow the ESM/ESP cascade do what it does as with everything else.  We're not asking the devs to code up something new for a special case, but to remove special-case code that doesn't have any practical justification and has proved to be a pain.

**Comment by Darklocq** [comment]
PS: I don't mean that to sound ranty (I sometimes forget this medium lacks voice tone, body language, etc.). I'm BEGGING, not demanding!

I would try to just go fix it myself, but I don't know jack about this (complex) code base, and it's outside my sphere of competence. I'm a Perl, bash, PHP and JS geek, not an app coder, much less a Windows app coder. I run this game and tools for it in a VM under macOS, and am not likely to be able to compile a local copy anyway, unless someone's worked up how to get a full Windows dev environment running under VMware Fusion).

**Comment by eckserah** [comment]
The Biped Object Flags names are actually specified by bethesda on the RACE record that the NPC uses. The names on there are the OFFICIAL names for them and any other name used in this case is incorrect and inaccurate. The only exceptions would be any flags that are labeled as "Unnamed". Anything that references Biped Object Flags should have them named based upon the race they belong to but that is not currently implemented. Try creating an armor in the CK an you'll notice that you HAVE to choose a race in order to do so and the race you select dictates what flags it can have

**Comment by Darklocq** [comment]
I don't know of anyone who wants to do anything with these other than the "Unnamed" ones. Many of them have become effectively named (since 2012) widely though unofficially as a modder's convention for extended gear options. But attempting to change them in the RACE records with TES5Edit has no effect.  That's the gist of it.  For my part, I want to both a) name them for following that convention for my own use, and b) also produce a mod (probably a variant of my Race Records Master mod) that does this for everyone who wants to work on gear modding.

**Comment by SWE-DivX** [comment]
> 
> 
> The Biped Object Flags names are actually specified by bethesda on the RACE record that the NPC uses. The names on there are the OFFICIAL names for them and any other name used in this case is incorrect and inaccurate. The only exceptions would be any flags that are labeled as "Unnamed". Anything that references Biped Object Flags should have them named based upon the race they belong to but that is not currently implemented. Try creating an armor in the CK an you'll notice that you HAVE to choose a race in order to do so and the race you select dictates what flags it can have

We are NOT talking about CK. We wish tes5edit reads the Race body flags name. It would make it easier when we create new races with new body parts. And of course armor modding for new races.
this would be seen more as a plus at the edge. ElminsterAU you have created one of the best tools for us noobs moders.

**Comment by Sharlikran** [comment]
This is being looked into and will be added to the next 4.1.3x iteration. Possibly a 4.1.3b depending on when it is finished. You will find it on our discord once it is ready. Do not ask what the status is on our discord. The conversation will be locked.

I understand @Darklocq that you were requesting or begging for the feature. It did sit dormant and you didn't constantly bother us so no worries. For the future I would appreciate the same type of request and patience.

However, for anyone coming along in the future and for @SWE-DivX I do need to reiterate something that maybe you missed from our [README.md](https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.4/README.md) 

This is our GitHub issue tracker. It is not the nexus. You are expected to make polite requests not demands. Irrespective of our response you do not argue about the answer. xEdit is not a replacement for the CK and it does not matter what the request is. If we choose not to add a feature and direct you to using the CK for a different request, responding in any kind of abrasive manner will be met with denial to post in our issue tracker at all. Consider this your warning.

Also consider it your warning for Discord as I will not tolerate any rebuttal in our Discord once this is locked.
