### ISSUE TITLE
UI Themes miscategorizing some dark ones as light

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#681]
**What is the version of xEdit you are using?**
TES5Edit 4.0.1 x64 (AAEA6B67) – Will upgrade to 4.0.2 today, but I don't think this version number is going to matter.

**Describe the bug**
This is trivial, but might as well report it anyway.

Under "Options" > "UI Theme" in the hamburger menu, several black or dark-grey themes are listed in the "Light" category rather than "Dark":
* Metropolis UI Black
* Metropolis UI Dark
* Obsidian

These might also qualify (they're super-saturated rather than dim, but are using light text on a background of low luminosity and deep color, which is one definition of 'dark'):
* Metropolis UI Blue
* Metropolis UI Green
* Windows 10 Blue
* Windows 10 Green
* Windows 10 Purple

**Comment by ElminsterAU** [comment]
You are wrong.

The relevant criteria if a theme is a "dark" or "light" theme is based on comparing the luminosity of the default text color for controls with the default background color for controls (in other words, the background and text color that will be used for the tree view, edit controls, and such).

All the themes you listed are correct classified according to this criteria.

**Comment by Darklocq** [comment]
I see what you mean. When toying around with them, I finally figured that the "dark" ones all have light text on dark background (and vice versa for "light") in the main window, regardless of other color/luminosity matters in other parts of the interface.  So, I guess close this as invalid.  Sorry for the non-useful report.
