### ISSUE TITLE
The path bar covers the forward and back buttons if the window is too small

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#682]
**What is the version of xEdit you are using?**
FO4Edit 4.0.1p RC6a for 4.0.2 (8AA47CA5)

**Describe the bug**
When the window for xEdit is too small (due to monitor resolution or just not having it full screen), the forward and back buttons are hidden by the path bar. It will extend until it reaches the first speedbutton (Help) rather than until it hits the back arrow. 

**To reproduce**
1) Launch xEdit
2) Reduce the size of the window until the path bar reaches the back button, then make it smaller

**Expected behavior**
The path bar stops at the back button

**Screenshots**
![2019-04-02 20_34_37-FO4Edit 4 0 1p RC6a for 4 0 2](https://user-images.githubusercontent.com/12984164/55444944-e3f56680-5586-11e9-81e8-9a18633c0291.png)

**Comment by Sharlikran** [comment]
@ElminsterAU Nobody would do this, but I tried it and the odd thing is, the buttons like help and videos and such are not covered just the back and forward button. So he does have a point. I also figure he knows he can shrink them.

![image](https://user-images.githubusercontent.com/1912426/55665144-db9f6480-57ee-11e9-8f6c-15d003d4f478.png)

Without scaling
![image](https://user-images.githubusercontent.com/1912426/55665168-38028400-57ef-11e9-9ce1-3ea3e4987cea.png)

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2j)
