### ISSUE TITLE
Camera Data not transferable (without deletion workaround)

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#683]
**What is the version of xEdit you are using?**
TES5Edit 4.0.1 x64 (AAEA6B67) starting session 2019-04-09 02:06:18
(I meant to move to 4.0.2 stable Nexus version, but didn't get around to it yet. I didn't see this addressed in the release notes, so I think it's still a valid issue.)

**Describe the bug**
Camera Data (under "MNAM - Map Data") in Worldspace records doesn't appear copyable by any means (unless you hit on the idea of nuking it in the target first).  While it's not a fatal bug, it's certainly inconsistent with the rest of app's record-copying behavior.

**To reproduce**
1. Have Skyrim with Update.esm and Dawnguard.em at least.
2. Load any mod that places anything in the outside game world. For kicks, load several mods that do so. (Some quick test conditions you can use: I had both [HorseInventory.esp](https://www.nexusmods.com/skyrim/mods/15842/) and [Armored-Horses.esp](https://www.nexusmods.com/skyrim/mods/13348/) loaded, to clean up their various essentially duplicate records in prep for a merge).
3. Open Worldspace 0000003c Tamriel Skyrim. Note that the record for this was missing both "MHDT - Max Height Data" and "Camera Data" information in Dawnguard.esm.  Update.esm (which loads earlier but was released later) included this data.  Mods veer back and forth including and deleting this info, depending on whether their overrides were from Update.esm or Dawnguard.esm or whatever.  (Using my horse test mods, HorseInventory is using Update.esm's version of the worldspace, and Armored-Horses.esp is using Dawnguard's.)  If one assumes that the later release is correct, or even that the later-loading official DLC is correct, one cannot actually do anything about it.
4. You can edit the MHDT material normally, either manually or by drag-and-drop copy-paste.
5. Try to add/edit the Camera Data entry in the last-loading mod. You can enter a value like "0" or "3" or something in the main Camera Data line, but it seems to have no effect. You cannot edit the individual subcomponents like Min Height, Max Height, and Initial Pitch at all.
6. Try to copy-paste from the mod to the left into the last one on the right, by drag-and-drop. It doesn't work.  It won't replace the Camera Data material, whether you drag Camera Data or the entire MNAM block.

**Expected behavior**
Everything in MNAM, including Camera Data and its Min Height through Initial Pitch entries, should be editable manually, and by the drag-and-drop method of copy-pasting (by dragging the entire MNAM, or just Camera Data, or just a sub-element thereof).

There is one workaround, and that is removing the entire MNAM record from the target mod; you can then drag-drop a new one from a mod to the left of it.  This is the only record type I've encountered where drag-drop and manual editing do not work unless you first destroy the original record block in the target mod manually and completely.

**Additional context**

I think this MNAM inconsistency stuff (in the game files, I don't mean in xEdit's behavior) may be the ultimate cause of some users ending up with an unusable world map (and thus a basically unplayable game). The only currently known fix for this is the [World Map Min_Max Height Pitch Tweak](https://www.nexusmods.com/skyrim/mods/26998/) mod, and which variant of it will work to resolve this for someone is a tedious trial-and-error exercise (nor a sure thing – it can stop working suddenly, especially if it is not below/after the bashed patch, a mod-loading tweak most people wouldn't ever contemplate due to blind faith in Wrye Bash).

Whether the Update.esm or Dawnguard.esm values for these records are "the one true version" doesn't seem to have been well-tested by anyone, perhaps owing to it being hard to figure out a way to even edit these records.

**Comment by zilav** [comment]
Because some fields in MNAM are optional and don't physically exist in older form version records. And in a lot of other places too across different records.

Force adding them by "nuking" without updating form version won't guarantee to work in the game depending on what Bethesda's reader code does in this particular case - check form version or check MNAM size.

Resaving plugins in CK is the only correct way of updating old form version records and adding optional fields.

**Comment by Darklocq** [comment]
Thanks for the tip. I actually did notice that the record size was mis-matched, and found that mystifying.
