### ISSUE TITLE
Cannot edit ARMO "BODT - Body Template" > "General Flags (sorted)" > "(ARMO)Non-Playable"

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#684]
**What is the version of xEdit you are using?**
TES5Edit 4.0.1 x64 (AAEA6B67) starting session 2019-04-09 02:06:18
(I meant to move to 4.0.2 stable Nexus version, but didn't get around to it yet. I didn't see this addressed in the release notes, so I think it's still a valid issue.)

**Describe the bug**
Turning this option on does nothing. The change is not saved.

**To reproduce**
1. Do "Edit" on "General Flags (sorted)" under an ARMO record.
2. Turn on the checkbox for "(ARMO)Non-Playable", and click "OK".
3. Notice that it did not actually set that flag on.

This happens regardless whether "Non-Playable" is also set in "Record Header" > "Record Flags".

See links below for mods I was testing with.

**Expected behavior**
It should be on if you set it on.

**Additional context**
Looking at some barding (horse armor) mods, it appears (I'm still testing this) that the technique for getting barding and saddles you can carry around as inventory but not equip on yourself is to _not_ have "Non-Playable" set in "Record Header" > "Record Flags" (which affects ability to pick up stuff and put it inventory), but _do_ have "(ARMO)Non-Playable" set in "BODT - Body Template" > "General Flags (sorted)".  This is what Armored-Horses.esp is doing.  Craftable Horse Barding.esp is not doing this, and I find that the player can actually equip saddles from that mod (at least for a while; they seem to get unequipped later, probably due to race records, and it may be that they simply appear to be equipped in the inventory list but are not actually being equipped on the character model – I suppose the real test would be to enchant one, and then apparently-equip it, and see if you're getting the buff it provides, whether you can see it on you or not).  Another such mod, HorseInventory.esp, was setting "Non-Playable" in "Record Flags" which made it impossible to get the items, though those particular ones are Outfit pieces one would not normally have access to.  (In a merger of all these mods, it's desirable to access those, so that they can be removed and replaced with crafted ones, and the old outfit copy isn't sitting around invisibly reducing carry capacity).

The mods in question (for Oldrim), which are convenient for testing:
* [Armored-Horses AKA Horse Armors for Skyrim](https://www.nexusmods.com/skyrim/mods/13348)
* [Horse Inventory](https://www.nexusmods.com/skyrim/mods/15842/)
* [Craftable Horse Barding](https://www.nexusmods.com/skyrim/mods/64069/)

**Comment by zilav** [comment]
Works fine for me.

Anyway BODT is older form version format, you need to resave plugin in CK to replace it with newer BOD2 subrecord which doesn't have flags at all.

**Comment by Darklocq** [comment]
Just a re-save? No manual twiddling?  Want to make sure I don't break something, and I do hope that the mod in question isn't actually dependent on that apparently obsolete flag being set.

**Comment by Darklocq** [comment]
PS: I'm looking at a BOD2 right now, in a more recent mod, and it still has these General Flags available: (ARMA)ModulatesVoice, and (ARMO)Non-Playable (plus Unknown 2–4 and 6–8), same as a BODT.

**Comment by Darklocq** [comment]
Could it be BODT that doesn't have the flags and that's what made the flags not saveable in my test case?

**Comment by Darklocq** [comment]
Just fired up xEdit again and tested this: the flags options show up for both record types, and are saveable in BODT, but not in BOD2. My initial report was mistaken, in mentioning BODT rather than BOD2 (in my defense, I was working with a merged ESP that had both variants in different records, depending on how old was the mod the merged-in record came from, and I didn't notice the one-character discrepancy).

I think the actual issue to report, then, is that the flags should be greyed out or just not appear for BOD2, for which they would be invalid.

**Comment by zilav** [comment]
They don't appear for BOD2, only for BODT. xEdit compares both subrecords against each other, so if you are browsing an override of old form version record with BODT by new form version record with BOD2, the flags will "appear" but they still don't exist and not editable in BOD2. This is intended.

**Comment by Darklocq** [comment]
I just created a new ESP (which forces BOD2 not BODT), and added an ARMA and ARMO in it, and if you edit "General Flags (sorted)" in them, you still get the option to turn these flags on, they just don't save as turned on when you do so.

[Screen shot](https://ibb.co/fXGf9Qm)

**Comment by zilav** [comment]
Ah I forgot that the field which got deprecated is Armor Type, not flags.

**Comment by Darklocq** [comment]
OK.  Anyway, it was just weird that the flags options appeared, not greyed out, and selectable as checkboxes but would not save.  I guess the solution would be to not make them selectable if the format can't support them?

**Comment by Darklocq** [comment]
PS: That itself would be a good indicator you have a mod with an old format. When you're editing quickly, you may turn on a checkbox for this flag or that, and not notice it wasn't saved, but if you can't do it at all, then you know something is up.

**Comment by zilav** [comment]
General Flags in BOD2 are virtual, xEdit shows them only to be able to align BODT and BOD2 fields against each other for conflicts resolution. As they are virtual, they are not saved.
