### ISSUE TITLE
PC Level Mult and Auto Calc Stats not connected

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#687]
**What is the version of xEdit you are using?**
4.0.1

**Describe the bug**
According to [the official docs](https://www.creationkit.com/index.php?title=Stats_Tab), if PC Level Mult is enabled, so must be Auto Calc Stats; both are under NPC > ACBS - Configuration > Flags (sorted). Having the former on without the latter isn't a valid configuration for an NPC, and will not work (it will be as if both flags are off).

**To reproduce**
1. Pick an NPC.
2. Edit ACBS - Configuration > Flags (sorted).
3. Enable PC Level Mult.
4. Disable Auto Calc Stats.
5. Note that xEdit treats this as valid and allows you to save it this way.

**Expected behavior**
Turning on PC Level Mult should automatically also turn on Auto Calc Stats, and turning Auto Calc Stats off should auto-disable PC Level Mult (but not vice versa – it's a one-way dependency, and Auto Calc Stats does not require PC Level Mult).

**Comment by zilav** [comment]
This can be done (and is done in some records iirc), however this is by far not the only place where several fields/flags/subrecords must edited simultaneously to correctly work in the game, and such knowledge is always a user's responsibility only. You can easily make edits that will do far worse up to crashing the game and xEdit doesn't hand hold from doing that either.

**Comment by Darklocq** [comment]
Fair enough.
