### ISSUE TITLE
xEdit not creating modern format by default

### ISSUE THREAD

**Issue by Darklocq** [TES5Edit/TES5Edit#689]
**What is the version of xEdit you are using?**
4.0.1

**Describe the bug**
Created a new ESP in the process of making an override (that is, I did "Copy as override into..." and picked the new file option).

It ended up being an ESP that did not support Mount Data entries in the RACE records, nor the "SNAM - Description" subrecord of the File Header record.

I would assume this is because I was doing an override from Skyrim.esm, and that if I'd done it from something more modern, like Dragonborn.esm, that the result would have been different, but I'm not certain of that.

It seems strange and probably unintentional that xEdit would write out an older format just to match the source file unless copying a record form that actually required it.

I worked around the issue in this case by loading the new mod into the CK and re-saving it.

**Comment by zilav** [comment]
There is no difference between copying as new or as override apart from the FormID number the copied record gets. Record's data itself remains the same as the original. If you copied old format record without Mount Data then the copy will also lack it. As I said open and save plugin in CK to update records to the latest form version and add missing fields.
