### ISSUE TITLE
scheduled save from save failure not removed on subsequent successes

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#694]
**What is the version of xEdit you are using?**
FO4Edit 4.1.2c EXTREMELY EXPERIMENTAL (842FBA0D) starting session 2019-05-06 00:35:29

**Describe the bug**
when saving with direct saves enabled, if there's a failure to save with the mod file being locked, the save will be scheduled to try replacing it upon xedit being closed. if the problem is corrected (the mod file is no longer locked) and a successful save is made, it replaces the file like it should, but on closing xedit the older scheduled save will replace the newer one.

**To reproduce**
1) try to save a mod while the file's locked. for example, fallout 4 process is still running. see in xedit that saving failed.
2) kill the fallout 4 process so the file is unlocked.
3) modify the mod and save again. see that saving succeeded and the original esp file was replaced with new.
4) close xedit.

**Expected behavior**
i expected the scheduled save to be cancelled after a successful one happened so the newest edits are preserved. instead it still fires off the scheduled replacing and overwrites newer work with older.

**Comment by ElminsterAU** [comment]
should be fixed with commit referenced above (should be in 4.0.2j)
