### ISSUE TITLE
Typo in Weap>DNAM>Animation Type: Balistic -> Ballistic

### ISSUE THREAD

**Issue by KeeltheSwift** [TES5Edit/TES5Edit#695]
**What is the version of xEdit you are using?**
FNVEdit 4.0.2 (9D0B47A5) starting session 2019-05-07 23:49:38

**Describe the bug**
Under DNAM>Animation Type, all instances of Ballistic misspelled as Balistic (Specifically Pistol and Rifle)

**To reproduce**
1. Go to any weapon that can be edited (e.g. 00004337 WeapLeadPipe Lead Pipe in TaleofTwoWastelands.esm)
2. Click on 'View'
3. Scroll down to 'DNAM>Animation Type'
4. Double Click "Melee (1 Hand)" to bring up drop-down menu listing Animation Types. Find Typo there.

**Expected behavior**
Pistol/Rifle - Balistic (1/2 Hand) -> Pistol/Rifle - Ballistic (1/2 Hand) _[2 l's]_

**Screenshots**
![image](https://user-images.githubusercontent.com/26212457/57350580-9db69880-712c-11e9-94da-db1b27b8b923.png)

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2j)
