### ISSUE TITLE
Double Listing of "Decrease Equip Time" in Weapon Mod Effect

### ISSUE THREAD

**Issue by KeeltheSwift** [TES5Edit/TES5Edit#696]
**What is the version of xEdit you are using?**
FNVEdit 4.0.2 (9D0B47A5) starting session 2019-05-07 23:49:38

**Describe the bug**
Mod Effect has "Decrease Equip Time" listed twice in drop down menu

**To reproduce**
1. Go to Weapons section of any non-FNV .esm/.esp (basically where records can be edited)
2. Click on Any weapon whose records you can edit
3. Scroll down to DNAM>Effect - Mod 1/2/3
4. Double Click to see dropdown menu listing all possible Mod Effects

**Expected behavior**
Only one instance of "Decrease Equip Time" or at least some way to distinguish the two.

**Screenshots**
![image](https://user-images.githubusercontent.com/50393611/57351512-271b9a00-7130-11e9-8378-129aa3178ef1.png)

**Additional context**

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
