### ISSUE TITLE
Cannot apply scripts using Classes, SysUtils, StrUtils or Windows units

### ISSUE THREAD

**Issue by pragasette** [TES5Edit/TES5Edit#697]
**What is the version of xEdit you are using?**
`SSEEdit 4.0.2 (F796EF8E) starting session 2019-05-10 15:52:06`

**Describe the bug**
 Applying a script which uses any unit in the title results in an error.

**To reproduce**
1. Go to `Edit Scripts` folder
2. Copy the `_newscript_.pas` template into a new ``userscript.pas``
3. Update it as suggested at https://tes5edit.github.io/docs/11-Scripting-Functions.html#s_11-2 example: [userscript.zip](https://github.com/TES5Edit/TES5Edit/files/3166896/userscript.zip)
4. Run `SSEEdit.exe`
5. Right click on any record, _Apply Script..._, choose _userscript_, _OK_
6. Execution fails with:
   > Cannot open file "C:\Path\To\SSEEdit\Edit Scripts\Classes.pas". The system cannot find the file specified.

**Expected behavior**
The script should be applied successfully, as it was with SSEEdit 3.2.2.

**Screenshots**
![classes-pas-error](https://user-images.githubusercontent.com/34663739/57535147-f0b56900-7341-11e9-9279-5b72c6b0a468.png)

**Comment by Sharlikran** [comment]
@FeelsMemeMan ( ͡° ͜ʖ ͡°)#4904 The intriguing thing is that people have been posting this and the solution for weeks now. Each time they are surprised so to the fix. It's not in Wrye Bash docs since it's not an Wrye Bash issue. It's an MO2 bug. It just prompted a nasty response on the nexus.

**Comment by fwdekker** [comment]
The suggestions you link to in step 3 are necessary for your project to compile in an IDE. However, you should remove the `uses` for `Systems.*` units when running it in xEdit. I'm not sure whether this is an error in the documentation or in the implementation, but I think it would be great if you could have the same code compile in both an IDE and in xEdit. This comment is more of a hotfix for you than a real solution to the issue though.

**Comment by pragasette** [comment]
@FWDekker, thank you for your comment, I'm aware you can remove the `uses` clause to execute the script, but that's not practical during the development phase, if you want to use a linter.

The only workaround for me is to stick with release 3.2.2 while writing scripts.
I even tried using conditional compilation:
```pascal
{$IFDEF DCC}
uses Classes;
{$ENDIF}
```
but unfortunately xEdit's Pascal doesn't seem to honour such directives.

In case there were no plans to support the feature any more, at least I meant this report to suggest the documentation to be updated accordingly, as it can be jarring to newcomers.

**Comment by zilav** [comment]
I think this is because in newer Delphi versions (which is used to compile new builds) units have namespaces, so it should be `System.Classes.pas` for example.

**Comment by pragasette** [comment]
@zilav, thank you, tried that but no luck: it strips the `System` namespace and still looks for the unit in the working directory.

Another option might be symlinking or copying those units to the script folder, but for some reason I found it harder than it sounds.

**Comment by zilav** [comment]
Looks like the interpreter itself strips them. Probably just need to hardcode all the standard lib unit names instead of checking them in compiled package information of executable.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2m)
