### ISSUE TITLE
Multiple Fallout New Vegas Installs 

### ISSUE THREAD

**Issue by a2937** [TES5Edit/TES5Edit#698]
**What is the version of xEdit you are using?**
FNVEdit 4.0.2 (9D0B47A5) starting session 2019-05-11 18:35:14

**Describe the bug**
I keep three different installations installed of Fallout New Vegas. I have to rename the directory constantly in order to get to the folder of the right install. It automatically defaults to the one with the default name. 

**To reproduce**
1. Install Fallout New Vegas 2 times
2. Open XEdit to alter a plugin on a different installation
3. Look at the plugins found for the normally named directory

**Expected behavior**
Some sort of prompt should come up to specify the location the installation of the game directory at start if the game isn't found. If it is found, there should be a spot in settings to open a different install directory. 

**Additional context**
I have a vanilla Fallout new vegas install, a new California install, and a Fallout Tale of Two Wastelands install. Those two mods do not play nicely with each other at all.

**Comment by ElminsterAU** [comment]
This is not an "issue". Please don't use issue reporting like a forum for questions about how to use the program. Parameters to point xEdit at a different data folder are documented on the information tab and in other places.
