### ISSUE TITLE
Cleaning only certain plug-ins

### ISSUE THREAD

**Issue by NiamhDream** [TES5Edit/TES5Edit#702]
TES5Edit 4.0.2 (SSEEdit 4.0.2 before I renamed it to work with Skyrim)

Not exactly a bug, but a question on how to clean just certain plugins and leave others alone.

I only want to clean some of my plugins because I have learned from the authors of some that their plugins shouldn't be cleaned because it can cause issues (and I have found it to be true when I accidentally cleaned these plugins in the past). The only plugins that LOOT shows as needing cleaning are Update and the 3 DLCs. I have tried using the old method of cleaning just certain plugins, but get a message "This function has been made obsolete by the introduction of Quick Auto Clean Mode." 

Do I have to use Quick Auto Clean Mode, or is there a way to clean only certain plugins? Or, if I have to use QAC, can I set it to always exclude certain plugins?

**To reproduce**
Attempt to clean only certain plugins by cleaning them in the old manner.
i.e. "Apply Filter for Cleaning", etc

**Expected behavior**
I receive a message that that feature has been made obsolete

**Comment by ElminsterAU** [comment]
Every time you run QAC, it will only clean a single file that you select.
