### ISSUE TITLE
[Tes5edit v4] Copy to selected records function working only for 2-4 selected records

### ISSUE THREAD

**Issue by TokcDK** [TES5Edit/TES5Edit#703]
(versions 4.0.2 and 4.1.2c)
One of most usable function was function "Copy to selected records" wich was using for many selected reecords. Tried first time to use it on v4 and found it working only for 2-4 selected records. It is same as not working because it have no sense to use it for several records wich can be easy changed manually. Tried to copy conditions list from one package to other 100 selected packages. In version 3 all is coping fine.

**Comment by ElminsterAU** [comment]
Read what's new. There are no such limits to copy to selected records when used correctly.

**Comment by TokcDK** [comment]
Ok. Found <Rewritten "copy [multiple] to selected records"> part in readme. Many things was changed and when the program using many years with same functions wich suddenly stop working.. I understood why v4 caused so many ass burning from users.) And many people have very bad english to read english readme to correct understand all new changes for same functions wich was used all this years and because it is so burning from new changes for them.
