### ISSUE TITLE
[xedit v4.0.2] Quickcleaning function

### ISSUE THREAD

**Issue by TokcDK** [TES5Edit/TES5Edit#704]
It is not bug like info. ITM\UDR cleaning function was moved frome main program but still let clean only one esp in one time (I know why esps cleaning by one).
In version 3 for save time for cleaning on many esps I opened all esps in xedit then applied Cleaning filter and ITM\UDR cleaning action and then instead of saving I just made screenshot of esps wich was offered for save by xedit and just exit without saving. After this I used this screenshot for open only plugins wich was offered. It is much faster than open each esp\esm from hundreds one by one. New standalone cleaning donot let me to process all esps and get list of plugins wich have records for cleaning.
It would be good to be possible to get list of all plugins wich only need to clean and then open them one by one to save many time.

**Comment by ElminsterAU** [comment]
That is not a reliable way to find what files need cleaning. It's perfectly possible for a file to not have anything to clean when loaded together like that, while finding records to clean when loaded on its own. Besides, the old functions are still available to experts (make sure to read what's new with attention to detail).

**Comment by TokcDK** [comment]
> That is not a reliable way to find what files need cleaning. It's perfectly possible for a file to not have anything to clean when loaded together like that, while finding records to clean when loaded on its own. Besides, the old functions are still available to experts (make sure to read what's new with attention to detail).

Yeah as I already said "(I know why esps cleaning by one)" and not all esp in wich was found dirty records will be with dirty records if opened one by one but it is still faster to open only this esps from list and not all active esps. Also found info about IKnowWhatImDoing parameter.
Maybe I dont know and there is exist function to get list of esps with found dirty records to open them by one for cleaning instead of screenshot?
Maybe will be possible to modify quickcleaning function for example to two steps: First find dirty records in all list and second open\clean\save esps from this list one by one?

**Comment by ElminsterAU** [comment]
What part of "the old functions are still available" wasn't clear?

**Comment by TokcDK** [comment]
..Also found info about IKnowWhatImDoing parameter.
Maybe I dont know and there is exist function to get list of esps with found dirty records to open them by one for cleaning instead of screenshot?
Maybe will be possible to modify quickcleaning function for example to two steps: First find dirty records in all list and second open\clean\save esps from this list one by one?

**Comment by Sharlikran** [comment]
@TokcDK There is not a way to keep the program open and release everything (clear memory) and start over. I don't remember why though.
