### ISSUE TITLE
[Feature Request] xEdit Macros

### ISSUE THREAD

**Issue by Elscrux** [TES5Edit/TES5Edit#705]
Many tasks in xEdit are repetitive and most people are not skilled enough or they don't have the time to create a script that does their work.
I have an idea how this could be changed although I am not sure how much effort this would be.
My idea is that the the user presses a key and from then on every action he performs on a record is 'recorded'.

Example:
![1](https://user-images.githubusercontent.com/34755314/58425629-8bc87580-809a-11e9-9b71-1db9dd385617.png)
![2](https://user-images.githubusercontent.com/34755314/58425636-8ec36600-809a-11e9-94d1-3891841192c1.png)
![3](https://user-images.githubusercontent.com/34755314/58425637-8ff49300-809a-11e9-83eb-bc8e510d96c1.png)
![4](https://user-images.githubusercontent.com/34755314/58425642-91be5680-809a-11e9-8afe-9fbb4f491020.png)

Now the user could select one or more records by the same signature and the same action will be done on pressing a key.

Another way would be that a xEdit script would be created that shows exactly what the user has done so it is much easier to start a script.
![1](https://user-images.githubusercontent.com/34755314/58427629-7e15ee80-80a0-11e9-923f-c750874597b4.png)
![2](https://user-images.githubusercontent.com/34755314/58427630-7eae8500-80a0-11e9-8ca9-98dac079eb21.png)
![3](https://user-images.githubusercontent.com/34755314/58427632-7fdfb200-80a0-11e9-8390-ceac6e9994b0.png)
```
unit UserScript;

function Initialize: integer;
begin
end;

function Process(e: IInterface): integer;
begin
	SetElementEditValues(e, 'DATA\Value', '165');
end;
end.
```

And something like that is generated. Would that be possible? It is probably very difficult but maybe you have a better idea how to realize my idea.

**Comment by ElminsterAU** [comment]
Very complex, this isn't going to be a near term feature.

**Comment by Elscrux** [comment]
> 
> 
> Very complex, this isn't going to be a near term feature.

Unfortunately that was probably obvious^^

**Comment by Sharlikran** [comment]
Will be marked for consideration in the future, thank you.
