### ISSUE TITLE
[Bug] TES5EditQuickAutoClean failed to rename Dawnguard save

### ISSUE THREAD

**Issue by Aareon** [TES5Edit/TES5Edit#706]
**What is the version of xEdit you are using?**
TES5Edit 4.0.2

**Describe the bug**
After cleaning Dawnguard.esm and attempting to close, a dialog appears to notify me that TES5Edit failed to rename the save to Dawnguard.esm.

**To reproduce**
1. Go to MO2, run TES5EditQuickAutoClean
2. Select `Dawnguard.esm` in Quick Auto Clean dialog and click `OK`
3. Wait for filter to do its thing
4. `Ctrl+S` to ensure there are no unsaved changes
6. Close TES5EditQuickAutoClean
7. See error

**Expected behavior**
TES5Edit renames the save file to `Dawnguard.esm` and closes succesfully.

**Screenshots**
1. [After cleaning](https://i.imgur.com/JGetKmi.png)
2. [Ctrl+S](https://i.imgur.com/8sbARYf.png)
3. [Close TES5EditQuickAutoClean](https://i.imgur.com/csqwLee.png)

**Additional context**
I'm using LOOT and TES5Edit.

**Comment by ElminsterAU** [comment]
Known MO2 bug. Please address this with MO2 developers.

**Comment by Aareon** [comment]
@ElminsterAU  If its a known bug, would you mind linking me to the issue pertaining to it?

**Comment by LostDragonist** [comment]
There wasn't any official GitHub issue for it until you created it.  So...

https://github.com/ModOrganizer2/modorganizer/issues/741
