### ISSUE TITLE
"Clean masters" function doesn't remove all masters at first use.

### ISSUE THREAD

**Issue by andrelo1** [TES5Edit/TES5Edit#708]
**What is the version of xEdit you are using?**
4.0.2

**Describe the bug**
"Clean masters" function doesn't remove all masters at first use, you have to click twice to remove all masters.

**To reproduce**
1. Create in CK FormList.
2. Add to it one form from Skyrim.esm, one from Dawnguard.esm and one from Dragonborn.esm.
3. Save and open in xEdit.
4. Remove two forms from Dawnguard.esm and Dragonborn.esm.
5. Clean masters.
6. Dragonborn.esm will not be removed after first use, but will be removed after second.

**Screenshots**
https://imgur.com/a/TrWnhSC

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2j)
