### ISSUE TITLE
[4.0.2] Strings is rewriting by "Copy as override (with overwriting) into..." function

### ISSUE THREAD

**Issue by TokcDK** [TES5Edit/TES5Edit#709]
For example. We have esp with strings for several languages.
We have several magic effects in this esp.
We have patch-esp where was added additional conditions for this magic effects but all other records and names is identical
We opened main esp and patch with conditions
If we will add new conditions manually by drag and drop to the main esp then all will be fine and this esp can be saved and if we will switch on another language strings will be no problems and all names will be changed to the current lanfuage.
But if we will use "Copy as override (with overwriting) into..." to write new conditions to the main esp then if we will try to switch to any other exist language for the esp then we will get "<Error: Unknown lstring ID ########>" instead of names.
It would be good to be possible to write only what was changed\added. But maybe kind of function is already exist somewhere?

**Comment by ElminsterAU** [comment]
Copy as override completely replaces the existing record. There really isn't any way to change that. This will result in new string IDs being allocated. There isn't much I can do about that. Localised modules (using external strings files) are really not suitable for editing.
