### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION 4.1.2c

### ISSUE THREAD

**Issue by zhesam** [TES5Edit/TES5Edit#710]
SSEEdit 4.1.2c EXTREMELY EXPERIMENTAL
Vortex 0.18.9

Tried run QuickAutoClean on RelightingSkyrim_SSE.esp
mod ver 1.0.6

running QAC on other mods are fine

log:
[SSEEditQuickAutoCleanException.log](https://github.com/TES5Edit/TES5Edit/files/3298913/SSEEditQuickAutoCleanException.log)

Same issue when apply any filters on this mod in SSEEdit
[SSEEditException.log](https://github.com/TES5Edit/TES5Edit/files/3298944/SSEEditException.log)

dunno is it mod related or xEdit issue.

**Comment by ElminsterAU** [comment]
Can you please try 4.0.2 instead and let me know if that works or has the same issue?

**Comment by zhesam** [comment]
Hi, sorry for long reply.
tried  4.0.2 and has no issues - neither on filter apply, neither when QAC
