### ISSUE TITLE
[Feature Request] Renumbering Assets IDs

### ISSUE THREAD

**Issue by paladinkolovrat** [TES5Edit/TES5Edit#711]
Suggestion
Add to "Renumber FormIDs" function ability to renumber(or create renumbered copy of) associated assets like facegengeom or voices files etc

That's pretty much obvious result of option, but not present, only in merging scripts or software.
This is absolutely must-have for manual merging. I use this mechanics: copy as override all entries of merging mods into new plugin, filter to exclude vanilla IDs, and renumber everything left. This help to avoid most errors(which surely will appear when using merging software) and give ability to copy entries with errors and script properties(VMAD Virtual machine or smth) without any issue(FO4).

**Comment by paladinkolovrat** [comment]
Another thing is renumbering of single entry - it would be nice, if default FormID in window will be the first free FormID with Load Order of destination plugin.

**Comment by Sharlikran** [comment]
This kind of automation has been suggested before. We typically do not do things like this. I have no issue with the request. However, this is not anything that would be done any time soon. One reason being that the file names for the voice files are not even contained in the plugin. The name of the files for VMAD are originally generated by the CK and typically are not changed even if you add a master in the CK.

The request will be closed and marked for consideration in the future but please do not ask for an update. If the feature is added, it will be in the change notes.
