### ISSUE TITLE
String list does not allow duplicates exception when viewing Quest record

### ISSUE THREAD

**Issue by garthand** [TES5Edit/TES5Edit#712]
**What is the version of xEdit you are using?**
4.0.2

**Describe the bug**
After loading this localized plugin, (I haven't seen the behavior on another plugin), expanding the Quest category and clicking on the contained quest raises the exception "String list does not allow duplicates."

[Unofficial Stalhrim Fur Armor Patch.zip](https://github.com/TES5Edit/TES5Edit/files/3308863/Unofficial.Stalhrim.Fur.Armor.Patch.zip)

**To reproduce**
1. Load this plugin (I haven't had it occur with any others)
2. Expand the Quest category
3. Click on the ccBGSSSE057_MiscQuest Quest
4. See the error

**Expected behavior**
No error message should appear when clicking on the quest.

**Screenshots**
![error](https://user-images.githubusercontent.com/8093079/59819782-0168df80-92ef-11e9-8206-9f3b9cdf15e4.png)

**Additional context**
The issue only seems to occur with plugins touching this record, and only when they are localized. I tried re-localizing the plugin but it seems to be something about the way the localization is generated or xEdit is reading the localization.

**Comment by garthand** [comment]
As an added note, I wonder if this occurs because the record in question is an ITM

**Comment by ElminsterAU** [comment]
Most likely the strings files are going to be corrupted and contain multiple entries with the same id

**Comment by ElminsterAU** [comment]
I don't have the files necessary to test this.
Please download xEdit 4.0.2i (or newer, if available at the time you are reading this) and try to reproduce the issue.
If you can, then delete the exception log (should be sitting beside the xEdit.exe) and reproduce the problem again. Then attach the newly created exception log to this issue.
TIA!

**Comment by garthand** [comment]
Hi, I've managed to reproduce the issue and have attached a log of the problem. I'm running 4.0.3 for reference. One thing that was interesting to note is that there is only a single record that needs to be in the strings files, and it appears to be entered into the strings files correctly. Thanks! 
[SSEEditException.log](https://github.com/TES5Edit/TES5Edit/files/4017246/SSEEditException.log)
