### ISSUE TITLE
Should QAC Clean Masters too?

### ISSUE THREAD

**Issue by lukemoore66** [TES5Edit/TES5Edit#713]
I came across a situation where all records from a master were ITMs when cleaning a plugin. An edge case, I know, and should never really happen. Wouldn't it make sense to clean masters too when using QAC, just in case? That way unnecessary masters aren't left over? Or is this beyond the scope of this feature?

**Comment by ElminsterAU** [comment]
The list of masters constitute a contract.

If you have ModA and ModB both making conflicting changes to the same vanilla record, and neither of them introduces dependencies on non-vanilla records, you can have a PatchAB that resolves this conflict without technically needing to have ModA or ModB as masters. But ModA and ModB definitely should be explicitly added as masters to PatchAB to ensure that a) the patch is always loaded after ModA and ModB and b) if ModA or ModB is not loaded, the patch is no longer loaded.

If you "clean masters" this explicit contract is broken. You should only use Clean Masters if you know exactly what you are doing and why.

**Comment by lukemoore66** [comment]
I understand. Your answer aligns with the philosophy of an 'auto clean', Were as my suggestion does not., as it is an edge case anyway.
