### ISSUE TITLE
There are no modules in the Data folder error

### ISSUE THREAD

**Issue by RowanSkie** [TES5Edit/TES5Edit#714]
**What is the version of xEdit you are using?**
I'm using FO4Edit 4.0.2.

**Describe the bug**
I have mods in Fallout 4 but I can't access them.

**To reproduce**
I open the app.

**Expected behavior**
I expected to find my mods placed.

**Screenshots**
https://i.imgur.com/6b6a6pq.png

**Comment by zilav** [comment]
I bet you use MO and didn't run FO4Edit from there.

**Comment by RowanSkie** [comment]
I use NMM 0.70.8.

**Comment by zilav** [comment]
Then run the game launcher to update paths in registry. And don't use NMM, it is bugged and obsolete.

**Comment by RowanSkie** [comment]
The community edition is being updated for that, which is why I said 0.70.8.

**Comment by zilav** [comment]
Since you are not commenting on your issue anymore, I assume you resolved the problem. It is clearly visible on screenshot in "using data path" line that FO4Edit looks for plugins in ...\Data\Data\ folder instead of just ...\Data\ and this path is pulled from the registry which is updated by the game launcher. So either run the launcher from Steam or fix registry entries yourself.

**Comment by RowanSkie** [comment]
Alright, thanks! I'll do that.

**Comment by Kennyyoubastard** [comment]
hey did you figure out how to fix this? I'm having the same problems and it's really bugging me. Any help would be much appreciated. Thanks!

**Comment by RowanSkie** [comment]
Like what zilav said, just run your game by Steam. Once it finished detecting your graphics, you close it and it's fine now.

**Comment by Reshiram110** [comment]
For those of you facing this issue, if you recently moved your skyrim install to a new folder, you will need to update the skyrim windows registry keys to point to the new install location. You can do this by either running the skyrim launcher, manually editing them with regedit, or, if you're lazy, this tool - https://www.nexusmods.com/skyrimspecialedition/mods/1194/
