### ISSUE TITLE
SSEEdit is looking in the wrong data path

### ISSUE THREAD

**Issue by StJamesHawke** [TES5Edit/TES5Edit#715]
I have just reinstalled Skyrim SE on a new disc, but SSEEdit is still looking for the Data in the old disc path, resulting in an error message "The are no modules in the data folder". How do I change the path to my current game disc?

**Comment by StJamesHawke** [comment]
Additional info. I am running Vortex which is located in the same disc as the game and executed the SSEEdit from the dashboard.

**Comment by zilav** [comment]
Run the game launcher from Steam.

**Comment by StJamesHawke** [comment]
Oh OK. Thanks

**Comment by Sharlikran** [comment]
The game is installed by steam. xEdit dosn't install the game or detect it incorrectly. The detection routine is the same for all tools such at LOOT, Wrye Bash, and even FNIS. If xEdit doesn't see your install correctly then that is an install issue.

![image](https://user-images.githubusercontent.com/1912426/60637019-9084f580-9dcd-11e9-85ce-ed3f31478752.png)

Either uninstall the game and install it where you want, with steam (meaning don't manually move it) and if it's not working, run the launcher as Zilav mentioned or contact Bethesda for help installing the game where you want it.
