### ISSUE TITLE
Range check error - SSEEdit 4.0.2 when applying script _xPatch-autoComplete

### ISSUE THREAD

**Issue by nwn9** [TES5Edit/TES5Edit#717]
**What is the version of xEdit you are using?**

SSEEdit 4.0.2 (F796EF8E) starting session 2019-07-14 21:31:58

**Describe the bug**

Range check error when applying script _xPatch-autoComplete.

**To reproduce**

**Expected behavior**
Script should complete the whole operation and create an ESL named by default VIS-Core. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26827032/61189594-fad04c80-a68f-11e9-8e08-0f47ec75f73b.png)

**Additional context**
[debug info.txt](https://github.com/TES5Edit/TES5Edit/files/3404306/debug.info.txt)

**Comment by zilav** [comment]
We provide support only for scripts distributed with xEdit. 3rd party scripts are not supported by us and questions should be addressed to their authors. If you believe that the error in not in the script but in xEdit itself, then isolate the issue using a test script with as few lines as possible.

**Comment by Sharlikran** [comment]
Contact the author or reproduce the issue with a test script as Zilav has mentioned.
