### ISSUE TITLE
GP Link Does not open with Firefox

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [TES5Edit/TES5Edit#719]
**What is the version of xEdit you are using?**
SSEEdit 4.0.2 (F796EF8E) starting session 2019-08-05 07:42:46

**Describe the bug**
Clicking on GP link does not open the GP YouTube Channel if using Firefox. If clicked, a small blue loading/starting circle appears for about a second and then does not send me to the YT Channel.
I am using the latest update of Firefox Quantum v68.0.1 (64-bit)

**To reproduce**
1. Go to 'GP Link'
2. Click on 'GP'
No other steps after the first 2

**Expected behavior**
Clicking on GP to open my Firefox Browser to view the Gamer
Poets Video Lists
**Screenshots**
Hard to time the screenshot in less than the second that the blue loading circle appears after clicking on the link

**Additional context**
No other additional context I can place here that is not related to above. Except the I have yet to see if it actually works with either Google Chrome, Microsoft Edge or IE. I do not have Chrome installed, and both of the Microsoft Browser are not made as my default Browsers. Only Firefox is.

**Comment by ElminsterAU** [comment]
Then something is wrong with your system. All xEdit does is using the ShellExecute windows API with a https url. Everything beyond that is up to the OS and wherever your registered browser is.
