### ISSUE TITLE
swap FNAM and LNAM in MUST

### ISSUE THREAD

**Issue by ghost** [TES5Edit/TES5Edit#720]
**What is the version of xEdit you are using?**
4.0.2

**Describe the bug**
FNAM and LNAM are swapped

I copied a vanilla combat music record in xedit into a new esp, created loop data in xedit, opened the esp in CK and saved. Same result, now there is an error because the CK fixed the order

**Expected behavior**
no error

TODO: flag as unordered and swap LNAM and FNAM

**Screenshots**
https://cdn.discordapp.com/attachments/512837488922984458/610411284545929236/lnam.PNG
https://cdn.discordapp.com/attachments/512837488922984458/610411333590188044/unknown.png

**Additional context**
see discord for more details but this is just not to forget it.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2j)
