### ISSUE TITLE
The MTNM field in RACE record is wrong

### ISSUE THREAD

**Issue by Som1Lse** [TES5Edit/TES5Edit#721]
**What is the version of xEdit you are using?**
SSEEdit 4.0.2 (F796EF8E) starting session 2019-08-19 22:05:30

**Describe the bug**
TES5Edit outputs `MTNM` fields in `RACE` records that are 5 bytes in size, with a null byte, at the end.

**To reproduce**
1. Load `skyrim.esm`.
2. Copy `DefaultRace` into a new `esp` file.
3. Save it.
4. View the file with a hex editor.

**Expected behavior**
The MTNM fields should have a length of 4 bytes.

**Additional context**
This is a problem because it confuses other tools, when loading race records, including one I am working on at this moment.

The solution (AFAIK, I am not familiar with the xEdit codebase, nor with Pascal) would be to change
```pascal
wbRArrayS('Movement Type Names', wbString(MTNM, 'Name')),
```
to
```pascal
wbRArrayS('Movement Type Names', wbString(MTNM, 'Name', 4)),
```
in `wbDefinitionsTES5.pas`, and other such files.

**Comment by ElminsterAU** [comment]
While I'll have a look at fixing this, you'll have to adjust your tool to properly handle such subrecords anyway, as there are going to be mods with them already in the wild, and the game engine and CK just ignore the terminating zero byte.

**Comment by ElminsterAU** [comment]
should be fixed with commit referenced above (which will be in 4.0.2j)
