### ISSUE TITLE
Cleaning Sim Settlement ESM error

### ISSUE THREAD

**Issue by Xurga** [TES5Edit/TES5Edit#723]
Downloaded Sim Settlements though Vortex. 
Used LOOT to set the load order. LOOT showed that Sim Settlement ESM needed cleaned. 
Ran xEdit on SimSettlement.esm
Went to close page when cleaning was done, got a error message. 

Error saving, SimSettlements.esm.save.2019_09_20_08_51_02: Record [NAVM:00000000] (in GRUP Cell Temporary Children of NavMeshGenCell [CELL:00000025]) must have a FormID.

Any clue on how I can fix it? 

[FO4Edit_log.txt](https://github.com/TES5Edit/TES5Edit/files/3636332/FO4Edit_log.txt)

I hope the link works, I am not very skilled with code. Just trying to mod a game to have more fun with it, and it keeps crashing suddenly, while gaming. Seems to crash with in 5 min of game play... If any one can tell me what I did wrong I would like to know, I do enjoy the addition of Sim Settlement and it's various aspects. But it seems to keep crashing the game.

**Comment by zilav** [comment]
Change it's FormID to any value valid for new records in this plugin.

**Comment by Xurga** [comment]
How do I do that? And how do I find a value not used by some ting else, so I do not mess some thing else up?

**Comment by zilav** [comment]
Press F2 on problematic NAVM record and enter any hex value XXYYYYYY, where XX is the current load order of plugin, YYYYYY is any random hex value. xEdit won't allow to assign FormID if it is already in use.
Or you can just copy as new any record from the game master into plugin, copy into clipboard it's newly assigned FormID, delete record and use that FormID.

**Comment by ElminsterAU** [comment]
This is an error in SimSettlements.esm and should be fixed by the author.
