### ISSUE TITLE
FO4Edit 4.0.2 "Stream Error" loading modules

### ISSUE THREAD

**Issue by redman76** [TES5Edit/TES5Edit#724]
FO4Edit 4.0.2

Whenever I try to load any module, it gives me "an error occurred while loading modules. Editing is disabled." When I look at the message log, it says there is a "stream read error" and that the exception is "EReadError."

**To reproduce**
1. Open FO4Edit
2. Load any module
3. Receive that error

**Expected behavior**
FO4Edit would load the module and clean it.

**Screenshots**
![image](https://user-images.githubusercontent.com/55610120/65366772-18181e80-dbdd-11e9-827d-4501f68b1503.png)

**Comment by ElminsterAU** [comment]
Your .ba2 files are corrupted. Verify files in steam
