### ISSUE TITLE
Fatal: Error loading plugin list: <EArgumentException: Invalid characters in path>

### ISSUE THREAD

**Issue by CyborgArmGun** [TES5Edit/TES5Edit#726]
**What is the version of xEdit you are using?**
TES5Edit 4.0.2 (F796EF8E) starting session 2019-09-25 16:08:34

**Describe the bug**
Getting error:
Loading active plugin list: C:\Users\nopublic\AppData\Local\Skyrim\Plugins.txt
Fatal: Error loading plugin list: <EArgumentException: Invalid characters in path>

**To reproduce**
Running portably through MO2  with command arguments:

-D:<"D:\Portableapps\Steam Portable\steamapps\common\Skyrim\Data"> -P:<"C:\Users\nopublic\Documents\My Games\Skyrim\plugins.txt">

**Expected behavior**
Load Plugins.txt

**Screenshots**
[Screen](https://imgur.com/01bRpRn.jpg)

**Additional context**
Copied MO Files to \Documents\My Games\Skyrim\ etc.

Running on Win 10 Enterprise (Library PC)
Version 1803
Build 17134.1006

**Comment by ElminsterAU** [comment]
< and > are not valid charterers in a path

**Comment by CyborgArmGun** [comment]
That got it, bless you, this turned into a good day due to your help. Thank o7

**Comment by ElminsterAU** [comment]
You are welcome. Happy modding.
