### ISSUE TITLE
Base Form IDs for New Vegas not implemented.

### ISSUE THREAD

**Issue by JayLCypher** [TES5Edit/TES5Edit#728]
**What is the version of xEdit you are using?**
FNVEdit 4.0.2 [Auto Load] (F796EF8E) starting session 2019-10-01 21:50:35

**Describe the bug**
Base FormIDs (GLOB, PlayerRef etc.) are not hardcoded similar to the game.
Without master file set to FalloutNV.esm, any script global reference to base game will not be correctly resolved, and go to XX000014 (XX being the mod's base ID, like 0D)

**To reproduce**
1. Download oHUD
2. Open oHUD.esm in xEdit
3. Observe it has no master file reference present.
4. Check iHUDActivateScript references.
5. Observe XX000014 Cannot resolve error
6. Add FalloutNV.esm as master
7. PlayerRef ID now resolved.

**Expected behavior**
Base IDs hardcoded, and will automatically be resolved regardless of base game esm / exe.
This should be the same behavior as base-game.
If the intent is to make mod creators aware when running "Check for errors", this should have a custom error message letting mod creator know to add FalloutNV.esm as master.

**Screenshots**
References of iHUDActivateScript in oHUD.esm
![Capture](https://user-images.githubusercontent.com/18422843/65997074-fd755d80-e498-11e9-91d1-7545dc71a729.PNG)

The script in question
![Capture1](https://user-images.githubusercontent.com/18422843/65997077-fd755d80-e498-11e9-84f3-a3fe97baba88.PNG)

Adding FalloutNV.esm as master to oHUD.esm
![Capture4](https://user-images.githubusercontent.com/18422843/65997151-20a00d00-e499-11e9-9951-3e14d8fd1430.PNG)

Now, xEdit correctly resolves script references.
![Capture5](https://user-images.githubusercontent.com/18422843/65997152-20a00d00-e499-11e9-8d9e-b80cb63dbe9d.PNG)

**Comment by ElminsterAU** [comment]
fixed in 4.0.2i
