### ISSUE TITLE
Zero-Reference Bug

### ISSUE THREAD

**Issue by paladinkolovrat** [TES5Edit/TES5Edit#729]
Zero-Reference not showed as error after checking.
https://i.imgur.com/FMCM7XM.jpg

This cause LODGen error like this
[01:57] [Commonwealth] Generating Object LOD
[08:04] [Commonwealth] Objects LOD generation error: Access violation at address 000000000162430D in module 'xLODGenx64.exe'. Read of address 0000000000000000
[08:04] LOD generation complete
And possible CTDs in world exploration(not tested)

Deleting of this entries solve problem with generation.

Suggestion: allow xEdit mark such references as error.

**Comment by zilav** [comment]
This is not an error, NULL is allowed in placed refs. It doesn't have sense but still not an issue from the technical pov in the game (unless they changed something in later games).

**Comment by paladinkolovrat** [comment]
>It doesn't have sense but still not an issue from the technical pov in the game 

But zero-reference cause issues in work with xEdit/xLODGen, so i think, some messages should be shown in Error check or Reference building, at least.
I spend alot of hours to figure out what the problem is.

**Comment by ElminsterAU** [comment]
No. It's not an error in the file. LODGen failing is a problem and should be fixed.

**Comment by ElminsterAU** [comment]
should be implemented in commit referenced above (will be in 4.0.2j)
