### ISSUE TITLE
How point sseedit to the correct install of Skyrim SE

### ISSUE THREAD

**Issue by 7oggle** [TES5Edit/TES5Edit#730]
I have 2 installs of Skyrim SE. One is installed in the default location in "ProgramFiles(x86)\Steam\Steamapps" etc..,  
and the other is installed in "C:\Games". <--- This is the install where my mods are.
Whenever I start up sseedit ( Like with QAC to clean mods) it automatically loads the default install in the steam folder, but i need it to load the install in the  "C:\Games" directory. How can I achieve this?

**Comment by ElminsterAU** [comment]
By reading the information tab
