### ISSUE TITLE
[Fallout 4] "Unknown 11" in the "Data-Flags" subrecord of CELL records

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#731]
Not sure what the best name for it would be, but the "Unknown 11" flag for the Data - Flags subrecord in FO4 CELL Records hides a cell from the "Interior Cell" list. It is used for PackIns, so that the PackIn "Cells" don't clutter the list.

It is not required for a PackIn to work (I tested by using xEdit to point a PackIn at a vanilla interior cell without the flag, and was able to drop the entire thing into a worldspace), but I did verify that removing that flag makes the cell created for a PackIn appear in the "Interior Cell" list.

A quick test shows that the flag is ignored for worldspace cells (though the only way for it to ever be put on one is if someone does so in xEdit), the cell still shows in the list of cells for the worldspace I made.

Test plugin is attached. 
[testPackIn.zip](https://github.com/TES5Edit/TES5Edit/files/3748737/testPackIn.zip)

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
