### ISSUE TITLE
New CK leaves Base record listed for deleted REFRs, should not be marked as error. 

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#732]
**What is the version of xEdit you are using?**
4.0.2

**Describe the bug**
xEdit reports an error for REFRs that are marked as deleted but have the Name - Base subrecord populated. A recent change to the CK means that that is how deleted records are left in the plugin, at least for the FO4 CK.  

**To reproduce**
1) Delete a REFR in the FO4 CK (possibly in most recent SSE CK as well)
2) Run "Check for Errors" in xEdit

**Expected behavior**
Deleted REFRs with leftover data in the NAME - Base subrecord are not considered errors, and don't show up in the messages tab as errors when you run Check for Errors.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
