### ISSUE TITLE
changing the form id of an overriden record doesn't update the link between original and override until restart.

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#733]
**What is the version of xEdit you are using?**
FO4Edit 4.0.2j (4CDC2E08) starting session 2019-10-22 14:55:20

**Describe the bug**
changing the form id of an overriden record doesn't update the link between original and override until restart. instead it becomes an injection which just happens to share the same form id as the mod it injects into, but xedit doesn't see the link between the two. possibly a cache issue.

**To reproduce**
1. make a form id in mod 1
2. override it in mod 2
3. back in mod 1, change the form id to something else.

**Expected behavior**
expected for the links between the two to update, so it'd still mark it as a proper override, with a green/yellow/red/etc background, but it's instead white as if it wasn't overriden. the override mod's record is treated as an injection despite their form ids matching.

**Comment by 7oggle** [comment]
yes ver 4.0.2

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
