### ISSUE TITLE
right side window's record overrides don't focus on currently selected mod

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#734]
**What is the version of xEdit you are using?**
FO4Edit 4.0.2j (4CDC2E08) starting session 2019-10-30 16:26:28

**Describe the bug**
whenever you're viewing a record with many overrides, instead of focusing on the record in currently selected plugin it always remains to the far left side, on the master.

**To reproduce**
1. open your whole modlist
2. go to any one of the latest mods, enter worldspace as those always have a ton of overrides and look at the root worldspace record

**Expected behavior**
expected the override in currently selected mod to be focused on, rather than no focus whatsoever.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (should be in 4.0.2l)
