### ISSUE TITLE
Ambiguity in Skyrim's QUST definition

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#737]
Opening issue here as requested on Discord.

**What is the version of xEdit you are using?**
TES5Edit 4.0.2k (63956442) starting session 2019-11-08 22:59:27

**Describe the bug**
There is an ambiguity in the `QUST` definition for Skyrim. `QSTA` subrecords can belong to either the `Objectives\Targets` section or the `Targets` section, and if there are no subrecords between the two, it becomes impossible to add any to the `Targets` section.

**To reproduce**
 1. Make a new, completely blank `QUST` in xEdit
 2. Add an `Objectives` section
 3. Add a `Targets` section (at the very bottom, *not* in the objectives section)
 4. Save and relaunch - notice that the targets have now moved up into the objectives section

**Expected behavior**
Saving the plugin in the CK readds the `DNAM`, `NEXT` and `ANAM` subrecords, which obviously solves the problem - maybe ANAM should be required?

**Comment by zilav** [comment]
Yes, ANAM subrecord between these QSTAs must be present to differentiate them from each other. Or NNAM, but descripton shouldn't be required in theory.
Create a new quest in CK, don't change or add anything and save. Check if ANAM is present.

**Comment by jbostrus** [comment]
I checked with SSE and FO4 CK's. Both produce very similar output. The DNAM, NEXT, and ANAM are all default created.

**Comment by zilav** [comment]
Please check all existing vanilla QUSTs that all these marked subrecords are present just in case, that their presence doesn't depend on something else.

**Comment by ElminsterAU** [comment]
should be fixed for skyrim with the commit referenced above (should be in 4.0.2m)
