### ISSUE TITLE
Ambiguity in Skyrim's PACK definition

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#747]
**What is the version of xEdit you are using?**
SSEEdit 4.0.2m RC1 for 4.0.3 (10A4DD4C) starting session 2019-11-18 23:07:22

**Describe the bug**
 There is an ambiguity in the `PACK` definition for Skyrim. `ANAM` subrecords can belong to either the `Package Data\Data Input Values` section or the `Procedure Tree\Branches` section, and if there are no subrecords between the two, it becomes impossible to add any to the `Procedure Tree\Branches` section.

**To reproduce**
1. Make a new `PACK` in xEdit
2. Add a `Package Data` section
3. Add a `Procedure Tree` section
4. Save and relaunch - notice that you now have two `Package Data\Data Input Values` entries, and that the `CITC` subrecord is now misplaced:
```
Error: record PACK contains unexpected (or out of order) subrecord CITC 43544943
Errors were found in: [PACK:01000801]
Contained subrecords: PKDT PSDT PKCU ANAM ANAM CITC 
```

**Expected behavior**
Creating a new `PACK` in the CK creates the `XNAM - Marker` subrecord (as well as the `OnBegin`, `OnEnd` and `OnChange` sections), so that subrecord should probably be required.

**Comment by Infernio** [comment]
#737 should probably be tagged and added to the 4.0.3 milestone as well, right?

**Comment by ElminsterAU** [comment]
It's already fixed and closed, so adding it doesn't do much at this point... But I've done it anyway

**Comment by Infernio** [comment]
I'm used to WB, where we use a script to generate changelogs based on the tags, milestones, and assigned people. But yeah, if you don't use something like that, not that much point in tagging closed issues.

**Comment by ElminsterAU** [comment]
I update whatsnew.md by hand and commit it together with the change, because not all changes have an issue, and some require more extensive and complex documentation than just a one-liner

**Comment by Infernio** [comment]
There's the idea floating around to add something like a What's New to WB: https://github.com/wrye-bash/wrye-bash/issues/465
But that's blocked by GUI refactoring, which is blocked by wx3, and so on...
Anyway, this is off topic 😛

**Comment by ElminsterAU** [comment]
should be fixed with commit referenced above (will be in 4.0.2n)
