### ISSUE TITLE
Changing ANAM in Skyrim's PACK does not update the CNAM prompt

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#748]
**What is the version of xEdit you are using?**
SSEEdit 4.0.2m RC1 for 4.0.3 (10A4DD4C) starting session 2019-11-18 23:07:22

**Describe the bug**
For `PACK` in Skyrim, changing `Package Data\Data Input Values\Value #0\ANAM - Type` does not actually update the prompt type for `CNAM - Value`.

**To reproduce**
1. Create a new `PACK` in xEdit
2. Add a `Package Data` section
3. Change `Package Data\Data Input Values\Value #0\ANAM - Type` to `Bool`
4. Add a `CNAM - Value` subrecord right below `ANAM - Type`
5. Change `ANAM - Type` to `Float`
6. Edit the value in `CNAM - Value` to a float, e.g. `1.0`
7. An error pops up: `'1.0' is not a valid integer value.`

**Expected behavior**
The prompt should expect a float value after `ANAM - Type` was changed.

**Screenshots**
Here shown with an override, but a single record is also enough to reproduce this:

![PACK_CNAM](https://user-images.githubusercontent.com/2845240/69099309-ba784500-0a5a-11ea-9c5c-1b86d04c2d1e.png)

**Comment by ElminsterAU** [comment]
should be fixed with commit referenced above (will be in 4.0.2n)
