### ISSUE TITLE
4K Script window scaling issue

### ISSUE THREAD

**Issue by TheLegg77** [TES5Edit/TES5Edit#749]
**What is the version of xEdit you are using?**
SSEEdit 4.0.2 (F796EF8E) starting session 2019-11-18 23:58:46

**Describe the bug**
Having set up SSEdit on a 4K monitor and configuring the font, column and row settings to a reasonable level I have discovered that applying a script which brings up a script specific window ( e.g in this case is AT - Quickchange ) resulted in the window being too small.  This leads to test boxes being unable to properly display text, drop down menus unable to display full information etc.

Apart from the standard make these windows bigger etc, would it be possible to allow the user to change the size of these windows ( like the item description window ) and allow a menu option to change the column width and row height of these windows ( similar to the one already in options menu )?

Attached two screenshots of example script windows.

**To reproduce**
1. Go to '4k display - Apply Scripts - AT - Quickchange 2.5'
2. Click on '...OK.'
3. Scroll down to '.N/A...'

**Expected behavior**
The script window to scale in a way that it is still usable, if not that the ability as an end user to define size and scale of the script window UI.

**Screenshots**
![xEdit01](https://user-images.githubusercontent.com/57924900/69106033-0af4a000-0a65-11ea-85de-5e73b4a82f4e.jpg)

![xEdit02](https://user-images.githubusercontent.com/57924900/69106038-1051ea80-0a65-11ea-82e5-685c1d955309.jpg)

**Additional context**

**Comment by VlitS** [comment]
Those scripts (created by mator, and not included with xEdit) create the windows using specific pixel values for the locations of the different features. That isn't exactly something Elminster can really fix...

**Comment by TheLegg77** [comment]
Ok will post this elsewhere, thanks

**Comment by Sharlikran** [comment]
Mator's scripts are not supported. Also the Delphi UI doesn't not allow you to scale those windows. The code is one line and there are no parameters for size or scale. We reported it to Delphi and never heard back.

Obviously hard coded windows like the settings has properties we can control. I am talking about the fact there is no properties for the pop up boxes from the scripts.

**Comment by TheLegg77** [comment]
Shame, but if it is out of your control not much that can be done.  Thanks for the fast responces.

**Comment by selsie** [comment]
You could try fiddling with the pixel values in the script. Setting height and width and spacing shouldn't be impossible to do.

**Comment by fireundubh** [comment]
This is easy enough for anyone to fix on their own.

Create a `scaleFactor` constant.

```delphi
const
  scaleFactor = Screen.PixelsPerInch / 96;
```

Wherever UI elements are defined, multiply all size and position values by `scaleFactor`.
```delphi
btnOk             := TButton.Create(frm);
btnOk.Parent      := frm;
btnOk.Left        := 62 * scaleFactor;
btnOk.Top         := 120 * scaleFactor;
btnOk.Width       := 75 * scaleFactor;
btnOk.Height      := 25 * scaleFactor;
btnOk.Caption     := 'Run';
btnOk.Default     := True;
btnOk.ModalResult := mrOk;
btnOk.TabOrder    := 3;
```

**Comment by TheLegg77** [comment]
Thanks, I will try xx

-------- Original Message --------
