### ISSUE TITLE
form id override's id changes while the original fails in case id number's changed to an existing id

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#750]
**What is the version of xEdit you are using?**
FO4Edit 4.0.2m RC1 for 4.0.3 (10A4DD4C) starting session 2019-11-19 03:42:18

**Describe the bug**
if you try to change it to an id that already exists, xedit will say it's already used and not change it, but the override will be changed regardless.

**To reproduce**
1) create two unique formids
2) override first formid into another mod
3) change the original's formid number to be the same as second's
4) click yes when it asks you if you want to update the override

**Expected behavior**
expected the override to fail changing as well in case the id is already used in the original's mod.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (is in 4.0.2n)
