### ISSUE TITLE
Drag Field & Drop issue (Linux)

### ISSUE THREAD

**Issue by jarrard** [TES5Edit/TES5Edit#774]
FO4Edit 4.0.3  (read additional context FIRST)

The issue:
Inability to drag and drop specific text fields to other mods (like a merge patch). I can however drag and drop entire columns without issue.

Steps to reproduce the behaviour:
1. Select any mod field of text,
2. Left click and drag to a conflicting mod on right
3. No drag and drop occurs, 

What's expected to happen:  The text data should overwrite that of to the right

**Screenshots**
not applicable.

**Additional context**
OK here comes the real nasty part everyone is going to BITE my head off about. This is done under wine5.0rc4staging (yes Linux) and its something that use to work. 
The terminal record shows a acknowledged action. (fixme doesn't mean it can't work)
```
0060:fixme:shell:DragSourceHelper_InitializeFromBitmap (0xbac7e30)->(0x1e4f91c, 0x61cc43d0): stub
0060:fixme:shell:SHDoDragDrop (0x20142 0x61cc43d0 (nil) 0x00000001 0x1e4fa08):stub.
```
Now this may not mean anything but I'm just wondering if anyone has any ideas as to what could be happening or if I'm missing something please let me know. 

Perhaps someone who has been testing this under Linux wine also can provide some input. I will continue testing this and trying to find a solution. 

Thank you for your time.

**Comment by ElminsterAU** [comment]
Wine is not an officially supported environment for xEdit.

Given that it works on real Windows and not Wine, it's going to be a bug in Wine, so you should be reporting it to the Wine team.

**Comment by jarrard** [comment]
I tested it with windows version set to XP and it works. 
Yes it does appear to be a issue with wine for sure. 

At least I found a workaround. Might help someone down the line.

**Comment by ThisNekoGuy** [comment]
@ElminsterAU I'm aware that Wine isn't an officially supported environment, and xEdit works mostly pretty well in Wine as it is, but would it be possible to produce a native build?

(I'm a junior dev but I've never messed with Pascal before and I'm coming from web dev, personally)

**Comment by ElminsterAU** [comment]
No, because there is no VCL for Linux. Delphi is limited to commend line applications for Linux currently.

**Comment by picobyte** [comment]
This is not a solution and since everything else just works in Linux via Wine, wouldn't it be feasible to add copy-paste in the context menu? This seems pretty low hanging fruit.
@jarrard, did you have a workaround, otherwise, can this be reopened?

**Comment by ThisNekoGuy** [comment]
> This is not a solution and since everything else just works in Linux via Wine, wouldn't it be feasible to add copy-paste in the context menu? This seems pretty low hanging fruit.

I've discovered that setting xEdit to run with WinXP compatibility mode in `winecfg` fixes the issue

Side note, zEdit has native Linux support planned with most of what's needed to do so already done

**Comment by picobyte** [comment]
@ThisNekoGuy, thanks I will try that.

**Comment by jarrard** [comment]
> @jarrard, did you have a workaround, otherwise, can this be reopened?

> I tested it with windows version set to XP and it works.   (you can make this APP/exe specific in winecfg)

> Side note, zEdit has native Linux support planned with most of what's needed to do so already done

Last time I looked at that project they had still not added > 255 plugin support, and also the new pesudo-plugin extension format.

**Comment by ThisNekoGuy** [comment]
> Last time I looked at that project they had still not added > 255 plugin support, and also the new pesudo-plugin extension format.

@jarrard 
The reason is mainly because Mator wanted to move away from xedit-lib because it was too limiting to perform the goals he has in mind (including native Linux compatibility)
In doing so, he's created "Esper," a C# re-implementation that's "almost" done; though, that means he's not been focusing on 255+ plugin support and ESLs yet

**Comment by picobyte** [comment]
> I've discovered that setting xEdit to run with WinXP compatibility mode in `winecfg` fixes the issue

Sorry for the late reply. I had changed the version to winxp in winecfg, but drag and drop still didn't seem to work. Somewhere found that gdiplus_winxp might be needed, but the archive that winetricks seemed to extract this from seems gone. Anyway thanks for the help.

**Comment by telinit** [comment]
> > This is not a solution and since everything else just works in Linux via Wine, wouldn't it be feasible to add copy-paste in the context menu? This seems pretty low hanging fruit.
> 
> I've discovered that setting xEdit to run with WinXP compatibility mode in `winecfg` fixes the issue
> 
> Side note, zEdit has native Linux support planned with most of what's needed to do so already done

Thank you. 

Setting windows version to WinXP in winecfg helped. And you can even set the version setting on per-application basis so only SSEEdit (or its clones) are affected.

I also installed gdiplus_winxp via protontricks just in case...
