### ISSUE TITLE
[Skyrim SE/LE] - Unknown Map Marker TNAM value 59.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#777]
Map Marker TNAM Unknown value 59 should be listed as "Castle Karstaag". It's an icon that was added to the game via the Dragonborn DLC. It's selectable in the CK when setting the marker type.

![image](https://user-images.githubusercontent.com/1762652/73128113-df6fc380-3f87-11ea-906d-8dd1f4d0c02a.png)

There are a couple of other unused icons that probably don't have values. I can provide a test .esp with all of these if needed.

**Comment by Arthmoor** [comment]
BTW, the only reason I brought it up is because this currently shows up as an error when doing a check for errors:

00:00] Checking for Errors in [06] Cutting Room Floor.esp
[00:03] [REFR:040143C1] (places MapMarker [STAT:00000010] in GRUP Cell Persistent Children of [CELL:040142EC] (in DLC2SolstheimWorld "Solstheim" [WRLD:04000800]) at 8,21)
[00:03]     REFR \ Map Marker \ TNAM - TNAM \ Type -> <Unknown: 59>
[00:04] Done: Checking for Errors, Processed Records: 4472, Errors found: 1, Elapsed Time: 00:04

**Comment by eckserah** [comment]
That would be pretty useful. If you can get me that test esp I'll add it all to xedit. Figured I'll start picking up things like this so elm can focus on some of the bigger changes/fixes

**Comment by Arthmoor** [comment]
As it turns out only the Karstaag marker is unknown. The other unused ones have been defined in xedit already.

[Map Marker Test.zip](https://github.com/TES5Edit/TES5Edit/files/4113023/Map.Marker.Test.zip)

**Comment by eckserah** [comment]
Awesome I'll get that put in asap.

**Comment by eckserah** [comment]
Fixed in PR ce5d314 @Sharlikran

**Comment by ElminsterAU** [comment]
should be resolved with the commits referenced above
