### ISSUE TITLE
next object id defaults to 801 instead of 800

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#780]
**What is the version of xEdit you are using?**
FO4Edit 4.0.3a (9A8C8E77) starting session 2020-02-01 20:25:54

**Describe the bug**
next object id defaults to 801 instead of 800 when ? is put in the input box to mark the closest free form id

**To reproduce**
1. make a new plugin
2. edit its next object id
3. put ? in the box

**Expected behavior**
expected it to be set to 800, or 001 if in esl extended form id mode

**Comment by fireundubh** [comment]
- Cannot reproduce in ESP, ESM, or ESL plugins using "Copy as override" with dev-4.1.4 build.
- Reproduced in ESP, ESM, and ESL plugins using "Copy as new record" with dev-4.1.4 build.

**Comment by yarrmateys** [comment]
there's another problem similar to this, if you renumber form ids by using 001-fff range and the number of records is below 2048, the next object id slot will be set to 800 instead of the true number that's below it.

**Comment by yarrmateys** [comment]
to add to that, creating new forms ignores the 001-7ff range if there are things in 800- range when the next form id is set to 00000001. say, you have 001, 002, 003, 004 and 820, then set next formid to 00000001 and try creating a new form, instead of it taking 005 id it'll go for 821, or whatever the largest form is. if you have 820 and 920, it'll go for 921 instead.
