### ISSUE TITLE
VirtualEditTree not Found

### ISSUE THREAD

**Issue by RityH** [TES5Edit/TES5Edit#783]
## I have tried two ways:
- 1. Download source file and comepile it. But it report a "...\VirtualEditTree"file not found, "JV...""TJ..."file not found, I can't find them.
- 2. Decompile your Tes5Edit.exe by Sisulizer, but also something about VirtualEditTree can not be decompile.

well, I never use Delphi before, the info of Delphi is Too Hard to Find.
Please help me, Tes5Edit is really a usefull tool to make mods, I wanna translate it and share it to more Chinese friend.

Thanks.

**Comment by ElminsterAU** [comment]
Go to the #dev-support channel on the xEdit discord. Follow the instructions in the pinned messages for setting up the development environment.

**Comment by RityH** [comment]
Thanks, I‘ll try~

**Comment by RityH** [comment]
Sorry, I don't find a folder named #dev-support under https://github.com/TES5Edit, am I find a wrong place?@_@

**Comment by Infernio** [comment]
On the xEdit discord, not the github: https://discord.gg/5t8RnNQ

**Comment by ElminsterAU** [comment]
D I S C O R D. Click the discord button in the top right corner of xEdit for the invite link.

**Comment by RityH** [comment]
@Infernio Thank you Very Much!
@ElminsterAU I'm sorry, I'm not familiar with this.
