### ISSUE TITLE
SSEEdit all versions - loading times almost twice slower than TES5Edit

### ISSUE THREAD

**Issue by Ne0niq** [TES5Edit/TES5Edit#785]
Hello, dear developers! 
I have problem with plugins loading times in SSEEdit. 

I modded Oldrim for years and used TES5Edit a lot, often restarted it to make some changes. Recently I started to build the mod set. Two moths of everyday work in SSEEdit has passed and I clearly see that xEdit in TES5Edit mode is almost twice faster than in SSEEdit mode. I mean only plugins loading time. In SSEEdit it's really slow comparing to TES5Edit.

**How to reproduce:**
To meaure loading times I selected only the main vanilla ESM files. 
- TES5EDIT mode on Oldrim gives **18 seconds** in total, where plugins being loaded in 9 seconds and caching take the rest 9 seconds.
- SSEEdit mode on SSE gives **28 seconds** in total, where plugins being loaded in 18 seconds and caching take the rest 10 seconds.

**Why SSEEdit mode is so slow?**
Vanilla files are not much different (summary size of SSE ESM's is only 18 Mb larger than Oldrim).
This applies not only to vanilla files, and very noticable when loading whole load order: with not much different summary amount of data of all plugins TES5Edit loads all Oldrim plugins from external USB HDD in **27 seconds**, while SSEEdit - in **MORE THAN A MINUTE**, and SSEEdit loads plugins on super fast Intel SSD (!). 

The difference in loading times is version independent. Currently I am using v4.1.3a.
My settings are mostly default, I changed only UI theme ans fonts.

So, should I get use to such slow loading times in SSEEdit or it can be investigated as actual issue?

**Comment by ElminsterAU** [comment]
All versions of xEdit are exactly the same program. And in TES5 and SSE modes they are using the same record definitions (with just minimal differences for SSE specific additions).

So. No. Whatever the problem is, it's on your end, not something inherently wrong with the software.
