### ISSUE TITLE
[Suggestion] Auto-renaming Batch files to make switching xEdit modes easier

### ISSUE THREAD

**Issue by GamerGoddessDin** [TES5Edit/TES5Edit#787]
I've already got one to switch to OldRim mode and can easily make some for the other modes. I just want to make sure you'd want them and to know where to put them in the repository if you did.

Here's the code for my "OldRim.bat":
```
rename *Edit.exe TES5Edit.exe
rename *EditQuickAutoClean.exe TES5EditQuickAutoClean.exe
rename *Edit_log.txt TES5Edit_log.txt
```

**Comment by GamerGoddessDin** [comment]
[Rename_Batches.zip](https://github.com/TES5Edit/TES5Edit/files/4272877/Rename_Batches.zip)
Went ahead and made all of them. Here's a zip file of all of them. They just need to be put in the same folder as the executables and log file and they work with a simple double-click.

**Comment by Sharlikran** [comment]
This is not the first time this has been suggested to some extent. There are many options for users to use xEdit with one install and if they choose they may choose to use multiple files. However, we have not approved these types of things in the past nor a menu or launcher prior to startup. This will not be implemented.

I communicate with mod manager authors and Vortex and MO2 both look for the files as they are named. Changing that would mean they would have to release a new version of the mod manager to account for the changes. I work with others to make things as simple as possible.

I appreciate your desire to simplify things.
