### ISSUE TITLE
Flipped indexes in display of blocks and sub-blocks

### ISSUE THREAD

**Issue by clayne** [TES5Edit/TES5Edit#792]
**What is the version of xEdit you are using?**
4.0.3

**Describe the bug**

**To reproduce**
Any trivial script calling `FullPath` on an object.

**Expected behavior**
`FullPath`'s output should match the actual indexes of what's in the data. For instance, if a CELL is in `Exterior Cell Block 1, -2, Exterior Sub-Block 4, -6`, `FullPath` should emit that. Instead it emits `Exterior Cell Block -2, 1, Exterior Sub-Block -6, 4`.

**Screenshots**
<img width="1751" alt="image" src="https://user-images.githubusercontent.com/2467434/76571319-77603880-6474-11ea-9458-f1310c63e905.png">

**Additional context**
This bug looks to have been there since 2012 atleast. The issue is that decoding of the block/sub-block data is using the order of low and high bytes in `TwbGroupRecord.GetName` but it should be using the order of high and low bytes as done in `TwbGroupRecord.GetShortName`.

**Comment by ElminsterAU** [comment]
this issue should be fixed in 4.0.3d
