### ISSUE TITLE
Remove records from "Compare Selected"

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#798]
Currently when you are looking at multiple records using "Compare Selected", if you want to remove a record from the compare you have to deselect it and then start a new compare. 

Would it be possible to add a "Remove from Compare" option to the context menu when you right click on the column header?

**Comment by fireundubh** [comment]
Ctrl+Click the highlighted records in the tree that you want to stop comparing.

**Comment by VlitS** [comment]
I already tested that. You then have to Right Click -> Compare Selected again, as doing so ends the compare, unless you are under your set limit for auto-compare. 

In any case, this would be most useful for large compares where finding by column is quicker than looking for the relevant record in the left pane.

**Comment by fireundubh** [comment]
In the dev-4.1.4 build:

- Cannot reproduce with selected records less than auto compare limit. Using Ctrl+Click to deselect records while below the limit will remove those records from the comparison view.
- Reproduced with selected records greater than auto compare limit.
- Additional issue: Using Ctrl+Click to deselect records while above the limit will reset the comparison and show only the deselected record in the view.
- Additional issue: The auto compare limit is equal to `limit-1`, so a limit of 10 means that only 9 records can be auto compared. This should be equal to `limit`.

**Comment by VlitS** [comment]
For the `limit-1` thing, that is because of the wording. Currently the option says:

`Auto "Compare Selected" when multi-selecting less than ___ records`

So if you are changing it to make it auto-compare up to the number entered (which I will agree is probably a little more intuitive, in my experience people are more used to less than or equal to than less than by itself), you need to also change the text. Maybe change it to 

`Auto "Compare Selected" up to ___ records`
