### ISSUE TITLE
texture file hashes decoding missing for MO4T

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#808]
**What is the version of xEdit you are using?**
FO4Edit 4.1.3b EXTREMELY EXPERIMENTAL (CDA61A13) starting session 2020-04-06 19:06:06

**Describe the bug**
the hash decoding is missing from weapons - 1st person model (MO4T). it still shows the raw hash.

**Comment by yarrmateys** [comment]
addition, there are also un-decoded texture hashes in BPDT - body part data, NAM5

**Comment by eckserah** [comment]
I'll take a look into this as it's most likely the same for fo76
