### ISSUE TITLE
Unknown field in Script Fragments decoded by Creation Kit error log.

### ISSUE THREAD

**Issue by kennyhigginbotham** [TES5Edit/TES5Edit#813]
**What is the version of xEdit you are using?**
FO4Edit 4.0.3

**Describe the bug**
QUST->VMAD->Script Fragments
PERK->VMAD->Script Fragments
...and wherever else VMAD is applicable 

The first "Unknown" field is "Extra bind data version" according to this Creation Kit warning I encountered after leaving the value set to 0.

> error: Extra bind data version too old. Must be version 2 or newer

**To reproduce**
Remove the first "Unknown" field, or set it's value below 2, on the VMAD->Script Fragments property of a quest, perk, or other entity that can have a virtual machine adapter. Then try opening the plugin with Creation Kit and check EditorWarnings.txt for the error message.

**Comment by kennyhigginbotham** [comment]
The "Check for Errors" function could also report when the value is not set or is less than 2.

**Comment by ElminsterAU** [comment]
should be fixed and documented with the commits referenced above
