### ISSUE TITLE
A really noob question :/

### ISSUE THREAD

**Issue by 70ggle** [TES5Edit/TES5Edit#815]
I'm using xedit for SSE, with vortex. I have 2 SSE installs. xedit points to the default install location. The one I want it to use is located here:  "C:\Games\SteamLibrary\Skyrim Special Edition\Data".

so in the command line I put "-d: C:\Games\SteamLibrary\Skyrim Special Edition\Data\"
and I get an error "no modules in data folder"
so I tried this "-d: C:\Games\SteamLibrary\Skyrim Special Edition\Data"
and I tried "-d: C:\Games\SteamLibrary\Skyrim Special Edition\"
all gave me same error. 
This is what the log said "Using Skyrim Special Edition Data Path: \"

Can someone tell me the correct way?
Again sorry for the noob question.

**Comment by ElminsterAU** [comment]
Where does it say to put a space after the : ?

**Comment by 70ggle** [comment]
Not sure but I just tried "-d:C:\Games\SteamLibrary\Skyrim Special Edition\Data\"
same error
But the log says this now "Using Skyrim Special Edition Data Path: C:\Games\SteamLibrary\Skyrim\"
Could it be because there are spaces between Skyrim Special Edition in the path?

Not showing it but i had a backslash at the end of data as well

**EDIT: Yes that was the problem the spaces between Skyrim and Special Edition**
