### ISSUE TITLE
FO3: Anchorage.esm & PointLookout.esm need Mark Modified applied during QAC

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#823]
**What is the version of xEdit you are using?**
FO3Edit 4.1.3b EXTREMELY EXPERIMENTAL (CDA61A13) starting session 2020-05-06 22:54:02
(Happens on 4.0.3b as well)

**Describe the bug**
QAC'ing the two DLCs listed above will cause the same bug as the disappearing Soul Cairn/Apocrypha in Skyrim.

**To reproduce**
1. QAC Anchorage.esm
2. `cow DLC02BaileysCrossroads 0 0`
3. Note that most of the worldspace is gone
4. QAC PointLookout.esm
5. `cow DLC4Pointlookout 0 0`
3. Note that most of the worldspace is gone

**Expected behavior**
QAC should apply Mark Modified to these two files, same as with Dawnguard.esm & Dragonborn.esm in Skyrim.

**Screenshots**

![ScreenShot0](https://user-images.githubusercontent.com/2845240/81227853-60117780-8fed-11ea-8407-0aa82d9a8c6c.png)

**Comment by ElminsterAU** [comment]
I'll have a look. In the meantime, you can use the command line parameter to force the mark modified to be applied to check if that fixes it.

**Comment by VlitS** [comment]
Both Infernio and the person who reported the issue confirmed that Right Click -> Mark Modified fixed the issue when done after cleaning:
[https://discordapp.com/channels/471930020454072348/540419940331552791/707688554880434248](https://discordapp.com/channels/471930020454072348/540419940331552791/707688554880434248)

**Comment by ElminsterAU** [comment]
this issue should be fixed in 4.0.3d
