### ISSUE TITLE
TES4: REFR\XRTM - Unknown is Reference Teleport Marker

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#824]
In the TESCS, you can get this by changing the `Reference` field on the `Teleport Ref` tab. Only ever shows up on `DOOR` references, and always links to a marker reference.
On Discord, we agreed that `Reference Teleport Marker` seems like the best name for this.

**Comment by Arthmoor** [comment]
Do you have a screenshot of the menu you found that in? In looking at the menu on a door, it won't let me select anything other than another door to link to, and XTRM isn't being filled in by doing that.

**Comment by Infernio** [comment]
![TESCS_Door](https://user-images.githubusercontent.com/2845240/82842078-9a798080-9ed8-11ea-8ad0-17faa671cad5.png)


To get there:
- Open Oblivion.esm in TESCS
- Under Interiors, scroll down to OblivionRDCavesMiddleA05
- The first object on the right should be OblivionRDCaveMiddleExit, which is what the screenshot is from

[And here's a full dump of all REFRs that have XRTM in Oblivion.esm](https://gist.github.com/Infernio/5a0af9d4d51d31409db5cdc21a8cf7fa)

**Comment by Arthmoor** [comment]
Oh, random Oblivion realm doors. No wonder I wasn't finding that tab.
