### ISSUE TITLE
 Feature Request:  Allow SSEEdit to Minimize during processing

### ISSUE THREAD

**Issue by LexiconCode** [TES5Edit/TES5Edit#827]
A paper cut issue is that the user can not minimize the SSEEdit application while its processing records. Personally this is frustrating as processing can take a long time and I'd like to have control over my workspace.

**Comment by ElminsterAU** [comment]
xEdit is a single threaded application, with the processing being performed on the same thread as the UI. This is the reason why you can't interact with the UI while the processing is going on.

I'll have a look at what can be done, but can't make any promises as the basic nature of the problem (single threaded design) can't be changed.

**Comment by ElminsterAU** [comment]
documented with commits referenced above, had already been previously implemented in 4.x.3h, just not documented in what's new
