### ISSUE TITLE
Feature Request-Create combined objects without modification

### ISSUE THREAD

**Issue by n0p0n3** [TES5Edit/TES5Edit#830]
Please add the ability to generate combined object and tree data without going through the compression/quality reduction phase. I'm trying to create a copy of each cell just like it is in game around the player, not simplified, for animation projects and others that need acurate map data.

**Comment by zilav** [comment]
xEdit is a tool to manipulate plugin files. How is your request related to that? I don't see any connection.

You can use xLODGens's terrain LOD generation to create meshes for terrain shape, setting Quality=0 will create exactly the same shape as stored in plugins. Then combine them with meshes from Objects LOD which doesn't have any "compression" since it uses available LOD meshes and textures as is.

**Comment by n0p0n3** [comment]
You're right it doesn't really relate, but xedit is the only tool I've found that comes close to doing what I need. I've done that for terrain meshes, but I thought xedit went through the records, placing all object meshes like they are ingame, then did something like quadratic mesh simplification to create higher quality lod meshes and textures. If not, I was mistaken and will close, but do you think it would be possible to do something like that?

**Comment by zilav** [comment]
Use DynDOLOD to generate objects LOD using full meshes, then merge them onto the terrain LOD meshes.

**Comment by n0p0n3** [comment]
Okay, that solves skyrim, but is there a version of DynDOLOD for fallout 4 and fallout76? Or a way to use the sse version with fallout 4 and 76? Everywhere I've searched points to xLODGEN. I'm trying to import into blender and eventually into unity, and not back into the creation engine, if that uncomplicates the matter. I'm using nifscope to convert .nif to .obj

**Comment by zilav** [comment]
There is FO4LODGen, but you'll have to rename full meshes as the LOD ones so it'll pick them up for generation.

**Comment by n0p0n3** [comment]
How exactly would I do that? just extract the meshes .bsa and copy say /meshes/architecture/airport/airportterminaldestroyed01.nif to /meshes/lod/architecture/airport/airportterminaldestroyed01_LOD.nif?

**Comment by zilav** [comment]
Yes.

**Comment by n0p0n3** [comment]
Ok. Thanks man, You're awsome. You have no idea how much you've helped me in this project. You might have just saved me MONTHS-YEARS of unnecessary work and revisions. Can't thank you enough.
