### ISSUE TITLE
Cannot copy NAVI records into new file.

### ISSUE THREAD

**Issue by distino** [TES5Edit/TES5Edit#831]
**What is the version of xEdit you are using?**
TES5Edit 4.0.3 (1CDF3AC7) 

**Describe the bug**
Trying to copy NAVI record from Skyrim.esm(Enderal forgotten stories) with "Deep copy as override into..." but Im getting a following error: 

[00:03] Error while copying [ \ [00] Skyrim.esm \ [50] GRUP Top "NAVI"]: [EAssertionFailed] Assertion failure (P:\TES5Edit\wbImplementation.pas, line 15543)

**To reproduce**
1. Load Skyrim.esm of Enderal forgotten stories (Latest TES5Edit or EnderalEdit as it doesn't matter, error happens on both)
2. Click on Navigation Mesh Info Map
3. Scroll down to Deep copy as override into... and choose whichever you want(ESP, ESM flagged ESP or ESM, error happens on all)

**Expected behavior**
I expected a record copied to a new file without any problems.

**Screenshots**

**Additional context**
Short story long, I've tried to convert Enderal forgotten stories to a "new land" mod for Skyrim. Not fully functionally of course, as it would take too much time. Mostly I needed only working cells which I got, but lately I have managed to copy basically everything even NPC's etc. without having a Skyrim CTD in main menu. It overwrites and causes some weird behavior in few places in normal Skyrim, but I'm fine with it. The thing is that navmesh is the only thing I cannot copy in xEdit it seems. I think it's maybe because of Enderal having "00000000" FormID set for NAVI. I don't know how Enderal was made, I mean the way that it doesn't create any problems and the game works fine, because even if you try to edit something in it's ESM with xEdit,  you won't be able to save changes because of : 

[00:00] Error saving EnderalBetterEnding.esp.save.2019_09_16_18_41_47: Record [NAVI:00000000] must have a FormID.

both Skyrim.esm and Enderal - Forgotten Stories.esm have it set to 00000000, while original Skyrim.esm from Skyrim game has normal FormID, by normal I mean not only 0's.

Is there a workaround that would allow me to copy navmesh record somehow?

**Comment by ElminsterAU** [comment]
That record is not meant to be copied. It should be generated by CK for your new file.

**Comment by distino** [comment]
I see, I was thinking it might be this way, oh well thanks for clarification.
