### ISSUE TITLE
Crash when extracting assets with filter

### ISSUE THREAD

**Issue by n0p0n3** [TES5Edit/TES5Edit#833]
**What is the version of xEdit you are using?**
xedit 4.1.3b x64

**Describe the bug**
data error popup message, 'exception in unit assets manager line 622: [EZdecompressionerror] data error' message

**To reproduce**
select .esm, apply filter for 'by record signature', choose static, static collection, and textureset. click ok. right click .esm, apply script, assetsmanager, select 'copy referenced objects', click ok.
runs a bit, then crashes with 'exception in unit assets manager line 622: [EZdecompressionerror] data error' message

**Expected behavior**
extract only nifs of the types selected in filter

**Additional context**
also happens in x32bit version, and xedit 4.0.3. I'm not very familiar with pascal, but it looks like a function that's declared without a definition (it's the only time ResourceCopy appears).

**Comment by n0p0n3** [comment]
I've had some success with selecting one category at a time, but when it does crash it's always the same 'exception in unit assets manager line 622: [EZdecompressionerror]' error, although the popup sometimes says data error, other times says buffer error. I don't know if it finishes before crashing or crashes partway through. I'm trying to extract only statics to replace the LOD meshes for a run through FO4LODGEN object LOD generation to recreate the whole map for a worldveiwer/VR engine adaptation.

**Comment by ElminsterAU** [comment]
You probably have broken files

**Comment by n0p0n3** [comment]
OK, I'll try verifying through steam and reinstalling if needed, but my internet is slow, so it'll take a few days for me to try again. BTW, what meshes did export worked great, but some were still low poly, probably because they had different LOD filenames in the records (like several trees use one LOD mesh instead of one for each different object). Not your problem, just gotta figure out how to change them.

**Comment by n0p0n3** [comment]
I'm going to go ahead and mark this as solved, even though I haven't tested it yet (steam constantly re-downloads same files over and over again) because I do recall having some issues when extracting files using BAE, so you're probably right. Thank you for your help, and keep up the work on the awesome tools
