### ISSUE TITLE
any info on latest build dependencies?

### ISSUE THREAD

**Issue by aminomancer** [TES5Edit/TES5Edit#834]
Hi, maybe I missed it but I couldn't find any documentation on compiling from the source code for these latest versions. Just hoping someone will point me in the right direction, thanks!

**Comment by Infernio** [comment]
Join the xEdit Discord (https://discord.gg/5t8RnNQ), head to the `#dev-support` channel, and read the second stickied message there.

**Comment by aminomancer** [comment]
thank you!
