### ISSUE TITLE
Can not remove master file

### ISSUE THREAD

**Issue by sergei-ogan** [TES5Edit/TES5Edit#845]
i could remove master file in file header from right click menu if i use sseedit3.

but i can not it at sseedit4. 
i want to know how to remove master file in file header.

**Comment by Infernio** [comment]
Remove all references to the master you want to remove from the file, then right click the file and choose `Clean Masters`.
The 'old way' of doing it no longer exists because it created broken files.

**Comment by ElminsterAU** [comment]
The "old way" never was "a way", it simply was people horribly horribly misusing xEdit. And the "new way" isn't "new", it's what people should have always been doing.

**Comment by sergei-ogan** [comment]
I thought people misused it because of the misuse-prone explanations and interfaces.
