### ISSUE TITLE
Record Flag "Unknown 13"

### ISSUE THREAD

**Issue by tarlazo** [TES5Edit/TES5Edit#847]
Record Flag "Unknown 13" in the Record Header is the "Sky Marker" checkbox in the "Reference/Extra" tab in the CK.

**Comment by eckserah** [comment]
for which game? also for which record?

**Comment by tarlazo** [comment]
Skyrim SE.
For example in
[REFR:000C987A] (places XMarkerHeading [STAT:00000034] in GRUP Cell Persistent Children of [CELL:00000D74] (in Tamriel "Skyrim" [WRLD:0000003C]) at 24,17)
I believe that the CK allows it only in references of statics which have the 'is marker' flag, like xmarker, xmarkerheading, mapmarker, and so on.

**Comment by eckserah** [comment]
Thanks im pushing a PR to fix this :)

**Comment by yarrmateys** [comment]
note, the same is valid for fallout 4.
