### ISSUE TITLE
Records with hardcoded FormIDs show as new records instead of overrides/injected

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#848]
**What is the version of xEdit you are using?**
TES5Edit 4.1.3b EXTREMELY EXPERIMENTAL (CDA61A13) starting session 2020-07-22 21:41:15

**Describe the bug**
Records with hardcoded FormIDs (i.e. anything with an object ID < `0x800`, regardless of the FormID prefix) will override or inject into the hardcoded set of records that the engine reserves. xEdit, however, shows them as new records.

**To reproduce**
1. Download [test.zip](https://github.com/TES5Edit/TES5Edit/files/4962363/test.zip) and install it with a mod manager (or manually) (SLE or SSE)
2. Open `test.esp` in xEdit and navigate to its only record at `0100000F`
3. Observe that xEdit shows this as a new record
4. Make sure that `test.esp` is enabled and launch the game
5. Type `player.additem f 100` and `player.openactorcontainer 1`, then hit Alt to see your own inventory
6. Notice that the gold has been renamed to `0x800 is not a safe region`, meaning that the new record at `0100000F` actually acts as an override

**Expected behavior**
xEdit should probably show this record as an override. Note that I've only confirmed this behavior for Skyrim LE and SE. Fallout 4 should not exhibit this behavior for version 1.0 plugins anymore. Older games should exhibit it, but I haven't tested it.

**Comment by ElminsterAU** [comment]
this issue should be fixed in 4.0.3d
