### ISSUE TITLE
FNV - cleaning dead money master erases map geometry

### ISSUE THREAD

**Issue by Bunslinger** [TES5Edit/TES5Edit#853]
FNVEdit 4.0.3

I used the quick clean application to clean the game's masters, and upon starting the Dead Money DLC, all map geometry is missing.

![Fallout - New Vegas Screenshot 2020 08 17 - 19 32 51 25](https://user-images.githubusercontent.com/44516563/90468796-1a744880-e0cc-11ea-9179-aa674f42b283.png)

in order to verify that the original .esm itself was the issue and not a mod, I redownloaded the dirty .esm from a fresh reinstall of the game and replaced the clean version with it. all map geometry appeared correctly.

so the steps to replicate are:
1. have the dead money DLC downloaded
2. open the dead money .esm file with the quick clean application so that it can clean it
3. start the game and travel to the dlc area
4. after the slideshow cutscene, the player will spawn into the world like normal, however the map will appear like the screenshot above

another thing to note: i cleaned other DLC master files with the quick clean application as well, and they played out just fine. i'm reporting this because it's a reproducible error that only happens with the dead money DLC.

additionally, interiors from this DLC appear to be fine, it's only the exterior worldspace that has its geometry erased.

**Comment by ElminsterAU** [comment]
Please try 4.0.3b from #xedit-builds on the xEdit discord (with the file first tried to vanilla). If that doesn't fix it please use the parameter to force mark modified when running QAC (again, against the vanilla file) and see if that fixes it. I would appreciate it if you could report the outcome.

**Comment by ElminsterAU** [comment]
this issue should be fixed in 4.0.3d
