### ISSUE TITLE
After cleaning dlcnukaworld.esm, items in Nuka-Town market vanish

### ISSUE THREAD

**Issue by UUFrost1** [TES5Edit/TES5Edit#855]
**What is the version of xEdit you are using?**
FO4Edit 4.0.3

**Describe the bug**
After cleaning dlcnukaworld.esm, multiple items vanish from inside the Nuka-Town Market.  Two of the most notable items are the starcore, and the desk to the right of Mackenzie Bridgeman(as you face her).   Re-downloading dlcnukaworld.esm from Steam fixes the problem.

My apologies if this is a duplicate report.  Considering the amount of time that's passed since 4.0.3 has been released, I can't imagine that this hasn't been reported yet.  If it's something on my side, I apologize.  If you need further information, please let me know.  This is my first bug report for FO4Edit.

Thanks,

Frost

**Comment by ElminsterAU** [comment]
Please use 4.0.3b from #xedit-builds on the xEdit discord server and let me know if that fixes the issue for you

**Comment by UUFrost1** [comment]
Thank you for the very fast response!  I have xedit 4.0.3b downloaded.  How do I run the quick auto clean mode?  It appears that the old cleaning method no longer works.

**Comment by ElminsterAU** [comment]
It works exactly like it did in 4.0.3

**Comment by UUFrost1** [comment]
There is no executable for a quick auto clean.  I have xedit.exe and a ton of script files.  Did I download the wrong package?

**Comment by ElminsterAU** [comment]
Rename the exe

**Comment by ElminsterAU** [comment]
All xEdit exes are exactly the same. They just behave according to their file name.

**Comment by UUFrost1** [comment]
Thank you for all your help.  I learned a lot!  Unfortunately the problem persists after cleaning with 4.0.3b.  It's not a crisis.  I can play just fine with one dirty plugin.

**Comment by ElminsterAU** [comment]
Ok, then please use the command line parameter described in what's new to force mark modified while cleaning (a restored vanilla version of the file). Please let me know if that fixes it.

**Comment by ElminsterAU** [comment]
this issue should be fixed in 4.0.3d
