### ISSUE TITLE
FO3: Copying ARMO/ARMA records as override causes access violation

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#857]
**What is the version of xEdit you are using?**
FO3Edit 4.1.3b EXTREMELY EXPERIMENTAL (CDA61A13) starting session 2020-08-28 18:24:36

**Describe the bug**
Trying to copy `ARMO` (or `ARMA`) as overrides records causes an access violation and breaks the entire program - you can't even switch to the View tab to see the result of the copy because it just throws more access violations. Not sure if this happens with any other record types as well. Does *not* seem to happen with Oblivion, FNV, Skyrim, SSE or FO4.

**To reproduce**
1. Open `Fallout3.esm`
2. Expand `Armor`, pick any entry (I used the first one, `0000431E`)
3. Right click and `Copy as override` into a new file

**Additional context**
[xEditException.log](https://github.com/TES5Edit/TES5Edit/files/5143384/xEditException.log)

**Comment by ElminsterAU** [comment]
4.1.3c on #xedit-builds should fix this

**Comment by Infernio** [comment]
Yup, works great now 👍
