### ISSUE TITLE
[Request] Add a CLI parameter for specifying the base ESP

### ISSUE THREAD

**Issue by JamesYeoman** [TES5Edit/TES5Edit#858]
What I'm thinking is something like `--esx-name=<path to ESP/ESM/ESL>`

The reasoning for this is so I can create a mini batch script that I can use to run that on all the ESPs in my Data folder by iterating over all them and calling xedit with that suggested CLI switch, rather than having to manually run it and click a checkbox for each of them.

Alternatively, I could try to use LOOT in the batch script to identify dirty plugins. Either way, something like that would require a way other than the GUI to specify the plugin for xedit to load

**Comment by VlitS** [comment]
Search for Autoload under the What's New tab.
