### ISSUE TITLE
tooltip always disappears after a second

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#860]
**What is the version of xEdit you are using?**
FO4Edit 4.1.3c EXTREMELY EXPERIMENTAL (768E0C49) starting session 2020-09-03 20:09:05

**Describe the bug**
the tooltip that appears if you shift+hover the mouse over an entry that's too long to fit to display its entirety will disappear after a second or so. it will also not reappear if the mouse's moved away and back onto it until shift is released and held again.

**To reproduce**
1. hold shift and hover the mouse over an entry too long to fit in the display box.

**Expected behavior**
expected the tooltip to remain visible indefinitely until the mouse's moved out of the box or shift is released like in 4.0.3, and if the mouse's moved off of it and back onto it to have it appear again.

**Comment by ElminsterAU** [comment]
should be fixed with commit above (will be in 4.1.3h)
