### ISSUE TITLE
Updates for Static Collections [FO4]

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#871]
The "Unknown 10" flag is for "Loadscreen Static Collection", so probably just "Loadscreen" or something similar as the flag. Since flag seems to just be informational, as you can place them in a worldspace in the CK, and loading them in-game shows they have collision data. Removing the flag and spawning an SCOL with non-STAT items in-game works fine.

Flora (FLOR) records are also a valid items type for an SCOL part (SCOL \ Parts \ Part \ ONAM - Static). The CK will let you make a "Loadscreen static" with FLOR items, and the resulting SCOL works fine in-game.

**Comment by ElminsterAU** [comment]
this issue should be fixed in 4.0.3d
