### ISSUE TITLE
EnderalEdit does not seem to respect loadorder.txt

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#872]
**What is the version of xEdit you are using?**
EnderalView 4.1.3d EXTREMELY EXPERIMENTAL (CC3D3763) starting session 2020-10-20 12:20:24

But this has been around for a long time.

**Describe the bug**
Load order in Enderal is not correct, it doesn't seem to use loadorder.txt to determine the order of inactive files (it also lists `[Time:2017-11-19 14:04:11]` as the File Order in the selection window).

**To reproduce**
1. Install some mods in Enderal (any mod manager should work, I obviously used WB)
2. Deactivate one of the plugins
3. Move the deactivated plugin between some of the active ones
4. Launch xEdit. The deactivated plugin should be at the end of the load order instead of in the middle

**Expected behavior**
The deactivated plugin should be in the middle of the load order, since that's what the loadorder.txt file specifies (same as in Skyrim LE, which is what Enderal is based on).

**Screenshots**
In WB:

![image](https://user-images.githubusercontent.com/2845240/96574539-e128a680-12cf-11eb-8fd9-70091055cf32.png)

In xEdit:

![image](https://user-images.githubusercontent.com/2845240/96574636-00bfcf00-12d0-11eb-9f5f-d51d36849baa.png)

**Comment by jbostrus** [comment]
Hmm small oversight when the Enderal code was added I think. Simple enough fix I'll push soon.

**Comment by ElminsterAU** [comment]
Should just be a check or two in the load order unit.

**Comment by Infernio** [comment]
Closing, confirmed fixed in 4.1.3e.
