### ISSUE TITLE
Can't open steam version of Fallout 76

### ISSUE THREAD

**Issue by n0p0n3** [TES5Edit/TES5Edit#876]
**What is the version of xEdit you are using?**
FO4LODGen 4.1.3b EXTREMELY EXPERIMENTAL Terrain LOD BETA (50FACBFD)

**Describe the bug**
Fatal: Could not open registry key: \SOFTWARE\Microsoft\Windows\CurrentVersion\Unin...\Fallout 76\
This can happen after Bethesda.net Launcher updates, run the game's launcher to restore registry settings.

I've started the game launcher and logged in to the main menu several times, but nothing changes. I do not currently have bethesda.net launcher installed, as all I have on there is morrowind and am low on hdd space. Will install if needed.

**Comment by ElminsterAU** [comment]
A) Then use one of the multiply different documented other ways to tell xEdit where to find the data folder.

B) FO4LODGen 4.1.3b EXTREMELY EXPERIMENTAL Terrain LOD BETA ???????

**Comment by n0p0n3** [comment]
A) okay, I moved the folder containing xedit into the fallout76 directory and it works now.
B) it's version 4.0.3 on the whats new popup, but it says xLODGen/xedit 4.1.3b EXTREMELY EXPERIMENTAL Terrain LOD BETA on the top in the menus. I was in a hurry and grabbed the header from one of the logs, must have grabbed the xlodgen one, but it has that in all my logs

**Comment by ElminsterAU** [comment]
You should be using 4.1.3d from #xedit-builds for fo76 right now

**Comment by n0p0n3** [comment]
Is there a prebuilt version of 4.1.3d available? I don't have a development setup at the moment and I don't see any build instructions. I don't actually need to work on fallout 76 yet, I was just trying to compare the map size to fallout 4's to see how much larger it actually is. Much of fallout 4's map is empty and could be discarded for the world viewer/replacement engine I'm working on.

**Comment by ElminsterAU** [comment]
yes, as I said, it's in #xedit-builds  (on the discord)

**Comment by n0p0n3** [comment]
OK, I haven't used discord, but I'll check it out. Thank you for all your
help and keep up the good work, xedit is realy useful.
