### ISSUE TITLE
New to FNV Edit and have a question!

### ISSUE THREAD

**Issue by megablackk1d** [TES5Edit/TES5Edit#877]
This is probably a stupid question but it was my first time using it. I meant to deselect everything but I ended up double clicking the check box and it loaded everything. I immediately closed it but I am worried it made changes to my plugins I didn't want. I was wondering if that actually occurred, but I assume I am ok.

**Comment by ElminsterAU** [comment]
xEdit will not make changes to your files without asking you (outside of running QAC, and in that case it will only modify the single file or let you select, and only towards the end of the process)

**Comment by megablackk1d** [comment]
> xEdit will not make changes to your files without asking you (outside of running QAC, and in that case it will only modify the single file or let you select, and only towards the end of the process)

So in in other words I'm good, and out of curiosity what is QAC? Thanks for the help by the way.

**Comment by ElminsterAU** [comment]
Quick auto clean
