### ISSUE TITLE
SCEN\FNAM\Unknown 3 is 'Show all text'

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#879]
**What is the version of xEdit you are using?**
SSEEdit 4.1.3d EXTREMELY EXPERIMENTAL (CC3D3763) starting session 2020-11-12 21:50:11

**Describe the bug**
The `Unknown 3` flag in `SCEN\FNAM` corresponds to the `Show all text` checkbox in the CK.

**Screenshots**

MQ201ReturnToPartyScene in CK and xEdit, with flag unchecked:

![image](https://user-images.githubusercontent.com/2845240/98994731-8d0c8d00-2530-11eb-8004-73cbdbf433ba.png)

![image](https://user-images.githubusercontent.com/2845240/98994795-aad9f200-2530-11eb-9d4f-22f52b661d2d.png)

MQ201ReturnToPartyScene in CK and xEdit, with flag checked:

![image](https://user-images.githubusercontent.com/2845240/98995071-1b810e80-2531-11eb-8800-fa85bbce34ac.png)

![image](https://user-images.githubusercontent.com/2845240/98995156-381d4680-2531-11eb-91b6-3b5bc9533ff5.png)

**Comment by yarrmateys** [comment]
the same case seems to be true in fallout 4. unknown 2  in SCEN's FNAM flags is show all text. can be observed for example in 00004E1E, ArturoGreetScene.
