### ISSUE TITLE
Minor problem with double clicking during module selection

### ISSUE THREAD

**Issue by Targuinia** [TES5Edit/TES5Edit#880]
**What is the version of xEdit you are using?**
SSEEdit 4.0.3 (1CDF3AC7) starting session 2020-11-18 23:05:25

**Describe the bug**
Double clicking a plugin properly starts xEdit with only that plugin, however double clicking anywhere on the listing starts xEdit, even parts that have other functions, like the checkbox to select it. This means that when accidentally enabling a plugin and quickly disabling it again counts as a double click.

**To reproduce**
1. Start xEdit.
2. Double click the checkbox or the button to expand the masters list of a plugin.
3. xEdit will start with that plugin loaded.

**Expected behavior**
The function of a UI element should take precedence over double clicking, e.g. toggling a plugin.

**Comment by ElminsterAU** [comment]
Should be fixed with the commit above (will be in 4.0.3h)

It no longer reacts to double clicks on both the check box and the +/- for expanding/collapsing child nodes
