### ISSUE TITLE
Ability to add breakpoints for new lines for Terminal Body Text items.

### ISSUE THREAD

**Issue by kennyhigginbotham** [TES5Edit/TES5Edit#884]
**What is the version of xEdit you are using?**
FO4Edit 4.0.3

**Describe the bug**
Not a bug, but a quality of life improvement.

When editing the text for Body Text items for Terminal records there is no way to add breakpoints for new lines. Body Text for terminals, and even Display Text for Menu Items, are very commonly multi-line and deserve a multi-line text editor.

**To reproduce**
1. Create a Terminal record.
2. Add Body Text.
3. Add a Body Text item.
4. Right click Text on the Body Text item and select Edit.
5. Observe that the editor prompt only has one line for editing and no way to add breakpoints for new lines.

**Comment by ElminsterAU** [comment]
Open the Multiline editor window instead of in place editor

**Comment by kennyhigginbotham** [comment]
Right clicking the Text value and choosing Edit opens a single line editor. Double clicking opens a multi-line window that only allows viewing and comparing. Am I overlooking something?

**Comment by ElminsterAU** [comment]
yes, holding shift while double clicking to get an editor instead of viewer

**Comment by kennyhigginbotham** [comment]
That worked! As thanks for the quick help I'm going from Apprentice to Journeyman.

I'll close this issue.
