### ISSUE TITLE
xEdit 4.0.3d - Crash by confirming add of *no* master

### ISSUE THREAD

**Issue by FelesNoctis** [TES5Edit/TES5Edit#886]
**What is the version of xEdit you are using?**
SSEEdit 4.0.3d (45059AE1)

**Describe the bug**
If you try to add a master to a plugin, but no plugin is selected for a master, xEdit will close. By default it will try to add the first available plugin at the top of the list, but if you click in the filter box and type something random (as long as it doesn't match a plugin), then click OK, xEdit will shut down.

**To reproduce**
1. Right click on any plugin
2. Click on 'Add Masters'
3. Click inside Filter text box
4. Type random gibberish (anything that does not match a plugin)
5. Click OK

**Expected behavior**
OK button is deactivated unless a master is checked?

**Screenshots**
![Add Master box](https://user-images.githubusercontent.com/16215725/100834710-3b656d00-3421-11eb-8924-0291e9a9e982.png)

**Comment by ElminsterAU** [comment]
should be fixed with the commit above (will be in 4.x.3h)
