### ISSUE TITLE
TES4Edit: RSWD Magic Effect hidden or not recognised

### ISSUE THREAD

**Issue by XJDHDR** [TES5Edit/TES5Edit#887]
**What is the version of xEdit you are using?**
TES4Edit 4.0.3 (1CDF3AC7) starting session 2020-12-03 08:04:29

**Describe the bug**
After opening Oblivion.esm in TES4Edit, I noticed that the Magic Effect "Resist Water Damage" (RSWD) doesn't seem to exist as far as the program is concerned. If I open the list of Magic Effects, no effect with the Editor ID RSWD exists. Furthermore, I opened the spell "Immune to Water Damage" (00066C43 - AbImmuneToWaterDamage), which uses that magic effect, and TES4Edit displayed this message under the EFID section: "RSWD <Warning: could not be resolved>"

I also tried to do an Editor ID search for anything with RSWD but there were no search results. This effect does appear in the Construction Set.

**Expected behavior**
I expected the "Resist Water Damage" magic effect to appear in the list of magic effects. I also expected the "Immune to Water Damage" spell to not display a "Could not be resolved" error.

**Screenshots**
![RSWD not resolved](https://user-images.githubusercontent.com/7355441/100925440-e1f75e00-3546-11eb-942e-0da43d58fc63.png)

**Comment by Infernio** [comment]
It's an unused effect in the game (and that spell is unused as well), so it's quite possible that Oblivion.esm simply doesn't include it.
I don't know if it's hardcoded in the engine, or if it's entirely missing and only found in the CS (as the UESP page for it seems to imply: https://en.uesp.net/wiki/Oblivion:Resist_Water_Damage).

**Comment by XJDHDR** [comment]
I think I've figured out what's going on. Technically, all magic effects are hardcoded in the engine but most of them are also modified by Oblivion.esm. I think that what is happening is that TES4Edit is only displaying the magic effects that have been modified, which does not include the RSWD effect.

The UESP page's remark that this doesn't appear in the game means that it can't be accessed through the default game, in the same way that most of the testing cells can't be accessed through regular gameplay. It also claims that there are no spells with this effect in the Construction Set, which is incorrect as the ability I mentioned uses it. It also claim that the effect does work, though I haven't been able to get it working so far. A test character I created with the spell in the OP is just as vulnerable to lava as any others.
Edit: It's possible I'm doing something wrong. Through Googling, I found a thread on a certain adult modding site where a user (Myst42) wanted a way to swim in lava. After being told about the RSWD effect, he claimed that it worked.

**Comment by XJDHDR** [comment]
Did a bit more testing and the RSWD effect does indeed do what it's supposed to. Any character with this effect can step into lava without harm. But the topic of this report is that this effect doesn't appear in TES4Edit.

**Comment by Infernio** [comment]
Then it's missing from the [file xEdit uses to represent hardcoded records](https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.4/Core/Hardcoded/Oblivion.esp). No idea how that one was originally created, it seems to be [unchanged since 2015](https://github.com/TES5Edit/TES5Edit/commits/dev-4.1.4/Oblivion.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat). So may have to be dumped by someone who knows their way around OBSE and Oblivion.

**Comment by ElminsterAU** [comment]
Back then it was created by opening CS without loading any file, marking any records that could be found as modified, and saving a new plugin.

**Comment by Infernio** [comment]
I've started redoing that process. So far I have a file with quite a few more hardcoded records than the previous one.

**Comment by Infernio** [comment]
Though, one problem I've noticed is that if I load this new file in xEdit (4.1.3d), every single record has `[FORMID HERE] <Error: Access violation at address 00C70CA0 in module 'xEdit.exe'. Read of address 00000000>` in its record header. Probably a consequence of #848?

**Comment by Infernio** [comment]
I've managed to dump out 166 hardcoded records, many of which were missing from the previous version of the file. There's a problem with the MGEFs, however: If I mark one of those as modified and save the file, it gets a FormID > 0x800 assigned, making it not hardcoded anymore.

**Comment by Infernio** [comment]
Cleaning out all the records that also exist in Oblivion.esm leaves me with a file equivalent to the current `Oblivion.esp`. I'll open an issue for the access violation I encountered, but other than that, there's nothing wrong with the hardcoded file. We can't simply add them to the hardcoded file, for the same reason we can't just add the hardcoded GSMTs.

Edit: ref #888

**Comment by ElminsterAU** [comment]
#888 has been resolved, and other than that, Infernio's last comment above says all there is to say about this issue.

**Comment by XJDHDR** [comment]
Just to confirm. Does this mean that the bug I reported is now fixed? That the "Resist Water Damage" magic effect will now appear in the list of them?

**Comment by ElminsterAU** [comment]
No, it means it's not a bug.

**Comment by XJDHDR** [comment]
Can you please explain? I don't see how a record that exists within both the game's and CS's code but doesn't show up in TES4Edit is not a bug. Especially since a spell record that is present in Oblivion.esm displays an error because the program can't find this record.

**Comment by ElminsterAU** [comment]
To repeat: see @Infernio 's comments above.

**Comment by XJDHDR** [comment]
I did see it. I don't see the answer. He said, "We can't simply add them to the hardcoded file, for the same reason we can't just add the hardcoded GSMTs" but didn't say what this reason is here. Nor in 888 or 848.

All I can think of is this: "If I mark one of those as modified and save the file, it gets a FormID > 0x800 assigned, making it not hardcoded anymore." If the CS can't save those with the correct FormID, can't you correct it in TES4Edit afterwards? Or even a hex editor if the former is incapable of doing this? In fact, I might give that a try either tonight or tomorrow.
