### ISSUE TITLE
GetNativeValue returning invalid values

### ISSUE THREAD

**Issue by DocterDum** [TES5Edit/TES5Edit#890]
**What is the version of xEdit you are using?**
FO4Edit 4.0.3 [Auto Load] (819FA7E8) starting session 2020-12-22 20:58:18

**Describe the bug**
GetNativeValue appears to be returning the wrong mod index when used with APPR keywords

**To reproduce**
Elements involved when testing:
- Fallout4.esm (00), mod1.esp (0A), mod2.esp (0C)
- Item -> Armor_Vault111_Underwear - Falllout4.esm, Changed by mod2.esp
- Keywords: 
-    ap_Legendary "Legendary" [KYWD:001E32C8] - Fallout4.esm
-    ap_Legendary2 "Legendary" [KYWD:0A000F99] - keyword from mod1.esp (0A), added to item by mod2.esp

Open item in Fo4Edit
Check APPR slots -> E.g. my case shows ap_Legendary2 "Legendary" [KYWD:0A000F99]
Run script (included below) on item
Script shows:
 - ap_Legendary   KYWD = 001E32C8 (Correct)
 - ap_Legendary2 KYWD = 08000F99 (Incorrect - 08 instead of 0A)

**Expected behavior**
GetNativeValue should return 0A000F99
08 is a mod that adds 4 COBJs - Not at all relevant to Keywords mentioned

**Screenshots**
![v111Script](https://user-images.githubusercontent.com/7615222/102879896-9e857500-449e-11eb-871e-04edbeb1acbf.PNG)
![v111APPR](https://user-images.githubusercontent.com/7615222/102879899-9fb6a200-449e-11eb-85e0-17b4d25d3440.PNG)

**Additional context**

`unit userscript;

function Initialize: integer;
begin
    Result := 0;
end;

function Process(e: IInterface): integer;
var
	attachSlot: IInterface;
    result, j: integer;
	item: string;

begin
	if not (EditorID(e) = 'Armor_Vault111_Underwear') then Exit;
	if Signature(e) <> 'ARMO' then Exit;

	attachSlot := ElementByPath(e, 'APPR');

	result := -1;
	for j := 0 to ElementCount(attachSlot)-1 do
		AddMessage(IntToHex(GetNativeValue(ElementByIndex(attachSlot, j)), 8)
);
end;

// Called after processing
function Finalize: integer;
begin
    Result := 0;
end;

end.`

EDIT:
I thought #352 had the same issue but I think I was wrong
https://tes5edit.github.io/docs/13-Scripting-Functions.html - doesn't indicate why this issue might be occurring

**Comment by ElminsterAU** [comment]
You are fundamentally wrong.

The FormIDs you see on your screen are "load order" mapped FormIDs (where the high byte of the FormID is the global FormID prefix derived from the load order of all loaded modules).

The FormIDs stored in files are "file specific" FormIDs (where the high byte is the offset into the array of masters of the file).

GetNativeValue works exactly like it should.

Your expectations are faulty.

**Comment by DocterDum** [comment]
Ohhh okay, I see what you're saying. Thank you for assisting, I appreciate the help.
