### ISSUE TITLE
[Skyrim SE] Unrecognized change in faction vendor data.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#891]
Form 000A3F16 in Skyrim.esm has zeroes in the PLVD data for the vendor location info. USSEP changes this to specify the shop's actual marker but the change on the data is not recognized as a conflict on the editing screen.

I've attached a pic of the issue.
![Unrecognized Change](https://user-images.githubusercontent.com/1762652/103142251-70ca4700-46bd-11eb-9510-e3a2d3f2977e.png)

**Comment by ElminsterAU** [comment]
This is correct. The value is ignored in Skyrim.esm, as the field is unused for "Near editor location". As such the row only contains a single value. There is nothing wrong here.
