### ISSUE TITLE
Ability to compare records (of the same signature) in different trees to each other.

### ISSUE THREAD

**Issue by mrudat** [TES5Edit/TES5Edit#892]
It would be useful to be able to compare records (of the same signature) in different trees to each other, eg. an ARMO record in plugin 1 to the ARMO record in plugin 2 by multiple selection.

You can sort of achieve that for most signatures by copying both records into a common patch, and selecting the records in question, but that's just not possible for REFRs in different CELLs.

**Comment by VlitS** [comment]
As long as they are at the same "Depth", you can just select them both, then right click -> Compare Selected.

If you are comparing persistent to non-persistent records in a worldspace, you can apply a filter with "Flatten Cell Children" and "Assign Persistent Worldspace Children to Cells". This will make them at the same "Depth", allowing you to compare them. 

For interior CELLs, they (persistent and temp REFRs) are already at the same depth, so you can just use Compare Selected without applying a filter first.

**Comment by mrudat** [comment]
I'll have to look through the documentation, but I don't believe that this feature is mentioned anywhere (certainly not where I looked). This may turn into a note to upgrade the documentation.

That said, I'm once again happy to find that a thing that I'd like xEdit to do, it already does.

**Comment by mrudat** [comment]
Moved to https://github.com/TES5Edit/docs/issues/12
