### ISSUE TITLE
[Skyrim] Several RACE subrecords are not marked as required

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#894]
**What is the version of xEdit you are using?**
TES5Edit 4.1.3e EXTREMELY EXPERIMENTAL (958937B2) starting session 2021-01-04 13:05:55

**Describe the bug**
Several of the subrecords in Skyrim's RACE record type are required, but not marked as such in xEdit. They are created by the CK when a blank record of type RACE is created and will be recreated whenever the plugin is resaved in the CK. I haven't checked yet, but this probably leads to ambiguities in parsing (see also #737 and #747).

This file contains a plugin with a 'blank' RACE, created by making a new RACE in the CK, then deleting everything xEdit let me delete, and resaving in the CK again:  [foo.zip](https://github.com/TES5Edit/TES5Edit/files/5764631/foo.zip)

Required subrecords (this is basically just the info from the plugin linked above; checked = xEdit already has it as required):
- [x] `DESC - Description`
- [x] `BOD2 - Biped Body Template` (entirely zeroed, but present)
- [x] `DATA - DATA`
  - Defaults differ somewhat, but probably not a big deal
- [x] `MNAM - Male Marker`
- [x] `FNAM - Female Marker`
- [x] `Movement Type Names` (filled with five strings: `BLDO`, `RUN1`, `SNEK`, `SWIM` and `WALK`)
- [x] `VTCK - Voices` (CK default is `MaleUniqueMolagBal [VTYP:0000002D]` and `FemaleUniqueAzura [VTYP:0000002E]`, xEdit default is NULL)
- [x] `PNAM - FaceGen - Main clamp` (CK default is 5.0, xEdit default is 0.0)
- [x] `UNAM - FaceGen - Face clamp` (CK default is 3.0, xEdit default is 0.0)
- [x] `Body Data` (including `NAM1`, `MNAM`, `INDX` and `FNAM`)
- [x] `GNAM - Body Part Data` (CK default is `DefaultBodyPartData [BPTD:0000001D]`)
- [x] `NAM3 - Marker NAM3 #3`
- [x] `Male Behavior Graph` (specifically, the `MNAM` in there)
- [x] `Female Behavior Graph` (specifically, the `FNAM` in there)
- [x] `Biped Object Names` (always consists of 32 strings, so a default version has 32 empty strings. All vanilla records have 32 strings here, and only fill out the ones they need - all others are left as empty strings. E.g. `DraugrRace [RACE:00000D53]` has 32 strings, with 0, 1, 2, 3, 4 and 9 having actual strings. The other 26 are empty strings.)
- [x] `VNAM - Equipment Flags` (CK default is all but crossbow checked, but this is obviously not required. The CK will only put them back if the entire subrecord is removed. Removing all flag values but leaving the subrecord around followed by resaving will leave VNAM unchanged.)

**To reproduce**
1. Create a new RACE record in the CK, save the plugin
1. Open the plugin in xEdit
1. Observe that you can now remove certain subrecords (see above)
1. Resave the plugin in the CK
1. Note that the subrecords have returned

**Expected behavior**
Those subrecords should be marked as required in xEdit's definitions.

**Comment by ElminsterAU** [comment]
should be fixed with commit above (will be in 4.0.3h)
