### ISSUE TITLE
You misspelled 4.1.3 into 4.0.3 in the last update.

### ISSUE THREAD

**Issue by FanFanMi** [TES5Edit/TES5Edit#895]
You misspelled 4.1.3 into 4.0.3 in the last update.

[https://prnt.sc/wg5d3d](https://prnt.sc/wg5d3d)

[https://github.com/TES5Edit/TES5Edit/releases](https://github.com/TES5Edit/TES5Edit/releases)

Happy New Year.

**Comment by VlitS** [comment]
No, he didn't. There are currently two branches: 
      4.0.x, which is the stable branch most people should be using. Current public release is 4.0.3, though 4.0.3d on the Discord server (#xedit-builds channel) has some fixes that are needed if you want to use QAC for Skyrim DLC. 
      4.1.x, which is the experimental branch. It has changes made to support Morrowind (Currently only works for view mode), and also FO76. There are some other features currently only in 4.1.x, but the TES3 support required the biggest changes, and is the main reason it isn't recommended for daily use even for other games (barring FO76, but you can't actually use any plugins made there anyway so it is primarily used for viewing there too even if you can use it in edit mode).

**Comment by FanFanMi** [comment]
Problem solved. Sorry.
