### ISSUE TITLE
TES3View crashes when opening Morrowind.esm

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#896]
**What is the version of xEdit you are using?**
Can't, it crashes :)
It's TES3View 4.1.3e though.

**Describe the bug**
Opening Morrowind.esm in TES3View crashes with in the latest experimental build.

**To reproduce**
1. Launch 4.1.3e with `-tes3 -view`
2. Double-click Morrowind.esm

**Expected behavior**
Morrowind.esm should open for viewing.

**Comment by ElminsterAU** [comment]
Can you please try again with 4.1.3e (Test Build 3) from #feedback? (I'll put out an 4.1.3f in the next few days)

**Comment by Infernio** [comment]
Still happens with test build 3. Doesn't leave behind an exception log either, just silently closes (and prints 'segmentation fault' if I launch it via git bash)

**Comment by ElminsterAU** [comment]
Ok, thanks for checking. I'll have a look.

**Comment by Infernio** [comment]
I guess this is fixed by aae13420aeb0989240c272e7c98fde65ec3c6c7a?

**Comment by ElminsterAU** [comment]
Yes

**Comment by Infernio** [comment]
Fixed in the commit mentioned above.
