### ISSUE TITLE
Request: "Unhide all..." option in column context menu please

### ISSUE THREAD

**Issue by cecell** [TES5Edit/TES5Edit#901]
When working with a record that is in multiple plugins it is often easy to hide one or more of the columns.  However, once you do this you can't easily unhide the records.  It would be VERY helpful if you could add an option to the column context menu named something like "Unhide all..." which would just clear the Hidden flag on all records in all of the plugins that contain it.

![image](https://user-images.githubusercontent.com/1248121/105872290-da40bc80-5fbf-11eb-8ea3-9010e108b809.png)

**Comment by CrazieIvan** [comment]
+1 This would certainly save a lot of time.  I actually stopped hiding columns because I couldn't unhide them, which is unfortunate.

**Comment by ElminsterAU** [comment]
should be implemented with commit listed above (will be in 4.0.3h)

**Comment by cecell** [comment]
ho-lee crap, you are the most amazing amazer that I have ever been amazed by

**Comment by CrazieIvan** [comment]
Thank you!
