### ISSUE TITLE
[Feature Request] Option to ignore MHDT conflicts when using Very Quick Show Conflicts

### ISSUE THREAD

**Issue by RabidAnteater** [TES5Edit/TES5Edit#902]
SSEEdit 4.0.3 

It would be useful to have an option to ignore MHDT conflicts when performing a Very Quick Show Conflicts.

On the assumption that MHDT conflicts are allowable, these can bring up a number of results in the search which currently need to be manually checked, but could be automatically filtered to speed things up.

**Comment by ElminsterAU** [comment]
should be resolved with commits referenced above (included in 4.0.4)
