### ISSUE TITLE
Any mod referred to in INOM and INOA in all present overrides will be added to a mod's master list on override.

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#904]
**What is the version of xEdit you are using?**
FNVEdit 4.1.3f EXTREMELY EXPERIMENTAL (4AC3F164) starting session 2021-02-25 03:08:14

**Describe the bug**
any time i attempt to copy something with INOM/INOA like dialogs/info into a new mod, it will check the INOM and INOA entries and attempt to add every single mod from every override present to the master list. it doesn't seem to happen if added to an unsaved parent, but once it's saved and created any override attempt will try to add all the mods that modify this parent.

**To reproduce**
1) load fnv with some mods that modify FollowersHired, for example tale of two wastelands and simply uncut.
2) attempt to override 000B16C8 from falloutnv.esm to a new file. the initial creation will work fine. save.
3) now attempt to override 0015C808. it will attempt to add every mod that modifies the parent, 00037084.

**Expected behavior**
Expected to just override it without it trying to add every master available.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above (which will be in 4.1.3h)

**Comment by CritLoren** [comment]
Not sure if related, but trying to copy INOM/INOA records doesn't do anything but change the counter at the top:
![image](https://user-images.githubusercontent.com/22298459/185667660-56c3c633-e62a-4a4b-ab4a-b45860bf9648.png)

**Comment by Infernio** [comment]
INOM/INOA don't actually exist in plugins, they're virtual elements generated by xEdit for your information. Trying to copy them *should* do nothing.
