### ISSUE TITLE
Can't use TES5Edit/SSEEdit

### ISSUE THREAD

**Issue by WolfyHorns** [TES5Edit/TES5Edit#905]
**What is the version of xEdit you are using?**
4.0.3.0

**Describe the bug**
When I launch the QuickClean and the common SSEEdit, it says it didn't found the registry key, even after I used my launcher.

**To reproduce**
1. Go to .exe of the file or the 'launch' button on MO2 or Vortex.
2. Click on 'launch'
3. See error
4. Click 'Ok' and see more errors.

**Expected behavior**
It should show my Skyrim files and let me clean them.

**Screenshots**
![Captura de Tela (72)](https://user-images.githubusercontent.com/79924227/109669548-f6042900-7b50-11eb-8aa2-dd2486be892e.png)
![Captura de Tela (73)](https://user-images.githubusercontent.com/79924227/109669559-f7355600-7b50-11eb-807a-a698e2c580fd.png)

**Comment by ElminsterAU** [comment]
Stop using TES5Edit for SSE.

**Comment by WolfyHorns** [comment]
> Stop using TES5Edit for SSE.

What should I use?

**Comment by ElminsterAU** [comment]
SSEEdit

**Comment by WolfyHorns** [comment]
Thx. I tried it before but didn't worked, but now it is. Maybe something I moved?

Well, anyway, it's solved. Thx.
