### ISSUE TITLE
CTD loading save games or going to Main Menu with created esp files with SSEEdit if you dont re-save with the CK

### ISSUE THREAD

**Issue by elafrosicky** [TES5Edit/TES5Edit#906]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.
4.0.3
**Describe the bug**
CTD loading save games or going to Main Menu with created esp files with SSEEdit if you dont re-save with the CK
**To reproduce**
CTD loading save games or going to Main Menu with created esp files with SSEEdit if you dont re-save with the CK
just do what i describe to reproduce
**Expected behavior**
Not CTD
**Screenshots**

**Additional context**

**Comment by jbostrus** [comment]
First up, you should always be final saving with CK. There's things of the plugin structure that haven't been decoded yet. So some data may be missing when created initially from xEdit. It will try to just copy verbatim data that is found but unknown. When you create new records in xEdit only that data is just blank, which the game won't like.

We would need to see the plugin at least before re-saving in CK to see what's up. Likely the game wants some value on a record and it's missing. See note above. When re-saving in CK it would add a default value to satisfy the game or fix a structure or something like that.

Without more details to figure out what is broken to look at there's not much we can do.

**Comment by elafrosicky** [comment]
The problem happened, copyin "copy as new record" in a new generated file, 
it happened with a lot of record type, (magic effect, spell, misc object, etc..)
i didnt know that in sse, you have to re-save in ck, so my bad.
is almost sure that is a not decoded problem when creating the new plugin in SSEEdit.
you can close this bug.
thanks,.
