### ISSUE TITLE
overriding a creature in fo3/fnv mode doesn't properly copy NIFZ and KFFZ sections.

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#908]
**What is the version of xEdit you are using?**
FNVEdit 4.1.3f EXTREMELY EXPERIMENTAL (4AC3F164) starting session 2021-03-03 15:01:37

**Describe the bug**
when trying to override a creature, the NIFZ and KFFZ sections aren't fully copied. it always seems to ignore the second entry.

**To reproduce**
1. override a creature into a new file, or drag and drop one into another.

**Expected behavior**
expected the overridden/copied entry to be identical to the one i copied it from.

**Comment by ElminsterAU** [comment]
should be fixed with commit referenced above (will be in 4.1.4h)
