### ISSUE TITLE
xEdit should double apostrophes in generated LOOT masterlist entry names

### ISSUE THREAD

**Issue by sibir-ine** [TES5Edit/TES5Edit#909]
**What is the version of xEdit you are using?**
TES4Edit 4.0.3 (Quick Auto Clean) (1CDF3AC7)
TES4Edit 4.0.3f (Quick Auto Clean) (E97FEB9E)
TES4Edit 4.1.3f EXTREMELY EXPERIMENTAL (Quick Auto Clean) (4AC3F164)

**Describe the bug**
When QAC generates a LOOT masterlist entry for a plugin with an apostrophe (') in its name, it doesn't append a second apostrophe to it.

**To reproduce**
1. Download & install a plugin with an apostrophe in its name (e.g. [this one](https://www.nexusmods.com/oblivion/mods/14957/))
2. Clean the plugin using QAC
3. Observe the entry name with a non-doubled apostrophe.

**Expected behavior**
xEdit should double apostrophes (i.e. `Auriel's Books.esp` should be `Auriel''s Books.esp`) for it to be syntactically valid. Otherwise, a user will have to manually append the apostrophe when they submit the entry to one of the masterlist.

**Comment by ElminsterAU** [comment]
should be fixed with commits referenced above

**Comment by sibir-ine** [comment]
Awesome, thanks!

**Comment by MacSplody** [comment]
For cleaning reports, only the dirty entries have escaped apostrophes.

![image](https://user-images.githubusercontent.com/1944639/121981039-e8cc1c80-cd84-11eb-912d-b7ac1139c9a0.png)
