### ISSUE TITLE
Curious about error message in version 4.0.3

### ISSUE THREAD

**Issue by primem0ver** [TES5Edit/TES5Edit#911]
I couldn't post this on the Nexus forums because they have all been locked.  I am developing a tool that has some similarities to yours but with a completely different focus.  I am testing its ability to convert mods to ESL's after compacting form ids with one step.  I am currently using SSEEdit version 4.0.3.  After dozens of successful tests I have encountered an issue.

The original mod has zero errors and zero error messages.  While loading a specific renumbered mod (with all references renumbered as well) reports 3 "unknown record type".  However, when I TEST the mod for errors, it repeats this message but only twice.  In addition the error count reports 0 errors.  When I look at the records, it is reporting an extra NPC with an id of 0.  That is the only thing I can find that is different (other than the ids).  When using a binary comparer, the only differences between the two files are the mentioned ids and the compressed npc sections.

I am going to go ahead and try and figure out what is going on myself by modifying my code to save and comparing the decompressed NPC sections but thought I would post this in case you are aware of any mis-reporting that happens.  I have attached a sample file if you would like to investigate.  

[TAotB - New Facial Hairs.zip](https://github.com/TES5Edit/TES5Edit/files/6161539/TAotB.-.New.Facial.Hairs.zip)

**Comment by Infernio** [comment]
That file is definitely broken. At the very least, some of the headers in the `NPC_` GRUP have the wrong sizes in them. WB shows this:
```
mod_links.pyo  112 Execute: Exception loading TAotB - New Facial Hairs.esp:

Traceback (most recent call last):
  File "bash\basher\mod_links.pyo", line 104, in Execute
  File "bash\basher\mod_links.pyo", line 89, in _load_mod
  File "bash\mod_files.pyo", line 230, in load
  File "bash\brec\record_groups.pyo", line 74, in load_rec_group
  File "bash\brec\record_groups.pyo", line 220, in _load_rec_group
  File "bash\brec\mod_io.pyo", line 321, in unpackRecHeader
  File "bash\brec\mod_io.pyo", line 190, in unpack_header
  File "bash\brec\mod_io.pyo", line 313, in unpack
ModReadError: TAotB - New Facial Hairs.esp: REC_HEADER: Attempted to read past (50857) end (50833) of file/buffer.
```
That's when it tries to read another `NPC_` record's header, but the file itself has already ended.

**Comment by primem0ver** [comment]
Thanks for your feedback. I found the problem and fixed it.  It was the GRUP header (and the code for changing the size after re-compression of records that required it).  The other record headers types were fine; though only because they didn't have any child records.
