### ISSUE TITLE
RNAM subrecord of INFO needs to be treated as case sensitive.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#914]
As an example:

![image](https://user-images.githubusercontent.com/1762652/112532710-c242aa80-8d6e-11eb-84c4-a4ad042dbd88.png)

"Draugr" vs "draugr" - this is being treated as an ITM when it's not.

**Comment by Infernio** [comment]
It shows up fine ingame? Some strings get pooled, which ignores case. That's why you sometimes have to add trailing spaces for MCM strings, for example.

**Comment by Arthmoor** [comment]
Yes, the change in case shows up in game. Why wouldn't it?

**Comment by Infernio** [comment]
Like I said above, some strings get pooled, at which point they ignore case.

**Comment by Arthmoor** [comment]
Well these changes show up in game and always have for other instances of this same type of issue I've reported before. xEdit should not be ignoring this,

**Comment by ElminsterAU** [comment]
Should be fixed in Skyrim / SSE with the commit above.
Funnily enough, it was already correct in all other games...

**Comment by Arthmoor** [comment]
Thank you :)
