### ISSUE TITLE
"Check for Errors" disregards duplicate FormIds

### ISSUE THREAD

**Issue by Glanzer-modder** [TES5Edit/TES5Edit#917]
This is not a bug report per se, it's more of a request that the "Check for Errors" function in xedit be able to report on duplicated FormIds in a plugin, in the same way that the new Dyndolod Alpha reports those. I'm using version: 4.0.3.

**Comment by ElminsterAU** [comment]
Duplicate FormIDs are reported on load in the current 4.1.x codebase. DynDoLOD is derived from that. The relevant code is too complex and expansive to backport to 4.0.x
