### ISSUE TITLE
For REFR, Linked Rooms Count needs to be updated whenever the Linked Rooms are changed

### ISSUE THREAD

**Issue by Infernio** [TES5Edit/TES5Edit#919]
**What is the version of xEdit you are using?**
SSEEdit 4.1.3f EXTREMELY EXPERIMENTAL (4AC3F164) starting session 2021-04-05 19:11:39

**Describe the bug**
This counter (`REFR\Bound Data\XRMR - Header\Linked Rooms Count`) exists (at least) in FO3, FNV, TES5, FO4 and FO76. It counts the number of linked rooms (`REFR\Bound Data\Linked Rooms`).
If the counter is wrong, the CK will misbehave. I haven't tested what the game does.
CK behavior is as follows:
  - More linked rooms than the counter -> the CK will discard the extraneous rooms
  - Fewer linked rooms than the counter -> the CK will discard the entire subrecord structure (`REFR\Bound Data`, i.e. XRMR/LNAM/INAM/XLRM)

**To reproduce**
1. Create a record with Bound Data (e.g. by copying `00105028` in TES5)
2. Add linked rooms, but do not update the linked rooms counter
3. Resave in the CK, observe that it has either corrected the counter or discarded the entire subrecord structure

**Expected behavior**
The counter should be updated automatically when you add or remove linked rooms.

**Screenshots**

![image](https://user-images.githubusercontent.com/2845240/113603143-d5ddf300-9643-11eb-9857-f62988bb645b.png)

*(After changing counter to 2 and resaving in the CK)*

**Comment by ElminsterAU** [comment]
Should be fixed with commits referenced above
