### ISSUE TITLE
Log conditions?  Seems inconsistent

### ISSUE THREAD

**Issue by primem0ver** [TES5Edit/TES5Edit#920]
Hello,
I am concerned about the file SSEEdit_log.txt.  Updating of this file seems inconsistent in that it doesn't get updated every time SSEEdit runs or performs operations on files.  Under what conditions does the log get created/updated?  Is there a way to force the log to be created/updated every time? Particularly when running error checks?  I am parsing the output for error information.

Thanks,

**Comment by ElminsterAU** [comment]
The log is saved reliably and consistently every time xEdit is closed gracefully.

Please use the Discord for questions and the issue system for bug reports and feature requests. TIA.
