### ISSUE TITLE
ESP's not showing up in data tab or anytab as a matter of fact even though it says the esp for the mod is installed in mo2 in 

### ISSUE THREAD

**Issue by Stormboy9** [TES5Edit/TES5Edit#938]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ElminsterAU** [comment]
Whatever your problem is in this regard, it's not a bug in xEdit. This is a support question, not a bug report. Please use the xEdit discord for support questions.
