### ISSUE TITLE
Record Flag "Unknown 11" for Location forms in Fallout 4: Handles checkbox for "Interior cells use ref location for world map player marker"

### ISSUE THREAD

**Issue by omniguous** [TES5Edit/TES5Edit#939]
**What is the version of xEdit you are using?**
4.0.3h HF1

**Describe the bug**
The Flag "Unknown 11" for Location Forms controls a checkbox that is visible in the CK.

**To reproduce**
1. Open a Location form in FO4Edit that has Unknown 11 Set to true
2. Open that same record in the CK
3. See that it has that checkbox enabled

**Expected behavior**
unsure,

**Screenshots**
![image](https://user-images.githubusercontent.com/82130105/126885707-1479a66c-3166-40ea-8124-9de7882e72b2.png)
![image](https://user-images.githubusercontent.com/82130105/126885712-faba4d4c-a9cd-4e32-8c64-5a4b2e6551f1.png)

**Additional context**
<3

**Comment by eckserah** [comment]
Added in 91602d031ac2ab30fa7bfc9869c5c595c3b443ff. Can be closed
