### ISSUE TITLE
FeatureRequest: InitializeFile + FinializeFile Userscript function calls

### ISSUE THREAD

**Issue by Idrinth** [TES5Edit/TES5Edit#942]
To allow preparation of files and cleanups afterwards, it would be nice to have those additional calls, that should get a file-IInterface passed in.
This is mostly a quality of life feature, but would make things like using multiple source-record-types for data easier.

**Comment by zilav** [comment]
```
function Initialize: integer;
begin
  ScriptProcessElements := [etFile];
end;
```
Only selected files interfaces will be passed into the Process function. Other possible values are `etGroupRecord` and `etMainRecord`.

You can also get the file interface from the passed record `f := GetFile(e);` and operate on it if needed.

**Comment by Idrinth** [comment]
Have been using `GetFile(e);` and a check for file name change so far, just thought it might be cleaner if there were function calls avaible - no need for a global for example and way less calls to `GetFile`.

**Comment by zilav** [comment]
Adding separate calls for file interfaces won't make it cleaner imho. The current functionality is enough I think to implement any sort of processing in selection. `GetFile(e)` is cheap, and you can also use `Equals(f1, f2)` to directly compare xEdit interfaces which is also very cheap.
