### ISSUE TITLE
Fatal <Exception: Too many modules> with pseudoesl flag

### ISSUE THREAD

**Issue by dmrickey** [TES5Edit/TES5Edit#945]
**What is the version of xEdit you are using?**
SSEEdit 4.0.3

I'm running the arguments `autoload` and `pseudoesl` so that I can go through and change esps to esps flagged as esls (espfe). 

It's telling me that I've got "too many full modules". I know I do.. that's the problem, that's why I'm changing some to esls. I'm not trying to build any patches or anything else, I just want to load *all* of my options and modify the ones that are able into espfes. I'm not trying to use any features where having too many loaded should be a real issue.  Is there no way to do that?

**Comment by ElminsterAU** [comment]
If you can't load your load order with pseudoesl, then you have too many modules that can't be esl flagged.

Also, this is not a bug report.

This is a support question which belongs on the discord.

**Comment by dmrickey** [comment]
Gotcha, thanks. I wasn't aware there was a discord, I'll try talking about it there

**Comment by ElminsterAU** [comment]
Top right corner of xEdit is a Discord button.
