### ISSUE TITLE
[FO4/F76] NPC_\AIDT - AI Data subrecord 4 Unknown bytes correspond to "No Slow Approach"

### ISSUE THREAD

**Issue by Evan555alpha** [TES5Edit/TES5Edit#947]
In an NPC's `AIDT - AI Data` subrecord, the last Unknown field appears to correspond to the `No Slow Approach` checkbox in the CK's corresponding tab in the Actor dialogue.
I'd imagine that anything other than` 01 00 00 00` is just memory garbage because that seems to be the way that Beth operates.
![](https://cdn.discordapp.com/attachments/486317996344868864/878541164368789504/unknown.png)
![](https://cdn.discordapp.com/attachments/486317996344868864/878541180332290058/unknown.png)

**Comment by yarrmateys** [comment]
it's probably just the first byte that's used for this function. the remaining three are likely unused/garbage data.

**Comment by Evan555alpha** [comment]
That's what I'm saying, yes.

**Comment by yarrmateys** [comment]
yeah, just mentioning it in case since there's a similar situation with "geared up weapons" which uses 1 byte, but xedit has both it and the following garbage byte defined for the entry so the results go outside the 0-12 range ck allows if the second byte's filled.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above

**Comment by yarrmateys** [comment]
as i thought, it using 4 bytes causes trouble. fallout 4 mode, record 000197CC for example has <unknown: 1769171200> because the 3 unused bytes after the value are counted when they shouldn't.
