### ISSUE TITLE
[TES4] Oblivion.esm shows as edited when using VQSC mode

### ISSUE THREAD

**Issue by MacSplody** [TES5Edit/TES5Edit#949]
**What is the version of xEdit you are using?**

TES4Edit 4.0.3h (Hotfix 1)

**Describe the bug**

Oblivion.esm is marked as edited when using VQSC mode, despite the user being unable to edit that file.
This happen immediately upon startup

**To reproduce**

1. At least two of `DLCBattlehornCastle.esp`, `DLCFrostcrag.esp`, `DLCHorseArmor.esp`, `DLCMehrunesRazor.esp`, `DLCOrrery.esp`, `DLCSpellTomes.esp`, `DLCThievesDen.esp`, `DLCVileLair.esp`, `Knights.esp` must be active in your load order.
2. Launch xEdit.exe with startup arguments `-tes4` `-vqsc`.
2. Wait for background loader to finish and remove the applied filter.
3. The main game master Oblivion.esm should be bold.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1944639/131210355-11568dd5-48a6-4d74-a6e2-ff0ad22bbb60.png)

![image](https://user-images.githubusercontent.com/1944639/131210880-17b7e234-55af-48c9-9b78-c27fbb2fa691.png)

![image](https://user-images.githubusercontent.com/1944639/131210902-5683495b-91dc-432f-a884-95eb4101f7b4.png)

![image](https://user-images.githubusercontent.com/1944639/131211176-b9662820-1b58-43f7-91ba-6d3bf2b2f846.png)

**Additional context**

Bug does not occur when using normal mode.

Bug does not occur when using VQSC mode if game is SSE.

**Comment by ElminsterAU** [comment]
should be fixed with the commits referenced above

**Comment by MacSplody** [comment]
> should be fixed with the commits referenced above

Thanks.
