### ISSUE TITLE
[Feature] Allow Process to run in parallel

### ISSUE THREAD

**Issue by Idrinth** [TES5Edit/TES5Edit#951]
Sometimes there is no requirement to run `Process()` in sequence, for speed reasons it would be nice if those calls could be run in parallel instead.
Since this is a major change, it should only be enabled by configuration call in Initialize, something like `EnableParallelProcess()`.
Alternatively being able to run a `procedure` in a different thread would also work the same way, giving script authors the ability to use more of the machine's resources for higher speed.

**Comment by ElminsterAU** [comment]
xEdit's core is not threadsafe
