### ISSUE TITLE
Bug: Time passed wrong for long running scripts

### ISSUE THREAD

**Issue by Idrinth** [TES5Edit/TES5Edit#953]
**What is the version of xEdit you are using?**
SSEEdit 4.0.3 (1CDF3AC7) starting session 2021-09-01 22:11:09

**Describe the bug**
The time used does not show hours passed, leading to a wrong displayed duration both in the toolbar and at the end of the script if a script runs for 60 minutes or more.

**To reproduce**
1. Pick a script that will run at least 60 minutes o
2. Run the script
3. Once an hour has passed check the titlebar's time passed
4. When done check the displayed duration

**Expected behavior**
I expected the hours used to be shown as well, either by having minutes exceed 60 or as a separate element.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/7874631/131736110-afa9e1da-ac28-44a2-9564-ba03bfe2cee4.png)

**Comment by ElminsterAU** [comment]
should be fixed with the commits referenced above
