### ISSUE TITLE
IMAD unknown flags in 4.1.3h

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#954]
**What is the version of xEdit you are using?**
FO4Edit 4.1.3h EXTREMELY EXPERIMENTAL (Hotfix 1) (655A4693) starting session 2021-09-01 22:16:55

**Describe the bug**
in the IMAD records, DoF Flag display is all wrong, possibly due to increasing their amount from 32 to 64. the first several defined unknowns (2-8) are removed, so that the normal entries under 9-14 are pushed to the top. records such as 001E22EA, VATSPlaybackDesatFastFollow instead of showing Use Target, Mode - Back, Blur radius Bit 2, 1 and 0 now shows <Unknown: 17>, 19, 20, and 21 with the first one, use target not even appearing. the same flags appear correctly in 4.0.3h

**To reproduce**
go to record 001E22EA in fallout4.esm
scroll down to DoF Flags

**Expected behavior**
expected the flags to use proper names as they do in 4.0.3h.

**Comment by ElminsterAU** [comment]
should be fixed with the commit referenced above
