### ISSUE TITLE
MteFunctions

### ISSUE THREAD

**Issue by and00r** [TES5Edit/TES5Edit#956]
Hi, is the updated MteFunction script still required for TES5Edit? 

https://github.com/matortheeternal/TES5EditScripts/issues/20

Doesn't say if the issue has been resolved or not

**Comment by ElminsterAU** [comment]
Not an xEdit issue.

**Comment by and00r** [comment]
oh, i see. but shouldnt it still be updated anyway?

**Comment by ElminsterAU** [comment]
The error is in the script. This is not a script that is part of xEdit. This is an SEP (Somebody Else's Problem).
