### ISSUE TITLE
FNVEditQuickAutoClean does not clean files according to LOOT. Despite running it several times, LOOT returns the same message every time. ie: FNVEdit Found X No of files etc for all DLC's. I am using latest version of FNVEdit. Does it work only on the 64Bit Version of FNV? 

### ISSUE THREAD

**Issue by DeepThought62** [TES5Edit/TES5Edit#957]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ElminsterAU** [comment]
There is no bug. You are doing something wrong. Support questions should go to the Discord.

**Comment by DeepThought62** [comment]
Ok, thanks
