### ISSUE TITLE
[FO4 but likely also everything else] Quick Auto Clean should force-enable "Remove OFST Data"

### ISSUE THREAD

**Issue by Evan555alpha** [TES5Edit/TES5Edit#959]
**What is the version of xEdit you are using?**
4.0.3h hotfix 1

**Describe the bug**
Quick Auto Clean will write zeroed out OFST data if the option "remove OFST Data from Worldspace" is unchecked, causing crashes with the game.

**To reproduce**
Disable removal of OFST data in the options panel
Run QAC on a plugin that has OFST data, such as a DLC Masterfile
Load in-game
Crash game

**Expected behavior**
QAC should either force-enable the previously mentioned option, or otherwise include removing OFST data - at least on all official DLC files - as part of the cleaning process, since cleaning them will change offsets, making the original OFST data invalid.

**Additional context**
I mention only doing it to all the official DLC files, as I'm sure that out there somewhere, there's a plugin that as OFST data that otherwise doesn't need cleaning, and removing OFST data would be kinda pointless if it is correct.

**Comment by ElminsterAU** [comment]
No. It will write unchanged OFST data if the option is unchecked.

**Comment by ElminsterAU** [comment]
Nobody should ever disable that. The option shouldn't exist at all.

**Comment by Evan555alpha** [comment]
Unchanged OFST data is still incorrect OFST data if the file has been changed (at least with children being removed from WRLD, anyway)
Yes, and I am suggesting this as a failsafe, not a reason to continue to keep that option.

**Comment by ElminsterAU** [comment]
Should be fixed with commits referenced above.

The option doesn't exist in the UI at all anymore. It can only be triggered now by passing the `-dontremoveoffsetdata` command line parameter. Which will be ignored if used together with quick clean or quick auto clean.
