### ISSUE TITLE
Version 4.0.3 after downloading from nexus my panda anti virus says its trying to connect to another computer blocks the whole program version 4.0.2 is works perfectly

### ISSUE THREAD

**Issue by Scotteyboy** [TES5Edit/TES5Edit#961]
**What is the version of xEdit you are using?**
Copy the first line from your xEdit messages window.

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ElminsterAU** [comment]
Yes, and it has been doing that since v4.0.0. it's checking if there is a newer version available on NexusMods or GitHub.
