### ISSUE TITLE
SLGM and FLOR refs are completely valid for pack data

### ISSUE THREAD

**Issue by ghyujkilop** [TES5Edit/TES5Edit#964]
**What is the version of xEdit you are using?**
4.0.3

**Describe the bug**
whenever I check errors on Immersive Encounters.esp I get a whole list of them in xEdit. But the author of the mod said "This gets brought up quite often but these errors are harmless. SLGM and FLOR refs are completely valid for pack data. xEdit is wrong on that one." Here's a link to the comments where you can find his comment: https://www.nexusmods.com/skyrimspecialedition/mods/18330?tab=posts&BH=0

**To reproduce**
Just right click check errors on xEdit for Immersive Encounters.esp.

**Expected behavior**
It shows the errors involving the mod.

**Screenshots**

**Additional context**
My personal error log: https://pastebin.com/RN4Jd8fe

**Comment by ElminsterAU** [comment]
should be fixed with commits referenced above (will be in 4.x.4)
