### ISSUE TITLE
Game master automatically re-added after clean masters removes it (when no masters left)

### ISSUE THREAD

**Issue by VlitS** [TES5Edit/TES5Edit#965]
**What is the version of xEdit you are using?**
SSEEdit 4.0.3h (Hotfix 1) (74B3720F)

**Describe the bug**
When "Clean Masters" removes all masters (due to it being a archive loader plugin or only having things like new keywords), xEdit re-adds Skyrim.esm as a master. 

**To reproduce**
1. Copy some Keyword records from Skyrim.esm as New Records into a new plugin
2. Save the plugin, then use "Add Masters" to add Skyrim.esm as a master and save. 
3. Relaunch xEdit, then run Clean Masters. 
4. Save and relaunch xEdit. 
5. The Messages tab will show Skyrim.esm being added as a master, and the new records will now show as overrides or injected records for Skyrim.esm. 

Also included test plugin. Using it, you would start at step 3

[CleanMastersTest.zip](https://github.com/TES5Edit/TES5Edit/files/7402148/CleanMastersTest.zip)

**Expected behavior**
xEdit leaves the plugin with no masters, or failing that, properly adds the master in a way that updates internal formIDs. 

**Screenshots**
![2021-10-22-22-27-39-xEdit](https://user-images.githubusercontent.com/12984164/138539519-9d4e32e8-f9fc-4668-b972-3f8f643945c4.png)

**Additional context**
Confirmed that the same issue happens with Fallout 4 if the plugin is set to have a File version of <1.0. Have not tested with other games, but is likely the same. 

When the File version is 1.0, Fallout4.esm is not removed because 00000000 (File Header) is treated as a reference to Fallout4.esm (and shows as a could not be resolved error if the plugin has no masters).

**Comment by ElminsterAU** [comment]
CleanMastersTest.esp is already broken and can't be used to reproduce the actual problem.

**Comment by ElminsterAU** [comment]
should be fixed with commits referenced above
