### ISSUE TITLE
Seeking instructions for building the projects

### ISSUE THREAD

**Issue by flayman** [TES5Edit/TES5Edit#966]
Hi. I'm a seasoned software engineer but have little experience of object Pascal. I'm trying to build the sources with Delphi 10.4 Community Edition but running into errors suggesting missing dependencies. Could we please have a readme around building the sources, including what are the dependencies and how to get them?

**Comment by ElminsterAU** [comment]
Setup and build instructions are currently provided in the pinned messages in the #dev-support channel on the xEdit Discord

**Comment by flayman** [comment]
Thanks. Apologies for failing to look there.

**Comment by ElminsterAU** [comment]
No worries, it's not obvious. I'll try to improve the documentation here on GitHub in the future.
