### ISSUE TITLE
XEdit not displaying Polish characters properly and doesn't allow me to use them.

### ISSUE THREAD

**Issue by justtoask** [TES5Edit/TES5Edit#968]
I use xedit 4.0.3.

the problem is that Xedit doesn't allow me to use Polish characters when editing things and changes them to English ones instead.

To reproduce the displaying problem you need to get Polish version of the files (at least thats the only way I know how, there might be the same with the Czech and Russian version), and for the characters problem you need to try typing one of the letters to the entries (is that how they're called?): ą ć ę ł ń ś ź ż.

I expected the program to replace the files with the right characters instead.

![image](https://user-images.githubusercontent.com/72657053/139316034-fd85dbe3-4502-40a8-a7de-0efbe3d9f01a.png)
the characters displaying wrong (the wierd e and ae)

I wanted to translate a mod for fallout 3 which is originally in Spanish, called "Animated Terminal Screen Savers" and I discovered this problem.

**Comment by ElminsterAU** [comment]
Read information about code pages in What's New. Act accordingly.

**Comment by justtoask** [comment]
I can't find this section, I'm blind. Does is have adifferent name? I was reading the file whatsnew.md and branches I was reading were dev-4.1.4 and master.

**Comment by ElminsterAU** [comment]
https://github.com/TES5Edit/TES5Edit/blob/dev-4.1.4/whatsnew.md#improved-language-and-codepage-support
