### ISSUE TITLE
NPC_ 'Geared Up Weapons' should only show 1 byte

### ISSUE THREAD

**Issue by yarrmateys** [TES5Edit/TES5Edit#972]
**What is the version of xEdit you are using?**
FO4Edit 4.1.3i EXTREMELY EXPERIMENTAL (RC1 for 4.1.4) (B5D24D6E) starting session 2021-11-07 18:31:13

**Describe the bug**
in the DNAM entry of the NPC_ records, Geared Up Weapons part, CK only supports values from 0-12, and only appears to be using one byte, but xEdit uses two. if the second byte contains garbage data, ck ignores it completely (ex. 00002EFE, YefimBobrov has 15873 (3E 01) defined in xEdit, but in CK it's just 1). CK doesn't purge that byte, just ignores it as if it didn't exist and reads the value as 1, which suggests that the secondary byte, which in this case has 3E stored is garbage/unused data.

**Expected behavior**
expected it to show only the first byte as CK does.

**Comment by ElminsterAU** [comment]
should be resolved with the commit referenced above
