### ISSUE TITLE
GetIsID condition with Hazard argument is reported as an error

### ISSUE THREAD

**Issue by Exit-9B** [TES5Edit/TES5Edit#973]
**What is the version of xEdit you are using?**
`SSEEdit 4.0.3j (RC2 for 4.0.4) (38946781) starting session 2021-11-08 14:25:18`

**Describe the bug**
Using the `GetIsID` condition in Skyrim with a Hazard (HAZD) form as the argument is considered an error. The condition can be created in Creation Kit and works in game.

**To reproduce**
1. Download and install https://www.nexusmods.com/skyrimspecialedition/mods/35464
2. Open `GuidingLight.esp` in xEdit
3. Right click the file and run "Check for Errors"
4. See multiple errors reported in the log that look like this:
```
[00:00]     QUST \ Aliases \ Alias \ Conditions \ Condition \ CTDA - CTDA \ Parameter #1 -> Found a HAZD reference, expected: ACTI,ALCH,AMMO,ARMA,ARMO,ASPC,BOOK,CONT,DOOR,ENCH,FLOR,FLST,FURN,GRAS,IDLM,KEYM,LIGH,LVLI,LVSP,MISC,MSTT,NPC_,NULL,PROJ,SCRL,SHOU,SLGM,SOUN,SPEL,STAT,TACT,TREE,WEAP
```

**Expected behavior**
No errors are reported on this mod, and `GetIsID` conditions can be created in xEdit using Hazard arguments.

**Comment by ElminsterAU** [comment]
should be resolved with the commits referenced above
