### ISSUE TITLE
[4.0.4] Readme change needed for binaries?

### ISSUE THREAD

**Issue by ashemedai** [TES5Edit/TES5Edit#979]
**What is the version of xEdit you are using?**
4.0.4 7zip download

**Describe the bug**
The Readme in this repo points out renaming the executable. The 7zip-file has 2 main executables since 4.0.4, `xFOEdit.exe` and `xTESEdit.exe`, instead of a single `SSEEdit.exe`. The two binaries are of a different size and, obviously, different hash.

The Readme states:

```
Rename to TES4Edit.exe to work with Oblivion.
Rename to TES5Edit.exe to work with Skyrim.
Rename to TES5VREdit.exe to work with Skyrim VR.
Rename to SSEEdit to work with Skyrim SE.
Rename to FO3Edit.exe to work with Fallout3.
Rename to FNVEdit.exe to work with New Vegas.
Rename to FO4Edit.exe to work with Fallout 4.
Rename to FO4VREdit.exe to work with Fallout 4 VR.
Rename to FO76Edit.exe to work with Fallout 76.
```

Should this now be understood to have `xFOEdit.exe` be renamed for the various Fallout games and `xTESEdit.exe` for the various Elder Scrolls games?

If so, I'm happy to whip up a PR, just want to make sure I understand what has changed.

**Comment by VlitS** [comment]
The only difference between the two are the icons used for the exe. Yes, I know there seems to be a significant size difference, that is just the icon. So you can rename xFOEdit.exe to SSEEdit.exe and it will work, it will just have the "wrong" icon.

**Comment by ElminsterAU** [comment]
What he said ^

**Comment by ashemedai** [comment]
Ah, of course. Totally forgot icons are embedded in the executable. 🤦🏻‍♂️ 

Thanks for clarifying!
