### ISSUE TITLE
Feature request: jump to referenced record

### ISSUE THREAD

**Issue by VariableVixen** [TES5Edit/TES5Edit#987]
I checked the open issues and didn't see this one, so apologies if I missed it.

The "referenced by" tab allows double-clicking to jump to a record that references the current one, but there's no way to jump to a record referenced _by_ the currently displayed one. If a context menu option could be added (obviously only for items that actually reference another record, not things like display names) to jump to the referenced item, it would make tasks like analysing and editing trees of leveled lists much easier, for instance.

**Comment by VlitS** [comment]
Control+Click lets you jump to the record being referenced as you are requesting. For records listed in the "Messages" tab (such as when running a script that outputs a list, or doing check for errors), it is Ctrl+doubleclick.

In my experience, a lot of the features I have asked about were already there. For things like this, it is probably best to ask about them on the discord (link in the top right of xEdit) first. Copy to (and remove from) selected records are probably my favorite example.

**Comment by VariableVixen** [comment]
Sorry about that, appreciate the help!
