### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by selsie** [TES5Edit/TES5Edit#996]
4.0.4 32bit

Loading the whole Modlist for patch creation, I get the error "Out of Memory". The Task manager shows only 2GB used by SSEedit, and I have 64GB RAM

To reproduce.... Just load my modlist. LOL

**Comment by 2001herne** [comment]
Try the 64-bit version (see #818). The binary for the 64-bit version should be in the "Optional" folder.

**Comment by Atengji** [comment]
The error is that xEdit has some bad data in its cache folder. The cure is emptying out the cache folder so it can be rebuilt.
